import type { LegendFigure } from '../types';
import { angle, fact, moment, src, tag, wiki } from './define';

export const ANIMAL_LEGENDS: readonly LegendFigure[] = [
  {
    id: 'lf_hachiko',
    name: 'Hachikō',
    kind: 'animal',
    hall: 'animals',
    region: 'east_asia',
    place: 'Tokyo, Japan',
    era: '1923–1935',
    died: 1935,
    gender: 'none',
    field: 'Akita dog',
    essence: 'Waited at the station for almost ten years.',
    whoTheyWere: 'An Akita dog in Tokyo remembered for his dedication to his owner, Professor Hidesaburō Ueno.',
    famousFor: 'Returning to Shibuya Station almost every day for years to wait for Ueno.',
    facts: [
      fact('f1', 'He met his owner at Shibuya Station every day after his commute home.', src(wiki('Hachikō'), 'Shibuya Station every day after his commute home')),
      fact('f2', 'After Ueno died in 1925, he kept waiting for almost ten years.', src(wiki('Hachikō'), 'almost ten years')),
      fact('f3', 'He is remembered worldwide with statues, movies and books.', src(wiki('Hachikō'), 'statues, movies, and books')),
    ],
    moments: [
      moment('m1', 'From 1925 until 1935 he returned to Shibuya Station almost every day to await Ueno.', src(wiki('Hachikō'), "returned to Shibuya Station almost every day to await Ueno's return")),
      moment('m2', 'When his story became known across Japan, his loyalty was widely reported and public interest grew.', src(wiki('Hachikō'), 'remarkable display of loyalty')),
    ],
    angles: [
      angle('a1', 'the station', 'What does a dog who waited at a station for ten years have in common with you?', 'Showing up for someone, again and again, says a lot about you.'),
      angle('a2', 'the same time every day', 'Why does a routine feel like love?', 'Small, steady habits can be the biggest way to care.'),
      angle('a3', 'undeterred', 'What keeps you going when nobody notices?', 'Loyalty does not need an audience.'),
      angle('a4', 'remembered', 'Why does a quiet dog get a statue?', 'Quiet faithfulness moves people more than noise.'),
    ],
    tags: [
      tag('attachment_avoidance', 'low', 'devoted to one person', 'He kept waiting for his owner for years.'),
      tag('conscientiousness', 'high', 'there every single day', 'He went to the station almost every day.'),
      tag('steadiness', 'high', 'calm and patient waiting', 'He waited patiently, year after year.'),
      tag('attachment_anxiety', 'high', 'waiting for his return', 'He kept watching for the one person he loved.'),
      tag('openness', 'low', 'same place, same time', 'He kept to the same station and the same routine.'),
    ],
    vetting: 'Real dog, died 1935; a beloved story of loyalty; no harm shown.',
  },
  {
    id: 'lf_balto',
    name: 'Balto',
    kind: 'animal',
    hall: 'animals',
    region: 'americas',
    place: 'Alaska and Cleveland, United States',
    era: 'About 1919–1933',
    died: 1933,
    gender: 'none',
    field: 'Sled dog',
    essence: 'Ran the last leg of the race to bring medicine to Nome.',
    whoTheyWere: 'A Siberian Husky sled dog who led the team on the final leg of the 1925 serum run to Nome.',
    famousFor: 'The serum run, and a statue in Central Park.',
    facts: [
      fact('f1', 'He ran the final leg of the 1925 serum run to Nome, carrying medicine to fight an outbreak.', src(wiki('Balto'), 'final leg of the 1925 serum run to Nome')),
      fact('f2', 'His fame led to a statue in Central Park.', src(wiki('Balto'), 'a statue in Central Park')),
      fact('f3', 'He is displayed today in the Cleveland Museum of Natural History.', src(wiki('Balto'), 'Cleveland Museum of Natural History')),
    ],
    moments: [
      moment('m1', 'When news came out in 1927 of his poor living conditions, the people of Cleveland raised money to buy him and his team.', src(wiki('Balto'), 'two-week fundraising effort in Cleveland')),
      moment('m2', 'Coverage at the time focused almost entirely on him, over the other dogs and mushers, including Togo.', src(wiki('Balto'), 'focused almost entirely on him')),
    ],
    angles: [
      angle('a1', 'the last leg', 'What does a dog who ran the final stretch have in common with you?', 'Finishing strong matters, even when others ran before you.'),
      angle('a2', 'the spotlight', 'What do you do when you get the credit for a team effort?', 'Sharing credit keeps the whole team strong.'),
      angle('a3', 'rescued', 'What happens when a whole city decides to help?', 'People coming together can change everything.'),
      angle('a4', 'the statue', 'Why did one dog become the face of the run?', 'Stories often need one face, but many hands made it happen.'),
    ],
    tags: [
      tag('extraversion', 'high', 'the famous face', 'He became a celebrity with a vaudeville tour.'),
      tag('relatedness', 'high', 'part of a team', 'He ran as part of a sled dog team.'),
      tag('self_efficacy', 'high', 'brought the medicine home', 'He led the team on the final leg to Nome.'),
      tag('locus_of_control', 'low', 'sold and moved around', 'He was sold and moved by others before Cleveland rescued him.'),
    ],
    vetting: 'Real dog, died 1933; the run is admired; the hard part of his life is told gently.',
  },
  {
    id: 'lf_togo',
    name: 'Togo',
    kind: 'animal',
    hall: 'animals',
    region: 'americas',
    place: 'Alaska, United States',
    era: '1913–1929',
    died: 1929,
    gender: 'none',
    field: 'Sled dog',
    essence: 'Ran the longest, hardest stretch of the serum run, with little credit.',
    whoTheyWere: 'The lead sled dog of musher Leonhard Seppala in the 1925 serum run to Nome.',
    famousFor: 'Covering far more distance than any other lead dog on the run.',
    facts: [
      fact('f1', 'He covered a far greater distance than any other lead dog on the 1925 serum run.', src(wiki('Togo_(dog)'), 'far greater distance than any other lead dogs')),
      fact('f2', 'His name, Cugu, means puppy in the Northern Sami language.', src(wiki('Togo_(dog)'), 'means puppy in Northern Sami language')),
      fact('f3', 'At first he was seen as a troublemaker, before Seppala saw he was a leader.', src(wiki('Togo_(dog)'), 'Deemed at first a troublemaker')),
    ],
    moments: [
      moment('m1', 'On the run, his team covered over 261 miles across some of the most dangerous parts of the trail.', src(wiki('Togo_(dog)'), '261 miles')),
      moment('m2', 'He saved the lives of his team and musher on several occasions.', src(wiki('Togo_(dog)'), 'saving the lives of his team and musher')),
      moment('m3', 'He was ill as a young puppy and needed intensive nursing.', src(wiki('Togo_(dog)'), 'ill as a young puppy')),
    ],
    angles: [
      angle('a1', 'the long stretch', 'What does a sled dog who ran the hardest miles have in common with you?', 'The hardest part of the work is often the part people don’t see.'),
      angle('a2', 'the troublemaker', 'What if the thing that gets you in trouble is what makes you a leader?', 'A restless streak can turn into leadership.'),
      angle('a3', 'left out of the news', 'How do you feel when someone else gets the credit?', 'What you did still counts, even unreported.'),
      angle('a4', 'the sick puppy', 'Who would have guessed the small, ill puppy would lead?', 'A slow start says little about how far you go.'),
    ],
    tags: [
      tag('conflict_assertiveness', 'high', 'bold and rowdy', 'He was bold and rowdy as a young dog.'),
      tag('competence', 'high', 'led over the worst ice', 'He led across the most dangerous parts of the trail.'),
      tag('autonomy', 'high', 'did things his own way', 'He was first seen as a troublemaker.'),
      tag('extraversion', 'low', 'out of the spotlight', 'His role was left out of the news at the time.'),
      tag('growth_mindset', 'high', 'from sick puppy to leader', 'He grew from an ill puppy into a lead dog.'),
    ],
    vetting: 'Real dog, died 1929; widely admired; no harm shown.',
  },
  {
    id: 'lf_greyfriars_bobby',
    name: 'Greyfriars Bobby',
    kind: 'animal',
    hall: 'animals',
    region: 'europe',
    place: 'Edinburgh, Scotland',
    era: 'About 1855–1872',
    died: 1872,
    gender: 'none',
    field: 'Terrier',
    essence: 'A little terrier said to have guarded a grave for 14 years.',
    whoTheyWere: 'A small terrier in 19th-century Edinburgh, said to have spent 14 years by the grave of his owner.',
    famousFor: 'His statue and drinking fountain in Edinburgh.',
    facts: [
      fact('f1', 'He is said to have sat by his owner’s grave for 14 years.', src(wiki('Greyfriars_Bobby'), 'sat by the grave for 14 years')),
      fact('f2', 'The Lord Provost of Edinburgh paid for his licence and gave him a collar, now in the Museum of Edinburgh.', src(wiki('Greyfriars_Bobby'), "paid for Bobby's licence")),
      fact('f3', 'The story is well known in Scotland, though its accuracy is disputed.', src(wiki('Greyfriars_Bobby'), 'accuracy is disputed')),
    ],
    moments: [
      moment('m1', 'He spent the rest of his life sitting on his master’s grave in Greyfriars Kirkyard.', src(wiki('Greyfriars_Bobby'), "sitting on his master's grave")),
      moment('m2', 'A year after he died, a drinking fountain topped with his statue was put up opposite the churchyard.', src(wiki('Greyfriars_Bobby'), "drinking fountain topped with Bobby's statue")),
    ],
    angles: [
      angle('a1', 'the grave', 'What does a little dog who kept watch for years have in common with you?', 'Some bonds outlast everything.'),
      angle('a2', 'the collar', 'What happens when a city decides you belong to all of it?', 'Being looked after by many people is a kind of home.'),
      angle('a3', 'true or not', 'Does it matter if every detail of a story is true?', 'A story can mean something even when the details are unsure.'),
      angle('a4', 'small and stubborn', 'How does a small dog become a city’s symbol?', 'Staying put can be its own kind of strength.'),
    ],
    tags: [
      tag('attachment_avoidance', 'low', 'stayed by his person', 'He stayed near his owner’s grave.'),
      tag('steadiness', 'high', 'kept the same post', 'He kept the same place for years.'),
      tag('relatedness', 'high', 'a whole city’s dog', 'Edinburgh looked after him.'),
      tag('openness', 'low', 'never left his spot', 'He stayed at the same kirkyard.'),
      tag('growth_mindset', 'low', 'content in one spot', 'He stayed at the same kirkyard for years.'),
    ],
    vetting: 'Real dog, died 1872; label says the story is disputed; no harm shown.',
  },
  {
    id: 'lf_seabiscuit',
    name: 'Seabiscuit',
    kind: 'animal',
    hall: 'animals',
    region: 'americas',
    place: 'United States',
    era: '1933–1947',
    died: 1947,
    gender: 'none',
    field: 'Racehorse',
    essence: 'A small, sleepy horse who became a symbol of hope.',
    whoTheyWere: 'An American thoroughbred racehorse who became the top money-winning racehorse up to the 1940s.',
    famousFor: 'Beating Triple Crown winner War Admiral in 1938.',
    facts: [
      fact('f1', 'He won only a quarter of his first 40 races.', src(wiki('Seabiscuit'), 'quarter of his first 40 races')),
      fact('f2', 'He beat the Triple Crown winner War Admiral by four lengths in a two-horse race.', src(wiki('Seabiscuit'), 'War Admiral, by four lengths')),
      fact('f3', 'He became a symbol of hope to many Americans during the Great Depression.', src(wiki('Seabiscuit'), 'symbol of hope to many Americans during the Great Depression')),
    ],
    moments: [
      moment('m1', 'As a young horse he was undersized, knobby-kneed and given to sleeping and eating for long periods.', src(wiki('Seabiscuit'), 'given to sleeping and eating for long periods')),
      moment('m2', 'He was named for his father, Hard Tack: sea biscuit is another name for hardtack.', src(wiki('Seabiscuit'), 'another name for hardtack')),
    ],
    angles: [
      angle('a1', 'the slow start', 'What does a horse who lost most of his first races have in common with you?', 'Where you start says little about where you finish.'),
      angle('a2', 'sleeping and eating', 'Can a lazy-looking start hide a champion?', 'Rest is not the same as giving up.'),
      angle('a3', 'the big match', 'What happens when the underdog meets the champion?', 'Belief can close a big gap.'),
      angle('a4', 'hope', 'Why do people cheer so hard for an unlikely winner?', 'Seeing someone come back gives everyone a lift.'),
    ],
    tags: [
      tag('growth_mindset', 'high', 'loser to champion', 'He went from losing most races to beating the best.'),
      tag('playfulness', 'high', 'loved naps and snacks', 'He was given to sleeping and eating.'),
      tag('conscientiousness', 'low', 'a lazy-looking start', 'Early on he was known for sleeping and eating.'),
      tag('self_efficacy', 'high', 'beat the champion', 'He beat the Triple Crown winner by four lengths.'),
      tag('extraversion', 'high', 'the crowd’s favourite', 'He became a national symbol of hope.'),
    ],
    vetting: 'Real horse, died 1947; widely loved; no harm shown.',
  },
  {
    id: 'lf_owney',
    name: 'Owney',
    kind: 'animal',
    hall: 'animals',
    region: 'americas',
    place: 'United States',
    era: 'About 1887–1897',
    died: 1897,
    gender: 'none',
    field: 'Postal dog',
    essence: 'A post office dog who rode the mail trains around the world.',
    whoTheyWere: 'A terrier mix adopted by the Albany post office who became the mascot of the Railway Mail Service.',
    famousFor: 'Travelling over 140,000 miles with the mail, collecting tags on his collar.',
    facts: [
      fact('f1', 'He travelled over 140,000 miles across the United States and around the world.', src(wiki('Owney_(dog)'), '140,000 miles')),
      fact('f2', 'Post offices he visited attached their own tags to his collar.', src(wiki('Owney_(dog)'), 'attach tags of their own to his collar')),
      fact('f3', 'He was honoured on a 2011 U.S. postage stamp.', src(wiki('Owney_(dog)'), '2011 U.S. postage stamp')),
    ],
    moments: [
      moment('m1', 'He loved the smell of the mail bags and would often sleep on them.', src(wiki('Owney_(dog)'), 'love the smell of the mail bags')),
      moment('m2', 'Clerks saw him as good luck, since no train he rode on was ever in a wreck.', src(wiki('Owney_(dog)'), 'no train he rode on was ever in a wreck')),
    ],
    angles: [
      angle('a1', 'the tags', 'What does a dog covered in souvenir tags have in common with you?', 'Every place you go leaves a little mark on you.'),
      angle('a2', 'the mail bags', 'Why fall in love with something as ordinary as a mail bag?', 'Loving the everyday makes any job feel like home.'),
      angle('a3', 'good luck', 'What does it feel like to be someone’s lucky charm?', 'Just being there can make people feel safer.'),
      angle('a4', 'on the move', 'Where would you go if every train was yours?', 'Curiosity can take you a very long way.'),
    ],
    tags: [
      tag('openness', 'high', 'rode trains everywhere', 'He travelled across the country and the world.'),
      tag('extraversion', 'high', 'everyone’s mascot', 'He was a welcome addition in any post office.'),
      tag('autonomy', 'high', 'went where he liked', 'He would ride on trains wherever they were taken.'),
      tag('conflict_cooperativeness', 'high', 'everyone’s good-luck charm', 'Clerks everywhere welcomed him.'),
      tag('conflict_assertiveness', 'high', 'guarded the mail', 'He let nobody but mail clerks touch the bags.'),
    ],
    vetting: 'Real dog, died 1897; a beloved mascot; the label does not dwell on his death.',
  },
  {
    id: 'lf_winnipeg_bear',
    name: 'Winnie the bear',
    kind: 'animal',
    hall: 'animals',
    region: 'europe',
    place: 'Canada and London, England',
    era: '1914–1934',
    died: 1934,
    gender: 'none',
    field: 'Black bear',
    essence: 'The real bear behind the name Winnie-the-Pooh.',
    whoTheyWere: 'A black bear named after the city of Winnipeg, who lived at London Zoo from 1915 until 1934.',
    famousFor: 'Inspiring the name of Winnie-the-Pooh.',
    facts: [
      fact('f1', 'She is best remembered for inspiring the name of Winnie-the-Pooh.', src(wiki('Winnipeg_(bear)'), "Shepard's character, Winnie-the-Pooh")),
      fact('f2', 'She was named after the city of Winnipeg, Manitoba.', src(wiki('Winnipeg_(bear)'), 'after his adopted home city of Winnipeg')),
      fact('f3', 'At London Zoo she was much loved for her playfulness and gentleness.', src(wiki('Winnipeg_(bear)'), 'playfulness and gentleness')),
    ],
    moments: [
      moment('m1', 'She travelled with a Canadian army vet all the way to England and became a regiment’s mascot.', src(wiki('Winnipeg_(bear)'), 'becoming the mascot of the CAVC')),
      moment('m2', 'A boy named Christopher Robin often visited her, and renamed his own teddy bear after her.', src(wiki('Winnipeg_(bear)'), 'Christopher Robin, who frequently visited the bear')),
    ],
    angles: [
      angle('a1', 'the name', 'What does a zoo bear who named a famous teddy have in common with you?', 'You can shape someone’s world without knowing it.'),
      angle('a2', 'gentle and playful', 'Why do people love the gentle ones best?', 'Kindness and play make people want to come back.'),
      angle('a3', 'the long trip', 'What is it like to end up far from where you started?', 'A new place can become a real home.'),
      angle('a4', 'the visitor', 'Who do you visit again and again, and why?', 'The friends we return to change us.'),
    ],
    tags: [
      tag('agreeableness', 'high', 'gentle with everyone', 'She was loved for her gentleness.'),
      tag('playfulness', 'high', 'loved for her play', 'She was loved for her playfulness.'),
      tag('relatedness', 'high', 'a boy’s best friend', 'Christopher Robin visited her often.'),
      tag('conflict_assertiveness', 'low', 'never a fighter', 'She was known for being gentle, not fierce.'),
      tag('attachment_anxiety', 'low', 'gentle with strangers', 'She was loved by visitors for her gentleness.'),
    ],
    vetting: 'Real bear, died 1934; widely loved; nothing harmful shown.',
  },
  {
    id: 'lf_pickles',
    name: 'Pickles',
    kind: 'animal',
    hall: 'animals',
    region: 'europe',
    place: 'London, England',
    era: '1962–1967',
    died: 1967,
    gender: 'none',
    field: 'Collie',
    essence: 'Found the stolen World Cup trophy on a walk.',
    whoTheyWere: 'A black and white collie who found the stolen World Cup trophy in London in 1966.',
    famousFor: 'Finding the Jules Rimet Trophy, wrapped in newspaper.',
    facts: [
      fact('f1', 'He found the stolen Jules Rimet Trophy in March 1966, four months before the World Cup in England.', src(wiki('Pickles_(dog)'), 'finding the stolen Jules Rimet Trophy')),
      fact('f2', 'The trophy was wrapped in newspaper by the wheel of a parked car.', src(wiki('Pickles_(dog)'), 'wrapped in newspaper lying by the front wheel of a parked car')),
      fact('f3', 'He was given the silver medal of the National Canine Defence League.', src(wiki('Pickles_(dog)'), 'silver medal of the National Canine Defence League')),
    ],
    moments: [
      moment('m1', 'He found the trophy while out on a walk with his owner, just seven days after it was stolen.', src(wiki('Pickles_(dog)'), 'just seven days after it was stolen')),
      moment('m2', 'When England won the trophy, he was invited to the celebration banquet.', src(wiki('Pickles_(dog)'), 'invited to the celebration banquet')),
    ],
    angles: [
      angle('a1', 'the walk', 'What does a dog who found the World Cup on a walk have in common with you?', 'Paying attention on an ordinary day can change everything.'),
      angle('a2', 'the nose', 'Why notice what everyone else walks past?', 'Curiosity finds what searching sometimes misses.'),
      angle('a3', 'the banquet', 'What would you do if you were invited to the big party?', 'Small acts can earn you a seat at the table.'),
      angle('a4', 'the newspaper', 'How do you spot treasure in plain wrapping?', 'Valuable things often don’t look valuable.'),
    ],
    tags: [
      tag('openness', 'high', 'sniffed out the unusual', 'He noticed a parcel others passed.'),
      tag('playfulness', 'high', 'treasure on a walk', 'He found it on an ordinary walk.'),
      tag('locus_of_control', 'low', 'luck on a walk', 'He found the trophy by chance on a walk.'),
      tag('self_efficacy', 'high', 'solved the big case', 'He found what the police were looking for.'),
      tag('attachment_anxiety', 'low', 'happy on any walk', 'He found the trophy on an ordinary walk.'),
    ],
    vetting: 'Real dog, died 1967; a cheerful story; the label does not dwell on his death.',
  },
  {
    id: 'lf_secretariat',
    name: 'Secretariat',
    kind: 'animal',
    hall: 'animals',
    region: 'americas',
    place: 'United States',
    era: '1970–1989',
    died: 1989,
    gender: 'none',
    field: 'Racehorse',
    essence: 'Won the Belmont by 31 lengths; nobody else was close.',
    whoTheyWere: 'An American thoroughbred racehorse, widely considered the greatest racehorse of all time.',
    famousFor: 'The 1973 Triple Crown and still-standing speed records.',
    facts: [
      fact('f1', 'He became the first Triple Crown winner in 25 years.', src(wiki('Secretariat_(horse)'), 'first Triple Crown winner in 25 years')),
      fact('f2', 'He still holds the fastest time in all three Triple Crown races.', src(wiki('Secretariat_(horse)'), 'still holding the fastest time record in all three')),
      fact('f3', 'He is widely considered the greatest racehorse of all time.', src(wiki('Secretariat_(horse)'), 'greatest racehorse of all time')),
    ],
    moments: [
      moment('m1', 'He won the Belmont Stakes by 31 lengths, often called the greatest race ever run.', src(wiki('Secretariat_(horse)'), 'won by 31 lengths')),
      moment('m2', 'On the farm he was called Big Red, and was known as a clown who loved cutting up.', src(wiki('Secretariat_(horse)'), 'he was Big Red', 'He was a clown')),
    ],
    angles: [
      angle('a1', '31 lengths', 'What does a horse who won by a mile have in common with you?', 'Sometimes you’re racing nobody but yourself.'),
      angle('a2', 'the clown', 'Can the greatest also be the silliest?', 'Joy and excellence go together just fine.'),
      angle('a3', 'records that last', 'What would you do so well it lasts fifty years?', 'Doing something fully can echo for a long time.'),
      angle('a4', 'a slow debut', 'Why did the greatest horse finish fourth in his first race?', 'Everyone starts somewhere.'),
    ],
    tags: [
      tag('competence', 'high', 'the greatest of all', 'He is considered the greatest racehorse ever.'),
      tag('playfulness', 'high', 'a clown on the farm', 'He was known as a clown who loved cutting up.'),
      tag('self_efficacy', 'high', 'won by thirty-one lengths', 'He won the Belmont by a huge margin.'),
      tag('extraversion', 'high', 'the leader of the crowd', 'He was the leader in the crowd.'),
      tag('conflict_assertiveness', 'high', 'raced to the front', 'He took the lead and kept it.'),
    ],
    vetting: 'Real horse, died 1989; widely admired; no harm shown.',
  },
  {
    id: 'lf_clever_hans',
    name: 'Clever Hans',
    kind: 'animal',
    hall: 'animals',
    region: 'europe',
    place: 'Germany',
    era: 'About 1894–1916',
    died: 1916,
    gender: 'none',
    field: 'Horse',
    essence: 'The horse who seemed to do maths, and taught scientists a lesson.',
    whoTheyWere: 'A horse in Germany who appeared to do arithmetic by tapping his hoof.',
    famousFor: 'The Clever Hans effect, still studied today.',
    facts: [
      fact('f1', 'He appeared to answer maths questions by tapping his hoof.', src(wiki('Clever_Hans'), 'tapping his hoof')),
      fact('f2', 'In 1907 a psychologist showed he was watching the reactions of his trainer.', src(wiki('Clever_Hans'), 'watching the reactions of his trainer')),
      fact('f3', 'The Clever Hans effect, named after him, is still important in science.', src(wiki('Clever_Hans'), 'Clever Hans effect')),
    ],
    moments: [
      moment('m1', 'His owner showed him around Germany and never charged admission.', src(wiki('Clever_Hans'), 'never charged admission')),
      moment('m2', 'His trainer had no idea he was giving Hans the cues.', src(wiki('Clever_Hans'), 'entirely unaware that he was providing such cues')),
    ],
    angles: [
      angle('a1', 'reading the room', 'What does a horse who read people instead of numbers have in common with you?', 'Noticing tiny signals in people is its own kind of clever.'),
      angle('a2', 'the trick', 'Was he fooling anyone, or just paying attention?', 'Being tuned in to people is a real skill.'),
      angle('a3', 'the scientist', 'Why does it help when someone checks how you got the answer?', 'Asking how, not just what, finds the truth.'),
      angle('a4', 'the lesson', 'How does a horse end up in science books?', 'Even a mistake can teach the world something.'),
    ],
    tags: [
      tag('agreeableness', 'high', 'tuned in to people', 'He read his trainer’s tiny cues.'),
      tag('conflict_cooperativeness', 'high', 'gave people what they hoped', 'He responded to what his trainer expected.'),
      tag('locus_of_control', 'low', 'followed the cues', 'His answers came from his trainer’s signals.'),
      tag('competence', 'low', 'no maths after all', 'He was not actually doing the arithmetic.'),
      tag('autonomy', 'low', 'followed his trainer', 'He responded to his trainer’s body language.'),
    ],
    vetting: 'Real horse, died about 1916; a gentle science story; no harm shown.',
  },
];
