import type { LegendFigure } from '../types';
import { angle, fact, moment, src, tag, wiki } from './define';

const HOKUSAI = wiki('Hokusai');
const KAHLO = wiki('Frida_Kahlo');
const BEETHOVEN = wiki('Ludwig_van_Beethoven');
const UMM = wiki('Umm_Kulthum');
const RYOKAN = wiki('Ryōkan');
const RACH = wiki('Sergei_Rachmaninoff');

export const ART_LEGENDS: readonly LegendFigure[] = [
  {
    id: 'lf_hokusai',
    name: 'Katsushika Hokusai',
    kind: 'real',
    hall: 'art',
    region: 'east_asia',
    place: 'Japan',
    era: '1760–1849',
    died: 1849,
    gender: 'man',
    field: 'Painting and printmaking',
    essence: 'Drew the same mountain for decades and never called it finished.',
    whoTheyWere: 'A Japanese painter and printmaker of the Edo period who used at least thirty names in his lifetime.',
    famousFor: 'The Great Wave off Kanagawa, from his series Thirty-Six Views of Mount Fuji.',
    facts: [
      fact('f1', 'His series Thirty-Six Views of Mount Fuji includes The Great Wave off Kanagawa.', src(HOKUSAI, 'Thirty-Six Views of Mount Fuji', 'Great Wave off Kanagawa')),
      fact('f2', 'He was known by at least thirty names during his life, more than any other major Japanese artist.', src(HOKUSAI, 'at least thirty names')),
      fact('f3', 'At 51 he took a new name and began the sketchbooks known as the Hokusai Manga.', src(HOKUSAI, 'at the age of 51', 'Hokusai Manga')),
    ],
    moments: [
      moment(
        'm1',
        'Looking back in his seventies, he wrote that nothing he drew before seventy was worth taking into account, and that he hoped to keep improving into his nineties.',
        src(HOKUSAI, 'nothing worth taking into account', 'at ninety'),
      ),
      moment('m2', 'He kept changing his artist name as his style changed.', src(HOKUSAI, 'changed his name')),
    ],
    angles: [
      angle('a1', 'the restarter', 'What does a printmaker who renamed himself thirty times have in common with you?', 'Starting over under a new name is not quitting. It can be the next draft of you.'),
      angle('a2', 'the late bloomer', 'Why did a man in his seventies think his best work was still ahead?', 'If your best work feels far off, that can be a sign you’re still growing.'),
      angle('a3', 'the same mountain', 'What do you get from drawing one mountain thirty-six ways?', 'Coming back to the same thing with fresh eyes is a skill, not a rut.'),
      angle('a4', 'the sketchbook', 'What happens when a master fills notebooks just for practice?', 'Small daily practice adds up to work people remember.'),
    ],
    tags: [
      tag('growth_mindset', 'high', 'still improving at seventy', 'He believed his skill would keep growing into old age.'),
      tag('openness', 'high', 'kept trying new styles', 'He explored new styles and kept changing his artist name.'),
      tag('playfulness', 'high', 'filled sketchbooks for fun', 'The Hokusai Manga are lively sketches of everyday life.'),
      tag('autonomy', 'high', 'renamed himself, often', 'He chose his own names as his work changed.'),
    ],
    vetting: 'Artist, died 1849; no political office; broadly admired.',
  },
  {
    id: 'lf_frida_kahlo',
    name: 'Frida Kahlo',
    kind: 'real',
    hall: 'art',
    region: 'americas',
    place: 'Mexico',
    era: '1907–1954',
    died: 1954,
    birthday: { md: '07-06', source: src(KAHLO, '6 July 1907') },
    gender: 'woman',
    field: 'Painting',
    essence: 'Painted herself because she was the subject she knew best.',
    whoTheyWere: 'A Mexican painter who began painting while recovering from a bus accident, working from her bed with a mirror above the easel.',
    famousFor: 'Her self-portraits and work inspired by the nature and folk art of Mexico.',
    facts: [
      fact('f1', 'She was injured in a bus accident at eighteen, which caused lifelong pain.', src(KAHLO, 'bus accident at the age of 18')),
      fact('f2', 'Her mother had an easel made so she could paint in bed.', src(KAHLO, 'specially-made easel', 'paint in bed')),
      fact('f3', 'She spent most of her life at La Casa Azul, the Blue House, now the Frida Kahlo Museum.', src(KAHLO, 'La Casa Azul', 'Frida Kahlo Museum')),
    ],
    moments: [
      moment('m1', 'She had a mirror placed above her easel so she could see herself while lying down.', src(KAHLO, 'mirror placed above the easel')),
      moment('m2', 'She explained that she painted herself because she was often alone and was the subject she knew best.', src(KAHLO, 'I paint myself because I am often alone')),
    ],
    angles: [
      angle('a1', 'the mirror', 'What does a painter who worked from her bed have in common with you?', 'The thing that limits you can also become the angle only you can see from.'),
      angle('a2', 'the subject she knew best', 'Why would someone paint the same face over and over?', 'Knowing yourself well is not vanity. It can be your best material.'),
      angle('a3', 'begin again', 'How does a plan for medical school turn into a life in paint?', 'A detour you never wanted can lead somewhere that feels like yours.'),
      angle('a4', 'the blue house', 'What can one home hold for a whole life?', 'The place you come back to can shape your work more than any trip.'),
    ],
    tags: [
      tag('conflict_assertiveness', 'high', 'painted exactly what she felt', 'Her self-portraits show pain and identity without softening them.'),
      tag('autonomy', 'high', 'made her own way to art', 'She turned to painting on her own terms during recovery.'),
      tag('steadiness', 'low', 'felt everything, painted it', 'She turned lifelong pain into the subject of her work.'),
      tag('openness', 'high', 'mixed folk art and self-portrait', 'She drew on Mexican folk art and culture in new ways.'),
    ],
    vetting: 'Painter, died 1954; no office; widely admired (political views mentioned nowhere in the entry).',
  },
  {
    id: 'lf_beethoven',
    name: 'Ludwig van Beethoven',
    kind: 'real',
    hall: 'art',
    region: 'europe',
    place: 'Germany and Austria',
    era: '1770–1827',
    died: 1827,
    gender: 'man',
    field: 'Music',
    essence: 'Kept writing music after he could no longer hear it.',
    whoTheyWere: 'A German composer and pianist who lived in Vienna and kept composing as his hearing faded.',
    famousFor: 'Nine symphonies, including the Ninth, the first major choral symphony.',
    facts: [
      fact('f1', 'He said his hearing loss began in 1798.', src(BEETHOVEN, 'hearing loss began in 1798')),
      fact('f2', 'His Ninth Symphony premiered in 1824.', src(BEETHOVEN, 'the Ninth, premiered in 1824')),
      fact('f3', 'The Ninth was the first major example of a choral symphony.', src(BEETHOVEN, 'first major example of a choral symphony')),
    ],
    moments: [
      moment(
        'm1',
        'At the Ninth’s premiere, the singer Caroline Unger turned him around so he could see the applause he could not hear.',
        src(BEETHOVEN, 'turned Beethoven around to see the applause he could not hear'),
      ),
      moment('m2', 'When singers begged him to change parts of the Ninth, he refused.', src(BEETHOVEN, 'Beethoven refused')),
    ],
    angles: [
      angle('a1', 'the unheard applause', 'What does a composer who couldn’t hear his own premiere have in common with you?', 'Your work can land with people even when you can’t see it landing.'),
      angle('a2', 'no changes', 'Why would someone refuse the singers who begged for an easier part?', 'Holding your ground on the thing you care about most can be worth the friction.'),
      angle('a3', 'the long fade', 'How do you keep making something when the tool you use starts to fail?', 'Adapting how you work can keep the work itself alive.'),
      angle('a4', 'the first of its kind', 'What does it take to add a choir to a symphony?', 'Breaking the usual format is easier when you know the format deeply.'),
    ],
    tags: [
      tag('agreeableness', 'low', 'refused to soften the Ninth', 'He turned down the singers who asked for easier parts.'),
      tag('steadiness', 'low', 'felt the loss deeply', 'His hearing loss weighed on him for decades.'),
      tag('autonomy', 'high', 'wrote it his way', 'He broke the usual symphony form by adding a choir.'),
      tag('attachment_avoidance', 'high', 'kept to himself', 'As his hearing faded, much of his work happened alone.'),
      tag('conflict_cooperativeness', 'low', 'stood firm on the score', 'He held to his own version even when performers objected.'),
    ],
    vetting: 'Composer, died 1827; no office; broadly admired. Entry avoids his darkest letters on purpose.',
  },
  {
    id: 'lf_umm_kulthum',
    name: 'Umm Kulthum',
    kind: 'real',
    hall: 'art',
    region: 'middle_east',
    place: 'Egypt',
    era: '1904–1975',
    died: 1975,
    gender: 'woman',
    field: 'Singing',
    essence: 'Sang on the first Thursday of every month, for forty years.',
    whoTheyWere: 'An Egyptian singer who began as a child, singing beside her father, and became the Arab world’s most celebrated voice.',
    famousFor: 'Monthly radio concerts and a funeral attended by over four million people.',
    facts: [
      fact('f1', 'As a child her father dressed her in boys’ clothes so she could sing in public.', src(UMM, 'dressed her in boys')),
      fact('f2', 'She performed a concert on the first Thursday of every month for forty years.', src(UMM, 'first Thursday of every month for forty years')),
      fact('f3', 'Her funeral in Cairo in 1975 drew a crowd of over four million people.', src(UMM, 'over 4 million people')),
    ],
    moments: [
      moment('m1', 'In 1934 she sang for the first broadcast of Egyptian Radio.', src(UMM, 'inaugural broadcast of the Egyptian Radio')),
      moment('m2', 'She moved to Cairo in the early 1920s, where her career took off.', src(UMM, 'moved to the city of Cairo in the early 1920s')),
    ],
    angles: [
      angle('a1', 'the monthly show', 'What does a singer who showed up every month for forty years have in common with you?', 'Showing up on a set day, again and again, builds something people can count on.'),
      angle('a2', 'the disguise', 'Why would a girl sing in boys’ clothes?', 'Sometimes you find a side door into the thing you love, and walk through it.'),
      angle('a3', 'the voice of millions', 'How does one voice end up loved by four million people at once?', 'The care you put into your craft is felt by people you’ll never meet.'),
      angle('a4', 'the move to Cairo', 'What changes when you take your talent to the big city?', 'Going where your work can grow is a choice you can make on purpose.'),
    ],
    tags: [
      tag('conscientiousness', 'high', 'every first Thursday, forty years', 'She kept a monthly concert schedule for four decades.'),
      tag('relatedness', 'high', 'sang to a whole region', 'Her concerts connected millions of listeners.'),
      tag('competence', 'high', 'owned every stage', 'She became the most distinguished singer of her era.'),
      tag('steadiness', 'high', 'steady for decades', 'Her long monthly run needed steady nerves.'),
      tag('extraversion', 'high', 'lived on stage', 'She performed publicly from childhood on.'),
    ],
    vetting: 'Singer, died 1975; no office; broadly beloved across the Arab world.',
  },
  {
    id: 'lf_ryokan',
    name: 'Ryōkan',
    kind: 'real',
    hall: 'art',
    region: 'east_asia',
    place: 'Japan',
    era: '1758–1831',
    died: 1831,
    gender: 'man',
    field: 'Poetry and calligraphy',
    essence: 'A hermit poet who wished he could give a thief the moon.',
    whoTheyWere: 'A quiet Japanese monk and poet who lived much of his life alone in a mountain hut.',
    famousFor: 'Simple poems about nature, his calligraphy, and stories of his kindness.',
    facts: [
      fact('f1', 'He lived much of his life as a hermit.', src(RYOKAN, 'lived much of his life as a hermit')),
      fact('f2', 'He refused any position as a priest, or even the title of poet.', src(RYOKAN, 'refused to accept any position as a priest')),
      fact('f3', 'He sometimes forgot to beg for food because he was playing with the village children.', src(RYOKAN, 'playing with the children of the nearby village')),
    ],
    moments: [
      moment(
        'm1',
        'As the story goes, a thief found nothing to steal in his hut, so Ryōkan gave him his clothes, then sat watching the moon, wishing he could have given him that too.',
        src(RYOKAN, 'thief', 'I wish I could have given him this beautiful moon'),
      ),
      moment('m2', 'His poems show a good sense of humour and a man who didn’t take himself too seriously.', src(RYOKAN, 'good sense of humour')),
    ],
    angles: [
      angle('a1', 'the moon', 'What does a poet who gave a thief his clothes have in common with you?', 'Letting go of what you can’t keep can leave room for what you actually love.'),
      angle('a2', 'no title', 'Why would someone refuse to be called a poet?', 'You can do the thing well without needing the label that comes with it.'),
      angle('a3', 'playing instead', 'What happens when you forget your errands because the game is better?', 'Time spent playing isn’t lost. It can be the part of the day that matters.'),
      angle('a4', 'enough', 'How much do you really need in one small hut?', 'Having less can make what’s left feel like plenty.'),
    ],
    tags: [
      tag('locus_of_control', 'low', 'let things go easily', 'He met being robbed with calm acceptance.'),
      tag('relatedness', 'low', 'content alone in his hut', 'He lived much of his life by himself on a mountain.'),
      tag('playfulness', 'high', 'played with the village kids', 'He forgot to beg for food because he was playing with children.'),
      tag('conflict_cooperativeness', 'high', 'gave the thief his clothes', 'He gave away what little he had to the man who robbed him.'),
    ],
    vetting: 'Hermit poet, died 1831; refused every religious post (not a founder or leader); broadly loved.',
  },
  {
    id: 'lf_rachmaninoff',
    name: 'Sergei Rachmaninoff',
    kind: 'real',
    hall: 'art',
    region: 'europe',
    place: 'Russia and the United States',
    era: '1873–1943',
    died: 1943,
    birthday: { md: '04-01', source: src(RACH, '1 April') },
    gender: 'man',
    field: 'Music',
    essence: 'Wrote his most loved concerto after three years of not writing.',
    whoTheyWere: 'A Russian composer and one of the finest pianists of his day, who later lived in the United States.',
    famousFor: 'His Piano Concerto No. 2, which marked his comeback as a composer.',
    facts: [
      fact('f1', 'After his First Symphony was badly received in 1897, he went through three years of writer’s block.', src(RACH, 'lasted three years', 'writer\'s block')),
      fact('f2', 'He gave piano lessons to support himself during those years.', src(RACH, 'he gave piano lessons')),
      fact('f3', 'His Piano Concerto No. 2 was finished in April 1901 and dedicated to the doctor who helped him.', src(RACH, 'finished in April 1901', 'dedicated to Dahl')),
    ],
    moments: [
      moment('m1', 'In 1900 he met almost daily with Nikolai Dahl, a physician and amateur musician, to get back to composing.', src(RACH, 'Nikolai Dahl', 'on a daily basis')),
      moment('m2', 'When the full concerto was first performed in 1901, it was received with enthusiasm.', src(RACH, 'enthusiastically received')),
    ],
    angles: [
      angle('a1', 'the comeback', 'What does a composer stuck for three years have in common with you?', 'A long stall is not the end of the story. It can be the part right before the turn.'),
      angle('a2', 'asking for help', 'Who dedicates their masterpiece to the person who helped them start again?', 'Getting help is part of the work, not a detour from it.'),
      angle('a3', 'the day job', 'Why would a great composer spend years teaching scales?', 'Paying the bills while you wait for the spark is nothing to hide.'),
      angle('a4', 'one bad review', 'How much can one bad night really cost you?', 'A harsh reaction can feel final. Your next piece still gets written.'),
    ],
    tags: [
      tag('competence', 'low', 'doubted his own skill', 'After one bad premiere he couldn’t compose for years.'),
      tag('steadiness', 'low', 'hit hard by criticism', 'The failed premiere left him heavily depressed for a time.'),
      tag('attachment_anxiety', 'high', 'felt every reaction', 'How people received his work affected him deeply.'),
      tag('growth_mindset', 'high', 'worked his way back', 'He met with a doctor almost daily to return to composing.'),
      tag('self_efficacy', 'low', 'unsure he could write', 'For three years he composed very little.'),
    ],
    vetting: 'Composer and pianist, died 1943; no office; broadly admired. Struggles described gently, no clinical detail.',
  },
];
