import type { LegendFigure } from '../types';
import { angle, fact, moment, src, tag, wiki } from './define';

const HOKUSAI = wiki('Hokusai');
const KAHLO = wiki('Frida_Kahlo');

export const ART_LEGENDS: readonly LegendFigure[] = [
  {
    id: 'lf_hokusai',
    name: 'Katsushika Hokusai',
    kind: 'real',
    hall: 'art',
    region: 'east_asia',
    place: 'Japan',
    era: '1760–1849',
    died: 1849,
    gender: 'man',
    field: 'Painting and printmaking',
    essence: 'Drew the same mountain for decades and never called it finished.',
    whoTheyWere: 'A Japanese painter and printmaker of the Edo period who used at least thirty names in his lifetime.',
    famousFor: 'The Great Wave off Kanagawa, from his series Thirty-Six Views of Mount Fuji.',
    facts: [
      fact('f1', 'His series Thirty-Six Views of Mount Fuji includes The Great Wave off Kanagawa.', src(HOKUSAI, 'Thirty-Six Views of Mount Fuji', 'Great Wave off Kanagawa')),
      fact('f2', 'He was known by at least thirty names during his life, more than any other major Japanese artist.', src(HOKUSAI, 'at least thirty names')),
      fact('f3', 'At 51 he took a new name and began the sketchbooks known as the Hokusai Manga.', src(HOKUSAI, 'at the age of 51', 'Hokusai Manga')),
    ],
    moments: [
      moment(
        'm1',
        'Looking back in his seventies, he wrote that nothing he drew before seventy was worth taking into account, and that he hoped to keep improving into his nineties.',
        src(HOKUSAI, 'nothing worth taking into account', 'at ninety'),
      ),
      moment('m2', 'He kept changing his artist name as his style changed.', src(HOKUSAI, 'changed his name')),
    ],
    angles: [
      angle('a1', 'the restarter', 'What does a printmaker who renamed himself thirty times have in common with you?', 'Starting over under a new name is not quitting. It can be the next draft of you.'),
      angle('a2', 'the late bloomer', 'Why did a man in his seventies think his best work was still ahead?', 'If your best work feels far off, that can be a sign you’re still growing.'),
      angle('a3', 'the same mountain', 'What do you get from drawing one mountain thirty-six ways?', 'Coming back to the same thing with fresh eyes is a skill, not a rut.'),
      angle('a4', 'the sketchbook', 'What happens when a master fills notebooks just for practice?', 'Small daily practice adds up to work people remember.'),
    ],
    tags: [
      tag('growth_mindset', 'high', 'still improving at seventy', 'He believed his skill would keep growing into old age.'),
      tag('openness', 'high', 'kept trying new styles', 'He explored new styles and kept changing his artist name.'),
      tag('playfulness', 'high', 'filled sketchbooks for fun', 'The Hokusai Manga are lively sketches of everyday life.'),
      tag('autonomy', 'high', 'renamed himself, often', 'He chose his own names as his work changed.'),
    ],
    vetting: 'Artist, died 1849; no political office; broadly admired.',
  },
  {
    id: 'lf_frida_kahlo',
    name: 'Frida Kahlo',
    kind: 'real',
    hall: 'art',
    region: 'americas',
    place: 'Mexico',
    era: '1907–1954',
    died: 1954,
    birthday: { md: '07-06', source: src(KAHLO, '6 July 1907') },
    gender: 'woman',
    field: 'Painting',
    essence: 'Painted herself because she was the subject she knew best.',
    whoTheyWere: 'A Mexican painter who began painting while recovering from a bus accident, working from her bed with a mirror above the easel.',
    famousFor: 'Her self-portraits and work inspired by the nature and folk art of Mexico.',
    facts: [
      fact('f1', 'She was injured in a bus accident at eighteen, which caused lifelong pain.', src(KAHLO, 'bus accident at the age of 18')),
      fact('f2', 'Her mother had an easel made so she could paint in bed.', src(KAHLO, 'specially-made easel', 'paint in bed')),
      fact('f3', 'She spent most of her life at La Casa Azul, the Blue House, now the Frida Kahlo Museum.', src(KAHLO, 'La Casa Azul', 'Frida Kahlo Museum')),
    ],
    moments: [
      moment('m1', 'She had a mirror placed above her easel so she could see herself while lying down.', src(KAHLO, 'mirror placed above the easel')),
      moment('m2', 'She explained that she painted herself because she was often alone and was the subject she knew best.', src(KAHLO, 'I paint myself because I am often alone')),
    ],
    angles: [
      angle('a1', 'the mirror', 'What does a painter who worked from her bed have in common with you?', 'The thing that limits you can also become the angle only you can see from.'),
      angle('a2', 'the subject she knew best', 'Why would someone paint the same face over and over?', 'Knowing yourself well is not vanity. It can be your best material.'),
      angle('a3', 'begin again', 'How does a plan for medical school turn into a life in paint?', 'A detour you never wanted can lead somewhere that feels like yours.'),
      angle('a4', 'the blue house', 'What can one home hold for a whole life?', 'The place you come back to can shape your work more than any trip.'),
    ],
    tags: [
      tag('conflict_assertiveness', 'high', 'painted exactly what she felt', 'Her self-portraits show pain and identity without softening them.'),
      tag('autonomy', 'high', 'made her own way to art', 'She turned to painting on her own terms during recovery.'),
      tag('steadiness', 'low', 'felt everything, painted it', 'She turned lifelong pain into the subject of her work.'),
      tag('openness', 'high', 'mixed folk art and self-portrait', 'She drew on Mexican folk art and culture in new ways.'),
      tag('agreeableness', 'low', 'painted herself honestly', 'She painted herself because she was the subject she knew best.'),
    ],
    vetting: 'Painter, died 1954; no office; widely admired (political views mentioned nowhere in the entry).',
  },
  {
    id: 'lf_leonardo_artist',
    name: 'Leonardo da Vinci',
    role: 'as an artist',
    roleOf: 'Leonardo da Vinci',
    kind: 'real',
    hall: 'art',
    region: 'europe',
    place: 'Italy',
    era: '1452–1519',
    died: 1519,
    birthday: { md: '04-15', source: src(wiki('Leonardo_da_Vinci'), '15 April 1452') },
    gender: 'man',
    field: 'Painting',
    essence: 'Painted the world’s most famous smile, and left plenty unfinished.',
    whoTheyWere: 'An Italian polymath of the High Renaissance, active as a painter, draughtsman, engineer and scientist.',
    famousFor: 'The Mona Lisa, The Last Supper and the Vitruvian Man drawing.',
    facts: [
      fact('f1', 'The Mona Lisa is regarded as the world’s most famous painting.', src(wiki('Leonardo_da_Vinci'), "Mona Lisa is regarded as the world's most famous painting")),
      fact('f2', 'He has fewer than 25 attributed major works, including numerous unfinished works.', src(wiki('Leonardo_da_Vinci'), 'fewer than 25 attributed major works', 'numerous unfinished works')),
      fact('f3', 'His Vitruvian Man drawing is regarded as a cultural icon.', src(wiki('Leonardo_da_Vinci'), 'Vitruvian Man')),
    ],
    moments: [
      moment('m1', 'With fewer than 25 major works, many unfinished, he still made some of the most influential paintings in the Western canon.', src(wiki('Leonardo_da_Vinci'), 'most influential paintings in the Western canon')),
      moment('m2', 'His notebooks mix drawings and notes on painting with anatomy, botany and astronomy.', src(wiki('Leonardo_da_Vinci'), 'notebooks, in which he made drawings and notes')),
    ],
    angles: [
      angle('a1', 'the unfinished pile', 'What does the painter of the Mona Lisa have in common with your half-done projects?', 'Unfinished things are not wasted. Some of them lead to the work that lasts.'),
      angle('a2', 'few, but famous', 'How do fewer than 25 major works change the world?', 'A small number of things done with care can matter more than a long list.'),
      angle('a3', 'art and science', 'What does a painter learn from studying anatomy?', 'Learning outside your field can make the thing you love better.'),
      angle('a4', 'the smile', 'Why is one quiet smile still the most famous painting there is?', 'Subtle work can stay with people longer than loud work.'),
    ],
    tags: [
      tag('openness', 'high', 'painted and studied everything', 'He mixed painting with anatomy and science.'),
      tag('conscientiousness', 'low', 'left many works unfinished', 'Many of his works were never completed.'),
      tag('growth_mindset', 'high', 'kept studying to paint better', 'His notebooks show constant study alongside his painting.'),
      tag('playfulness', 'high', 'followed his curiosity', 'He jumped between subjects that interested him.'),
    ],
    vetting: 'Artist, died 1519; no office; broadly admired.',
  },
  {
    id: 'lf_vincent_van_gogh',
    name: 'Vincent van Gogh',
    kind: 'real',
    hall: 'art',
    region: 'europe',
    place: 'Netherlands and France',
    era: '1853–1890',
    died: 1890,
    birthday: { md: '03-30', source: src(wiki('Vincent_van_Gogh'), '30 March 1853') },
    gender: 'man',
    field: 'Painting',
    essence: 'Made about 2,100 artworks in just over a decade.',
    whoTheyWere: 'A Dutch Post-Impressionist painter who took up painting in 1881 and wrote long letters to his brother Theo.',
    famousFor: 'Bold, colourful paintings like his sunflowers and Starry Night Over the Rhône.',
    facts: [
      fact('f1', 'In just over a decade he created about 2,100 artworks, including around 860 oil paintings.', src(wiki('Vincent_van_Gogh'), 'about 2,100 artworks', 'around 860 oil paintings')),
      fact('f2', 'He took up painting in 1881.', src(wiki('Vincent_van_Gogh'), 'taking up painting in 1881')),
      fact('f3', 'His younger brother Theo supported him, and the two kept up a long correspondence by letter.', src(wiki('Vincent_van_Gogh'), 'His younger brother Theo supported him financially')),
    ],
    moments: [
      moment('m1', 'Most of his oil paintings came in the last two years of his life.', src(wiki('Vincent_van_Gogh'), 'most of them in the last two years of his life')),
      moment('m2', 'His letters to Theo are the fullest record we have of his life and thinking.', src(wiki('Vincent_van_Gogh'), 'most comprehensive primary source on Van Gogh is his correspondence with his younger brother')),
    ],
    angles: [
      angle('a1', 'letters to Theo', 'What does a painter who wrote hundreds of letters to his brother have in common with you?', 'Having one person you tell everything to can keep your work going.'),
      angle('a2', 'a late start', 'What can someone do in ten years if they start painting in their late twenties?', 'Starting later doesn’t limit how much you can make.'),
      angle('a3', 'the sunflowers', 'Why paint the same flowers again and again?', 'Coming back to one subject is how you find your own style.'),
      angle('a4', 'all that colour', 'What happens when you paint what you feel, not just what you see?', 'Bringing your own feeling into your work is what makes it yours.'),
    ],
    tags: [
      tag('relatedness', 'high', 'wrote to his brother constantly', 'His letters to Theo ran through his whole life.'),
      tag('steadiness', 'low', 'felt everything strongly', 'His paintings carry strong feeling in bold colour.'),
      tag('conscientiousness', 'high', 'painted almost every day', 'He made about 2,100 artworks in just over a decade.'),
      tag('attachment_avoidance', 'low', 'leaned on Theo', 'His brother supported him through his working life.'),
    ],
    vetting: 'Painter, died 1890; no office; broadly beloved. Entry avoids his illness and death.',
  },
  {
    id: 'lf_antoni_gaudi',
    name: 'Antoni Gaudí',
    kind: 'real',
    hall: 'art',
    region: 'europe',
    place: 'Catalonia, Spain',
    era: '1852–1926',
    died: 1926,
    birthday: { md: '06-25', source: src(wiki('Antoni_Gaudí'), '25 June 1852') },
    gender: 'man',
    field: 'Architecture',
    essence: 'Built churches that look like they grew instead of being built.',
    whoTheyWere: 'A Catalan architect and designer whose buildings in Barcelona have a style all their own.',
    famousFor: 'The Sagrada Família, the most-visited monument in Spain.',
    facts: [
      fact('f1', 'His magnum opus is the Sagrada Família in Barcelona.', src(wiki('Antoni_Gaudí'), 'magnum opus, the Sagrada Família')),
      fact('f2', 'Seven of his works were declared UNESCO World Heritage Sites.', src(wiki('Antoni_Gaudí'), 'seven of his works were declared UNESCO World Heritage Sites')),
      fact('f3', 'His work was influenced by architecture, nature and religion.', src(wiki('Antoni_Gaudí'), 'architecture, nature, and religion')),
    ],
    moments: [
      moment('m1', 'His first projects were lampposts for the Plaça Reial in Barcelona.', src(wiki('Antoni_Gaudí'), 'lampposts he designed for the Plaça Reial')),
      moment('m2', 'He considered every detail of his creations, combining ceramics, stained glass and wrought ironwork.', src(wiki('Antoni_Gaudí'), 'considered every detail of his creations')),
    ],
    angles: [
      angle('a1', 'from lampposts up', 'What does an architect who started with lampposts have in common with you?', 'Small first jobs can be the start of something people visit from everywhere.'),
      angle('a2', 'every detail', 'Why would someone care about every tile and railing?', 'Caring about the small parts is what makes the whole thing feel alive.'),
      angle('a3', 'nature as a teacher', 'What can a tree teach someone who builds churches?', 'Borrowing from what already works around you is a smart way to create.'),
      angle('a4', 'the never-ending project', 'What is it like to start something that outlives you?', 'Some work is worth starting even if you won’t see it finished.'),
    ],
    tags: [
      tag('openness', 'high', 'designed like nobody else', 'His buildings have a style entirely their own.'),
      tag('conscientiousness', 'high', 'cared about every detail', 'He considered every detail of his creations.'),
      tag('autonomy', 'high', 'followed his own style', 'His work stood apart from the styles of his time.'),
      tag('extraversion', 'low', 'lived for the work', 'Most of his life went into his buildings.'),
    ],
    vetting: 'Architect, died 1926; no office; broadly admired.',
  },
  {
    id: 'lf_claude_monet',
    name: 'Claude Monet',
    kind: 'real',
    hall: 'art',
    region: 'europe',
    place: 'France',
    era: '1840–1926',
    died: 1926,
    birthday: { md: '11-14', source: src(wiki('Claude_Monet'), '14 November 1840') },
    gender: 'man',
    field: 'Painting',
    essence: 'Painted the same haystacks over and over to catch the light.',
    whoTheyWere: 'A French painter and founder of Impressionism who loved painting outdoors.',
    famousFor: 'Impression, Sunrise, which gave Impressionism its name, and his water lilies.',
    facts: [
      fact('f1', 'The term Impressionism comes from the title of his painting Impression, Sunrise.', src(wiki('Claude_Monet'), 'derived from the title of his painting Impression, Sunrise')),
      fact('f2', 'He painted series like haystacks and Rouen Cathedral to capture changing light and seasons.', src(wiki('Claude_Monet'), 'series of haystacks', 'changing of light')),
      fact('f3', 'From 1883 he lived in Giverny, where he made a garden with a water-lily pond.', src(wiki('Claude_Monet'), 'From 1883, Monet lived in Giverny', 'water-lily pond')),
    ],
    moments: [
      moment('m1', 'The water lilies in his own garden occupied him for the last 20 years of his life.', src(wiki('Claude_Monet'), 'occupied him for the last 20 years of his life')),
      moment('m2', 'An early mentor, Eugène Boudin, introduced him to painting outdoors.', src(wiki('Claude_Monet'), 'Eugène Boudin, who introduced him to the concept of plein air painting')),
    ],
    angles: [
      angle('a1', 'the same haystack', 'What does a painter who painted haystacks again and again have in common with you?', 'Looking at the same thing at different times shows you how much changes.'),
      angle('a2', 'his own garden', 'Why build a garden just to paint it?', 'Making the setting you need is a smart way to do your best work.'),
      angle('a3', 'a name from a title', 'How does one painting name a whole movement?', 'Sometimes the thing you make gives a name to what others were feeling too.'),
      angle('a4', 'the mentor', 'Who first takes you outside to see things differently?', 'The right nudge from someone else can set the direction of your life.'),
    ],
    tags: [
      tag('openness', 'high', 'chased changing light', 'He painted the same scene at many times of day.'),
      tag('conscientiousness', 'high', 'painted series after series', 'His series took years of steady work.'),
      tag('extraversion', 'low', 'happiest in his garden', 'His later life centred on his garden at Giverny.'),
      tag('growth_mindset', 'high', 'kept painting the pond', 'He painted water lilies for the last 20 years of his life.'),
    ],
    vetting: 'Painter, died 1926; no office; broadly admired.',
  },
  {
    id: 'lf_georgia_okeeffe',
    name: 'Georgia O’Keeffe',
    kind: 'real',
    hall: 'art',
    region: 'americas',
    place: 'United States',
    era: '1887–1986',
    died: 1986,
    birthday: { md: '11-15', source: src(wiki("Georgia_O'Keeffe"), 'November 15, 1887') },
    gender: 'woman',
    field: 'Painting',
    essence: 'Painted flowers so large you had to look closely.',
    whoTheyWere: 'An American modernist painter whose career spanned seven decades and stayed independent of major art movements.',
    famousFor: 'Her paintings of flowers, hills and the desert landscapes of New Mexico.',
    facts: [
      fact('f1', 'She is called the “Mother of American modernism”.', src(wiki("Georgia_O'Keeffe"), 'Mother of American modernism')),
      fact('f2', 'Her career spanned seven decades and stayed largely independent of major art movements.', src(wiki("Georgia_O'Keeffe"), 'career spanned seven decades', 'independent of major art movements')),
      fact('f3', 'She painted New York skyscrapers from a 30th floor apartment.', src(wiki("Georgia_O'Keeffe"), '30th floor apartment')),
    ],
    moments: [
      moment('m1', 'She began spending part of each year in the Southwest, and later moved to New Mexico for good.', src(wiki("Georgia_O'Keeffe"), 'spending part of the year in the Southwest', 'moved to New Mexico')),
      moment('m2', 'She lived for 40 years at her home and studio in New Mexico.', src(wiki("Georgia_O'Keeffe"), 'lived for the next 40 years')),
    ],
    angles: [
      angle('a1', 'the close-up', 'What does a painter who made flowers huge have in common with you?', 'Making the small thing big is a way of saying: look, this matters.'),
      angle('a2', 'her own movement', 'Who paints for seven decades without joining a movement?', 'Your work can stand on its own without fitting a label.'),
      angle('a3', 'the move west', 'What changes when you move somewhere that finally fits?', 'The place you live can change what you notice and make.'),
      angle('a4', 'city and desert', 'Can the same eye love skyscrapers and empty hills?', 'You can love very different things and still be one person.'),
    ],
    tags: [
      tag('autonomy', 'high', 'stayed outside every movement', 'Her work remained independent of major art movements.'),
      tag('relatedness', 'low', 'at home in the desert', 'She lived for decades in the New Mexico landscape.'),
      tag('openness', 'high', 'saw flowers differently', 'She painted natural forms in a new, close-up way.'),
      tag('steadiness', 'high', 'seven decades of work', 'Her career spanned seven decades.'),
      tag('growth_mindset', 'low', 'settled in New Mexico', 'She lived for 40 years at her home in New Mexico.'),
    ],
    vetting: 'Painter, died 1986; no office; broadly admired.',
  },
  {
    id: 'lf_michelangelo',
    name: 'Michelangelo',
    kind: 'real',
    hall: 'art',
    region: 'europe',
    place: 'Italy',
    era: '1475–1564',
    died: 1564,
    birthday: { md: '03-06', source: src(wiki('Michelangelo'), '6 March 1475') },
    gender: 'man',
    field: 'Sculpture and painting',
    essence: 'Didn’t think he was a painter, then painted the Sistine Chapel ceiling.',
    whoTheyWere: 'An Italian sculptor, painter, architect and poet of the High Renaissance who became famous young.',
    famousFor: 'The statue of David and the frescoes of the Sistine Chapel ceiling.',
    facts: [
      fact('f1', 'He sculpted the Pietà and David before the age of 30.', src(wiki('Michelangelo'), 'the Pietà and David, were sculpted before the age of 30')),
      fact('f2', 'He painted the scenes from Genesis on the ceiling of the Sistine Chapel in Rome.', src(wiki('Michelangelo'), 'ceiling of the Sistine Chapel')),
      fact('f3', 'He was also an architect and a poet.', src(wiki('Michelangelo'), 'sculptor, painter, architect, and poet')),
    ],
    moments: [
      moment('m1', 'Although he did not see himself as a painter, he created two of the most influential frescoes in Western art.', src(wiki('Michelangelo'), 'did not consider himself a painter')),
      moment('m2', 'After the first scaffolding came down on the ceiling, he painted the figures larger.', src(wiki('Michelangelo'), 'after the initial scaffolding had been removed', 'made the figures larger')),
    ],
    angles: [
      angle('a1', 'not a painter', 'What does a sculptor who didn’t call himself a painter have in common with you?', 'You can be great at something you don’t feel is your thing yet.'),
      angle('a2', 'step back, then adjust', 'Why change your style halfway through a ceiling?', 'Stepping back to see your work is how you know what to change.'),
      angle('a3', 'early fame', 'What do you do after your best-known work comes before thirty?', 'Early success is a start, not a ceiling.'),
      angle('a4', 'many crafts', 'Can one person be a sculptor, painter, architect and poet?', 'You don’t have to pick just one way to express yourself.'),
    ],
    tags: [
      tag('competence', 'high', 'mastered stone young', 'He sculpted David before he was 30.'),
      tag('self_efficacy', 'low', 'didn’t see himself as a painter', 'He doubted himself as a painter, then painted the ceiling.'),
      tag('growth_mindset', 'high', 'adjusted mid-ceiling', 'He changed the size of his figures after seeing the work.'),
      tag('conscientiousness', 'high', 'years on one ceiling', 'The Sistine frescoes took sustained, careful work.'),
    ],
    vetting: 'Artist, died 1564; no office; broadly admired.',
  },
  {
    id: 'lf_amrita_sher_gil',
    name: 'Amrita Sher-Gil',
    kind: 'real',
    hall: 'art',
    region: 'south_asia',
    place: 'Hungary and India',
    era: '1913–1941',
    died: 1941,
    birthday: { md: '01-30', source: src(wiki('Amrita_Sher-Gil'), '30 January 1913') },
    gender: 'woman',
    field: 'Painting',
    essence: 'Mixed Paris training with Indian life and made something new.',
    whoTheyWere: 'A Hungarian–Indian painter, called a pioneer of modern Indian art.',
    famousFor: 'Blending Western and traditional Indian art in her paintings.',
    facts: [
      fact('f1', 'She has been called one of the greatest avant-garde women artists of the early 20th century.', src(wiki('Amrita_Sher-Gil'), 'greatest avant-garde women artists of the early 20th century')),
      fact('f2', 'At sixteen she sailed to Europe with her mother to train as a painter in Paris.', src(wiki('Amrita_Sher-Gil'), 'At sixteen, Sher-Gil sailed to Europe with her mother to train as a painter in Paris')),
      fact('f3', 'She is sometimes known as India’s Frida Kahlo for the way she blended Western and traditional art.', src(wiki('Amrita_Sher-Gil'), "India's Frida Kahlo")),
    ],
    moments: [
      moment('m1', 'She trained in Paris first at the Académie de la Grande Chaumière.', src(wiki('Amrita_Sher-Gil'), 'Académie de la Grande Chaumière')),
      moment('m2', 'On her 103rd birthday, Google celebrated her with a Doodle.', src(wiki('Amrita_Sher-Gil'), 'Google celebrated her 103rd birthday')),
    ],
    angles: [
      angle('a1', 'two worlds', 'What does a painter with one foot in Paris and one in India have in common with you?', 'Being between two places can be exactly what makes your view new.'),
      angle('a2', 'sixteen and sailing', 'What does it take to cross the world at sixteen to learn something?', 'Going where the training is takes courage at any age.'),
      angle('a3', 'the blend', 'How do you mix two traditions without losing either?', 'You can keep what you love from both sides and make something of your own.'),
      angle('a4', 'a short, bright career', 'How much can someone make in a short time?', 'The size of your impact isn’t measured in years.'),
    ],
    tags: [
      tag('openness', 'high', 'blended two art worlds', 'She mixed Western and traditional Indian art.'),
      tag('self_efficacy', 'high', 'off to Paris at sixteen', 'She went abroad young to train as a painter.'),
      tag('autonomy', 'high', 'her own modern style', 'She is called a pioneer of modern Indian art.'),
      tag('conflict_assertiveness', 'high', 'painted boldly', 'Her style was described as revolutionary.'),
    ],
    vetting: 'Painter, died 1941; no office; broadly admired.',
  },
  {
    id: 'lf_tove_jansson',
    name: 'Tove Jansson',
    kind: 'real',
    hall: 'art',
    region: 'europe',
    place: 'Finland',
    era: '1914–2001',
    died: 2001,
    birthday: { md: '08-09', source: src(wiki('Tove_Jansson'), '9 August 1914') },
    gender: 'woman',
    field: 'Illustration and writing',
    essence: 'Drew the Moomins and spent summers on a tiny island.',
    whoTheyWere: 'A Finland-Swedish author, painter and illustrator, raised by artist parents.',
    famousFor: 'The Moomin books and comic strips.',
    facts: [
      fact('f1', 'She wrote the Moomin novel series for children, starting in 1945.', src(wiki('Tove_Jansson'), 'Moomin novel series for children', '1945')),
      fact('f2', 'She was an author, novelist, comic strip author, painter and illustrator.', src(wiki('Tove_Jansson'), 'author, novelist and comic strip author, painter and illustrator')),
      fact('f3', 'Her mother was an illustrator and postage stamp designer, and her father a sculptor.', src(wiki('Tove_Jansson'), 'her mother an illustrator and postage stamp designer, her father a sculptor')),
    ],
    moments: [
      moment('m1', 'Her family spent summers in a rented cottage on one of the islands of Pellinki.', src(wiki('Tove_Jansson'), 'summers in a rented cottage on one of the islands of Pellinki')),
      moment('m2', 'Later she and her partner spent summers on the small island of Klovharu, filmed for hours of home footage.', src(wiki('Tove_Jansson'), 'Klovharu island in Pellinki')),
    ],
    angles: [
      angle('a1', 'the island summer', 'What does an artist who spent summers on a tiny island have in common with you?', 'Getting away to a small quiet place can be where your ideas grow.'),
      angle('a2', 'stories for all ages', 'Why do children’s stories land with grown-ups too?', 'Gentle stories can carry big feelings.'),
      angle('a3', 'an artistic family', 'What do you take from the people who raised you?', 'You can build on what you were given and still make it your own.'),
      angle('a4', 'many hats', 'Author, painter, comic artist: why choose?', 'Working in more than one form can keep each one fresh.'),
    ],
    tags: [
      tag('playfulness', 'high', 'invented the Moomins', 'She created a whole playful world for children.'),
      tag('relatedness', 'low', 'loved island solitude', 'She spent long summers on a small, remote island.'),
      tag('openness', 'high', 'worked in many forms', 'She wrote, painted, illustrated and drew comics.'),
      tag('attachment_avoidance', 'high', 'kept a private island life', 'Her summers away were quiet and private.'),
      tag('growth_mindset', 'low', 'the same island each summer', 'She spent her summers on a small island in Pellinki.'),
    ],
    vetting: 'Author and artist, died 2001; no office; broadly beloved.',
  },
];
