import type { LegendFigure } from '../types';
import { angle, fact, moment, src, tag, wiki } from './define';

const TUBMAN = wiki('Harriet_Tubman');

export const CHANGEMAKER_LEGENDS: readonly LegendFigure[] = [
  {
    id: 'lf_harriet_tubman',
    name: 'Harriet Tubman',
    kind: 'real',
    hall: 'changemakers',
    region: 'americas',
    place: 'United States',
    era: 'c. 1822–1913',
    died: 1913,
    gender: 'woman',
    field: 'Abolition and rescue',
    essence: 'Went back, again and again, and never lost a passenger.',
    whoTheyWere: 'An American abolitionist who escaped slavery and then returned to guide others to freedom.',
    famousFor: 'About 13 missions on the Underground Railroad, rescuing about 70 people.',
    facts: [
      fact('f1', 'After escaping slavery she made some 13 missions to rescue about 70 enslaved people.', src(TUBMAN, 'some 13 missions to rescue approximately 70 enslaved people')),
      fact('f2', 'People called her “Moses”.', src(TUBMAN, '"Moses", as she was called')),
      fact('f3', 'She travelled by night and in extreme secrecy.', src(TUBMAN, 'traveled by night and in extreme secrecy')),
    ],
    moments: [
      moment('m1', 'She later said she “never lost a passenger”.', src(TUBMAN, 'never lost a passenger')),
      moment('m2', 'After the Fugitive Slave Act of 1850, she guided people farther north, into Canada, and helped them find work.', src(TUBMAN, 'Fugitive Slave Act of 1850', 'find work')),
    ],
    angles: [
      angle('a1', 'going back', 'What does a woman who kept returning for others have in common with you?', 'Getting free is one thing. Going back for your people is another kind of brave.'),
      angle('a2', 'never lost a passenger', 'How do you keep everyone safe on the hardest trip there is?', 'Being responsible for others can make you sharper, not smaller.'),
      angle('a3', 'by night', 'What can you do quietly that others never see?', 'Not every important thing needs an audience.'),
      angle('a4', 'one group at a time', 'How do you free seventy people?', 'Big things get done in small, repeated trips.'),
    ],
    tags: [
      tag('self_efficacy', 'high', 'went back, again and again', 'She returned on mission after mission.'),
      tag('conflict_cooperativeness', 'high', 'risked everything for others', 'She guided others to freedom at great personal risk.'),
      tag('steadiness', 'high', 'calm under pressure', 'She never lost a passenger on dangerous night journeys.'),
      tag('competence', 'high', 'knew every route', 'She led about 13 successful missions.'),
      tag('attachment_anxiety', 'high', 'went back for everyone', 'She went back again and again for others.'),
    ],
    vetting: 'Abolitionist, died 1913; no political office; broadly admired. Entry focuses on rescue, not war.',
  },
  {
    id: 'lf_rosa_parks',
    name: 'Rosa Parks',
    kind: 'real',
    hall: 'changemakers',
    region: 'americas',
    place: 'United States',
    era: '1913–2005',
    died: 2005,
    birthday: { md: '02-04', source: src(wiki('Rosa_Parks'), 'February 4, 1913') },
    gender: 'woman',
    field: 'Civil rights',
    essence: 'Stayed in her seat and started a movement.',
    whoTheyWere: 'An American civil rights activist who worked as a seamstress in Montgomery, Alabama.',
    famousFor: 'Refusing to give up her bus seat in 1955, which sparked the Montgomery bus boycott.',
    facts: [
      fact('f1', 'In 1955 she refused to move from her seat on a bus in Montgomery, Alabama, defying segregation laws.', src(wiki('Rosa_Parks'), 'refusal to move from her seat on a bus in Montgomery')),
      fact('f2', 'Her refusal sparked the Montgomery bus boycott.', src(wiki('Rosa_Parks'), 'sparked the Montgomery bus boycott')),
      fact('f3', 'From 1954 she worked as a seamstress.', src(wiki('Rosa_Parks'), 'worked as a seamstress')),
    ],
    moments: [
      moment('m1', 'On 1 December 1955 she left work, bought a few things at a drug store, and walked to Court Square to wait for her bus.', src(wiki('Rosa_Parks'), 'December 1, 1955', 'wait for her bus')),
      moment('m2', 'She is sometimes called the mother of the civil rights movement.', src(wiki('Rosa_Parks'), 'mother')),
    ],
    angles: [
      angle('a1', 'staying put', 'What does a seamstress who stayed in her seat have in common with you?', 'Quietly refusing what’s wrong can be louder than shouting.'),
      angle('a2', 'an ordinary evening', 'How does an ordinary trip home change history?', 'Big moments often arrive on normal days.'),
      angle('a3', 'the boycott', 'What happens when one action inspires many?', 'Your one brave choice can give other people courage.'),
      angle('a4', 'after work', 'What does it take to stand firm when you’re tired?', 'Holding your ground doesn’t need a speech, just steadiness.'),
    ],
    tags: [
      tag('conflict_cooperativeness', 'low', 'wouldn’t give up her seat', 'She refused to move from her seat.'),
      tag('steadiness', 'high', 'calm and firm', 'She stood firm quietly.'),
      tag('conflict_assertiveness', 'low', 'brave without a speech', 'Her protest was a quiet refusal.'),
      tag('locus_of_control', 'high', 'changed things by acting', 'Her action sparked a boycott.'),
    ],
    vetting: 'Activist, died October 2005 (within the ≤2005 rule); no office; broadly honoured.',
  },
  {
    id: 'lf_frederick_douglass',
    name: 'Frederick Douglass',
    kind: 'real',
    hall: 'changemakers',
    region: 'americas',
    place: 'United States',
    era: '1818–1895',
    died: 1895,
    gender: 'man',
    field: 'Abolition and writing',
    essence: 'Escaped slavery and wrote a bestseller about it.',
    whoTheyWere: 'An American abolitionist, orator and writer who escaped slavery in 1838.',
    famousFor: 'His Narrative of the Life of Frederick Douglass, and his speeches.',
    facts: [
      fact('f1', 'His Narrative of the Life of Frederick Douglass (1845) became a bestseller.', src(wiki('Frederick_Douglass'), 'Narrative of the Life of Frederick Douglass', 'became a bestseller')),
      fact('f2', 'He wrote three autobiographies.', src(wiki('Frederick_Douglass'), 'wrote three autobiographies')),
      fact('f3', 'He was an abolitionist, orator, writer and social reformer.', src(wiki('Frederick_Douglass'), 'abolitionist, orator, writer')),
    ],
    moments: [
      moment('m1', 'He escaped to the North in September 1838 and took the surname Douglass.', src(wiki('Frederick_Douglass'), 'escaped to the North in September 1838')),
      moment('m2', 'When the woman teaching him to read was told to stop, she took a newspaper from him and hid the reading materials.', src(wiki('Frederick_Douglass'), 'snatched a newspaper away from Douglass')),
    ],
    angles: [
      angle('a1', 'learning to read', 'What does a man who learned to read against the rules have in common with you?', 'What others try to keep from you can become your strength.'),
      angle('a2', 'a new name', 'Why choose your own name?', 'Naming yourself is a way of owning your story.'),
      angle('a3', 'the speaker', 'How does one voice move a whole movement?', 'Speaking clearly about what you’ve lived can change minds.'),
      angle('a4', 'writing it down', 'Why write your story three times?', 'Telling your story again as you grow is honest, not repetitive.'),
    ],
    tags: [
      tag('conflict_assertiveness', 'high', 'spoke out powerfully', 'He was one of the great orators of his time.'),
      tag('growth_mindset', 'high', 'learned to read anyway', 'He learned to read despite being stopped.'),
      tag('autonomy', 'high', 'named himself', 'He chose the surname Douglass after escaping.'),
      tag('self_efficacy', 'high', 'escaped to freedom', 'He escaped slavery in 1838.'),
    ],
    vetting: 'Abolitionist and writer, died 1895; entry focuses on his writing and speeches; broadly honoured.',
  },
  {
    id: 'lf_sojourner_truth',
    name: 'Sojourner Truth',
    kind: 'real',
    hall: 'changemakers',
    region: 'americas',
    place: 'United States',
    era: 'c. 1797–1883',
    died: 1883,
    gender: 'woman',
    field: 'Abolition and women’s rights',
    essence: 'Took her case to court to get her son back, and won.',
    whoTheyWere: 'An American abolitionist and activist for civil and women’s rights.',
    famousFor: 'Her speech at the 1851 Ohio Women’s Convention.',
    facts: [
      fact('f1', 'She escaped slavery with her infant daughter in 1826.', src(wiki('Sojourner_Truth'), 'escaped with her infant daughter to freedom in 1826')),
      fact('f2', 'In 1828 she went to court to recover her son, the first Black woman to win such a case against a white man.', src(wiki('Sojourner_Truth'), 'first Black woman to win such a case against a white man')),
      fact('f3', 'She gave herself the name Sojourner Truth in 1843.', src(wiki('Sojourner_Truth'), 'gave herself the name Sojourner Truth in 1843')),
    ],
    moments: [
      moment('m1', 'She spoke at the Ohio Women’s Convention in Akron.', src(wiki('Sojourner_Truth'), "Ohio Women's Convention in Akron")),
      moment('m2', 'She went to court for her son and won.', src(wiki('Sojourner_Truth'), 'going to court to recover her son')),
    ],
    angles: [
      angle('a1', 'the court case', 'What does a mother who took on a court for her son have in common with you?', 'Fighting for the people you love can make you braver than you thought.'),
      angle('a2', 'a new name', 'What does it mean to choose your own name?', 'You can decide your own name and say it out loud.'),
      angle('a3', 'the speech', 'How does one short speech last for generations?', 'Plain, honest words can outlive fancy ones.'),
      angle('a4', 'leaving with her baby', 'What does it take to walk away with everything at stake?', 'Courage often looks like one step at a time.'),
    ],
    tags: [
      tag('attachment_avoidance', 'low', 'fought for her son', 'She went to court to get her son back.'),
      tag('self_efficacy', 'high', 'won against the odds', 'She won a case few believed possible.'),
      tag('conflict_assertiveness', 'high', 'spoke at conventions', 'She addressed public conventions.'),
      tag('autonomy', 'high', 'named herself', 'She chose her own name in 1843.'),
      tag('attachment_anxiety', 'high', 'fought to get her son back', 'She went to court to get her son back.'),
    ],
    vetting: 'Abolitionist, died 1883; no office; broadly honoured.',
  },
  {
    id: 'lf_jane_addams',
    name: 'Jane Addams',
    kind: 'real',
    hall: 'changemakers',
    region: 'americas',
    place: 'United States',
    era: '1860–1935',
    died: 1935,
    birthday: { md: '09-06', source: src(wiki('Jane_Addams'), 'September 6, 1860') },
    gender: 'woman',
    field: 'Social work',
    essence: 'Opened a house where whole neighbourhoods came for help.',
    whoTheyWere: 'An American reformer and social worker, recognised as a founder of social work in the US.',
    famousFor: 'Hull House in Chicago, and the 1931 Nobel Peace Prize.',
    facts: [
      fact('f1', 'In 1889 she co-founded Hull House, one of America’s most famous settlement houses, in Chicago.', src(wiki('Jane_Addams'), 'co-founded Hull House')),
      fact('f2', 'In 1931 she became the first American woman awarded the Nobel Peace Prize.', src(wiki('Jane_Addams'), 'first American woman to be awarded the Nobel Peace Prize')),
      fact('f3', 'She is recognised as the founder of the social work profession in the United States.', src(wiki('Jane_Addams'), 'founder of the social work profession in the United States')),
    ],
    moments: [
      moment('m1', 'Hull House offered social services to poor, largely immigrant families.', src(wiki('Jane_Addams'), 'largely immigrant famil')),
      moment('m2', 'She was a leading advocate for world peace.', src(wiki('Jane_Addams'), 'advocate for world peace')),
    ],
    angles: [
      angle('a1', 'open house', 'What does a reformer who opened her house to neighbours have in common with you?', 'Making a place where people feel welcome is real change.'),
      angle('a2', 'founding a job', 'What does it take to invent a whole profession?', 'Doing something nobody had a name for can become a path for thousands.'),
      angle('a3', 'peace', 'Why work for peace when it feels far away?', 'Steady, hopeful work counts even when results are slow.'),
      angle('a4', 'first woman', 'What changes when you’re the first to be honoured?', 'Recognition can make room for the next person.'),
    ],
    tags: [
      tag('relatedness', 'high', 'built a neighbourhood home', 'She made Hull House a centre for families.'),
      tag('conflict_cooperativeness', 'high', 'worked for peace', 'She advocated for world peace.'),
      tag('locus_of_control', 'high', 'founded a profession', 'She shaped social work in the US.'),
      tag('agreeableness', 'high', 'welcomed everyone', 'Hull House served families from many backgrounds.'),
      tag('attachment_anxiety', 'low', 'opened her door to all', 'She opened a house where whole neighbourhoods came for help.'),
    ],
    vetting: 'Reformer, died 1935; no elected office; broadly admired.',
  },
  {
    id: 'lf_chiune_sugihara',
    name: 'Chiune Sugihara',
    kind: 'real',
    hall: 'changemakers',
    region: 'east_asia',
    place: 'Japan and Lithuania',
    era: '1900–1986',
    died: 1986,
    birthday: { md: '01-01', source: src(wiki('Chiune_Sugihara'), '1 January 1900') },
    gender: 'man',
    field: 'Diplomacy',
    essence: 'Kept writing visas from a moving train to save refugees.',
    whoTheyWere: 'A Japanese diplomat who served as vice-consul in Kaunas, Lithuania.',
    famousFor: 'Issuing transit visas that helped thousands of Jews flee Europe in the Second World War.',
    facts: [
      fact('f1', 'He helped thousands of Jews flee Europe by issuing transit visas.', src(wiki('Chiune_Sugihara'), 'helped thousands of Jews flee Europe by issuing transit visas')),
      fact('f2', 'He did it at the risk of his career and his family’s lives.', src(wiki('Chiune_Sugihara'), 'risking his career and the lives of his family')),
      fact('f3', 'He served as vice-consul in Kaunas, Lithuania.', src(wiki('Chiune_Sugihara'), 'vice-consul for the Japanese Empire in Kaunas')),
    ],
    moments: [
      moment('m1', 'Witnesses said he kept writing visas after boarding his train, and threw them to refugees from the window as it pulled out.', src(wiki('Chiune_Sugihara'), 'throwing visas into the crowd')),
      moment('m2', 'He kept writing visas even while travelling from his hotel.', src(wiki('Chiune_Sugihara'), 'still writing visas while in transit')),
    ],
    angles: [
      angle('a1', 'from the train window', 'What does a diplomat who wrote visas from a moving train have in common with you?', 'Doing the right thing until the very last minute matters.'),
      angle('a2', 'risking the job', 'Why risk your career for strangers?', 'Some choices are bigger than any job.'),
      angle('a3', 'paperwork that saves lives', 'Can a stack of forms be heroic?', 'Ordinary work, done with conscience, can save lives.'),
      angle('a4', 'quiet courage', 'What does bravery look like at a desk?', 'Courage often looks quiet, not dramatic.'),
    ],
    tags: [
      tag('conflict_cooperativeness', 'high', 'helped thousands of strangers', 'He issued visas to refugees at great risk.'),
      tag('autonomy', 'high', 'followed his conscience', 'He issued visas despite the risk to his career.'),
      tag('conscientiousness', 'high', 'wrote visa after visa', 'He kept writing visas to the last moment.'),
      tag('conflict_assertiveness', 'low', 'quiet, steady courage', 'His bravery was quiet, done at a desk.'),
    ],
    vetting: 'Diplomat (not a head of government or military), died 1986; honoured as Righteous Among the Nations.',
  },
  {
    id: 'lf_louis_braille',
    name: 'Louis Braille',
    kind: 'real',
    hall: 'changemakers',
    region: 'europe',
    place: 'France',
    era: '1809–1852',
    died: 1852,
    birthday: { md: '01-04', source: src(wiki('Louis_Braille'), '4 January 1809') },
    gender: 'man',
    field: 'Education',
    essence: 'Invented a way for blind people to read, and it’s still used worldwide.',
    whoTheyWere: 'A French educator who lost his sight as a child after an accident in his father’s workshop.',
    famousFor: 'Inventing braille, the reading and writing system named after him.',
    facts: [
      fact('f1', 'He invented braille, a reading and writing system for visually impaired people.', src(wiki('Louis_Braille'), 'inventor of a reading and writing system named after him')),
      fact('f2', 'His system is used worldwide and remains virtually unchanged.', src(wiki('Louis_Braille'), 'used worldwide and remains virtually unchanged')),
      fact('f3', 'He was blinded after an accident with a stitching awl in his father’s workshop.', src(wiki('Louis_Braille'), 'accident with a stitching awl')),
    ],
    moments: [
      moment('m1', 'He lost the sight in one eye at three, and an infection later spread to both eyes.', src(wiki('Louis_Braille'), 'blinded in one eye at the age of three')),
      moment('m2', 'He became an educator and built a system other blind readers could use.', src(wiki('Louis_Braille'), 'French educator')),
    ],
    angles: [
      angle('a1', 'the dots', 'What does an educator who invented braille have in common with you?', 'Building the tool you need can help millions who need it too.'),
      angle('a2', 'unchanged', 'How good does an idea have to be to stay the same for two centuries?', 'Simple, well-made ideas last.'),
      angle('a3', 'the workshop', 'How can the place of an accident become the place of an idea?', 'Hard starts can lead to great work.'),
      angle('a4', 'the teacher', 'Why teach what you invented?', 'Sharing what you made is how it changes lives.'),
    ],
    tags: [
      tag('openness', 'high', 'invented a new way to read', 'He created a whole reading system.'),
      tag('growth_mindset', 'high', 'turned loss into invention', 'He built braille after losing his sight.'),
      tag('conflict_cooperativeness', 'high', 'made it for others', 'His system helps blind readers worldwide.'),
      tag('conscientiousness', 'high', 'designed it carefully', 'His system remains virtually unchanged.'),
      tag('locus_of_control', 'low', 'took what happened and built', 'He lost his sight after an accident as a child.'),
    ],
    vetting: 'Educator and inventor, died 1852; no office; broadly admired.',
  },
  {
    id: 'lf_ida_b_wells',
    name: 'Ida B. Wells',
    kind: 'real',
    hall: 'changemakers',
    region: 'americas',
    place: 'United States',
    era: '1862–1931',
    died: 1931,
    birthday: { md: '07-16', source: src(wiki('Ida_B._Wells'), 'July 16, 1862') },
    gender: 'woman',
    field: 'Journalism and civil rights',
    essence: 'A teacher turned reporter who wouldn’t stop telling the truth.',
    whoTheyWere: 'An American investigative journalist, educator and early leader of the civil rights movement.',
    famousFor: 'Her investigative reporting, and helping found the NAACP.',
    facts: [
      fact('f1', 'She was one of the founders of the NAACP.', src(wiki('Ida_B._Wells'), 'one of the founders of the National Association for the Advancement of Colored People')),
      fact('f2', 'In the 1890s she documented racist violence in articles and pamphlets.', src(wiki('Ida_B._Wells'), 'documented lynching')),
      fact('f3', 'She co-owned and wrote for the Memphis Free Speech and Headlight newspaper.', src(wiki('Ida_B._Wells'), 'Memphis Free Speech and Headlight')),
    ],
    moments: [
      moment('m1', 'To keep her younger siblings together as a family, she found work as a teacher.', src(wiki('Ida_B._Wells'), 'keep her younger siblings together')),
      moment('m2', 'Her investigative journalism was eventually carried nationally.', src(wiki('Ida_B._Wells'), 'investigative journalism was carried nationally')),
    ],
    angles: [
      angle('a1', 'keeping the family together', 'What does a reporter who kept her siblings together have in common with you?', 'Taking care of your people can make you fearless elsewhere.'),
      angle('a2', 'the facts', 'Why document every case?', 'Careful facts can be stronger than any opinion.'),
      angle('a3', 'her own paper', 'Why own the newspaper you write for?', 'Having your own platform lets you say what needs saying.'),
      angle('a4', 'founding together', 'What can a group of founders do that one person can’t?', 'Building with others makes the work last.'),
    ],
    tags: [
      tag('conflict_assertiveness', 'high', 'reported what others hid', 'She documented injustice openly.'),
      tag('attachment_avoidance', 'low', 'kept her siblings close', 'She worked to keep her family together.'),
      tag('conscientiousness', 'high', 'documented every case', 'Her reporting was careful and investigative.'),
      tag('locus_of_control', 'high', 'built the NAACP', 'She helped found a lasting organisation.'),
      tag('conflict_cooperativeness', 'low', 'wouldn’t back down', 'She would not stop telling the truth.'),
    ],
    vetting: 'Journalist and activist, died 1931; no office; broadly honoured. Violence named only in general terms.',
  },
  {
    id: 'lf_fred_korematsu',
    name: 'Fred Korematsu',
    kind: 'real',
    hall: 'changemakers',
    region: 'americas',
    place: 'United States',
    era: '1919–2005',
    died: 2005,
    birthday: { md: '01-30', source: src(wiki('Fred_Korematsu'), 'January 30, 1919') },
    gender: 'man',
    field: 'Civil rights',
    essence: 'Lost his case at the Supreme Court, then won forty years later.',
    whoTheyWere: 'An American civil rights activist who resisted the internment of Japanese Americans during the Second World War.',
    famousFor: 'Korematsu v. United States, and having his conviction overturned in 1983.',
    facts: [
      fact('f1', 'He resisted the internment of Japanese Americans during the Second World War.', src(wiki('Fred_Korematsu'), 'resisted the internment of Japanese Americans')),
      fact('f2', 'In 1983 a federal judge formally vacated his conviction.', src(wiki('Fred_Korematsu'), 'formally vacated the conviction')),
      fact('f3', 'In 1998 he received the Presidential Medal of Freedom.', src(wiki('Fred_Korematsu'), 'Presidential Medal of Freedom')),
    ],
    moments: [
      moment('m1', 'He challenged the internment order, and the Supreme Court ruled against him in 1944.', src(wiki('Fred_Korematsu'), 'Korematsu v. United States (1944)')),
      moment('m2', 'California later created Fred Korematsu Day, first observed on his 92nd birthday.', src(wiki('Fred_Korematsu'), 'Fred Korematsu Day')),
    ],
    angles: [
      angle('a1', 'the long wait', 'What does a man who waited forty years to be cleared have in common with you?', 'Being right can take a long time to be recognised.'),
      angle('a2', 'saying no', 'Why refuse an order you believe is wrong?', 'Standing by what you know is fair takes nerve.'),
      angle('a3', 'losing, then winning', 'What happens after you lose the biggest case?', 'A loss can be the first chapter, not the last.'),
      angle('a4', 'a day in his name', 'How does one person’s stand become a day to remember?', 'Your courage can teach people long after.'),
    ],
    tags: [
      tag('conflict_cooperativeness', 'low', 'refused the order', 'He challenged the internment order.'),
      tag('steadiness', 'high', 'patient for forty years', 'He kept his stand until his conviction was overturned.'),
      tag('conflict_assertiveness', 'high', 'challenged the government', 'He took his case all the way to the Supreme Court.'),
      tag('locus_of_control', 'low', 'waited for the courts', 'For decades his fate was in others’ hands.'),
    ],
    vetting: 'Activist, died March 2005 (within the ≤2005 rule); no office; broadly honoured.',
  },
  {
    id: 'lf_mary_mcleod_bethune',
    name: 'Mary McLeod Bethune',
    kind: 'real',
    hall: 'changemakers',
    region: 'americas',
    place: 'United States',
    era: '1875–1955',
    died: 1955,
    birthday: { md: '07-10', source: src(wiki('Mary_McLeod_Bethune'), 'July 10, 1875') },
    gender: 'woman',
    field: 'Education',
    essence: 'Started a small school that became a university.',
    whoTheyWere: 'An American educator, humanitarian and civil rights activist.',
    famousFor: 'Founding the school that became Bethune-Cookman University.',
    facts: [
      fact('f1', 'She started a private school for Black American students that later became Bethune-Cookman University.', src(wiki('Mary_McLeod_Bethune'), 'later became Bethune-Cookman University')),
      fact('f2', 'She founded the National Council of Negro Women in 1935.', src(wiki('Mary_McLeod_Bethune'), 'National Council of Negro Women in 1935')),
      fact('f3', 'A 1974 statue of her was the first monument to honour a Black American and a woman in a public park in Washington.', src(wiki('Mary_McLeod_Bethune'), 'first monument to honor a Black American and a woman in a public par')),
    ],
    moments: [
      moment('m1', 'Her home in Daytona Beach, Florida, is now a National Historic Landmark.', src(wiki('Mary_McLeod_Bethune'), 'Daytona Beach, Florida, as a National Historic Landmark')),
      moment('m2', 'She was the only Black American woman in an official role with the US delegation that created the United Nations.', src(wiki('Mary_McLeod_Bethune'), 'only Black American woman to hold an official position')),
    ],
    angles: [
      angle('a1', 'the small school', 'What does a teacher whose small school became a university have in common with you?', 'Small starts can grow into something huge if you keep tending them.'),
      angle('a2', 'in the room', 'What does it mean to be the only one like you in the room?', 'Your presence can change the room.'),
      angle('a3', 'education first', 'Why put learning at the centre of change?', 'Opening doors to learning opens every other door.'),
      angle('a4', 'building groups', 'Why found organisations instead of working alone?', 'Building something shared helps it outlast you.'),
    ],
    tags: [
      tag('locus_of_control', 'high', 'built a school from scratch', 'She founded a school that became a university.'),
      tag('relatedness', 'high', 'brought women together', 'She founded the National Council of Negro Women.'),
      tag('self_efficacy', 'high', 'the only one, and stayed', 'She held a unique role at the UN’s founding.'),
      tag('conscientiousness', 'high', 'grew it step by step', 'She built her school into a university.'),
    ],
    vetting: 'Educator, died 1955; held appointed roles but no elected office; broadly honoured.',
  },
];
