import type { LegendFigure } from '../types';
import { angle, fact, moment, src, tag, wiki } from './define';

const BATTUTA = wiki('Ibn_Battuta');
const EARHART = wiki('Amelia_Earhart');
const TENZING = wiki('Tenzing_Norgay');

export const EXPLORER_LEGENDS: readonly LegendFigure[] = [
  {
    id: 'lf_ibn_battuta',
    name: 'Ibn Battuta',
    kind: 'real',
    hall: 'explorers',
    region: 'africa',
    place: 'Morocco',
    era: '1304–c. 1369',
    died: 1369,
    gender: 'man',
    field: 'Travel and writing',
    essence: 'Left for a sixteen-month trip and came home twenty-four years later.',
    whoTheyWere: 'A traveller and scholar from Tangier who spent about thirty years crossing Africa, Asia and Iberia.',
    famousFor: 'The Rihla, the account of his journeys, and travelling farther than any explorer before modern times.',
    facts: [
      fact('f1', 'He set out from Tangier at 21 on a trip that would usually take sixteen months.', src(BATTUTA, 'at the age of 21', 'sixteen months')),
      fact('f2', 'He did not return to Morocco for 24 years.', src(BATTUTA, 'would not return to Morocco again for 24 years')),
      fact('f3', 'He travelled around 117,000 km, more than any other explorer in pre-modern history.', src(BATTUTA, '117,000 km')),
    ],
    moments: [
      moment(
        'm1',
        'He wrote that he set out alone, with no travelling companion and no caravan, swayed by an overmastering impulse.',
        src(BATTUTA, 'I set out alone', 'overmastering impulse'),
      ),
      moment('m2', 'Near the end of his life he dictated the story of his journeys, known as the Rihla.', src(BATTUTA, 'dictated an account of his journeys')),
    ],
    angles: [
      angle('a1', 'the long way home', 'What does a man whose trip ran twenty-two years late have in common with you?', 'Plans that stretch far past their schedule can still be the best thing you did.'),
      angle('a2', 'setting out alone', 'Who leaves home with no companion and no caravan?', 'Going first, without company, is scary and sometimes the only way to start.'),
      angle('a3', 'telling it later', 'Why tell the story decades after the trip?', 'Some experiences only make sense once you look back and put them in words.'),
      angle('a4', 'the farthest traveller', 'How far can curiosity carry one person?', 'Following your curiosity one city at a time adds up to a life.'),
    ],
    tags: [
      tag('openness', 'high', 'kept going to the next city', 'His sixteen-month trip became twenty-four years of travel.'),
      tag('extraversion', 'high', 'met the whole known world', 'He travelled among people across three continents.'),
      tag('conscientiousness', 'low', 'let the plan stretch', 'He kept changing course far beyond his original trip.'),
      tag('relatedness', 'high', 'told everyone the story', 'He shared his travels in a book still read today.'),
    ],
    vetting: 'Traveller and writer, died c. 1369; no office; broadly admired.',
  },
  {
    id: 'lf_amelia_earhart',
    name: 'Amelia Earhart',
    kind: 'real',
    hall: 'explorers',
    region: 'americas',
    place: 'United States',
    era: '1897–1937',
    died: 1937,
    birthday: { md: '07-24', source: src(EARHART, 'July 24, 1897') },
    gender: 'woman',
    field: 'Aviation',
    essence: 'Flew the Atlantic alone because nobody said she couldn’t.',
    whoTheyWere: 'An American aviator who became one of the most celebrated figures of early flight.',
    famousFor: 'The first woman to fly solo and nonstop across the Atlantic, in 1932.',
    facts: [
      fact('f1', 'In 1932 she became the first woman to make a nonstop solo transatlantic flight.', src(EARHART, 'first woman to make a nonstop solo transatlantic flight')),
      fact('f2', 'She helped found the Ninety-Nines, an organization for women pilots.', src(EARHART, 'Ninety-Nines')),
      fact('f3', 'In 1937 she disappeared over the Pacific while trying to fly around the world.', src(EARHART, 'disappeared over the Pacific Ocean')),
    ],
    moments: [
      moment('m1', 'In 1928 she crossed the Atlantic as a passenger, the first woman to do so by plane.', src(EARHART, 'first female passenger to cross the Atlantic')),
      moment('m2', 'She called her marriage a “partnership” with “dual control”.', src(EARHART, 'dual control')),
    ],
    angles: [
      angle('a1', 'from passenger to pilot', 'What does a woman who rode across the Atlantic, then flew it herself, have in common with you?', 'Watching something done once can be the start of doing it yourself.'),
      angle('a2', 'dual control', 'What does a partnership look like when both people keep their own wings?', 'Being close to someone and staying yourself can go together.'),
      angle('a3', 'making room', 'Why would a famous pilot help start a club for other women pilots?', 'Making space for others like you is part of going first.'),
      angle('a4', 'the open sky', 'What makes someone keep reaching for the next, bigger flight?', 'Wanting the next challenge is a strength. So is knowing why you want it.'),
    ],
    tags: [
      tag('self_efficacy', 'high', 'flew it herself', 'After crossing as a passenger, she flew the Atlantic solo.'),
      tag('openness', 'high', 'chased the next horizon', 'She kept attempting bigger flights, up to a world flight.'),
      tag('autonomy', 'high', 'kept her own controls', 'She described her marriage as dual control.'),
      tag('attachment_avoidance', 'high', 'needed her own space', 'She insisted on independence even within her marriage.'),
    ],
    vetting: 'Aviator, died 1937; no office; broadly admired.',
  },
  {
    id: 'lf_tenzing_norgay',
    name: 'Tenzing Norgay',
    kind: 'real',
    hall: 'explorers',
    region: 'south_asia',
    place: 'Nepal and India',
    era: '1914–1986',
    died: 1986,
    gender: 'man',
    field: 'Mountaineering',
    essence: 'Climbed toward Everest for twenty years before standing on top.',
    whoTheyWere: 'A Nepalese-Indian Sherpa mountaineer who worked on British Everest expeditions from the 1930s.',
    famousFor: 'With Edmund Hillary, the first people confirmed on the summit of Mount Everest, in 1953.',
    facts: [
      fact('f1', 'On 29 May 1953 he and Edmund Hillary were the first people confirmed on Everest’s summit.', src(TENZING, '29 May 1953', 'first people confirmed to have reached the summit')),
      fact('f2', 'In the 1930s he worked as a high-altitude porter on three British attempts on Everest.', src(TENZING, 'high-altitude porter in three official British attempts')),
      fact('f3', 'Time named him one of the 100 most influential people of the 20th century.', src(TENZING, '100 most influential people')),
    ],
    moments: [
      moment('m1', 'As a teenager he ran away from home twice, first to Kathmandu, then to Darjeeling.', src(TENZING, 'ran away from home twice')),
      moment('m2', 'His mother lived to see him climb Everest.', src(TENZING, 'She lived to see him climb Everest')),
    ],
    angles: [
      angle('a1', 'twenty years of climbing', 'What does a man who carried loads up Everest for years have in common with you?', 'Years of unseen work can be exactly what gets you to the top.'),
      angle('a2', 'the rope team', 'Who stands on top of the world as half of a pair?', 'Reaching something big with a partner doesn’t make it less yours.'),
      angle('a3', 'running toward the mountains', 'Why would a teenager run away to where the expeditions start?', 'Going where your thing happens is a first step anyone can take.'),
      angle('a4', 'seen by home', 'What does it mean when the people who raised you get to see you make it?', 'Sharing the big moment with the people from the start makes it land.'),
    ],
    tags: [
      tag('conflict_cooperativeness', 'high', 'made it a two-person summit', 'He reached the top as a partner, roped together with Hillary.'),
      tag('steadiness', 'high', 'calm at extreme altitude', 'He worked high on the mountain through many expeditions.'),
      tag('conflict_assertiveness', 'low', 'did the work, quietly', 'For years he carried loads on other people’s expeditions.'),
      tag('attachment_anxiety', 'low', 'trusted the rope team', 'Climbing roped together means trusting your partner with your life.'),
      tag('autonomy', 'low', 'worked within the team plan', 'He climbed for years inside expeditions led by others.'),
    ],
    vetting: 'Mountaineer, died 1986; no office; broadly admired.',
  },
  {
    id: 'lf_matthew_henson',
    name: 'Matthew Henson',
    kind: 'real',
    hall: 'explorers',
    region: 'americas',
    place: 'United States',
    era: '1866–1955',
    died: 1955,
    birthday: { md: '08-08', source: src(wiki('Matthew_Henson'), 'August 8, 1866') },
    gender: 'man',
    field: 'Arctic exploration',
    essence: 'Said he was the first of his party to reach the North Pole.',
    whoTheyWere: 'An American explorer who spent about 23 years on Arctic voyages as a navigator and craftsman.',
    famousFor: 'The 1908–1909 expedition that claimed to reach the North Pole.',
    facts: [
      fact('f1', 'He went on seven Arctic voyages over nearly 23 years.', src(wiki('Matthew_Henson'), 'seven voyages to the Arctic over a period of nearly 23 years')),
      fact('f2', 'He studied Inuit survival techniques.', src(wiki('Matthew_Henson'), 'he studied Inuit survival techniques')),
      fact('f3', 'In 1937 he was the first African American made a life member of The Explorers Club.', src(wiki('Matthew_Henson'), 'first African American to be made a life member of The Explorers Club')),
    ],
    moments: [
      moment('m1', 'He later said that he was the first of their party to reach the North Pole, on 6 April 1909.', src(wiki('Matthew_Henson'), 'he was the first of their party to reach the North Pole')),
      moment('m2', 'He served as navigator and craftsman, and was known as the expedition’s “first man”.', src(wiki('Matthew_Henson'), 'navigator and craftsman')),
    ],
    angles: [
      angle('a1', 'first to the pole', 'What does an explorer who reached the pole first, and waited for credit, have in common with you?', 'Doing the work first matters, even before anyone writes it down.'),
      angle('a2', 'learning from locals', 'Why learn survival from the people who live there?', 'The best teachers are often the people who already live it.'),
      angle('a3', 'the craftsman', 'What makes the person who fixes everything so important?', 'Being the one who keeps things running is a quiet kind of leadership.'),
      angle('a4', 'credit later', 'What happens when recognition comes decades late?', 'Your worth isn’t decided by when people notice it.'),
    ],
    tags: [
      tag('competence', 'high', 'navigator and fixer', 'He was the expedition’s navigator and craftsman.'),
      tag('steadiness', 'high', 'calm in the Arctic', 'He spent years in harsh Arctic conditions.'),
      tag('conflict_assertiveness', 'low', 'did the work, quietly', 'He got little credit for decades.'),
      tag('growth_mindset', 'high', 'learned Inuit skills', 'He studied Inuit survival techniques.'),
      tag('autonomy', 'low', 'navigator on the team', 'He served as navigator and craftsman on the expedition.'),
    ],
    vetting: 'Explorer, died 1955; no office; broadly admired.',
  },
  {
    id: 'lf_jacques_cousteau',
    name: 'Jacques Cousteau',
    kind: 'real',
    hall: 'explorers',
    region: 'europe',
    place: 'France',
    era: '1910–1997',
    died: 1997,
    birthday: { md: '06-11', source: src(wiki('Jacques_Cousteau'), '11 June 1910') },
    gender: 'man',
    field: 'Ocean exploration',
    essence: 'Helped invent scuba gear, then filmed the sea in colour.',
    whoTheyWere: 'A French oceanographer, filmmaker and author who explored and filmed the undersea world.',
    famousFor: 'Co-inventing the Aqua-Lung and his underwater documentaries.',
    facts: [
      fact('f1', 'He co-invented the Aqua-Lung, the first successful open-circuit scuba apparatus.', src(wiki('Jacques_Cousteau'), 'called the Aqua-Lung')),
      fact('f2', 'His film won the 1956 Palme d’Or at Cannes.', src(wiki('Jacques_Cousteau'), "1956 Palme d'Or")),
      fact('f3', 'His first book was The Silent World.', src(wiki('Jacques_Cousteau'), 'The Silent World')),
    ],
    moments: [
      moment('m1', 'His film was one of the first to use underwater filming to show the deep sea in colour.', src(wiki('Jacques_Cousteau'), 'underwater cinematography to document the ocean depths in color')),
      moment('m2', 'His sons took part in the adventures of his ship, the Calypso.', src(wiki('Jacques_Cousteau'), 'adventures of the Calypso')),
    ],
    angles: [
      angle('a1', 'the breathing machine', 'What does an explorer who built his own diving gear have in common with you?', 'Sometimes you have to build the tool before you can go where you want.'),
      angle('a2', 'filming the deep', 'Why bring a camera under the sea?', 'Showing people what you’ve seen is how they come to care.'),
      angle('a3', 'the family ship', 'What is it like to share your adventures with your family?', 'Bringing people you love into your passion makes it bigger.'),
      angle('a4', 'the silent world', 'What can you hear in a world without sound?', 'Quiet places can show you the most.'),
    ],
    tags: [
      tag('openness', 'high', 'went where nobody could', 'He helped invent gear to explore under the sea.'),
      tag('self_efficacy', 'high', 'built his own way down', 'He co-invented the Aqua-Lung.'),
      tag('relatedness', 'high', 'shared the sea with everyone', 'He made films and books for the public.'),
      tag('extraversion', 'high', 'led a ship of adventurers', 'His crew and family sailed with him on Calypso.'),
    ],
    vetting: 'Oceanographer, died 1997; served as a naval officer, never a commander in battle; broadly admired.',
  },
  {
    id: 'lf_yuri_gagarin',
    name: 'Yuri Gagarin',
    kind: 'real',
    hall: 'explorers',
    region: 'europe',
    place: 'Russia',
    era: '1934–1968',
    died: 1968,
    birthday: { md: '03-09', source: src(wiki('Yuri_Gagarin'), '9 March 1934') },
    gender: 'man',
    field: 'Spaceflight',
    essence: 'A former steel-plant worker who became the first person in space.',
    whoTheyWere: 'A pilot and cosmonaut who became the first person to travel into outer space.',
    famousFor: 'Orbiting Earth on Vostok 1 on 12 April 1961.',
    facts: [
      fact('f1', 'On 12 April 1961, aboard Vostok 1, he completed one orbit of Earth.', src(wiki('Yuri_Gagarin'), 'Vostok 1', 'one orbit of Earth on 12 April 1961')),
      fact('f2', 'The flight took 108 minutes.', src(wiki('Yuri_Gagarin'), 'The flight took 108 minutes')),
      fact('f3', 'In his youth he worked as a foundryman at a steel plant.', src(wiki('Yuri_Gagarin'), 'foundryman at a steel plant')),
    ],
    moments: [
      moment('m1', 'Before the flight, the candidates were tested in a simulator on a full-size mock-up of the spacecraft.', src(wiki('Yuri_Gagarin'), 'tested in a simulator')),
      moment('m2', 'After the flight he became an international celebrity.', src(wiki('Yuri_Gagarin'), 'international celebrity')),
    ],
    angles: [
      angle('a1', 'from the foundry', 'What does a steelworker who became the first person in space have in common with you?', 'Where you start says nothing about how far you can go.'),
      angle('a2', '108 minutes', 'What can change in less than two hours?', 'One short, brave moment can redefine a life.'),
      angle('a3', 'the test', 'Why practise in a mock-up before the real thing?', 'Preparing carefully is what lets you stay calm when it counts.'),
      angle('a4', 'suddenly famous', 'What do you do when the whole world knows your name?', 'Staying yourself after a big moment is its own challenge.'),
    ],
    tags: [
      tag('self_efficacy', 'high', 'went first into space', 'He became the first person to travel into space.'),
      tag('steadiness', 'high', 'calm on the launchpad', 'He was chosen for readiness under pressure.'),
      tag('openness', 'high', 'went where no one had', 'He travelled where no person had been.'),
      tag('autonomy', 'low', 'trained within the team', 'He trained and flew as part of a programme.'),
    ],
    vetting: 'Cosmonaut, died 1968; a pilot, not a commander in war; entry avoids Cold War politics.',
  },
  {
    id: 'lf_ernest_shackleton',
    name: 'Ernest Shackleton',
    kind: 'real',
    hall: 'explorers',
    region: 'europe',
    place: 'Ireland and Britain',
    era: '1874–1922',
    died: 1922,
    birthday: { md: '02-15', source: src(wiki('Ernest_Shackleton'), '15 February 1874') },
    gender: 'man',
    field: 'Antarctic exploration',
    essence: 'Lost his ship to the ice and got his crew out anyway.',
    whoTheyWere: 'An Anglo-Irish Antarctic explorer who led three British expeditions to the Antarctic.',
    famousFor: 'The Endurance expedition, when his ship sank and the crew escaped across ice and sea.',
    facts: [
      fact('f1', 'He led three British expeditions to the Antarctic.', src(wiki('Ernest_Shackleton'), 'led three British expeditions to the Antarctic')),
      fact('f2', 'His ship, Endurance, was trapped in pack ice and sank in the Weddell Sea in 1915.', src(wiki('Ernest_Shackleton'), 'Endurance, became trapped in pack ice')),
      fact('f3', 'The crew camped on the sea ice, then took lifeboats to Elephant Island.', src(wiki('Ernest_Shackleton'), 'Elephant Island')),
    ],
    moments: [
      moment('m1', 'To get help, a small party made a stormy sea voyage of about 1,330 kilometres in a lifeboat to South Georgia.', src(wiki('Ernest_Shackleton'), 'South Georgia', 'stormy ocean voyage')),
      moment('m2', 'When the ice they camped on broke up, they launched the lifeboats.', src(wiki('Ernest_Shackleton'), 'camping on the sea ice until it disintegrated')),
    ],
    angles: [
      angle('a1', 'when the plan sinks', 'What does an explorer whose ship sank have in common with you?', 'When the original plan fails, getting everyone home is a plan too.'),
      angle('a2', 'the lifeboat', 'What does it take to cross a stormy sea in a small boat?', 'Big rescues are made of small, brave decisions.'),
      angle('a3', 'the crew first', 'Why does the leader worry about everyone else?', 'Looking after your people is what makes them trust you.'),
      angle('a4', 'stuck in the ice', 'What do you do while you wait for things to move?', 'Keeping spirits up while stuck is a real skill.'),
    ],
    tags: [
      tag('steadiness', 'high', 'kept calm on the ice', 'He held the crew together after the ship sank.'),
      tag('locus_of_control', 'high', 'took charge of the rescue', 'He organised the escape and the voyage for help.'),
      tag('relatedness', 'high', 'put his crew first', 'His focus was getting everyone out alive.'),
      tag('self_efficacy', 'high', 'crossed a stormy sea', 'He made the lifeboat voyage to find help.'),
    ],
    vetting: 'Explorer, died 1922; no office; broadly admired.',
  },
  {
    id: 'lf_isabella_bird',
    name: 'Isabella Bird',
    kind: 'real',
    hall: 'explorers',
    region: 'europe',
    place: 'England',
    era: '1831–1904',
    died: 1904,
    birthday: { md: '10-15', source: src(wiki('Isabella_Bird'), '15 October 1831') },
    gender: 'woman',
    field: 'Travel writing',
    essence: 'Rode 800 miles through the Rockies and wrote it all to her sister.',
    whoTheyWere: 'An English explorer, writer, photographer and naturalist who travelled the world.',
    famousFor: 'Her travel books, and being the first woman elected a fellow of the Royal Geographical Society.',
    facts: [
      fact('f1', 'She was the first woman elected a fellow of the Royal Geographical Society.', src(wiki('Isabella_Bird'), 'first woman to be elected as a fellow of the Royal Geographical Society')),
      fact('f2', 'In 1873 she covered over 800 miles in the Rocky Mountains.', src(wiki('Isabella_Bird'), 'over 800 miles in the Rocky Mountains in 1873')),
      fact('f3', 'Her letters to her sister became one of her most famous books.', src(wiki('Isabella_Bird'), 'Her letters to her sister')),
    ],
    moments: [
      moment('m1', 'Her father gave her 100 pounds and leave to stay away as long as it lasted, the start of her life of travel.', src(wiki('Isabella_Bird'), 'leave to stay away as long as it lasted')),
      moment('m2', 'With Fanny Jane Butler she founded a hospital in Srinagar, in Kashmir.', src(wiki('Isabella_Bird'), 'John Bishop Memorial Hospital in Srinagar')),
    ],
    angles: [
      angle('a1', 'letters home', 'What does a traveller who wrote everything to her sister have in common with you?', 'Telling someone close what you’re living through can make it a story.'),
      angle('a2', 'as long as it lasts', 'What would you do with a budget and permission to go?', 'Saying yes to the open door can start a whole life.'),
      angle('a3', 'first woman in', 'What does it mean to be the first woman in the room?', 'Being first opens the door wider for others.'),
      angle('a4', 'giving back', 'Why would a traveller build a hospital?', 'Places that changed you can be places you help.'),
    ],
    tags: [
      tag('openness', 'high', 'rode across the Rockies', 'She travelled over 800 miles in the mountains.'),
      tag('relatedness', 'high', 'wrote to her sister', 'Her famous book grew from letters to her sister.'),
      tag('autonomy', 'high', 'travelled on her own terms', 'She travelled widely, often alone.'),
      tag('conflict_cooperativeness', 'high', 'founded a hospital', 'She helped found a hospital in Srinagar.'),
    ],
    vetting: 'Explorer and writer, died 1904; no office; broadly admired.',
  },
  {
    id: 'lf_nellie_bly',
    name: 'Nellie Bly',
    kind: 'real',
    hall: 'explorers',
    region: 'americas',
    place: 'United States',
    era: '1864–1922',
    died: 1922,
    birthday: { md: '05-05', source: src(wiki('Nellie_Bly'), 'May 5, 1864') },
    gender: 'woman',
    field: 'Journalism and travel',
    essence: 'Raced around the world in 72 days to beat a novel.',
    whoTheyWere: 'An American journalist who wrote under the pen name Nellie Bly.',
    famousFor: 'Her record-breaking trip around the world in 72 days.',
    facts: [
      fact('f1', 'She travelled around the world in 72 days, a record at the time.', src(wiki('Nellie_Bly'), 'trip around the world in 72 days')),
      fact('f2', 'She set out to turn the novel Around the World in Eighty Days into fact.', src(wiki('Nellie_Bly'), 'turn the fictional Around the World in Eighty Days')),
      fact('f3', 'She also worked undercover as a reporter.', src(wiki('Nellie_Bly'), 'worked undercover to report')),
    ],
    moments: [
      moment('m1', 'When she proposed the trip, her editor doubted she could do it.', src(wiki('Nellie_Bly'), 'The editor expressed doubts she could do it')),
      moment('m2', 'Nellie Bly was a pen name; she was born Elizabeth Jane Cochran.', src(wiki('Nellie_Bly'), 'better known by her pen name Nellie Bly')),
    ],
    angles: [
      angle('a1', 'beating a book', 'What does a reporter who raced a novel around the world have in common with you?', 'Taking an idea literally can lead somewhere real.'),
      angle('a2', 'the doubtful editor', 'What do you do when your boss doubts you?', 'Proving it by doing it is sometimes the only answer.'),
      angle('a3', 'a new name', 'Why work under a different name?', 'A new name can give you room to be bolder.'),
      angle('a4', 'the scoop', 'What makes someone go undercover for a story?', 'Going where the story is takes nerve and care.'),
    ],
    tags: [
      tag('self_efficacy', 'high', 'proved the editor wrong', 'She went despite her editor’s doubts.'),
      tag('openness', 'high', 'raced around the world', 'She turned a novel’s idea into a real trip.'),
      tag('conflict_assertiveness', 'high', 'pitched the impossible', 'She proposed the trip herself.'),
      tag('playfulness', 'high', 'made it a race', 'She treated a fictional challenge as a real game.'),
      tag('conflict_cooperativeness', 'low', 'went anyway', 'Her editor doubted her, and she went anyway.'),
    ],
    vetting: 'Journalist, died 1922; no office; broadly admired.',
  },
  {
    id: 'lf_roald_amundsen',
    name: 'Roald Amundsen',
    kind: 'real',
    hall: 'explorers',
    region: 'europe',
    place: 'Norway',
    era: '1872–1928',
    died: 1928,
    birthday: { md: '07-16', source: src(wiki('Roald_Amundsen'), '16 July 1872') },
    gender: 'man',
    field: 'Polar exploration',
    essence: 'Learned from the Inuit, then led the first team to the South Pole.',
    whoTheyWere: 'A Norwegian polar explorer of the Heroic Age of Antarctic Exploration.',
    famousFor: 'Leading the first team to reach the South Pole, on 14 December 1911.',
    facts: [
      fact('f1', 'His party of five became the first to reach the South Pole on 14 December 1911.', src(wiki('Roald_Amundsen'), 'first to reach the South Pole on 14 December 1911')),
      fact('f2', 'From 1903 to 1906 he led the first expedition through the Northwest Passage.', src(wiki('Roald_Amundsen'), 'first expedition to successfully traverse the Northwest Passage')),
      fact('f3', 'In 1926 he and 15 others in the airship Norge were the first verified to reach the North Pole.', src(wiki('Roald_Amundsen'), 'airship Norge')),
    ],
    moments: [
      moment('m1', 'From the Netsilik Inuit he learned to use sled dogs and wear animal skins, which he found invaluable later.', src(wiki('Roald_Amundsen'), 'Netsilik Inuit', 'sled dogs')),
      moment('m2', 'He left Norway in 1910 on the ship Fram, heading for Antarctica.', src(wiki('Roald_Amundsen'), 'ship Fram')),
    ],
    angles: [
      angle('a1', 'learn from the experts', 'What does an explorer who copied the Inuit have in common with you?', 'Learning from people who already know is the fastest way to get good.'),
      angle('a2', 'the right gear', 'Why swap wool for animal skins?', 'Using what actually works beats what you’re used to.'),
      angle('a3', 'both poles', 'What drives someone to want both ends of the Earth?', 'Big goals stack: one success gives you the nerve for the next.'),
      angle('a4', 'the plan', 'How do you win a race to the South Pole?', 'Careful preparation is often the real reason things go right.'),
    ],
    tags: [
      tag('conscientiousness', 'high', 'planned every detail', 'His careful preparation made the Pole possible.'),
      tag('growth_mindset', 'high', 'learned from the Inuit', 'He adopted Inuit survival skills.'),
      tag('openness', 'high', 'went to both poles', 'He explored the Arctic and the Antarctic.'),
      tag('locus_of_control', 'high', 'led from the front', 'He led the team that reached the South Pole.'),
    ],
    vetting: 'Explorer, died 1928; no office; broadly admired.',
  },
];
