import type { LegendFigure } from '../types';
import { angle, fact, moment, src, tag, wiki } from './define';

const DUTCHMAN = wiki('Flying_Dutchman');
const BROWNIE = wiki('Brownie_(folklore)');
const TANUKI = wiki('Bake-danuki');

export const GHOST_LEGENDS: readonly LegendFigure[] = [
  {
    id: 'lf_flying_dutchman',
    name: 'The Flying Dutchman',
    kind: 'story',
    hall: 'ghosts',
    region: 'europe',
    place: 'Sailors’ legend, Dutch seas',
    era: 'Told since the 1600s',
    gender: 'none',
    field: 'Ghost ship',
    essence: 'A ship that never makes port and never stops sailing.',
    whoTheyWere: 'A legendary ghost ship, said to be unable to make port and doomed to sail the sea forever.',
    famousFor: 'Sailors’ sightings near the Cape of Good Hope, and an opera by Richard Wagner.',
    facts: [
      fact('f1', 'The ship is said never to make port and to sail the sea forever.', src(DUTCHMAN, 'never able to make port and doomed to sail the sea forever')),
      fact('f2', 'The stories probably began in the age of the Dutch East India Company in the 1600s.', src(DUTCHMAN, 'Dutch East India Company')),
      fact('f3', 'Richard Wagner wrote an opera, The Flying Dutchman, in 1843.', src(DUTCHMAN, 'The Flying Dutchman (1843)')),
    ],
    moments: [
      moment(
        'm1',
        'A 1795 account tells of sailors who saw what they took for the lost ship in a storm, until it turned out to be a dark thick cloud. The story spread anyway.',
        src(DUTCHMAN, '1795', 'a dark thick cloud', 'spread like wild-fire'),
      ),
      moment('m2', 'Some tellings model its captain on a Dutch captain famous for the speed of his voyages.', src(DUTCHMAN, 'renowned for the speed of his trips')),
    ],
    angles: [
      angle('a1', 'the endless voyage', 'What does a ship that never stops sailing have in common with you?', 'Keeping a steady course is strong. Knowing when to come into port is too.'),
      angle('a2', 'the same route', 'What happens when you refuse to change course, no matter what?', 'Being stubborn can carry you far, and sometimes it’s worth asking where.'),
      angle('a3', 'the cloud', 'Why does a story spread even after the ship turns out to be a cloud?', 'What people think they saw can travel faster than what happened.'),
      angle('a4', 'the fast captain', 'What legend grows around someone who keeps arriving too fast?', 'Being known for one thing can turn into a story bigger than you.'),
    ],
    tags: [
      tag('openness', 'low', 'the same route, forever', 'It sails the same seas and never changes course.'),
      tag('growth_mindset', 'low', 'never changes course', 'The ghost ship keeps doing the same thing forever.'),
      tag('conflict_cooperativeness', 'low', 'won’t bend for anyone', 'In the legend it never gives in to the sea.'),
      tag('relatedness', 'low', 'sails alone', 'It roams the oceans with no port and no company.'),
      tag('competence', 'low', 'never reaches port', 'The ship can never make port.'),
    ],
    vetting: 'Sailors’ ghost legend; no real person named as the captain in the entry; no harm to children.',
  },
  {
    id: 'lf_brownie',
    name: 'The Brownie',
    kind: 'story',
    hall: 'ghosts',
    region: 'europe',
    place: 'Scottish folklore',
    era: 'Told since at least the 1500s',
    gender: 'none',
    field: 'Household spirit',
    essence: 'Does the chores at night and leaves if you make a fuss about it.',
    whoTheyWere: 'A household spirit from Scottish folklore that comes out at night, while everyone sleeps, to do the chores.',
    famousFor: 'Quietly helping a household, and leaving forever if given clothes.',
    facts: [
      fact('f1', 'A brownie is said to come out at night while the owners sleep, doing chores and farm tasks.', src(BROWNIE, 'come out at night while the owners of the house are asleep')),
      fact('f2', 'Families left a bowl of cream or porridge by the hearth for it.', src(BROWNIE, 'bowl of cream or porridge')),
      fact('f3', 'If given a gift of clothing, a brownie leaves forever.', src(BROWNIE, 'gift of clothing, he will leave forever')),
    ],
    moments: [
      moment('m1', 'The first English mention of a brownie disappearing after being given clothes is from a book published in 1584.', src(BROWNIE, '1584')),
      moment('m2', 'Brownies were said to be easily offended, leaving if they felt insulted or taken advantage of.', src(BROWNIE, 'easily offended')),
    ],
    angles: [
      angle('a1', 'the night shift', 'What does a spirit who cleans while everyone sleeps have in common with you?', 'Helping without needing credit is a quiet kind of strength.'),
      angle('a2', 'no thanks needed', 'Why would a gift make a helper leave?', 'Some people help best when nobody turns it into a big deal.'),
      angle('a3', 'a bowl of cream', 'What’s the smallest thanks that still counts?', 'Small, steady appreciation can matter more than a grand gesture.'),
      angle('a4', 'knowing your worth', 'When is it time to walk away?', 'Leaving when you’re taken for granted is allowed.'),
    ],
    tags: [
      tag('conflict_assertiveness', 'low', 'works without a word', 'It helps silently while the house sleeps.'),
      tag('attachment_avoidance', 'high', 'helps from a distance', 'It never shows itself to the family it helps.'),
      tag('extraversion', 'low', 'only comes out at night', 'It works only when everyone else is asleep.'),
      tag('openness', 'low', 'one house, one routine', 'It stays with one household, doing the same chores.'),
      tag('relatedness', 'low', 'happy on its own', 'It keeps to itself and needs no company.'),
    ],
    vetting: 'Folklore household spirit; no religious figure; no harm to children.',
  },
  {
    id: 'lf_tanuki',
    name: 'The Tanuki',
    kind: 'story',
    hall: 'ghosts',
    region: 'east_asia',
    place: 'Japanese folklore',
    era: 'Told for centuries',
    gender: 'none',
    field: 'Shapeshifter',
    essence: 'A shapeshifter with eight disguises, one more than the fox.',
    whoTheyWere: 'A shapeshifting raccoon dog from Japanese folklore, often a comical trickster.',
    famousFor: 'Changing shape for the fun of it, and the tea kettle that never ran dry.',
    facts: [
      fact('f1', 'A saying goes that the fox has seven disguises, and the tanuki has eight.', src(TANUKI, 'the tanuki has eight')),
      fact('f2', 'Some tellings say tanuki simply like to change their form.', src(TANUKI, 'simply like to change their form')),
      fact('f3', 'Tanuki statues are seen all over Japan, made in Shigaraki ware.', src(TANUKI, 'Shigaraki ware')),
    ],
    moments: [
      moment(
        'm1',
        'In the tale of Bunbuku Chagama, a tanuki disguised as a monk’s tea kettle boiled tea that never ran out.',
        src(TANUKI, 'disguised as a teapot', 'never run out'),
      ),
      moment('m2', 'Tanuki are said to drum on their bellies to make a pom-pom sound.', src(TANUKI, 'drum on their bellies')),
    ],
    angles: [
      angle('a1', 'eight disguises', 'What does a shapeshifter with one more trick than the fox have in common with you?', 'Being able to show up in different ways is a skill, not a fake.'),
      angle('a2', 'for the fun of it', 'Why change shape just because you can?', 'Doing something for fun is a good enough reason.'),
      angle('a3', 'the bottomless kettle', 'What happens when a trickster becomes the most useful thing in the room?', 'Your playful side can also be your most generous one.'),
      angle('a4', 'the belly drum', 'Who makes music with whatever they’ve got?', 'You can make a good time out of very little.'),
    ],
    tags: [
      tag('playfulness', 'high', 'changes shape for fun', 'Tellings say tanuki change form just because they like it.'),
      tag('conscientiousness', 'low', 'makes it up as it goes', 'It improvises one disguise after another.'),
      tag('extraversion', 'high', 'loves an audience', 'It plays tricks to get a reaction from people.'),
      tag('openness', 'high', 'tries every shape', 'It has more disguises than the fox.'),
    ],
    hidden: {
      needs: [
        { axis: 'playfulness', lean: 'high' },
        { axis: 'conscientiousness', lean: 'low' },
      ],
    },
    vetting: 'Folklore animal trickster; entry avoids the ribald imagery; no harm to children.',
  },
  {
    id: 'lf_headless_horseman',
    name: 'The Headless Horseman',
    kind: 'story',
    hall: 'ghosts',
    region: 'americas',
    place: 'American and European folklore',
    era: 'Told since the Middle Ages; Sleepy Hollow 1820',
    gender: 'none',
    field: 'Ghost rider',
    essence: 'A rider who chases travellers at night, and throws a pumpkin.',
    whoTheyWere: 'A ghostly rider of folklore, seen carrying his head or missing it altogether.',
    famousFor: 'Washington Irving’s 1820 story “The Legend of Sleepy Hollow”.',
    facts: [
      fact('f1', 'He appears in “The Legend of Sleepy Hollow”, a short story written in 1820 by Washington Irving.', src(wiki('Headless_Horseman'), 'written in 1820 by American writer Washington Irving')),
      fact('f2', 'Depending on the legend, he carries his head or is missing it altogether.', src(wiki('Headless_Horseman'), 'either carrying his head, or is missing his head altogether')),
      fact('f3', 'Irish folklore has a similar headless rider called the dullahan.', src(wiki('Headless_Horseman'), 'dullahan')),
    ],
    moments: [
      moment('m1', 'In Irving’s story the Horseman chases the schoolteacher Ichabod Crane and throws his pumpkin head at him.', src(wiki('Headless_Horseman'), 'throwing his pumpkin head at him')),
      moment('m2', 'Afterwards only Ichabod’s hat was found, near a shattered pumpkin.', src(wiki('Headless_Horseman'), 'shattered pumpkin')),
    ],
    angles: [
      angle('a1', 'the pumpkin', 'What does a ghost who throws a pumpkin have in common with you?', 'Sometimes the scariest thing turns out to be a bit ridiculous.'),
      angle('a2', 'the chase', 'Why do some stories stay with us on dark roads?', 'Fear makes a story stick, and a laugh makes it bearable.'),
      angle('a3', 'the mystery', 'Was it a ghost, or a prank?', 'Not every mystery needs solving to be fun.'),
      angle('a4', 'many countries', 'Why do so many places have a headless rider?', 'Some stories belong to everyone.'),
    ],
    tags: [
      tag('playfulness', 'high', 'scary, then silly', 'The story ends with a thrown pumpkin.'),
      tag('conscientiousness', 'high', 'rides every night', 'The Horseman roams the same roads again and again.'),
      tag('relatedness', 'low', 'rides alone', 'He is a solitary rider in the dark.'),
      tag('attachment_anxiety', 'high', 'forever searching', 'In some tellings he searches for what he lost.'),
      tag('growth_mindset', 'low', 'rides the same roads', 'He roams the same roads again and again.'),
    ],
    vetting: 'Folklore and fiction ghost; no religious figure; no harm to children.',
  },
  {
    id: 'lf_banshee',
    name: 'The Banshee',
    kind: 'story',
    hall: 'ghosts',
    region: 'europe',
    place: 'Irish folklore',
    era: 'Told for centuries',
    gender: 'woman',
    field: 'Spirit',
    essence: 'A spirit who wails for a family, so they’ll know.',
    whoTheyWere: 'A female spirit in Irish folklore whose name means “woman of the fairy mound”.',
    famousFor: 'Her wailing, said to warn a family of a coming loss.',
    facts: [
      fact('f1', 'Her name means “woman of the fairy mound” or “fairy woman”.', src(wiki('Banshee'), 'woman of the fairy mound')),
      fact('f2', 'In folklore she announces a loss in a family by wailing or keening.', src(wiki('Banshee'), 'heralds the death of a family member')),
      fact('f3', 'She wears a grey cloak over a green dress.', src(wiki('Banshee'), 'grey cloak over a green dress')),
    ],
    moments: [
      moment('m1', 'She is sometimes seen combing her long hair, and in some legends can only keen while combing it.', src(wiki('Banshee'), 'combing her hair')),
      moment('m2', 'Her name is tied to the fairy mounds that dot the Irish countryside.', src(wiki('Banshee'), 'mounds')),
    ],
    angles: [
      angle('a1', 'the warning', 'What does a spirit who warns a family have in common with you?', 'Telling people hard news gently is a kind of care.'),
      angle('a2', 'keening', 'Why would grief be sung out loud?', 'Letting feelings out can be healthier than holding them in.'),
      angle('a3', 'the comb', 'What small habit makes a legend memorable?', 'Little details are what make a character real.'),
      angle('a4', 'the fairy mound', 'Why do old places hold old stories?', 'The places around you can carry long memories.'),
    ],
    tags: [
      tag('steadiness', 'low', 'feels and wails', 'She expresses grief loudly.'),
      tag('attachment_avoidance', 'low', 'tied to her family', 'She is linked to particular families.'),
      tag('attachment_anxiety', 'high', 'keeps watch over them', 'She is said to sense coming loss.'),
      tag('playfulness', 'low', 'solemn and serious', 'Her role is solemn.'),
      tag('growth_mindset', 'low', 'the same old warning', 'She has warned families the same way for centuries.'),
    ],
    vetting: 'Folklore spirit; not sacred in a living religion; described gently, no harm to children.',
  },
  {
    id: 'lf_loch_ness_monster',
    name: 'The Loch Ness Monster',
    kind: 'story',
    hall: 'ghosts',
    region: 'europe',
    place: 'Scottish folklore',
    era: 'World famous since 1933',
    gender: 'none',
    field: 'Lake monster',
    essence: 'Nessie: seen by many, proven by none.',
    whoTheyWere: 'A creature of Scottish folklore said to live in Loch Ness, known affectionately as Nessie.',
    famousFor: 'Disputed sightings and photographs since 1933.',
    facts: [
      fact('f1', 'Known affectionately as Nessie, it is said to live in Loch Ness in the Scottish Highlands.', src(wiki('Loch_Ness_Monster'), 'known affectionately as Nessie')),
      fact('f2', 'It came to worldwide attention in 1933.', src(wiki('Loch_Ness_Monster'), 'brought to worldwide attention in 1933')),
      fact('f3', 'Scientists explain sightings as hoaxes, wishful thinking or misidentified animals and objects.', src(wiki('Loch_Ness_Monster'), 'hoaxes, wishful thinking')),
    ],
    moments: [
      moment('m1', 'The 1934 “surgeon’s photograph” is perhaps the most famous alleged photo of the creature.', src(wiki('Loch_Ness_Monster'), "surgeon's photograph")),
      moment('m2', 'Evidence for it is anecdotal, with disputed photos and sonar readings.', src(wiki('Loch_Ness_Monster'), 'Evidence of its existence is anecdotal')),
    ],
    angles: [
      angle('a1', 'seen, not proven', 'What does a monster nobody can prove have in common with you?', 'Some things are fun to wonder about even without an answer.'),
      angle('a2', 'the famous photo', 'Why do we want to believe the blurry picture?', 'Hope can make us see what we want to see.'),
      angle('a3', 'the quiet loch', 'What hides under calm surfaces?', 'Calm on top doesn’t mean nothing’s going on underneath.'),
      angle('a4', 'a nickname', 'Why give a monster a cute name?', 'A little affection can make something scary feel friendly.'),
    ],
    tags: [
      tag('extraversion', 'low', 'hides in the depths', 'It is rarely, if ever, seen.'),
      tag('attachment_avoidance', 'high', 'keeps out of sight', 'It avoids being proven.'),
      tag('openness', 'low', 'never leaves the loch', 'It stays in the same loch.'),
      tag('playfulness', 'high', 'the world’s favourite mystery', 'Nessie is a beloved, playful mystery.'),
      tag('competence', 'low', 'too careful to be caught', 'It has never been proven to exist.'),
    ],
    vetting: 'Modern folklore creature; no religious figure; no harm to children.',
  },
  {
    id: 'lf_yeti',
    name: 'The Yeti',
    kind: 'story',
    hall: 'ghosts',
    region: 'south_asia',
    place: 'Himalayan folklore',
    era: 'Told for generations',
    gender: 'none',
    field: 'Mountain creature',
    essence: 'Leaves giant footprints in the snow, and never stays for a photo.',
    whoTheyWere: 'A large, hairy creature of folklore said to live in the Himalayas, also called the Abominable Snowman.',
    famousFor: 'Footprints in the snow and endless searches.',
    facts: [
      fact('f1', 'It is said to live in the Himalayan mountain range.', src(wiki('Yeti'), 'inhabit the Himalayan mountain range')),
      fact('f2', 'It is also called the Abominable Snowman.', src(wiki('Yeti'), 'Abominable Snowman')),
      fact('f3', 'Folklorists trace it partly to Sherpa folklore and misidentified animals like bears or yaks.', src(wiki('Yeti'), 'Sherpa folklore', 'bear or yak')),
    ],
    moments: [
      moment('m1', 'Searchers have offered plaster casts of large footprints as evidence.', src(wiki('Yeti'), 'plaster casts of large footprints')),
      moment('m2', 'It is often compared to Bigfoot of North America.', src(wiki('Yeti'), 'Bigfoot of North America')),
    ],
    angles: [
      angle('a1', 'the footprints', 'What does a creature known only by its footprints have in common with you?', 'You can leave a mark without needing to be seen.'),
      angle('a2', 'the high mountains', 'Why live where nobody else can?', 'Some of us need space and quiet to be ourselves.'),
      angle('a3', 'the search', 'Why keep looking for something you might never find?', 'The search can be the adventure.'),
      angle('a4', 'cousins', 'Why do mountain creatures appear in stories everywhere?', 'People everywhere wonder about the wild.'),
    ],
    tags: [
      tag('relatedness', 'low', 'lives alone in the snow', 'It is a solitary mountain creature.'),
      tag('attachment_avoidance', 'high', 'avoids every camera', 'It is never reliably seen.'),
      tag('extraversion', 'low', 'stays out of sight', 'It is known by traces, not appearances.'),
      tag('autonomy', 'high', 'lives by its own rules', 'It lives far from people.'),
      tag('competence', 'low', 'careful to stay hidden', 'It is known only by traces like footprints.'),
    ],
    vetting: 'Folklore creature; not a worshipped figure; no harm to children.',
  },
  {
    id: 'lf_will_o_the_wisp',
    name: 'Will-o’-the-wisp',
    kind: 'story',
    hall: 'ghosts',
    region: 'europe',
    place: 'European folklore',
    era: 'Told for centuries',
    gender: 'none',
    field: 'Ghost light',
    essence: 'A light over the marsh that may show the way, or lead you astray.',
    whoTheyWere: 'A ghost light of folklore seen by travellers at night over bogs, swamps and marshes.',
    famousFor: 'Its flickering light, and being the original jack-o’-lantern.',
    facts: [
      fact('f1', 'It is a ghost light seen by travellers at night over bogs, swamps or marshes.', src(wiki("Will-o'-the-wisp"), 'ghost light seen by travellers at night')),
      fact('f2', 'Its Latin name, ignis fatuus, means “foolish flame”.', src(wiki("Will-o'-the-wisp"), 'ignis fatuus', 'foolish flame')),
      fact('f3', 'The term jack-o’-lantern first referred to a will-o’-the-wisp.', src(wiki("Will-o'-the-wisp"), "jack-o'-lantern")),
    ],
    moments: [
      moment('m1', 'In folklore it might reveal a path, or lead travellers away from it.', src(wiki("Will-o'-the-wisp"), 'reveal (or conceal) a path')),
      moment('m2', 'In the United States such lights are often called spook-lights or ghost-lights.', src(wiki("Will-o'-the-wisp"), 'spook-lights')),
    ],
    angles: [
      angle('a1', 'the light ahead', 'What does a light that might lead you astray have in common with you?', 'Not every shiny thing ahead is the right path.'),
      angle('a2', 'foolish flame', 'Why follow something you’re not sure about?', 'Curiosity is good. A little caution keeps you safe.'),
      angle('a3', 'the original lantern', 'How does a ghost light become a Halloween pumpkin?', 'Old stories turn into new traditions.'),
      angle('a4', 'path or puzzle', 'Is it guiding you, or testing you?', 'How you read a sign says something about you.'),
    ],
    tags: [
      tag('playfulness', 'high', 'teases travellers', 'It may lead people astray for fun.'),
      tag('conscientiousness', 'low', 'never stays still', 'It flickers and wanders.'),
      tag('agreeableness', 'low', 'not reliably helpful', 'It might lead you off the path.'),
      tag('extraversion', 'high', 'wants to be noticed', 'It glows to catch your eye.'),
    ],
    vetting: 'Folklore light; no religious figure; no harm to children.',
  },
  {
    id: 'lf_tsukumogami',
    name: 'Tsukumogami',
    kind: 'story',
    hall: 'ghosts',
    region: 'east_asia',
    place: 'Japanese folklore',
    era: 'Told since medieval times',
    gender: 'none',
    field: 'Living objects',
    essence: 'Old tools that come alive on their hundredth birthday.',
    whoTheyWere: 'Tools and objects in Japanese folklore that have gained a spirit after long use.',
    famousFor: 'The idea that a 100-year-old object becomes alive and self-aware.',
    facts: [
      fact('f1', 'Tsukumogami are tools that have gained a spirit.', src(wiki('Tsukumogami'), 'tools that have acquired a kami or spirit')),
      fact('f2', 'In one old scroll, a tool gains a spirit after 100 years.', src(wiki('Tsukumogami'), 'after the passage of 100 years')),
      fact('f3', 'Today the word applies to almost any object that has reached its 100th birthday.', src(wiki('Tsukumogami'), '100th birthday')),
    ],
    moments: [
      moment('m1', 'The Tsukumogami Emaki scroll tells how old tools become tsukumogami.', src(wiki('Tsukumogami'), 'Tsukumogami Emaki')),
      moment('m2', 'An object that reaches 100 is said to become alive and self-aware.', src(wiki('Tsukumogami'), 'alive and self-aware')),
    ],
    angles: [
      angle('a1', 'the old tool', 'What does a teapot that came alive at 100 have in common with you?', 'Things that are loved and used for a long time gain a character of their own.'),
      angle('a2', 'patience', 'What happens when you just keep going for a century?', 'Long, quiet persistence can transform you.'),
      angle('a3', 'respect for things', 'Why treat old objects with care?', 'Looking after what you have is its own kind of respect.'),
      angle('a4', 'the birthday', 'What would you be like on your hundredth?', 'Every year adds something.'),
    ],
    tags: [
      tag('steadiness', 'high', 'a hundred patient years', 'They wait a century to awaken.'),
      tag('openness', 'low', 'the same tool for ages', 'They stay the same object for a hundred years.'),
      tag('playfulness', 'high', 'objects with personality', 'They come to life with their own character.'),
      tag('growth_mindset', 'high', 'grows a spirit with time', 'Time turns them into something new.'),
      tag('self_efficacy', 'low', 'waits a century to wake', 'They wait a hundred years before they awaken.'),
    ],
    vetting: 'Folklore spirits of objects; not worshipped figures; no harm to children.',
  },
  {
    id: 'lf_leprechaun',
    name: 'The Leprechaun',
    kind: 'story',
    hall: 'ghosts',
    region: 'europe',
    place: 'Irish folklore',
    era: 'Told for centuries',
    gender: 'none',
    field: 'Fairy',
    essence: 'A tiny shoemaker with a pot of gold and three wishes.',
    whoTheyWere: 'A small supernatural being of Irish folklore, often a solitary fairy who makes shoes.',
    famousFor: 'A hidden pot of gold at the end of the rainbow.',
    facts: [
      fact('f1', 'Later tales show leprechauns as shoemakers with a pot of gold at the end of the rainbow.', src(wiki('Leprechaun'), 'pot of gold at the end of the rainbow')),
      fact('f2', 'Some class the leprechaun as a solitary fairy.', src(wiki('Leprechaun'), 'solitary fairy')),
      fact('f3', 'A 19th-century poem calls him the Fairy Shoemaker.', src(wiki('Leprechaun'), 'Fairy Shoemaker')),
    ],
    moments: [
      moment('m1', 'In one old tale, a man captures his captors, who grant him three wishes for their release.', src(wiki('Leprechaun'), 'three wishes in exchange for release')),
      moment('m2', 'His main occupation is said to be making and mending shoes.', src(wiki('Leprechaun'), 'making and cobb')),
    ],
    angles: [
      angle('a1', 'the shoemaker', 'What does a fairy who mends shoes have in common with you?', 'Steady, careful craft can hide a lot of treasure.'),
      angle('a2', 'the hidden gold', 'Why keep your treasure secret?', 'Not everything valuable needs to be on show.'),
      angle('a3', 'three wishes', 'What would you ask for if you caught one?', 'Knowing what you want is half the magic.'),
      angle('a4', 'solitary', 'Why does a fairy work alone?', 'Some people do their best work by themselves.'),
    ],
    tags: [
      tag('relatedness', 'low', 'works alone', 'He is a solitary fairy.'),
      tag('playfulness', 'high', 'full of mischief', 'Leprechauns partake in mischief.'),
      tag('conscientiousness', 'high', 'mends every shoe', 'His occupation is making and mending shoes.'),
      tag('attachment_avoidance', 'high', 'guards his gold', 'He hides his pot of gold.'),
      tag('competence', 'low', 'guards his gold carefully', 'He keeps his pot of gold hidden.'),
    ],
    vetting: 'Folklore fairy; no religious figure; entry avoids stereotypes; no harm to children.',
  },
];
