import type { LegendFigure } from '../types';
import { angle, fact, moment, src, tag, wiki } from './define';

const NIGHTINGALE = wiki('Florence_Nightingale');

export const HEALER_LEGENDS: readonly LegendFigure[] = [
  {
    id: 'lf_florence_nightingale',
    name: 'Florence Nightingale',
    kind: 'real',
    hall: 'healers',
    region: 'europe',
    place: 'England',
    era: '1820–1910',
    died: 1910,
    birthday: { md: '05-12', source: src(NIGHTINGALE, '12 May 1820') },
    gender: 'woman',
    field: 'Nursing and statistics',
    essence: 'Fought for hospital reform with a lamp and a chart.',
    whoTheyWere: 'An English social reformer and statistician, known as the founder of modern nursing.',
    famousFor: '“The Lady with the Lamp”, and the first secular nursing school in the world.',
    facts: [
      fact('f1', 'She founded a nursing school at St Thomas’ Hospital in London in 1860, the first secular nursing school in the world.', src(NIGHTINGALE, 'first secular nursing school in the world', '1860')),
      fact('f2', 'She is famous for the polar area diagram, also called the Nightingale rose diagram.', src(NIGHTINGALE, 'polar area diagram', 'Nightingale rose diagram')),
      fact('f3', 'She was an innovator in statistics who used graphics to make data easier to act on.', src(NIGHTINGALE, 'innovator in statistics')),
    ],
    moments: [
      moment('m1', 'She became known as “The Lady with the Lamp” for making ward rounds for wounded soldiers at night.', src(NIGHTINGALE, 'The Lady with the Lamp', 'ward rounds')),
      moment('m2', 'She turned hospital data into diagrams so people could see what needed to change.', src(NIGHTINGALE, 'graphical forms')),
    ],
    angles: [
      angle('a1', 'the chart', 'What does a nurse who argued with diagrams have in common with you?', 'Showing the evidence clearly can change minds that arguments can’t.'),
      angle('a2', 'night rounds', 'Who walks the wards at night when everyone else is asleep?', 'Care that happens when nobody’s watching still counts.'),
      angle('a3', 'building the school', 'Why build a school instead of just doing the job?', 'Making a way for others to do what you do multiplies it.'),
      angle('a4', 'the reformer', 'What does it take to fix a system everyone else has accepted?', 'Being stubborn about the right thing is useful.'),
    ],
    tags: [
      tag('conscientiousness', 'high', 'kept the numbers', 'She collected data and turned it into clear charts.'),
      tag('locus_of_control', 'high', 'changed the system', 'She set out to fix how hospitals and nursing worked.'),
      tag('conflict_assertiveness', 'high', 'pushed for reform', 'She argued openly for changes to hospital care.'),
      tag('playfulness', 'low', 'all business', 'Her work was serious, careful and practical.'),
      tag('attachment_anxiety', 'high', 'checked every ward at night', 'She made ward rounds with a lamp at night.'),
    ],
    vetting: 'Reformer and statistician, died 1910; no political office; broadly admired.',
  },
  {
    id: 'lf_mary_seacole',
    name: 'Mary Seacole',
    kind: 'real',
    hall: 'healers',
    region: 'americas',
    place: 'Jamaica and Britain',
    era: '1805–1881',
    died: 1881,
    birthday: { md: '11-23', source: src(wiki('Mary_Seacole'), '23 November 1805') },
    gender: 'woman',
    field: 'Nursing',
    essence: 'Paid her own way to a war to look after the sick.',
    whoTheyWere: 'A Jamaican nurse and businesswoman who learned healing from her mother, a “doctress”.',
    famousFor: 'Her nursing in the Crimean War and her autobiography.',
    facts: [
      fact('f1', 'She was famous for her nursing work during the Crimean War.', src(wiki('Mary_Seacole'), 'nursing work during the Crimean War')),
      fact('f2', 'Her autobiography was the first written by a Black woman in Britain.', src(wiki('Mary_Seacole'), 'first autobiography written by a Black woman in Britain')),
      fact('f3', 'In 2004 she was voted the greatest Black Briton.', src(wiki('Mary_Seacole'), 'greatest Black B')),
    ],
    moments: [
      moment('m1', 'She went to the Crimean War in 1855 planning to set up the “British Hotel” as a place for sick and recovering officers.', src(wiki('Mary_Seacole'), 'British Hotel')),
      moment('m2', 'Her mother ran a boarding house and had herbalist skills, and taught her.', src(wiki('Mary_Seacole'), 'herbalist skills')),
    ],
    angles: [
      angle('a1', 'going anyway', 'What does a nurse who made her own way to a war have in common with you?', 'If the official route won’t take you, you can still find a way to help.'),
      angle('a2', 'the hotel', 'Why open a hotel in a war zone?', 'Comfort and care are part of healing too.'),
      angle('a3', 'her mother’s skills', 'What did you learn from the people who raised you?', 'Skills passed down quietly can turn out to be your greatest gift.'),
      angle('a4', 'remembered late', 'What happens when you’re forgotten for a century?', 'Being overlooked doesn’t erase what you did.'),
    ],
    tags: [
      tag('self_efficacy', 'high', 'went on her own', 'She travelled to the Crimean War on her own initiative.'),
      tag('conflict_cooperativeness', 'high', 'cared for the sick', 'She set up a place for sick and recovering soldiers.'),
      tag('autonomy', 'high', 'ran her own business', 'She was a businesswoman as well as a nurse.'),
      tag('openness', 'high', 'went far from home to help', 'She travelled from Jamaica to the Crimean War.'),
    ],
    vetting: 'Nurse, died 1881; no office; broadly admired.',
  },
  {
    id: 'lf_alexander_fleming',
    name: 'Alexander Fleming',
    kind: 'real',
    hall: 'healers',
    region: 'europe',
    place: 'Scotland',
    era: '1881–1955',
    died: 1955,
    birthday: { md: '08-06', source: src(wiki('Alexander_Fleming'), '6 August 1881') },
    gender: 'man',
    field: 'Microbiology',
    essence: 'Came back from holiday to find mould on a dish, and found penicillin.',
    whoTheyWere: 'A Scottish physician and microbiologist.',
    famousFor: 'Discovering penicillin, the first antibiotic substance, in 1928.',
    facts: [
      fact('f1', 'In 1928 he discovered penicillin, the first antibiotic substance.', src(wiki('Alexander_Fleming'), 'first antibiotic substance discovered')),
      fact('f2', 'He shared the 1945 Nobel Prize in Physiology or Medicine.', src(wiki('Alexander_Fleming'), '1945 Nobel Prize in Physiology or Medicine')),
      fact('f3', 'His discovery has been called the “single greatest victory ever achieved over disease”.', src(wiki('Alexander_Fleming'), 'single greatest victory ever achieved over disease')),
    ],
    moments: [
      moment('m1', 'On 3 September 1928 he came back from a family holiday to the culture plates he had left on his bench.', src(wiki('Alexander_Fleming'), 'returned to his laboratory having spent a holiday with his family')),
      moment('m2', 'Before that, in 1922, he had discovered the enzyme lysozyme.', src(wiki('Alexander_Fleming'), 'enzyme lysozyme')),
    ],
    angles: [
      angle('a1', 'the messy bench', 'What does a scientist who found penicillin on an old dish have in common with you?', 'Noticing what’s odd, instead of cleaning it away, can change everything.'),
      angle('a2', 'after the holiday', 'What do you see when you come back with fresh eyes?', 'A break can be when the answer shows up.'),
      angle('a3', 'the first one', 'What does it mean to find the first of something?', 'Being curious about one small thing can help millions.'),
      angle('a4', 'shared credit', 'Why share a Nobel Prize?', 'Big breakthroughs are often finished by a team.'),
    ],
    tags: [
      tag('openness', 'high', 'curious about the odd dish', 'He paid attention to an unexpected result.'),
      tag('conscientiousness', 'low', 'left plates on the bench', 'His messy bench led to the discovery.'),
      tag('playfulness', 'high', 'experimented freely', 'His curiosity followed unexpected leads.'),
      tag('competence', 'high', 'knew what he was seeing', 'He recognised the importance of the mould.'),
      tag('locus_of_control', 'low', 'found it by chance', 'He came back from holiday to find mould on a dish.'),
    ],
    vetting: 'Scientist, died 1955; no office; broadly admired.',
  },
  {
    id: 'lf_elizabeth_blackwell',
    name: 'Elizabeth Blackwell',
    kind: 'real',
    hall: 'healers',
    region: 'americas',
    place: 'England and the United States',
    era: '1821–1910',
    died: 1910,
    birthday: { md: '02-03', source: src(wiki('Elizabeth_Blackwell'), '3 February 1821') },
    gender: 'woman',
    field: 'Medicine',
    essence: 'Admitted to medical school as a joke, then became America’s first woman doctor.',
    whoTheyWere: 'An English-American physician, the first woman to earn a medical degree in the United States.',
    famousFor: 'Earning the first medical degree awarded to a woman in the United States.',
    facts: [
      fact('f1', 'She was the first woman to earn a medical degree in the United States.', src(wiki('Elizabeth_Blackwell'), 'first woman to earn a medical degree in the United States')),
      fact('f2', 'With her sister Emily she founded the New York Infirmary for Women and Children in 1857.', src(wiki('Elizabeth_Blackwell'), 'New York Infirmary for Women and Children')),
      fact('f3', 'She was the first woman on the UK Medical Register.', src(wiki('Elizabeth_Blackwell'), 'first woman on the Medical Register')),
    ],
    moments: [
      moment('m1', 'Rejected by every medical school but one, she was admitted when the male students voted her in, as a joke.', src(wiki('Elizabeth_Blackwell'), 'albeit as a joke')),
      moment('m2', 'In 1847 she became the first woman to attend medical school in the United States.', src(wiki('Elizabeth_Blackwell'), 'first woman to attend medical school in the United States')),
    ],
    angles: [
      angle('a1', 'in as a joke', 'What does a doctor who was admitted as a joke have in common with you?', 'How you got in matters less than what you do once you’re there.'),
      angle('a2', 'every no but one', 'What keeps you applying after the rejections?', 'You only need one yes.'),
      angle('a3', 'building her own', 'Why start a hospital with your sister?', 'If the place you need doesn’t exist, you can build it.'),
      angle('a4', 'the first', 'What changes after you’re the first?', 'Going first makes the next person’s path easier.'),
    ],
    tags: [
      tag('steadiness', 'high', 'kept going through rejection', 'She kept applying after being turned down.'),
      tag('self_efficacy', 'high', 'took the joke seriously', 'She made the most of an admission meant as a joke.'),
      tag('locus_of_control', 'high', 'built her own infirmary', 'She founded a hospital for women and children.'),
      tag('conflict_assertiveness', 'high', 'pushed into medicine', 'She pursued medicine despite strong opposition.'),
      tag('playfulness', 'low', 'took the joke seriously', 'She was admitted as a joke and treated it as no joke.'),
    ],
    vetting: 'Physician, died 1910; no office; broadly admired.',
  },
  {
    id: 'lf_clara_barton',
    name: 'Clara Barton',
    kind: 'real',
    hall: 'healers',
    region: 'americas',
    place: 'United States',
    era: '1821–1912',
    died: 1912,
    birthday: { md: '12-25', source: src(wiki('Clara_Barton'), 'December 25, 1821') },
    gender: 'woman',
    field: 'Nursing and relief',
    essence: 'A self-taught nurse who founded the American Red Cross.',
    whoTheyWere: 'An American nurse, teacher and patent clerk who taught herself nursing.',
    famousFor: 'Founding the American Red Cross.',
    facts: [
      fact('f1', 'She founded the American Red Cross.', src(wiki('Clara_Barton'), 'founded the American Red Cross')),
      fact('f2', 'She was also a teacher and a patent clerk.', src(wiki('Clara_Barton'), 'a teacher, and a patent clerk')),
      fact('f3', 'She did not attend nursing school and was self-taught.', src(wiki('Clara_Barton'), 'did not attend nursing school')),
    ],
    moments: [
      moment('m1', 'She was called the “Angel of the Battlefield” after helping an overwhelmed surgeon.', src(wiki('Clara_Barton'), 'Angel of the Battlefield')),
      moment('m2', 'After the war she ran the Office of Missing Soldiers, to find or identify missing men.', src(wiki('Clara_Barton'), 'Office of Missing Soldiers')),
    ],
    angles: [
      angle('a1', 'self-taught', 'What does a nurse who taught herself have in common with you?', 'You don’t need permission to learn what’s needed.'),
      angle('a2', 'the missing', 'Why spend years finding people others had lost track of?', 'Helping families get answers is a deep kind of care.'),
      angle('a3', 'from clerk to founder', 'How does a patent clerk end up founding the Red Cross?', 'The path to your life’s work can be winding.'),
      angle('a4', 'when it’s overwhelming', 'What do you do when the people in charge are overwhelmed?', 'Stepping in when others can’t is what makes a helper.'),
    ],
    tags: [
      tag('conflict_cooperativeness', 'high', 'helped where needed', 'She came to the aid of an overwhelmed surgeon.'),
      tag('locus_of_control', 'high', 'founded the Red Cross', 'She built an organisation to help in disasters.'),
      tag('growth_mindset', 'high', 'taught herself nursing', 'She learned nursing without formal schooling.'),
      tag('steadiness', 'high', 'steady under pressure', 'She worked calmly amid chaos.'),
    ],
    vetting: 'Nurse, died 1912; no office; broadly admired.',
  },
  {
    id: 'lf_virginia_apgar',
    name: 'Virginia Apgar',
    kind: 'real',
    hall: 'healers',
    region: 'americas',
    place: 'United States',
    era: '1909–1974',
    died: 1974,
    birthday: { md: '06-07', source: src(wiki('Virginia_Apgar'), 'June 7, 1909') },
    gender: 'woman',
    field: 'Medicine',
    essence: 'Invented a one-minute check that every newborn still gets.',
    whoTheyWere: 'An American physician and medical researcher, a leader in anaesthesiology.',
    famousFor: 'The Apgar score, used to check a newborn’s health right after birth.',
    facts: [
      fact('f1', 'In 1952 she developed the 10-point Apgar score for checking newborns.', src(wiki('Virginia_Apgar'), '10-point Apgar score')),
      fact('f2', 'The test is given one minute and five minutes after birth.', src(wiki('Virginia_Apgar'), 'one minute and five minutes after birth')),
      fact('f3', 'She was a leader in the fields of anesthesiology and teratology.', src(wiki('Virginia_Apgar'), 'leader in the fields of anesthesiology and teratology')),
    ],
    moments: [
      moment('m1', 'Her test checks a newborn’s breathing, skin colour, reflexes, motion and heart rate.', src(wiki('Virginia_Apgar'), "breathing, skin color, reflexes, motion, and heart rate")),
      moment('m2', 'A friend said she did more than any other physician to bring the problem of birth defects out of back rooms.', src(wiki('Virginia_Apgar'), 'bring the problem of birth defects out of back rooms')),
    ],
    angles: [
      angle('a1', 'one minute', 'What does a doctor whose check takes one minute have in common with you?', 'A simple, clear tool can do more good than a complicated one.'),
      angle('a2', 'everyone’s first test', 'How does one idea reach almost every newborn?', 'Practical ideas spread because they help.'),
      angle('a3', 'out of the back rooms', 'Why talk about the hard topics?', 'Being open about what others hide can change care for everyone.'),
      angle('a4', 'five simple signs', 'What can five quick checks tell you?', 'Breaking a big question into small steps makes it answerable.'),
    ],
    tags: [
      tag('conscientiousness', 'high', 'made a clear checklist', 'She built a simple, structured test.'),
      tag('competence', 'high', 'changed newborn care', 'Her score is used around the world.'),
      tag('conflict_assertiveness', 'high', 'spoke about hard topics', 'She brought birth defects into open discussion.'),
      tag('relatedness', 'high', 'cared about every newborn', 'She built her work around the health of newborns.'),
    ],
    vetting: 'Physician, died 1974; no office; broadly admired.',
  },
  {
    id: 'lf_charles_drew',
    name: 'Charles R. Drew',
    kind: 'real',
    hall: 'healers',
    region: 'americas',
    place: 'United States',
    era: '1904–1950',
    died: 1950,
    birthday: { md: '06-03', source: src(wiki('Charles_R._Drew'), 'June 3, 1904') },
    gender: 'man',
    field: 'Surgery and blood research',
    essence: 'Worked out how to store blood so it could save lives far away.',
    whoTheyWere: 'An American surgeon and medical researcher who studied blood transfusions.',
    famousFor: 'Building large-scale blood banks and inventing what became bloodmobiles.',
    facts: [
      fact('f1', 'He developed improved techniques for blood storage and large-scale blood banks.', src(wiki('Charles_R._Drew'), 'improved techniques for blood storage', 'large-scale blood banks')),
      fact('f2', 'He invented what became known as bloodmobiles, mobile donation stations.', src(wiki('Charles_R._Drew'), 'bloodmobiles')),
      fact('f3', 'He found that blood plasma could be preserved longer by separating it from the cells.', src(wiki('Charles_R._Drew'), 'blood plasma was able to be preserved')),
    ],
    moments: [
      moment('m1', 'In 1940 he was recruited to help the Blood for Britain project.', src(wiki('Charles_R._Drew'), 'Blood for Britain')),
      moment('m2', 'He became director of the first American Red Cross Blood Bank in 1941.', src(wiki('Charles_R._Drew'), 'first American Red Cross Blood Bank')),
    ],
    angles: [
      angle('a1', 'keeping it fresh', 'What does a surgeon who learned to store blood have in common with you?', 'Solving the boring storage problem can be what saves lives.'),
      angle('a2', 'on wheels', 'Why put a blood bank on wheels?', 'Taking help to people makes it reach further.'),
      angle('a3', 'the big system', 'How do you go from one lab to a whole country’s supply?', 'Scaling something up is its own kind of invention.'),
      angle('a4', 'the director', 'What changes when you lead the first of something?', 'Building the first version sets the pattern for all the rest.'),
    ],
    tags: [
      tag('conscientiousness', 'high', 'perfected storage methods', 'He improved how blood is stored.'),
      tag('openness', 'high', 'invented the bloodmobile', 'He came up with mobile donation stations.'),
      tag('locus_of_control', 'high', 'built blood banks', 'He led large-scale blood bank projects.'),
      tag('competence', 'high', 'expert in transfusion', 'He was a leading researcher in his field.'),
      tag('playfulness', 'low', 'careful, exacting work', 'He worked out how to store blood so it could save lives.'),
    ],
    vetting: 'Surgeon, died 1950; no office; broadly admired.',
  },
  {
    id: 'lf_avicenna',
    name: 'Avicenna (Ibn Sina)',
    kind: 'real',
    hall: 'healers',
    region: 'middle_east',
    place: 'Persia',
    era: 'c. 980–1037',
    died: 1037,
    gender: 'man',
    field: 'Medicine and philosophy',
    essence: 'Wrote a medical encyclopedia used for six centuries.',
    whoTheyWere: 'A Persian scholar often described as the father of early modern medicine.',
    famousFor: 'The Canon of Medicine and The Book of Healing.',
    facts: [
      fact('f1', 'His Canon of Medicine became a standard medical text at many medieval European universities.', src(wiki('Avicenna'), 'standard medical text at many medieval European universities')),
      fact('f2', 'He is often described as the father of early modern medicine.', src(wiki('Avicenna'), 'father of early modern medicine')),
      fact('f3', 'His Book of Healing is a philosophical and scientific encyclopedia.', src(wiki('Avicenna'), 'The Book of Healing, a philosophical and scientific encyclopedia')),
    ],
    moments: [
      moment('m1', 'As a boy he was sent to a greengrocer who taught him arithmetic.', src(wiki('Avicenna'), 'Indian greengrocer, who taught him arithmetic')),
      moment('m2', 'In Bukhara he had access to some of the great libraries of the time.', src(wiki('Avicenna'), 'access to the great libraries')),
    ],
    angles: [
      angle('a1', 'the greengrocer', 'What does a scholar who learned maths from a greengrocer have in common with you?', 'Good teachers can be found in unexpected places.'),
      angle('a2', 'the library', 'What happens when a curious mind gets a great library?', 'Access to the right books can change a life.'),
      angle('a3', 'one big book', 'Why write everything you know into one encyclopedia?', 'Organising what you know helps others build on it.'),
      angle('a4', 'six hundred years', 'How does a book stay useful for centuries?', 'Clear, careful work outlasts its author.'),
    ],
    tags: [
      tag('openness', 'high', 'studied everything', 'He wrote on medicine, philosophy and science.'),
      tag('conscientiousness', 'high', 'organised all he knew', 'He compiled huge encyclopedias.'),
      tag('growth_mindset', 'high', 'learned from anyone', 'He learned arithmetic from a greengrocer.'),
      tag('extraversion', 'low', 'lived in the libraries', 'He spent his youth in great libraries.'),
      tag('playfulness', 'low', 'a lifetime of careful study', 'He wrote a medical encyclopedia used for six centuries.'),
    ],
    vetting: 'Physician and philosopher, died 1037; no religious or political office; broadly admired.',
  },
  {
    id: 'lf_elizabeth_garrett_anderson',
    name: 'Elizabeth Garrett Anderson',
    kind: 'real',
    hall: 'healers',
    region: 'europe',
    place: 'England',
    era: '1836–1917',
    died: 1917,
    birthday: { md: '06-09', source: src(wiki('Elizabeth_Garrett_Anderson'), '9 June 1836') },
    gender: 'woman',
    field: 'Medicine',
    essence: 'Found a side door into medicine and held it open for others.',
    whoTheyWere: 'An English physician, the first woman to qualify in Britain as a physician and surgeon.',
    famousFor: 'Being the first woman to qualify as a doctor in Britain.',
    facts: [
      fact('f1', 'She was the first woman to qualify in Britain as a physician and surgeon.', src(wiki('Elizabeth_Garrett_Anderson'), 'first woman to qualify in Britain as a physician')),
      fact('f2', 'She was the first female dean of a British medical school.', src(wiki('Elizabeth_Garrett_Anderson'), 'first female dean of a British medical school')),
      fact('f3', 'She was the second of eleven children.', src(wiki('Elizabeth_Garrett_Anderson'), 'second of eleven chi')),
    ],
    moments: [
      moment('m1', 'She got her credentials through a “side door”: a loophole in admissions at the Society of Apothecaries.', src(wiki('Elizabeth_Garrett_Anderson'), 'side door', 'loophole')),
      moment('m2', 'She privately obtained a certificate in anatomy and physiology before being admitted in 1862.', src(wiki('Elizabeth_Garrett_Anderson'), 'privately obtained a certificate in anatomy and physiology')),
    ],
    angles: [
      angle('a1', 'the side door', 'What does a doctor who used a loophole to qualify have in common with you?', 'If the front door is locked, a side door still gets you in.'),
      angle('a2', 'studying privately', 'Why study on your own when the classroom won’t have you?', 'Learning on your own can be the start of something official.'),
      angle('a3', 'holding the door', 'What do you do after you get in?', 'Making the path easier for the next person is part of going first.'),
      angle('a4', 'one of eleven', 'How do you find your path in a big family?', 'Your own direction can start anywhere.'),
    ],
    tags: [
      tag('self_efficacy', 'high', 'found a way in', 'She used a loophole to qualify as a doctor.'),
      tag('conscientiousness', 'high', 'studied privately', 'She earned certificates on her own.'),
      tag('locus_of_control', 'high', 'made her own path', 'She found a route into a closed profession.'),
      tag('conflict_assertiveness', 'high', 'pushed into medicine', 'She pursued medicine despite opposition.'),
    ],
    vetting: 'Physician, died 1917; entry focuses on medicine; broadly admired.',
  },
  {
    id: 'lf_dorothea_dix',
    name: 'Dorothea Dix',
    kind: 'real',
    hall: 'healers',
    region: 'americas',
    place: 'United States',
    era: '1802–1887',
    died: 1887,
    birthday: { md: '04-04', source: src(wiki('Dorothea_Dix'), 'April 4, 1802') },
    gender: 'woman',
    field: 'Care reform',
    essence: 'Lobbied state after state for better care for people who were ill.',
    whoTheyWere: 'An American advocate for poor people living with mental illness.',
    famousFor: 'Lobbying for the first generation of American mental hospitals.',
    facts: [
      fact('f1', 'Through sustained lobbying she helped create the first generation of American mental hospitals.', src(wiki('Dorothea_Dix'), 'first generation of American mental asylums')),
      fact('f2', 'During the Civil War she served as Superintendent of Army Nurses.', src(wiki('Dorothea_Dix'), 'Superintendent of Army Nurses')),
      fact('f3', 'She lobbied state legislatures and the United States Congress.', src(wiki('Dorothea_Dix'), 'lobbying state legislatures and the United States Congress')),
    ],
    moments: [
      moment('m1', 'On a trip to Europe to recover her health, she met British reformers who inspired her work.', src(wiki('Dorothea_Dix'), 'met British social reformers who inspired her')),
      moment('m2', 'She grew up in Worcester, Massachusetts, among her parents’ relatives.', src(wiki('Dorothea_Dix'), 'Worcester, Massachusetts')),
    ],
    angles: [
      angle('a1', 'state after state', 'What does a reformer who lobbied state after state have in common with you?', 'Saying the same important thing many times is how change happens.'),
      angle('a2', 'inspired abroad', 'What can a trip to recover your health change?', 'Rest and new people can point you to your purpose.'),
      angle('a3', 'speaking up for others', 'Why fight for people who can’t speak for themselves?', 'Using your voice for others is a quiet kind of power.'),
      angle('a4', 'leading nurses', 'How do you organise care in a crisis?', 'Structure is a form of care too.'),
    ],
    tags: [
      tag('conflict_assertiveness', 'high', 'lobbied lawmakers', 'She pressed state legislatures and Congress.'),
      tag('conflict_cooperativeness', 'high', 'spoke up for others', 'She advocated for poor people who were ill.'),
      tag('conscientiousness', 'high', 'organised nurses', 'She was Superintendent of Army Nurses.'),
      tag('steadiness', 'high', 'kept at it for years', 'Her program of lobbying was sustained over years.'),
      tag('playfulness', 'low', 'serious about reform', 'She lobbied state after state for better care.'),
    ],
    vetting: 'Reformer, died 1887; no elected office; broadly admired.',
  },
];
