import type { LegendFigure } from '../types';
import { angle, fact, moment, src, tag, wiki } from './define';

const BEETHOVEN = wiki('Ludwig_van_Beethoven');
const UMM = wiki('Umm_Kulthum');
const RACH = wiki('Sergei_Rachmaninoff');

export const MUSIC_LEGENDS: readonly LegendFigure[] = [
  {
    id: 'lf_beethoven',
    name: 'Ludwig van Beethoven',
    kind: 'real',
    hall: 'music',
    region: 'europe',
    place: 'Germany and Austria',
    era: '1770–1827',
    died: 1827,
    gender: 'man',
    field: 'Music',
    essence: 'Kept writing music after he could no longer hear it.',
    whoTheyWere: 'A German composer and pianist who lived in Vienna and kept composing as his hearing faded.',
    famousFor: 'Nine symphonies, including the Ninth, the first major choral symphony.',
    facts: [
      fact('f1', 'He said his hearing loss began in 1798.', src(BEETHOVEN, 'hearing loss began in 1798')),
      fact('f2', 'His Ninth Symphony premiered in 1824.', src(BEETHOVEN, 'the Ninth, premiered in 1824')),
      fact('f3', 'The Ninth was the first major example of a choral symphony.', src(BEETHOVEN, 'first major example of a choral symphony')),
    ],
    moments: [
      moment(
        'm1',
        'At the Ninth’s premiere, the singer Caroline Unger turned him around so he could see the applause he could not hear.',
        src(BEETHOVEN, 'turned Beethoven around to see the applause he could not hear'),
      ),
      moment('m2', 'When singers begged him to change parts of the Ninth, he refused.', src(BEETHOVEN, 'Beethoven refused')),
    ],
    angles: [
      angle('a1', 'the unheard applause', 'What does a composer who couldn’t hear his own premiere have in common with you?', 'Your work can land with people even when you can’t see it landing.'),
      angle('a2', 'no changes', 'Why would someone refuse the singers who begged for an easier part?', 'Holding your ground on the thing you care about most can be worth the friction.'),
      angle('a3', 'the long fade', 'How do you keep making something when the tool you use starts to fail?', 'Adapting how you work can keep the work itself alive.'),
      angle('a4', 'the first of its kind', 'What does it take to add a choir to a symphony?', 'Breaking the usual format is easier when you know the format deeply.'),
    ],
    tags: [
      tag('agreeableness', 'low', 'refused to soften the Ninth', 'He turned down the singers who asked for easier parts.'),
      tag('steadiness', 'low', 'felt the loss deeply', 'His hearing loss weighed on him for decades.'),
      tag('autonomy', 'high', 'wrote it his way', 'He broke the usual symphony form by adding a choir.'),
      tag('attachment_avoidance', 'high', 'kept to himself', 'As his hearing faded, much of his work happened alone.'),
      tag('conflict_cooperativeness', 'low', 'stood firm on the score', 'He held to his own version even when performers objected.'),
    ],
    vetting: 'Composer, died 1827; no office; broadly admired. Entry avoids his darkest letters on purpose.',
  },
  {
    id: 'lf_umm_kulthum',
    name: 'Umm Kulthum',
    kind: 'real',
    hall: 'music',
    region: 'middle_east',
    place: 'Egypt',
    era: '1904–1975',
    died: 1975,
    gender: 'woman',
    field: 'Singing',
    essence: 'Sang on the first Thursday of every month, for forty years.',
    whoTheyWere: 'An Egyptian singer who began as a child, singing beside her father, and became the Arab world’s most celebrated voice.',
    famousFor: 'Monthly radio concerts and a funeral attended by over four million people.',
    facts: [
      fact('f1', 'As a child her father dressed her in boys’ clothes so she could sing in public.', src(UMM, 'dressed her in boys')),
      fact('f2', 'She performed a concert on the first Thursday of every month for forty years.', src(UMM, 'first Thursday of every month for forty years')),
      fact('f3', 'Her funeral in Cairo in 1975 drew a crowd of over four million people.', src(UMM, 'over 4 million people')),
    ],
    moments: [
      moment('m1', 'In 1934 she sang for the first broadcast of Egyptian Radio.', src(UMM, 'inaugural broadcast of the Egyptian Radio')),
      moment('m2', 'She moved to Cairo in the early 1920s, where her career took off.', src(UMM, 'moved to the city of Cairo in the early 1920s')),
    ],
    angles: [
      angle('a1', 'the monthly show', 'What does a singer who showed up every month for forty years have in common with you?', 'Showing up on a set day, again and again, builds something people can count on.'),
      angle('a2', 'the disguise', 'Why would a girl sing in boys’ clothes?', 'Sometimes you find a side door into the thing you love, and walk through it.'),
      angle('a3', 'the voice of millions', 'How does one voice end up loved by four million people at once?', 'The care you put into your craft is felt by people you’ll never meet.'),
      angle('a4', 'the move to Cairo', 'What changes when you take your talent to the big city?', 'Going where your work can grow is a choice you can make on purpose.'),
    ],
    tags: [
      tag('conscientiousness', 'high', 'every first Thursday, forty years', 'She kept a monthly concert schedule for four decades.'),
      tag('relatedness', 'high', 'sang to a whole region', 'Her concerts connected millions of listeners.'),
      tag('competence', 'high', 'owned every stage', 'She became the most distinguished singer of her era.'),
      tag('steadiness', 'high', 'steady for decades', 'Her long monthly run needed steady nerves.'),
      tag('extraversion', 'high', 'lived on stage', 'She performed publicly from childhood on.'),
    ],
    vetting: 'Singer, died 1975; no office; broadly beloved across the Arab world.',
  },
  {
    id: 'lf_rachmaninoff',
    name: 'Sergei Rachmaninoff',
    kind: 'real',
    hall: 'music',
    region: 'europe',
    place: 'Russia and the United States',
    era: '1873–1943',
    died: 1943,
    birthday: { md: '04-01', source: src(RACH, '1 April') },
    gender: 'man',
    field: 'Music',
    essence: 'Wrote his most loved concerto after three years of not writing.',
    whoTheyWere: 'A Russian composer and one of the finest pianists of his day, who later lived in the United States.',
    famousFor: 'His Piano Concerto No. 2, which marked his comeback as a composer.',
    facts: [
      fact('f1', 'After his First Symphony was badly received in 1897, he went through three years of writer’s block.', src(RACH, 'lasted three years', 'writer\'s block')),
      fact('f2', 'He gave piano lessons to support himself during those years.', src(RACH, 'he gave piano lessons')),
      fact('f3', 'His Piano Concerto No. 2 was finished in April 1901 and dedicated to the doctor who helped him.', src(RACH, 'finished in April 1901', 'dedicated to Dahl')),
    ],
    moments: [
      moment('m1', 'In 1900 he met almost daily with Nikolai Dahl, a physician and amateur musician, to get back to composing.', src(RACH, 'Nikolai Dahl', 'on a daily basis')),
      moment('m2', 'When the full concerto was first performed in 1901, it was received with enthusiasm.', src(RACH, 'enthusiastically received')),
    ],
    angles: [
      angle('a1', 'the comeback', 'What does a composer stuck for three years have in common with you?', 'A long stall is not the end of the story. It can be the part right before the turn.'),
      angle('a2', 'asking for help', 'Who dedicates their masterpiece to the person who helped them start again?', 'Getting help is part of the work, not a detour from it.'),
      angle('a3', 'the day job', 'Why would a great composer spend years teaching scales?', 'Paying the bills while you wait for the spark is nothing to hide.'),
      angle('a4', 'one bad review', 'How much can one bad night really cost you?', 'A harsh reaction can feel final. Your next piece still gets written.'),
    ],
    tags: [
      tag('competence', 'low', 'doubted his own skill', 'After one bad premiere he couldn’t compose for years.'),
      tag('steadiness', 'low', 'hit hard by criticism', 'The failed premiere left him heavily depressed for a time.'),
      tag('attachment_anxiety', 'high', 'felt every reaction', 'How people received his work affected him deeply.'),
      tag('growth_mindset', 'high', 'worked his way back', 'He met with a doctor almost daily to return to composing.'),
      tag('self_efficacy', 'low', 'unsure he could write', 'For three years he composed very little.'),
    ],
    vetting: 'Composer and pianist, died 1943; no office; broadly admired. Struggles described gently, no clinical detail.',
  },
  {
    id: 'lf_louis_armstrong',
    name: 'Louis Armstrong',
    kind: 'real',
    hall: 'music',
    region: 'americas',
    place: 'United States',
    era: '1901–1971',
    died: 1971,
    birthday: { md: '08-04', source: src(wiki('Louis_Armstrong'), 'August 4, 1901') },
    gender: 'man',
    field: 'Jazz',
    essence: 'Turned jazz from a group sound into a stage for one voice.',
    whoTheyWere: 'An American jazz trumpeter and singer from New Orleans, nicknamed “Satchmo” and “Pops”.',
    famousFor: 'His trumpet, his gravelly voice and “What a Wonderful World”.',
    facts: [
      fact('f1', 'He shifted the focus of jazz from collective improvisation to solo performance.', src(wiki('Louis_Armstrong'), 'shifting the focus of the music from collective improvisation to solo performance')),
      fact('f2', 'He was skilled at scat singing.', src(wiki('Louis_Armstrong'), 'skilled at scat singing')),
      fact('f3', 'His best known songs include “What a Wonderful World” and “La Vie en rose”.', src(wiki('Louis_Armstrong'), 'What a Wonderful World', 'La Vie en rose')),
    ],
    moments: [
      moment('m1', 'Around 1922 he followed his mentor, Joe “King” Oliver, to Chicago to play in his band.', src(wiki('Louis_Armstrong'), 'followed his mentor, Joe "King" Oliver, to Chicago')),
      moment('m2', 'He was known for joking with the audience and keeping a joyful public image.', src(wiki('Louis_Armstrong'), 'joking with the audience')),
    ],
    angles: [
      angle('a1', 'the solo', 'What does a trumpeter who made room for the solo have in common with you?', 'Stepping forward on your own can change what everyone else thinks is possible.'),
      angle('a2', 'following the mentor', 'Why follow your teacher to a new city?', 'Going where the people you learn from are is a smart early move.'),
      angle('a3', 'the joy', 'What does a grin do for a whole room?', 'Bringing warmth to the room is a talent, not a side note.'),
      angle('a4', 'scat', 'What happens when you run out of words and keep singing?', 'Making it up as you go can be the most honest part of the show.'),
    ],
    tags: [
      tag('playfulness', 'high', 'joked with every crowd', 'He was known for joking with the audience.'),
      tag('extraversion', 'high', 'lived for the stage', 'His career was built on performing live.'),
      tag('openness', 'high', 'invented as he played', 'He was a skilful improviser.'),
      tag('agreeableness', 'high', 'a joyful public face', 'He kept a warm, joyful public image.'),
      tag('autonomy', 'low', 'followed his mentor', 'He followed his mentor to Chicago to play in his band.'),
    ],
    vetting: 'Musician, died 1971; no office; broadly beloved.',
  },
  {
    id: 'lf_mozart',
    name: 'Wolfgang Amadeus Mozart',
    kind: 'real',
    hall: 'music',
    region: 'europe',
    place: 'Austria',
    era: '1756–1791',
    died: 1791,
    birthday: { md: '01-27', source: src(wiki('Wolfgang_Amadeus_Mozart'), '27 January 1756') },
    gender: 'man',
    field: 'Music',
    essence: 'Played for royalty at five and wrote more than 800 works.',
    whoTheyWere: 'A Classical composer from Salzburg who became one of the greatest composers in Western music.',
    famousFor: 'More than 800 works, including symphonies, operas and concertos.',
    facts: [
      fact('f1', 'He completed more than 800 works in his life.', src(wiki('Wolfgang_Amadeus_Mozart'), 'more than 800 works')),
      fact('f2', 'At five he could play keyboard and violin, had begun to compose, and had performed for European royalty.', src(wiki('Wolfgang_Amadeus_Mozart'), 'At the age of five he was already competent on keyboard and violin')),
      fact('f3', 'He was born in Salzburg and trained by his father Leopold.', src(wiki('Wolfgang_Amadeus_Mozart'), 'Born in Salzburg', 'his father Leopold')),
    ],
    moments: [
      moment('m1', 'In 1781, after quarrels with his Salzburg employers, he was dismissed, and chose to stay in Vienna.', src(wiki('Wolfgang_Amadeus_Mozart'), 'he was dismissed', 'chose to remain in Vienna')),
      moment('m2', 'His father took him on a grand tour of Europe as a child.', src(wiki('Wolfgang_Amadeus_Mozart'), 'took him on a grand tour of Europe')),
    ],
    angles: [
      angle('a1', 'leaving the steady job', 'What does a composer who walked away from his employer have in common with you?', 'Choosing your own path over a safe job is scary, and sometimes right.'),
      angle('a2', 'early talent', 'What do you do with a gift that showed up at five?', 'Talent is a start. What you build with it is the story.'),
      angle('a3', 'so much music', 'How do you write more than 800 works in one life?', 'Steady making adds up to more than you can picture.'),
      angle('a4', 'the big city', 'Why stay in Vienna with no job lined up?', 'Betting on the place where your work can grow takes nerve.'),
    ],
    tags: [
      tag('autonomy', 'high', 'chose Vienna over his employer', 'He stayed in Vienna after being dismissed.'),
      tag('playfulness', 'high', 'music full of play', 'He wrote a huge range of lively works.'),
      tag('competence', 'high', 'mastered music at five', 'He played and composed as a small child.'),
      tag('conscientiousness', 'low', 'followed his own rhythm', 'He quarrelled with his employers over how to work.'),
      tag('agreeableness', 'low', 'clashed with his bosses', 'His quarrels with his Salzburg employers came to a head.'),
    ],
    vetting: 'Composer, died 1791; no office; broadly admired.',
  },
  {
    id: 'lf_ella_fitzgerald',
    name: 'Ella Fitzgerald',
    kind: 'real',
    hall: 'music',
    region: 'americas',
    place: 'United States',
    era: '1917–1996',
    died: 1996,
    birthday: { md: '04-25', source: src(wiki('Ella_Fitzgerald'), 'April 25, 1917') },
    gender: 'woman',
    field: 'Jazz singing',
    essence: 'Went on stage to dance, sang instead, and became the First Lady of Song.',
    whoTheyWere: 'An American jazz singer known for her pure tone and her horn-like scat singing.',
    famousFor: 'Her voice, her scat singing and 14 Grammy Awards.',
    facts: [
      fact('f1', 'She was called the “First Lady of Song” and the “Queen of Jazz”.', src(wiki('Ella_Fitzgerald'), 'First Lady of Song', 'Queen of Jazz')),
      fact('f2', 'Her accolades included 14 Grammy Awards.', src(wiki('Ella_Fitzgerald'), '14 Grammy Awards')),
      fact('f3', 'She found stability in her music with the Chick Webb Orchestra.', src(wiki('Ella_Fitzgerald'), 'Chick Webb Orchestra')),
    ],
    moments: [
      moment(
        'm1',
        'At 17 she went on at one of the first Amateur Nights at the Apollo Theater, planning to dance, but she was intimidated by a dance duo and sang instead.',
        src(wiki('Ella_Fitzgerald'), 'Amateur Nights at the Apollo Theater', 'intended to go on stage and dance'),
      ),
      moment('m2', 'She was noted for her timing, diction and improvising.', src(wiki('Ella_Fitzgerald'), 'impeccable diction')),
    ],
    angles: [
      angle('a1', 'plan B', 'What does a singer who meant to dance that night have in common with you?', 'The backup plan can turn out to be the real one.'),
      angle('a2', 'nerves on stage', 'What do you do when the act before you is better?', 'Switching to what you do best in the moment is a skill.'),
      angle('a3', 'the horn voice', 'How do you sing like a trumpet?', 'Using what you have in an unexpected way is how you sound like no one else.'),
      angle('a4', 'finding stability', 'What changes when you find the right band?', 'The right group around you can steady everything else.'),
    ],
    tags: [
      tag('competence', 'high', 'perfect timing and tone', 'She was noted for her pure tone and phrasing.'),
      tag('extraversion', 'low', 'nervous before the show', 'She was intimidated on stage at her first Amateur Night.'),
      tag('openness', 'high', 'sang like an instrument', 'Her scat singing was horn-like and improvised.'),
      tag('relatedness', 'high', 'grew with her band', 'She found stability with the Chick Webb Orchestra.'),
    ],
    vetting: 'Singer, died 1996; no office; broadly beloved.',
  },
  {
    id: 'lf_clara_schumann',
    name: 'Clara Schumann',
    kind: 'real',
    hall: 'music',
    region: 'europe',
    place: 'Germany',
    era: '1819–1896',
    died: 1896,
    birthday: { md: '09-13', source: src(wiki('Clara_Schumann'), '13 September 1819') },
    gender: 'woman',
    field: 'Piano',
    essence: 'Played concerts for 61 years and changed what a recital is.',
    whoTheyWere: 'A German virtuoso pianist, composer and piano teacher of the Romantic era.',
    famousFor: 'A 61-year concert career that reshaped the piano recital.',
    facts: [
      fact('f1', 'Over a 61-year concert career she changed the format and repertoire of the piano recital.', src(wiki('Clara_Schumann'), '61-year concert career')),
      fact('f2', 'She married the composer Robert Schumann in 1840, and they had eight children.', src(wiki('Clara_Schumann'), 'eight children')),
      fact('f3', 'Her image appeared on the 100 Deutsche Mark banknote from 1989 to 2002.', src(wiki('Clara_Schumann'), '100 Deutsche Mark banknote')),
    ],
    moments: [
      moment('m1', 'She gave the public premieres of many works by her husband and by Johannes Brahms.', src(wiki('Clara_Schumann'), 'public premieres of many works by her husband and by Brahms')),
      moment('m2', 'With Robert she encouraged the young Johannes Brahms.', src(wiki('Clara_Schumann'), 'encouraged Johannes Brahms')),
    ],
    angles: [
      angle('a1', 'sixty-one years', 'What does a pianist who played for sixty-one years have in common with you?', 'Staying with something for decades lets you change it from the inside.'),
      angle('a2', 'the champion', 'Why play other people’s music to the world first?', 'Lifting up someone else’s work is a kind of leadership.'),
      angle('a3', 'eight children and a career', 'How do you keep a career going with a full house?', 'Holding many roles at once is real work, even when nobody sees it.'),
      angle('a4', 'changing the format', 'What happens when you decide a recital should be different?', 'Small changes to how something is done can last for generations.'),
    ],
    tags: [
      tag('conscientiousness', 'high', 'a 61-year career', 'She kept performing for 61 years.'),
      tag('conflict_cooperativeness', 'high', 'premiered others’ music', 'She introduced works by her husband and Brahms.'),
      tag('steadiness', 'high', 'steady through a full life', 'She balanced a long career with eight children.'),
      tag('relatedness', 'high', 'encouraged young Brahms', 'She and Robert encouraged Brahms and stayed close to him.'),
    ],
    vetting: 'Pianist and composer, died 1896; no office; broadly admired.',
  },
  {
    id: 'lf_johann_sebastian_bach',
    name: 'Johann Sebastian Bach',
    kind: 'real',
    hall: 'music',
    region: 'europe',
    place: 'Germany',
    era: '1685–1750',
    died: 1750,
    gender: 'man',
    field: 'Music',
    essence: 'Walked hundreds of kilometres to hear an organist play.',
    whoTheyWere: 'A German composer and musician of the late Baroque period, known for his huge output.',
    famousFor: 'The Brandenburg Concertos, the Cello Suites and the Goldberg Variations.',
    facts: [
      fact('f1', 'He wrote the Brandenburg Concertos and the Cello Suites.', src(wiki('Johann_Sebastian_Bach'), 'Brandenburg Concertos', 'Cello Suites')),
      fact('f2', 'His keyboard works include the Goldberg Variations and The Well-Tempered Clavier.', src(wiki('Johann_Sebastian_Bach'), 'Goldberg Variations', 'Well-Tempered Clavier')),
      fact('f3', 'In 1723 he became Thomaskantor, director of music in Leipzig.', src(wiki('Johann_Sebastian_Bach'), 'Thomaskantor')),
    ],
    moments: [
      moment('m1', 'To hear the organist Dieterich Buxtehude play in Lübeck, he travelled 450 kilometres each way, reportedly on foot.', src(wiki('Johann_Sebastian_Bach'), '450-kilometre', 'reportedly on foot')),
      moment('m2', 'In Leipzig he decided to compose a new cycle of cantatas every year.', src(wiki('Johann_Sebastian_Bach'), 'annual cycles')),
    ],
    angles: [
      angle('a1', 'the long walk', 'What does a composer who walked 450 kilometres to hear one musician have in common with you?', 'Going far to learn from someone you admire says a lot about what you care about.'),
      angle('a2', 'a piece every week', 'What do you get from making something new on a schedule?', 'A steady habit can produce work that outlives you.'),
      angle('a3', 'the teacher’s job', 'Can a day job hold a lifetime of masterpieces?', 'Great work can come out of an ordinary routine.'),
      angle('a4', 'many instruments', 'Why write for every instrument there is?', 'Trying every form keeps you learning.'),
    ],
    tags: [
      tag('conscientiousness', 'high', 'a cantata cycle a year', 'He set himself a new cycle of cantatas every year.'),
      tag('growth_mindset', 'high', 'walked to learn', 'He travelled far on foot to hear a master play.'),
      tag('playfulness', 'low', 'serious about craft', 'His work was careful and deeply structured.'),
      tag('steadiness', 'high', 'decades of steady work', 'He held long posts and kept composing.'),
    ],
    vetting: 'Composer, died 1750; a church musician, not a religious leader; broadly admired.',
  },
  {
    id: 'lf_frederic_chopin',
    name: 'Frédéric Chopin',
    kind: 'real',
    hall: 'music',
    region: 'europe',
    place: 'Poland and France',
    era: '1810–1849',
    died: 1849,
    birthday: { md: '03-01', source: src(wiki('Frédéric_Chopin'), '1 March 1810') },
    gender: 'man',
    field: 'Piano',
    essence: 'Wrote almost only for the piano, and invented a new form for it.',
    whoTheyWere: 'A Polish composer and pianist of the early Romantic period who wrote mainly for solo piano.',
    famousFor: 'His nocturnes, waltzes and mazurkas, and creating the instrumental ballade.',
    facts: [
      fact('f1', 'He wrote primarily for solo piano.', src(wiki('Frédéric_Chopin'), 'wrote primarily for solo piano')),
      fact('f2', 'He created the instrumental ballade as a genre.', src(wiki('Frédéric_Chopin'), 'instrumental ballade (which Chopin created as an instrumental genre)')),
      fact('f3', 'His performances were noted for their nuance and sensitivity.', src(wiki('Frédéric_Chopin'), 'noted for their nuance and sensitivity')),
    ],
    moments: [
      moment('m1', 'A child prodigy, he composed his early works in Warsaw before leaving Poland at 20.', src(wiki('Frédéric_Chopin'), 'leaving Poland at age 20')),
      moment('m2', 'A short visit to Mallorca in 1838–39 became one of his most productive periods of composition.', src(wiki('Frédéric_Chopin'), 'one of his most productive periods of composition')),
    ],
    angles: [
      angle('a1', 'one instrument', 'What does a composer who wrote almost only for piano have in common with you?', 'Going deep on one thing can be its own kind of freedom.'),
      angle('a2', 'leaving home at twenty', 'What do you carry with you when you leave your country young?', 'Home can come with you in the work you make.'),
      angle('a3', 'quiet power', 'Can soft playing be the most powerful kind?', 'Gentleness and sensitivity can hold a room.'),
      angle('a4', 'a new form', 'How do you invent a kind of music that didn’t exist?', 'You can make the container your ideas need.'),
    ],
    tags: [
      tag('steadiness', 'low', 'played with deep feeling', 'His playing was known for nuance and sensitivity.'),
      tag('extraversion', 'low', 'preferred small rooms', 'His music was made for the intimate sound of solo piano.'),
      tag('openness', 'high', 'invented the ballade', 'He created a new instrumental genre.'),
      tag('conscientiousness', 'high', 'polished every phrase', 'His technique was described as without equal.'),
      tag('growth_mindset', 'low', 'stayed with the piano', 'He wrote almost only for solo piano.'),
    ],
    vetting: 'Composer, died 1849; no office; broadly admired.',
  },
  {
    id: 'lf_hibari_misora',
    name: 'Hibari Misora',
    kind: 'real',
    hall: 'music',
    region: 'east_asia',
    place: 'Japan',
    era: '1937–1989',
    died: 1989,
    birthday: { md: '05-29', source: src(wiki('Hibari_Misora'), 'May 29, 1937') },
    gender: 'woman',
    field: 'Singing',
    essence: 'Started recording at twelve and gave a country hope after the war.',
    whoTheyWere: 'A Japanese singer and actress whose stage name means “lark in the beautiful sky”.',
    famousFor: '1,200 recorded songs and her swan song “Kawa no Nagare no Yō ni”.',
    facts: [
      fact('f1', 'She recorded a total of 1,200 songs.', src(wiki('Hibari_Misora'), 'recorded a total of 1,200 songs')),
      fact('f2', 'She began her recording career in 1949 at the age of 12.', src(wiki('Hibari_Misora'), 'recording career in 1949 at the age of 12')),
      fact('f3', 'Her name means “lark in the beautiful sky”.', src(wiki('Hibari_Misora'), 'lark in the beautiful sky')),
    ],
    moments: [
      moment('m1', 'She was honoured for giving the public hope and encouragement after World War II.', src(wiki('Hibari_Misora'), 'giving the public hope and encouragement after World War II')),
      moment('m2', 'Her swan song “Kawa no Nagare no Yō ni” is still performed as a tribute to her.', src(wiki('Hibari_Misora'), 'Kawa no Nagare no Yō ni')),
    ],
    angles: [
      angle('a1', 'hope after hard times', 'What does a singer who lifted a country’s mood have in common with you?', 'Bringing a little hope to people around you matters more than it seems.'),
      angle('a2', 'twelve years old', 'What does it take to start a career at twelve?', 'Being young doesn’t mean your voice isn’t ready.'),
      angle('a3', 'the last song', 'Why does one song become how people remember you?', 'One piece of work can carry everything you stood for.'),
      angle('a4', 'twelve hundred songs', 'How do you keep singing for a whole life?', 'Showing up for your craft year after year is its own kind of greatness.'),
    ],
    tags: [
      tag('relatedness', 'high', 'sang hope to a country', 'She was honoured for encouraging people after the war.'),
      tag('self_efficacy', 'high', 'recording at twelve', 'She started her recording career as a child.'),
      tag('conscientiousness', 'high', 'twelve hundred songs', 'She recorded 1,200 songs.'),
      tag('extraversion', 'high', 'a life on stage', 'She was a singer and actress from childhood.'),
    ],
    vetting: 'Singer, died 1989; no office; broadly beloved in Japan.',
  },
];
