import type { LegendFigure } from '../types';
import { angle, fact, moment, src, tag, wiki } from './define';

const ANANSI = wiki('Anansi');
const MULAN = wiki('Hua_Mulan');
const MOMO = wiki('Momotarō');
const ROBIN = wiki('Robin_Hood');

export const MYTH_LEGENDS: readonly LegendFigure[] = [
  {
    id: 'lf_anansi',
    name: 'Anansi',
    kind: 'story',
    hall: 'myth',
    region: 'africa',
    place: 'Akan folktales, West Africa',
    era: 'Told for centuries',
    gender: 'none',
    field: 'Trickster tales',
    essence: 'A spider who wanted every story in the world, and got them.',
    whoTheyWere: 'A trickster spider from Akan folklore, linked with stories, wisdom, wit and mischief.',
    famousFor: 'Winning all the world’s stories from the sky god, and giving his name to the spider tales.',
    facts: [
      fact('f1', 'Anansi is most often shown as a spider, and is linked with stories, wisdom and cunning.', src(ANANSI, 'most commonly depicted as a spider', 'stories, wisdom')),
      fact('f2', 'The whole tradition of tales is named after him: anansesem, or spider tales.', src(ANANSI, 'anansesem')),
      fact('f3', 'His tales spread to the Caribbean and the Americas.', src(ANANSI, 'Caribbean')),
    ],
    moments: [
      moment(
        'm1',
        'In the tale, the sky god Nyame kept all the stories, and set Anansi four tasks for them: catch a python, hornets, a leopard and a dwarf spirit.',
        src(ANANSI, 'sky god Nyame', 'python Onini', 'leopard Osebo'),
      ),
      moment('m2', 'Through cunning, and advice from his wife Aso, Anansi tricked each one into capture.', src(ANANSI, 'consultation of his wife Aso')),
    ],
    angles: [
      angle('a1', 'all the stories', 'What does a spider who bargained for every story have in common with you?', 'Wanting something big enough to ask the sky for it is a good start.'),
      angle('a2', 'brains over size', 'How does the smallest creature catch a leopard?', 'You don’t need to be the strongest in the room if you’re the cleverest.'),
      angle('a3', 'asking your partner', 'Who does the trickster ask when he gets stuck?', 'Even the cleverest plan gets better with one good outside opinion.'),
      angle('a4', 'the name on the tales', 'What does it take to have a whole tradition named after you?', 'Being the one who keeps the stories going is its own kind of legacy.'),
    ],
    tags: [
      tag('playfulness', 'high', 'won by playing tricks', 'He solves every task with a trick, not force.'),
      tag('openness', 'high', 'wanted every story', 'He set out to own all the stories in the world.'),
      tag('agreeableness', 'low', 'no rule-follower', 'He bargains, bends rules and outwits everyone.'),
      tag('conflict_cooperativeness', 'low', 'wanted them all for himself', 'He wanted the stories that the sky god held.'),
    ],
    hidden: {
      needs: [
        { axis: 'playfulness', lean: 'high' },
        { axis: 'agreeableness', lean: 'low' },
      ],
    },
    vetting: 'Folktale trickster (not a worshipped deity in the tales used); Akan source; no harm to children.',
  },
  {
    id: 'lf_hua_mulan',
    name: 'Hua Mulan',
    kind: 'story',
    hall: 'myth',
    region: 'east_asia',
    place: 'Chinese folk ballad',
    era: 'Ballad from c. 400–500s',
    gender: 'woman',
    field: 'Folk heroine',
    essence: 'Took her father’s place, and nobody noticed for twelve years.',
    whoTheyWere: 'The heroine of the Ballad of Mulan, a Chinese folk song first written down over a thousand years ago.',
    famousFor: 'Disguising herself to take her aged father’s place in the army.',
    facts: [
      fact('f1', 'The first known written record of Mulan is the Ballad of Mulan, a folk song.', src(MULAN, 'first known written record of Mulan is the Ballad of Mulan')),
      fact('f2', 'In the story she takes her aged father’s place because there is no other grown man in the family.', src(MULAN, 'took her aged father\'s place')),
      fact('f3', 'Offered high office at the end, she asks only for a horse to ride home.', src(MULAN, 'asking only for a horse')),
    ],
    moments: [
      moment('m1', 'The ballad opens with Mulan sighing at her loom, after her father is named in the call-up notices.', src(MULAN, 'Mulan sighs at her loom')),
      moment('m2', 'Back home in her old clothes, she meets her comrades, who are shocked: in twelve years they never knew she was a woman.', src(MULAN, 'For twelve years of their enlistment together')),
    ],
    angles: [
      angle('a1', 'in his place', 'What does a daughter who stepped up for her father have in common with you?', 'Stepping in for someone you love can show you what you’re capable of.'),
      angle('a2', 'just a horse', 'Why would a hero turn down high office for a ride home?', 'Knowing what you actually want is worth more than the biggest prize.'),
      angle('a3', 'the loom', 'What goes through your head the moment before you decide?', 'A sigh can come right before your bravest choice.'),
      angle('a4', 'twelve years unseen', 'How do you do the job so well that nobody questions you?', 'Doing the work well can speak louder than who people expect you to be.'),
    ],
    tags: [
      tag('self_efficacy', 'high', 'went to war for her family', 'She takes her father’s place in the army.'),
      tag('attachment_avoidance', 'low', 'did it for her father', 'Her whole story starts from wanting to protect him.'),
      tag('relatedness', 'high', 'came home to her family', 'She turns down office to go back to her family.'),
      tag('autonomy', 'low', 'answered the call-up', 'She acts from duty to the summons her father received.'),
      tag('attachment_anxiety', 'high', 'worried for her father', 'She took her father’s place so he would not have to go.'),
    ],
    vetting: 'Folk ballad heroine (legendary, not a real commander); widely loved; no harm to children.',
  },
  {
    id: 'lf_momotaro',
    name: 'Momotarō',
    kind: 'story',
    hall: 'myth',
    region: 'east_asia',
    place: 'Japanese folklore',
    era: 'Told for centuries',
    gender: 'man',
    field: 'Folk hero',
    essence: 'Shared his dumplings and gained a dog, a monkey and a pheasant.',
    whoTheyWere: 'The Peach Boy, a popular hero of Japanese folklore.',
    famousFor: 'Setting out for Demon Island with three animal friends he won over with dumplings.',
    facts: [
      fact('f1', 'His name means Peach Boy.', src(MOMO, 'Peach Boy')),
      fact('f2', 'He sets out for Onigashima, Demon Island, to stop a band of oni raiding the land.', src(MOMO, 'Onigashima')),
      fact('f3', 'The standard version of the story spread through school textbooks.', src(MOMO, 'school textbooks')),
    ],
    moments: [
      moment(
        'm1',
        'On the way he befriends a talking dog, monkey and pheasant, who help him in exchange for some of his millet dumplings.',
        src(MOMO, 'dog, monkey and pheasant', 'kibi dango'),
      ),
      moment('m2', 'He and his new friends return home with the treasure the oni had taken.', src(MOMO, 'plundered treasure')),
    ],
    angles: [
      angle('a1', 'the dumpling deal', 'What does a boy who recruited friends with snacks have in common with you?', 'Sharing what you have is often how a team starts.'),
      angle('a2', 'unlikely friends', 'Why would a dog, a monkey and a pheasant work together?', 'People who don’t seem to match can make the best team.'),
      angle('a3', 'setting out', 'What does it take to leave home for an island full of trouble?', 'Going toward the hard thing is easier with friends beside you.'),
      angle('a4', 'bringing it home', 'What do you do with the win?', 'A win means more when it goes back to the people it was for.'),
    ],
    tags: [
      tag('conflict_cooperativeness', 'high', 'shared his dumplings', 'He wins helpers by sharing his food.'),
      tag('attachment_anxiety', 'low', 'trusted strangers on the road', 'He welcomes three animals he’s only just met.'),
      tag('self_efficacy', 'high', 'headed for Demon Island', 'He sets out to face the oni himself.'),
      tag('relatedness', 'high', 'built a team', 'His whole quest depends on the friends he makes.'),
    ],
    vetting: 'Folk hero tale; no religious figure; no harm to children.',
  },
  {
    id: 'lf_robin_hood',
    name: 'Robin Hood',
    kind: 'story',
    hall: 'myth',
    region: 'europe',
    place: 'English folklore',
    era: 'Ballads from the 1400s',
    gender: 'man',
    field: 'Folk outlaw',
    essence: 'An outlaw whose men followed him more gladly than the king’s.',
    whoTheyWere: 'A legendary outlaw of English folklore, a skilled archer, first found in ballads from the 1400s.',
    famousFor: '“Robbing the rich to give to the poor.”',
    facts: [
      fact('f1', 'In the legend he is a highly skilled archer and swordsman.', src(ROBIN, 'highly skilled archer and swordsman')),
      fact('f2', 'The earliest known ballads about him date from the 15th century.', src(ROBIN, 'earliest known ballads about him date from the 15th century')),
      fact('f3', 'He is most closely linked with robbing the rich to give to the poor.', src(ROBIN, 'robbing the rich to give to the poor')),
    ],
    moments: [
      moment('m1', 'In an early ballad, a king notices that Robin’s men follow him more willingly than the king’s own men follow the king.', src(ROBIN, 'His men are more at his byddynge')),
      moment('m2', 'Over the centuries the story gathered a whole band around him, including Maid Marian and Little John.', src(ROBIN, 'Maid Marian', 'Little John')),
    ],
    angles: [
      angle('a1', 'the loyal band', 'What does an outlaw whose friends followed him gladly have in common with you?', 'People follow the person who treats them well, title or not.'),
      angle('a2', 'rich and poor', 'Who decides what’s fair when the rules aren’t?', 'Caring about fairness can mean questioning how things are set up.'),
      angle('a3', 'the archer', 'What happens when your best skill is also your calling card?', 'Getting really good at one thing can open every other door.'),
      angle('a4', 'the growing legend', 'How does one ballad turn into a whole band of friends?', 'Your story gets richer with every person you add to it.'),
    ],
    tags: [
      tag('conflict_assertiveness', 'high', 'stood up to the sheriff', 'He openly defies the people in power.'),
      tag('playfulness', 'high', 'merry men, merry life', 'His band is known for adventure and fun.'),
      tag('conflict_cooperativeness', 'high', 'gave to the poor', 'He is known for giving to people in need.'),
      tag('autonomy', 'high', 'lived by his own rules', 'He lives outside the law, in the greenwood.'),
    ],
    vetting: 'Folk legend; not a real figure or religious figure; no harm to children.',
  },
  {
    id: 'lf_king_arthur',
    name: 'King Arthur',
    kind: 'story',
    hall: 'myth',
    region: 'europe',
    place: 'British legend',
    era: 'Told since the Middle Ages',
    gender: 'man',
    field: 'Legendary king',
    essence: 'A king with a round table, so nobody sat at the head.',
    whoTheyWere: 'A legendary British king whose story has been told in many versions, with no single true one.',
    famousFor: 'Excalibur, Merlin, Camelot and the Knights of the Round Table.',
    facts: [
      fact('f1', 'His legend includes the sword Excalibur, the magician Merlin and his court at Camelot.', src(wiki('King_Arthur'), 'the sword Excalibur', 'Merlin')),
      fact('f2', 'Many tales focus on the Knights of the Round Table.', src(wiki('King_Arthur'), 'Knights of the Round Table')),
      fact('f3', 'The legend varies widely from text to text, and there is no one canonical version.', src(wiki('King_Arthur'), 'there is no one canonical version')),
    ],
    moments: [
      moment('m1', 'In the tales, Arthur’s final rest is on the island of Avalon.', src(wiki('King_Arthur'), 'final rest in Avalon')),
      moment('m2', 'A twelfth-century French writer added Lancelot and the Holy Grail, and started the genre of Arthurian romance.', src(wiki('King_Arthur'), 'added Lancelot and the Holy Grail')),
    ],
    angles: [
      angle('a1', 'the round table', 'What does a king with a round table have in common with you?', 'Making everyone feel equal at the table makes the group stronger.'),
      angle('a2', 'many versions', 'Why does one story get retold so many ways?', 'A good story belongs to everyone who tells it.'),
      angle('a3', 'the wise friend', 'What does a king need with a magician by his side?', 'Even leaders need someone wiser to talk to.'),
      angle('a4', 'Avalon', 'Why does the story never quite end?', 'Some hopes are worth keeping open.'),
    ],
    tags: [
      tag('agreeableness', 'high', 'sat everyone as equals', 'His round table put his knights on equal footing.'),
      tag('relatedness', 'high', 'led a fellowship', 'His story centres on his knights and court.'),
      tag('autonomy', 'low', 'listened to Merlin', 'He relied on Merlin’s guidance.'),
      tag('locus_of_control', 'high', 'built Camelot', 'He made a court that became a legend.'),
    ],
    vetting: 'Legendary king (not a real ruler); no religious figure; entry avoids the darker versions.',
  },
  {
    id: 'lf_paul_bunyan',
    name: 'Paul Bunyan',
    kind: 'story',
    hall: 'myth',
    region: 'americas',
    place: 'American and Canadian folklore',
    era: 'In print since 1893',
    gender: 'man',
    field: 'Tall tales',
    essence: 'A giant lumberjack said to have dragged his axe and made the Grand Canyon.',
    whoTheyWere: 'A giant lumberjack and folk hero of American and Canadian tall tales.',
    famousFor: 'His superhuman feats, and Babe the Blue Ox.',
    facts: [
      fact('f1', 'He is a giant lumberjack and folk hero of American and Canadian folklore.', src(wiki('Paul_Bunyan'), 'giant lumberjack and folk hero')),
      fact('f2', 'He is usually joined by Babe the Blue Ox.', src(wiki('Paul_Bunyan'), 'Babe the Blue Ox')),
      fact('f3', 'He first appeared in print in 1893, after earlier oral tradition.', src(wiki('Paul_Bunyan'), 'first appeared in print in 1893')),
    ],
    moments: [
      moment('m1', 'Tales say he created the Grand Canyon by pulling his axe behind him.', src(wiki('Paul_Bunyan'), 'creating the Grand Canyon by pulling his ax behind him')),
      moment('m2', 'Another tale says he made Mount Hood by putting stones on his campfire.', src(wiki('Paul_Bunyan'), 'Mount Hood by putting stones on his campfire')),
    ],
    angles: [
      angle('a1', 'the tall tale', 'What does a lumberjack who made the Grand Canyon by accident have in common with you?', 'A little exaggeration can make a story everyone remembers.'),
      angle('a2', 'the blue ox', 'Why does every giant need a best friend?', 'Even the biggest helpers need a partner.'),
      angle('a3', 'big work', 'What does it feel like when your work reshapes the land?', 'Steady effort can leave a bigger mark than you planned.'),
      angle('a4', 'campfire stories', 'Why do stories grow every time they’re told?', 'Stories get better when lots of people add to them.'),
    ],
    tags: [
      tag('playfulness', 'high', 'tall tales and big laughs', 'His stories are joyful exaggerations.'),
      tag('extraversion', 'high', 'larger than life', 'He is a giant whose deeds everyone talks about.'),
      tag('conscientiousness', 'high', 'superhuman work ethic', 'His tales revolve around his superhuman labours.'),
      tag('attachment_anxiety', 'low', 'easygoing giant', 'He takes huge tasks in his stride.'),
    ],
    vetting: 'Folk tall-tale character; no religious figure; no harm to children.',
  },
  {
    id: 'lf_beowulf',
    name: 'Beowulf',
    kind: 'story',
    hall: 'myth',
    region: 'europe',
    place: 'Old English epic',
    era: 'Epic poem, early Middle Ages',
    gender: 'man',
    field: 'Epic hero',
    essence: 'Crossed the sea to help a king nobody else could help.',
    whoTheyWere: 'The hero of the Old English epic poem Beowulf, from the Geats.',
    famousFor: 'Facing the monster Grendel, Grendel’s mother, and later a dragon.',
    facts: [
      fact('f1', 'He belongs to the Geats in the poem.', src(wiki('Beowulf_(hero)'), 'clan of the Geats')),
      fact('f2', 'He came to help King Hrothgar.', src(wiki('Beowulf_(hero)'), 'Beowulf has come to help him')),
      fact('f3', 'Late in life he faces a dragon.', src(wiki('Beowulf_(hero)'), 'the fight with the dragon')),
    ],
    moments: [
      moment('m1', 'Since no weapon could harm Grendel, Beowulf fought him with his bare hands.', src(wiki('Beowulf_(hero)'), 'no manmade weapon could harm Grendel')),
      moment('m2', 'When Grendel’s mother came the next night, he resolved to go down after her into her lair.', src(wiki('Beowulf_(hero)'), 'He resolved to descend')),
    ],
    angles: [
      angle('a1', 'crossing the sea to help', 'What does a hero who sailed to help a stranger’s kingdom have in common with you?', 'Showing up for someone else’s problem is a kind of bravery.'),
      angle('a2', 'bare hands', 'What do you do when your usual tools don’t work?', 'Sometimes you face things with just yourself, and that’s enough.'),
      angle('a3', 'going down after it', 'Why follow the trouble back to where it lives?', 'Dealing with the root of a problem is harder and better.'),
      angle('a4', 'the last fight', 'What does courage look like later in life?', 'Bravery doesn’t retire.'),
    ],
    tags: [
      tag('self_efficacy', 'high', 'faced it barehanded', 'He fought Grendel without weapons.'),
      tag('conflict_cooperativeness', 'high', 'came to a stranger’s aid', 'He travelled to help King Hrothgar.'),
      tag('steadiness', 'high', 'calm before monsters', 'He faced every threat steadily.'),
      tag('extraversion', 'high', 'a hero of the mead hall', 'He was celebrated in the hall after his victory.'),
    ],
    vetting: 'Epic-poem hero; no religious figure; entry keeps the violence mild.',
  },
  {
    id: 'lf_scheherazade',
    name: 'Scheherazade',
    kind: 'story',
    hall: 'myth',
    region: 'middle_east',
    place: 'One Thousand and One Nights',
    era: 'Tales compiled c. 700s–1300s',
    gender: 'woman',
    field: 'Storyteller',
    essence: 'Saved lives by telling a story that never quite ended.',
    whoTheyWere: 'The legendary narrator of One Thousand and One Nights, the learned daughter of the royal vizier.',
    famousFor: 'Telling interlinked stories over 1,001 nights.',
    facts: [
      fact('f1', 'She is the narrator and framing character of One Thousand and One Nights.', src(wiki('Scheherazade'), 'legendary narrator and central framing character of One Thousand and One Nights')),
      fact('f2', 'She told a continuous sequence of interlinked stories over 1,001 nights.', src(wiki('Scheherazade'), 'continuous sequence of interlinked stories over the course of 1,001 nights')),
      fact('f3', 'In the tale, she saves herself and the women of the kingdom.', src(wiki('Scheherazade'), 'ultimately the women of the kingdom')),
    ],
    moments: [
      moment('m1', 'She volunteered to marry the angry king, and on their wedding night began telling a story.', src(wiki('Scheherazade'), 'volunteers to marry him', 'begins telling a')),
      moment('m2', 'Her stories turn the king into a just and stable ruler.', src(wiki('Scheherazade'), 'just and stable king')),
    ],
    angles: [
      angle('a1', 'one more story', 'What does a storyteller who kept stopping at the best part have in common with you?', 'Knowing how to hold attention is a real power.'),
      angle('a2', 'changing a mind', 'How do stories change someone who won’t listen to arguments?', 'People change through stories more than through lectures.'),
      angle('a3', 'volunteering', 'Why step forward when everyone else steps back?', 'Courage can be quiet and clever at the same time.'),
      angle('a4', 'night after night', 'What can you build by showing up a thousand times?', 'Patience and creativity together can change anything.'),
    ],
    tags: [
      tag('openness', 'high', 'endless stories', 'She told tale after interlinked tale.'),
      tag('self_efficacy', 'high', 'volunteered to face the king', 'She stepped forward to marry him.'),
      tag('conscientiousness', 'high', 'a thousand nights of stories', 'She kept going night after night.'),
      tag('agreeableness', 'high', 'won him over gently', 'Her stories changed the king without force.'),
    ],
    vetting: 'Legendary narrator; not a religious figure; entry avoids the violence of the frame story.',
  },
  {
    id: 'lf_nasreddin',
    name: 'Nasreddin Hodja',
    kind: 'story',
    hall: 'myth',
    region: 'middle_east',
    place: 'Folklore of Turkey and Central Asia',
    era: 'Told for centuries',
    gender: 'man',
    field: 'Wise fool',
    essence: 'A wise fool whose jokes teach you something.',
    whoTheyWere: 'A folk character from the folklore of Central Asia and beyond, hero of funny, satirical tales.',
    famousFor: 'Thousands of short stories, sometimes witty, sometimes wise.',
    facts: [
      fact('f1', 'He is the hero of humorous short stories and satirical anecdotes.', src(wiki('Nasreddin'), 'humorous short stories and satirical anecdotes')),
      fact('f2', 'His adventures are celebrated in dozens of languages.', src(wiki('Nasreddin'), 'dozens of languages')),
      fact('f3', 'In 2022 the tradition of telling his comic tales was added to UNESCO’s Intangible Cultural Heritage list.', src(wiki('Nasreddin'), 'UNESCO Intangible Cultural Heritage list')),
    ],
    moments: [
      moment('m1', 'In one tale a neighbour asks to borrow his donkey, and he doesn’t feel inclined to lend it.', src(wiki('Nasreddin'), 'lend me your donkey')),
      moment('m2', 'A Nasreddin story usually has a subtle humour and something to teach.', src(wiki('Nasreddin'), 'subtle humour and a pedagogic nature')),
    ],
    angles: [
      angle('a1', 'the wise fool', 'What does a joker whose jokes are lessons have in common with you?', 'Being funny and being wise can be the same thing.'),
      angle('a2', 'the donkey', 'How do you say no without saying no?', 'A light touch can get you out of awkward spots.'),
      angle('a3', 'laughing at yourself', 'Why let the joke be on you?', 'Not taking yourself too seriously makes you easier to learn from.'),
      angle('a4', 'everyone’s story', 'How does one character belong to so many countries?', 'Humour travels further than almost anything.'),
    ],
    tags: [
      tag('playfulness', 'high', 'jokes with a point', 'His stories are funny and teach something.'),
      tag('agreeableness', 'low', 'teases everyone', 'His tales gently mock people and customs.'),
      tag('conflict_assertiveness', 'low', 'dodges instead of fighting', 'He uses wit to avoid direct conflict.'),
      tag('openness', 'high', 'sees things sideways', 'He looks at problems from odd angles.'),
    ],
    vetting: 'Folk character (not a religious leader); no harm to children.',
  },
  {
    id: 'lf_john_henry',
    name: 'John Henry',
    kind: 'story',
    hall: 'myth',
    region: 'americas',
    place: 'American folklore',
    era: 'Told since the 1800s',
    gender: 'man',
    field: 'Folk hero',
    essence: 'Raced a steam drill with a hammer, and won.',
    whoTheyWere: 'An American folk hero, a freedman said to be a steel-driving man building railroad tunnels.',
    famousFor: 'His race against a steam-powered rock drill.',
    facts: [
      fact('f1', 'He is said to have been a “steel-driving man” hammering drills into rock for railroad tunnels.', src(wiki('John_Henry_(folklore)'), 'steel-driving man')),
      fact('f2', 'His story is told in a classic blues folk song.', src(wiki('John_Henry_(folklore)'), 'classic blues folk song')),
      fact('f3', 'He is an American folk hero.', src(wiki('John_Henry_(folklore)'), 'American folk hero')),
    ],
    moments: [
      moment('m1', 'In the legend his strength was measured in a race against a steam-powered rock drill, and he won.', src(wiki('John_Henry_(folklore)'), 'race against a steam-powered rock drill')),
      moment('m2', 'The song about his duel with the machine exists in many versions.', src(wiki('John_Henry_(folklore)'), 'exists in many versions')),
    ],
    angles: [
      angle('a1', 'person versus machine', 'What does a man who raced a drilling machine have in common with you?', 'What people bring, heart and skill, still matters next to machines.'),
      angle('a2', 'the song', 'Why does a work song keep a hero alive?', 'The stories we sing together keep people with us.'),
      angle('a3', 'all in', 'What does it mean to give everything to one effort?', 'Giving your all is powerful, and so is knowing your limits.'),
      angle('a4', 'pride in the work', 'Why care so much about doing the job yourself?', 'Pride in your craft is worth defending.'),
    ],
    tags: [
      tag('self_efficacy', 'high', 'took on the machine', 'He raced a steam drill and won.'),
      tag('conscientiousness', 'high', 'tireless worker', 'He was a steel-driving man building tunnels.'),
      tag('competence', 'high', 'the best with a hammer', 'His skill outpaced a machine.'),
      tag('growth_mindset', 'low', 'did it the old way', 'He stood by the old way of working.'),
      tag('conflict_cooperativeness', 'low', 'wouldn’t step aside', 'He raced the steam drill rather than give way.'),
    ],
    vetting: 'Folk hero; no religious figure; his death in the tale is not described.',
  },
];
