import type { LegendFigure } from '../types';
import { angle, fact, moment, src, tag, wiki } from './define';

const CURIE = wiki('Marie_Curie');
const HAYTHAM = wiki('Ibn_al-Haytham');
const LOVELACE = wiki('Ada_Lovelace');
const RAMANUJAN = wiki('Srinivasa_Ramanujan');
const GUTENBERG = wiki('Johannes_Gutenberg');

export const SCIENCE_LEGENDS: readonly LegendFigure[] = [
  {
    id: 'lf_marie_curie',
    name: 'Marie Curie',
    kind: 'real',
    hall: 'science',
    region: 'europe',
    place: 'Poland and France',
    era: '1867–1934',
    died: 1934,
    birthday: { md: '11-07', source: src(CURIE, '7 November 1867') },
    gender: 'woman',
    field: 'Physics and chemistry',
    essence: 'Found two new elements and named one after home.',
    whoTheyWere:
      'A Polish-born physicist and chemist who did her work in France and studied radioactivity, a word she coined.',
    famousFor: 'The first person to win a Nobel Prize twice, in two different sciences.',
    facts: [
      fact('f1', 'With Pierre Curie she discovered the elements polonium and radium.', src(CURIE, 'polonium', 'radium')),
      fact('f2', 'She was the first woman to win a Nobel Prize.', src(CURIE, 'first woman to win a Nobel Prize')),
      fact('f3', 'She coined the term radioactivity.', src(CURIE, 'radioactivity—a term she coined')),
    ],
    moments: [
      moment(
        'm1',
        'During the First World War she developed mobile X-ray units for field hospitals.',
        src(CURIE, 'First World War', 'mobile radiography units', 'field hospitals'),
      ),
      moment(
        'm2',
        'After Pierre died in a Paris street accident in 1906, she kept the research going.',
        src(CURIE, 'Pierre died in 1906 in a Paris street accident'),
      ),
    ],
    angles: [
      angle('a1', 'the patient tester', 'What does a scientist who named an element after home have in common with you?', 'The slow, careful part of a project can be exactly where the discovery hides.'),
      angle('a2', 'the one who kept going', 'Who keeps the work alive when the person beside you is suddenly gone?', 'Carrying something forward after a loss can be its own kind of strength.'),
      angle('a3', 'the practical genius', 'What does a physicist building X-ray vans for a war tell you about your skills?', 'The thing you know deeply can help in places nobody planned for.'),
      angle('a4', 'twice, in two fields', 'How does one person win twice, in two different sciences?', 'Going deep on one question can open doors in more than one direction.'),
    ],
    tags: [
      tag('openness', 'high', 'chased an unknown glow', 'She studied a new kind of radiation that nobody understood yet.'),
      tag('conscientiousness', 'high', 'measured everything, twice', 'Her discoveries came from systematic, repeated measurement.'),
      tag('extraversion', 'low', 'at home in the lab', 'Her life’s work happened in the quiet of a laboratory.'),
      tag('growth_mindset', 'high', 'learned a new field', 'She moved from physics into chemistry and won in both.'),
      tag('playfulness', 'low', 'serious about the work', 'She treated research as work that mattered, not a game.'),
    ],
    vetting: 'Scientist, died 1934; no political office; broadly admired worldwide.',
  },
  {
    id: 'lf_ibn_al_haytham',
    name: 'Ibn al-Haytham',
    kind: 'real',
    hall: 'science',
    region: 'middle_east',
    place: 'Basra and Cairo',
    era: 'c. 965–c. 1040',
    died: 1040,
    gender: 'man',
    field: 'Optics and mathematics',
    essence: 'Said a good idea has to survive an experiment.',
    whoTheyWere: 'A scholar born in Basra who did most of his work in Cairo, writing on light, vision and mathematics.',
    famousFor: 'His Book of Optics, and an early version of the scientific method.',
    facts: [
      fact('f1', 'He argued that a hypothesis must be supported by experiments or mathematical reasoning.', src(HAYTHAM, 'hypothesis must be supported by experiments')),
      fact('f2', 'He is sometimes described as the world’s first true scientist.', src(HAYTHAM, 'first true scientist')),
      fact('f3', 'He wrote Doubts Concerning Ptolemy, questioning the most respected astronomer of his time.', src(HAYTHAM, 'Doubts Concerning Ptolemy')),
    ],
    moments: [
      moment(
        'm1',
        'The story goes that he pretended to be mad to escape a task for the caliph, and was kept under house arrest.',
        src(HAYTHAM, 'feigned madness', 'house arrest'),
      ),
      moment('m2', 'During that time he wrote his Book of Optics.', src(HAYTHAM, 'During this time, he wrote his influential Book of Optics')),
    ],
    angles: [
      angle('a1', 'prove it', 'What does a thinker who doubted the greatest astronomer have in common with you?', 'Asking “how do we know?” is not rude. It is how good ideas get better.'),
      angle('a2', 'the locked room', 'What can someone build while stuck in one room?', 'A stretch of time you didn’t choose can still hold your best work.'),
      angle('a3', 'the first scientist', 'Why would a scholar from a thousand years ago care how you test your plans?', 'Trying something small before trusting it fully is a habit worth keeping.'),
      angle('a4', 'light and sight', 'What does a man who studied how eyes see have to say about how you see things?', 'Checking what you actually saw, not what you expected, changes a lot.'),
    ],
    tags: [
      tag('openness', 'high', 'questioned how sight works', 'He studied light and vision when little was known about them.'),
      tag('agreeableness', 'low', 'doubted the great Ptolemy', 'He wrote a whole book questioning the most trusted astronomer.'),
      tag('autonomy', 'high', 'followed his own method', 'He set his own standard: ideas must survive experiments.'),
      tag('relatedness', 'low', 'worked alone in confinement', 'His most famous book was written while he was kept apart.'),
      tag('growth_mindset', 'high', 'tested, then revised', 'He treated ideas as things to test, not to defend.'),
    ],
    vetting: 'Scholar, died c. 1040; no political or religious office; admired across cultures.',
  },
  {
    id: 'lf_ada_lovelace',
    name: 'Ada Lovelace',
    kind: 'real',
    hall: 'science',
    region: 'europe',
    place: 'England',
    era: '1815–1852',
    died: 1852,
    birthday: { md: '12-10', source: src(LOVELACE, '10 December 1815') },
    gender: 'woman',
    field: 'Mathematics',
    essence: 'Saw a computer’s future before the computer existed.',
    whoTheyWere: 'An English mathematician and writer who worked with Charles Babbage on his planned Analytical Engine.',
    famousFor: 'Notes often called the first published computer program.',
    facts: [
      fact('f1', 'Her Note G described a method for the Analytical Engine to calculate Bernoulli numbers.', src(LOVELACE, 'Note G', 'Bernoulli numbers')),
      fact('f2', 'She was the first to recognise the machine had uses beyond pure calculation.', src(LOVELACE, 'first to recognise the machine had applications beyond pure calculation')),
      fact('f3', 'She called her approach “poetical science”.', src(LOVELACE, 'poetical science')),
    ],
    moments: [
      moment(
        'm1',
        'Translating an article about the engine, she added seven long notes of her own that ran longer than the article.',
        src(LOVELACE, 'seven long explanatory notes'),
      ),
      moment('m2', 'She described herself as an “Analyst (& Metaphysician)”.', src(LOVELACE, 'Analyst (& Metaphysician)')),
    ],
    angles: [
      angle('a1', 'the footnote that won', 'What do a translator’s notes from the 1840s have in common with you?', 'The extra thing you add because you care can become the part people remember.'),
      angle('a2', 'poetical science', 'What happens when someone mixes poetry and mathematics?', 'You don’t have to choose between the careful side of you and the imaginative one.'),
      angle('a3', 'beyond the brief', 'Who looks at a calculator and sees music and art?', 'Seeing what something could become is a skill, even before anyone agrees.'),
      angle('a4', 'the early idea', 'What does it feel like to be a hundred years early?', 'An idea can be right long before the world is ready to use it.'),
    ],
    tags: [
      tag('openness', 'high', 'imagined machines making music', 'She saw uses for the engine far beyond arithmetic.'),
      tag('playfulness', 'high', 'mixed poetry with maths', 'She called her own method poetical science.'),
      tag('self_efficacy', 'high', 'wrote more than asked', 'She added notes longer than the article she was translating.'),
      tag('autonomy', 'high', 'named her own role', 'She described herself in her own terms, as an Analyst.'),
    ],
    vetting: 'Mathematician, died 1852; no political office; broadly admired.',
  },
  {
    id: 'lf_srinivasa_ramanujan',
    name: 'Srinivasa Ramanujan',
    kind: 'real',
    hall: 'science',
    region: 'south_asia',
    place: 'India and England',
    era: '1887–1920',
    died: 1920,
    birthday: { md: '12-22', source: src(RAMANUJAN, '22 December 1887') },
    gender: 'man',
    field: 'Mathematics',
    essence: 'Mailed his notebooks to a stranger and changed mathematics.',
    whoTheyWere: 'An Indian mathematician who first developed his research in isolation, then worked with G. H. Hardy in Cambridge.',
    famousFor: 'Thousands of results in number theory, and the number 1729.',
    facts: [
      fact('f1', 'At 16 he borrowed a library copy of a book of 5,000 theorems and studied it in detail.', src(RAMANUJAN, 'collection of 5,000 theorems')),
      fact('f2', 'He was elected a Fellow of the Royal Society in 1918.', src(RAMANUJAN, 'Fellow of the Royal Society', '1918')),
      fact('f3', 'The number 1729 is called the Hardy–Ramanujan number.', src(RAMANUJAN, 'Hardy–Ramanujan number')),
      fact('f4', 'He first developed his own mathematical research in isolation.', src(RAMANUJAN, 'developed his own mathematical research in isolation')),
    ],
    moments: [
      moment('m1', 'He wrote to the Cambridge mathematician G. H. Hardy, sending pages of his own results.', src(RAMANUJAN, 'Hardy', 'letter')),
      moment(
        'm2',
        'Visiting him in hospital, Hardy mentioned his taxi number, 1729, as dull, and Ramanujan replied that it was a very interesting number.',
        src(RAMANUJAN, '1729', 'hospital', 'interesting'),
      ),
    ],
    angles: [
      angle('a1', 'the letter', 'What does a self-taught mathematician who wrote to a stranger in Cambridge have in common with you?', 'Sending your work to someone who might get it is a risk worth taking.'),
      angle('a2', 'self-taught', 'How far can someone get learning mostly on their own?', 'The way you learned something matters less than how far you take it.'),
      angle('a3', 'interesting numbers', 'Who looks at a taxi number and sees something beautiful?', 'Noticing what others call dull is its own kind of talent.'),
      angle('a4', 'the stubborn path', 'What if the thing you love is the only subject you want to study?', 'Going all in on one thing has costs, and sometimes it’s still the right call.'),
    ],
    tags: [
      tag('openness', 'high', 'saw patterns everywhere', 'He found something interesting in a number others called dull.'),
      tag('conscientiousness', 'low', 'skipped the usual steps', 'He reached results by his own route, working in isolation.'),
      tag('extraversion', 'low', 'worked in isolation', 'He first developed his research alone, before anyone saw it.'),
      tag('self_efficacy', 'high', 'wrote to a stranger', 'He sent his results to a famous mathematician he had never met.'),
    ],
    hidden: {
      needs: [
        { axis: 'openness', lean: 'high' },
        { axis: 'conscientiousness', lean: 'low' },
        { axis: 'extraversion', lean: 'low' },
      ],
    },
    vetting: 'Mathematician, died 1920; no political office; broadly admired.',
  },
  {
    id: 'lf_johannes_gutenberg',
    name: 'Johannes Gutenberg',
    kind: 'real',
    hall: 'science',
    region: 'europe',
    place: 'Germany',
    era: 'c. 1400–1468',
    died: 1468,
    gender: 'man',
    field: 'Printing',
    essence: 'Failed at selling mirrors, then changed how the world reads.',
    whoTheyWere: 'A German inventor and craftsman whose printing press made printing far faster.',
    famousFor: 'The movable-type printing press and the Gutenberg Bible.',
    facts: [
      fact('f1', 'He invented the movable-type printing press.', src(GUTENBERG, 'invented the movable-type printing press')),
      fact('f2', 'In 1455 he completed the 42-line Bible, known as the Gutenberg Bible.', src(GUTENBERG, '42-line Bible')),
      fact('f3', 'About 180 copies of that Bible were printed.', src(GUTENBERG, 'About 180 copies were printed')),
    ],
    moments: [
      moment('m1', 'Around 1439 he was caught up in a failed business making polished metal mirrors for pilgrims.', src(GUTENBERG, 'financial misadventure', 'polished metal mirrors')),
      moment('m2', 'He convinced the moneylender Johann Fust to lend him 800 guilders for the press.', src(GUTENBERG, 'Johann Fust', '800 guilders')),
    ],
    angles: [
      angle('a1', 'after the mirrors', 'What does an inventor whose first business failed have in common with you?', 'A flop can be the training for the thing that works.'),
      angle('a2', 'the loan', 'Who do you convince when your idea needs money first?', 'Asking for backing is part of building something new.'),
      angle('a3', 'faster', 'What changes when you make an old thing a hundred times faster?', 'Improving how something is done can matter as much as inventing it.'),
      angle('a4', 'the long project', 'How many years go into one perfect book?', 'Some work only shows its value once it’s finished.'),
    ],
    tags: [
      tag('openness', 'high', 'imagined a faster way', 'He built a press that printed much faster than before.'),
      tag('autonomy', 'high', 'ran his own workshop', 'He built and ran his own printing enterprise.'),
      tag('growth_mindset', 'high', 'tried again after a flop', 'After the mirror business failed, he turned to printing.'),
      tag('conscientiousness', 'high', 'set every line by hand', 'His Bible was a long, exact piece of work.'),
      tag('competence', 'low', 'a failed business first', 'He was caught up in a failed mirror business before printing.'),
    ],
    vetting: 'Inventor, died 1468; no office; broadly admired.',
  },
  {
    id: 'lf_nikola_tesla',
    name: 'Nikola Tesla',
    kind: 'real',
    hall: 'science',
    region: 'europe',
    place: 'Austro-Hungarian Empire and the United States',
    era: '1856–1943',
    died: 1943,
    birthday: { md: '07-10', source: src(wiki('Nikola_Tesla'), '10 July 1856') },
    gender: 'man',
    field: 'Electrical engineering',
    essence: 'Imagined the power in your wall socket before it existed.',
    whoTheyWere: 'A Serbian-American engineer and inventor who moved to the United States in 1884 and built his own laboratories in New York.',
    famousFor: 'His work on the alternating current (AC) electricity supply system and the Tesla coil.',
    facts: [
      fact('f1', 'He is known for his contributions to the modern alternating current electricity supply system.', src(wiki('Nikola_Tesla'), 'alternating current (AC) electricity supply system')),
      fact('f2', 'His AC induction motor patents were licensed by Westinghouse Electric in 1888.', src(wiki('Nikola_Tesla'), 'induction motor', 'Westinghouse Electric in 1888')),
      fact('f3', 'He worked for a short time at the Edison Machine Works before going out on his own.', src(wiki('Nikola_Tesla'), 'Edison Machine Works')),
    ],
    moments: [
      moment('m1', 'In 1884 he moved to the United States, where he became a citizen.', src(wiki('Nikola_Tesla'), 'In 1884, he migrated to the United States')),
      moment('m2', 'In his later years he walked to the park every day to feed the pigeons, and nursed injured birds back to health.', src(wiki('Nikola_Tesla'), 'feed the pigeons', 'nursed injured birds')),
    ],
    angles: [
      angle('a1', 'striking out alone', 'What does an inventor who left a famous company to build his own lab have in common with you?', 'Leaving the safe setup to try your own idea is a real kind of nerve.'),
      angle('a2', 'the future in his head', 'Who imagines the power grid before anyone has one?', 'Seeing how things could work is useful long before anyone else sees it.'),
      angle('a3', 'the pigeons', 'Why would a famous inventor spend his mornings looking after birds?', 'Quiet care for small things can sit right next to big ambition.'),
      angle('a4', 'a new country', 'What changes when you take your ideas to a whole new country?', 'A fresh start somewhere new can be where your work finally clicks.'),
    ],
    tags: [
      tag('openness', 'high', 'imagined a new power system', 'He worked on ideas for electricity that were new at the time.'),
      tag('self_efficacy', 'high', 'struck out on his own', 'He left Edison’s works to set up his own laboratories.'),
      tag('relatedness', 'low', 'happiest with his inventions', 'He spent long stretches alone with his work.'),
      tag('attachment_avoidance', 'high', 'kept people at a distance', 'He lived much of his later life alone in hotels.'),
    ],
    vetting: 'Inventor, died 1943; no office; broadly admired.',
  },
  {
    id: 'lf_galileo_galilei',
    name: 'Galileo Galilei',
    kind: 'real',
    hall: 'science',
    region: 'europe',
    place: 'Italy',
    era: '1564–1642',
    died: 1642,
    birthday: { md: '02-15', source: src(wiki('Galileo_Galilei'), '15 February 1564') },
    gender: 'man',
    field: 'Astronomy and physics',
    essence: 'Pointed a telescope at the sky and found new moons.',
    whoTheyWere: 'An Italian astronomer and physicist who built improved telescopes and taught at the University of Padua.',
    famousFor: 'Discovering the four largest moons of Jupiter, now called the Galilean moons.',
    facts: [
      fact('f1', 'With a telescope he improved himself, he observed the phases of Venus, lunar craters and sunspots.', src(wiki('Galileo_Galilei'), 'phases of Venus', 'sunspots')),
      fact('f2', 'The four large moons of Jupiter he discovered are called the Galilean moons.', src(wiki('Galileo_Galilei'), 'Galilean moons')),
      fact('f3', 'He also built an early microscope.', src(wiki('Galileo_Galilei'), 'early microscope')),
    ],
    moments: [
      moment('m1', 'After his trial in 1633 he spent the rest of his life under house arrest, and kept writing a major book on motion and mechanics.', src(wiki('Galileo_Galilei'), '1633', 'rest of his life under house arrest')),
      moment('m2', 'He taught geometry, mechanics and astronomy at the University of Padua until 1610.', src(wiki('Galileo_Galilei'), 'University of Padua')),
    ],
    angles: [
      angle('a1', 'look for yourself', 'What does an astronomer who built his own telescope have in common with you?', 'Checking something with your own eyes can change what you thought you knew.'),
      angle('a2', 'working from home', 'What can someone still make when they’re stuck at home for years?', 'A stretch you didn’t choose can still hold some of your best work.'),
      angle('a3', 'new moons', 'Why would four tiny dots next to Jupiter matter so much?', 'Small details, looked at properly, can turn a big picture around.'),
      angle('a4', 'the teacher', 'What does it mean to teach while you’re still discovering?', 'Explaining what you know can sharpen what you’re still figuring out.'),
    ],
    tags: [
      tag('openness', 'high', 'looked where nobody had', 'He turned an improved telescope on the night sky.'),
      tag('conflict_assertiveness', 'high', 'stood by what he saw', 'He published observations that challenged accepted ideas.'),
      tag('autonomy', 'high', 'built his own tools', 'He improved the telescope himself and made an early microscope.'),
      tag('growth_mindset', 'high', 'kept working under arrest', 'He wrote a major book while confined at home.'),
      tag('agreeableness', 'low', 'said what he saw', 'He reported what his own telescope showed.'),
    ],
    vetting: 'Scientist, died 1642; no office. Trial mentioned neutrally, no religious argument.',
  },
  {
    id: 'lf_mary_anning',
    name: 'Mary Anning',
    kind: 'real',
    hall: 'science',
    region: 'europe',
    place: 'England',
    era: '1799–1847',
    died: 1847,
    birthday: { md: '05-21', source: src(wiki('Mary_Anning'), '21 May 1799') },
    gender: 'woman',
    field: 'Fossil collecting',
    essence: 'Found sea monsters in the cliffs of a small seaside town.',
    whoTheyWere: 'An English fossil collector from Lyme Regis who searched the cliffs for fossils and sold them to support herself.',
    famousFor: 'The first correctly identified ichthyosaur skeleton, found when she was twelve.',
    facts: [
      fact('f1', 'She found the first correctly identified ichthyosaur skeleton when she was twelve years old.', src(wiki('Mary_Anning'), 'first correctly identified ichthyosaur skeleton when she was twelve')),
      fact('f2', 'She also found the first two nearly complete plesiosaur skeletons.', src(wiki('Mary_Anning'), 'first two nearly complete plesiosaur skeletons')),
      fact('f3', 'As a woman, she was not eligible to join the Geological Society of London.', src(wiki('Mary_Anning'), 'not eligible to join the Geological Society of London')),
    ],
    moments: [
      moment('m1', 'As a baby she survived when lightning struck the tree she was under, and was revived in a bath of hot water.', src(wiki('Mary_Anning'), 'lightning struck the tree', 'revived in a bath of hot water')),
      moment('m2', 'She kept supporting herself by selling fossils from her shop.', src(wiki('Mary_Anning'), 'continued to support herself selling fossils')),
    ],
    angles: [
      angle('a1', 'the cliff walk', 'What does a girl searching seaside cliffs for fossils have in common with you?', 'Going back to the same place, again and again, is how rare things get found.'),
      angle('a2', 'no seat at the table', 'What do you do when the club won’t let you in?', 'Your work can matter even when the official room doesn’t make space for you.'),
      angle('a3', 'the shop', 'Why would a great discoverer also run a fossil shop?', 'Paying the bills and doing important work can happen at the same counter.'),
      angle('a4', 'twelve', 'What can someone find at twelve that the experts missed?', 'Being early in something doesn’t mean you have nothing to add.'),
    ],
    tags: [
      tag('conscientiousness', 'high', 'searched the cliffs again and again', 'Finding fossils meant patient, repeated searching.'),
      tag('competence', 'high', 'knew fossils better than experts', 'Her finds shaped what scientists understood.'),
      tag('conflict_assertiveness', 'low', 'let the fossils speak', 'She often did not receive full credit for her work.'),
      tag('steadiness', 'high', 'kept going through hard years', 'She struggled financially but kept working.'),
      tag('openness', 'low', 'stayed by her home coast', 'She kept selling fossils from her shop at home.'),
    ],
    vetting: 'Fossil collector, died 1847; no office; broadly admired.',
  },
  {
    id: 'lf_jagadish_chandra_bose',
    name: 'Jagadish Chandra Bose',
    kind: 'real',
    hall: 'science',
    region: 'south_asia',
    place: 'India',
    era: '1858–1937',
    died: 1937,
    birthday: { md: '11-30', source: src(wiki('Jagadish_Chandra_Bose'), '30 November 1858') },
    gender: 'man',
    field: 'Physics and plant science',
    essence: 'Studied radio waves and how plants respond.',
    whoTheyWere: 'An Indian scientist with interests in physics, biology and science fiction, who pioneered work on radio microwave optics.',
    famousFor: 'The crescograph, which measured how plants respond, and founding the Bose Institute.',
    facts: [
      fact('f1', 'He invented the crescograph to measure how plants respond to stimuli.', src(wiki('Jagadish_Chandra_Bose'), 'crescograph')),
      fact('f2', 'He founded the Bose Institute, established in 1917.', src(wiki('Jagadish_Chandra_Bose'), 'Bose Institute', '1917')),
      fact('f3', 'He was generally critical of the patent system.', src(wiki('Jagadish_Chandra_Bose'), 'critical of the patent system')),
    ],
    moments: [
      moment('m1', 'In one demonstration, his waves travelled 23 metres through two walls to ring a bell in a closed room.', src(wiki('Jagadish_Chandra_Bose'), '23 metres through two intervening walls', 'ring a bell')),
      moment('m2', 'He is also considered the father of Bengali science fiction.', src(wiki('Jagadish_Chandra_Bose'), 'father of Bengali science fiction')),
    ],
    angles: [
      angle('a1', 'through two walls', 'What does a scientist who rang a bell through two walls have in common with you?', 'A good demonstration can explain more than a long argument.'),
      angle('a2', 'plants and people', 'Who looks at a plant and sees something that responds like we do?', 'Noticing what others overlook can open a whole new field.'),
      angle('a3', 'knowledge for all', 'Why would an inventor dislike patents?', 'Sharing what you know freely is a choice with its own kind of power.'),
      angle('a4', 'scientist and storyteller', 'Can the same person write physics and science fiction?', 'Your imaginative side can feed your careful side, and back again.'),
    ],
    tags: [
      tag('openness', 'high', 'from radio waves to plants', 'He moved between physics, botany and science fiction.'),
      tag('conflict_cooperativeness', 'high', 'shared his ideas freely', 'He was critical of keeping knowledge locked in patents.'),
      tag('autonomy', 'high', 'built his own instruments', 'He invented the crescograph for his own research.'),
      tag('playfulness', 'high', 'wrote science fiction too', 'He is seen as the father of Bengali science fiction.'),
    ],
    vetting: 'Scientist, died 1937; no office; broadly admired.',
  },
  {
    id: 'lf_leonardo_inventor',
    name: 'Leonardo da Vinci',
    role: 'as an inventor',
    roleOf: 'Leonardo da Vinci',
    kind: 'real',
    hall: 'science',
    region: 'europe',
    place: 'Italy',
    era: '1452–1519',
    died: 1519,
    birthday: { md: '04-15', source: src(wiki('Leonardo_da_Vinci'), '15 April 1452') },
    gender: 'man',
    field: 'Engineering and science',
    essence: 'Filled notebooks with flying machines centuries early.',
    whoTheyWere: 'An Italian polymath of the High Renaissance, active as a painter, engineer, scientist and architect.',
    famousFor: 'His notebooks of inventions and studies, including designs for flying machines.',
    facts: [
      fact('f1', 'He conceptualised flying machines and concentrated solar power.', src(wiki('Leonardo_da_Vinci'), 'conceptualised flying machines', 'concentrated solar power')),
      fact('f2', 'His notebooks cover anatomy, astronomy, botany, cartography and more.', src(wiki('Leonardo_da_Vinci'), 'anatomy, astronomy, botany, cartography')),
      fact('f3', 'Most of his writings are in mirror-image cursive.', src(wiki('Leonardo_da_Vinci'), 'mirror-image cursive')),
    ],
    moments: [
      moment('m1', 'He wrote with his left hand, so writing from right to left in his notebooks was probably easier for him.', src(wiki('Leonardo_da_Vinci'), 'wrote with his left hand')),
      moment('m2', 'He filled his notebooks with drawings and notes on subject after subject.', src(wiki('Leonardo_da_Vinci'), 'notebooks, in which he made drawings and notes')),
    ],
    angles: [
      angle('a1', 'the notebook', 'What does an inventor who sketched flying machines in a notebook have in common with you?', 'Writing down every odd idea is how the good ones get kept.'),
      angle('a2', 'his own way of writing', 'Why would someone write backwards for a whole lifetime?', 'Doing things the way that works for you is allowed, even if it looks odd.'),
      angle('a3', 'everything at once', 'What happens when you’re curious about everything?', 'Wide curiosity is a strength, even when it pulls you in many directions.'),
      angle('a4', 'too early', 'What is it like to imagine a machine nobody can build yet?', 'An idea can be worth having even before its time comes.'),
    ],
    tags: [
      tag('openness', 'high', 'curious about everything', 'His notebooks jump from anatomy to astronomy to machines.'),
      tag('conscientiousness', 'low', 'followed the next idea', 'He moved between subjects and left many projects unfinished.'),
      tag('autonomy', 'high', 'wrote his own way', 'He wrote in mirror-image script all his life.'),
      tag('playfulness', 'high', 'dreamed up flying machines', 'He designed machines far ahead of his time.'),
    ],
    vetting: 'Polymath, died 1519; no office; broadly admired. Weapon designs left out of the entry.',
  },
];
