import type { LegendFigure } from '../types';
import { angle, fact, moment, src, tag, wiki } from './define';

export const SCREEN_LEGENDS: readonly LegendFigure[] = [
  {
    id: 'lf_buster_keaton',
    name: 'Buster Keaton',
    kind: 'real',
    hall: 'screen',
    region: 'americas',
    place: 'United States',
    era: '1895–1966',
    died: 1966,
    birthday: { md: '10-04', source: src(wiki('Buster_Keaton'), 'October 4, 1895') },
    gender: 'man',
    field: 'Silent comedy',
    essence: 'Did the wildest stunts in film without ever cracking a smile.',
    whoTheyWere: 'An American actor, comedian and filmmaker who started as a child star in his family’s travelling act.',
    famousFor: 'Silent comedies full of daring stunts, and his deadpan face.',
    facts: [
      fact('f1', 'His stoic, deadpan expression earned him the nickname “The Great Stone Face”.', src(wiki('Buster_Keaton'), 'The Great Stone Face')),
      fact('f2', 'He is best known for silent films full of physical comedy and inventive stunts.', src(wiki('Buster_Keaton'), 'physical comedy and inventive stunts')),
      fact('f3', 'Orson Welles called his film The General “the greatest comedy ever made”.', src(wiki('Buster_Keaton'), 'the greatest comedy ever made')),
    ],
    moments: [
      moment('m1', 'As a child he performed in his family’s travelling vaudeville act.', src(wiki('Buster_Keaton'), "child vaudeville star, performing as part of his family's traveling act")),
      moment('m2', 'He moved from short films to features like Sherlock Jr. and The General.', src(wiki('Buster_Keaton'), 'Sherlock Jr. (1924)', 'The General (1926)')),
    ],
    angles: [
      angle('a1', 'the straight face', 'What does a comedian who never smiled have in common with you?', 'Staying calm while everything goes wrong can be the funniest, bravest thing.'),
      angle('a2', 'his own stunts', 'Why do the dangerous bit yourself?', 'Trusting your own skill in the big moment is its own kind of confidence.'),
      angle('a3', 'the family act', 'What do you carry from the people you started with?', 'Your earliest stage can shape your whole style.'),
      angle('a4', 'inventing gags', 'How do you build a joke out of a moving train?', 'Big ideas often come from playing with what’s right in front of you.'),
    ],
    tags: [
      tag('steadiness', 'high', 'calm in total chaos', 'His face stayed still while the world collapsed around him.'),
      tag('playfulness', 'high', 'built comedy from stunts', 'His films are full of inventive physical comedy.'),
      tag('self_efficacy', 'high', 'did his own stunts', 'He performed daring, inventive stunts himself.'),
      tag('conflict_assertiveness', 'low', 'said it all with silence', 'His humour came from a quiet, deadpan face.'),
    ],
    vetting: 'Actor and filmmaker, died 1966; no office; broadly admired.',
  },
  {
    id: 'lf_audrey_hepburn',
    name: 'Audrey Hepburn',
    kind: 'real',
    hall: 'screen',
    region: 'europe',
    place: 'Britain and the Netherlands',
    era: '1929–1993',
    died: 1993,
    birthday: { md: '05-04', source: src(wiki('Audrey_Hepburn'), '4 May 1929') },
    gender: 'woman',
    field: 'Film and humanitarian work',
    essence: 'A film star who spent her later years working for children.',
    whoTheyWere: 'A British actress and humanitarian, recognised as a film and fashion icon.',
    famousFor: 'Roman Holiday, Breakfast at Tiffany’s and her work as a UNICEF Goodwill Ambassador.',
    facts: [
      fact('f1', 'For Roman Holiday she became the first actress to win an Academy Award, a Golden Globe and a BAFTA for one performance.', src(wiki('Audrey_Hepburn'), 'Roman Holiday', 'first actress to win an Academy Award, a Golden Globe Award and a BAFTA')),
      fact('f2', 'She worked with UNICEF from 1954 onwards and became a Goodwill Ambassador.', src(wiki('Audrey_Hepburn'), 'contributed to UNICEF from 1954 onwards', 'Goodwill Ambassador')),
      fact('f3', 'She studied ballet at the Arnhem Conservatory during the Second World War.', src(wiki('Audrey_Hepburn'), 'studied ballet at the Arnhem Conservatory')),
    ],
    moments: [
      moment('m1', 'Between 1988 and 1992 she worked in some of the poorest communities of Africa, South America and Asia.', src(wiki('Audrey_Hepburn'), 'Between 1988 and 1992, she worked in some of the poorest communities')),
      moment('m2', 'By 1944, as a teenager, she was performing ballet to raise money for the resistance.', src(wiki('Audrey_Hepburn'), 'performing ballet to raise money to support the resistance')),
    ],
    angles: [
      angle('a1', 'the second act', 'What does a film star who turned to charity work have in common with you?', 'What you do with your later chapters can mean the most.'),
      angle('a2', 'dancing for others', 'What can a teenager’s ballet do in wartime?', 'Using your talent to help others counts, at any age.'),
      angle('a3', 'grace', 'Why do people still remember her style?', 'Quiet elegance can be stronger than loud attention.'),
      angle('a4', 'fame as a tool', 'How do you use being famous for something good?', 'Whatever attention you get can be pointed at what matters.'),
    ],
    tags: [
      tag('conflict_cooperativeness', 'high', 'gave her time to children', 'She worked for UNICEF in some of the poorest places.'),
      tag('agreeableness', 'high', 'gentle and gracious', 'She was known for warmth as well as style.'),
      tag('relatedness', 'high', 'drawn to people in need', 'Her later years centred on others.'),
      tag('attachment_anxiety', 'low', 'steady and trusting', 'She worked calmly alongside strangers worldwide.'),
    ],
    vetting: 'Actress and humanitarian, died 1993; no office; broadly beloved.',
  },
  {
    id: 'lf_jim_henson',
    name: 'Jim Henson',
    kind: 'real',
    hall: 'screen',
    region: 'americas',
    place: 'United States',
    era: '1936–1990',
    died: 1990,
    birthday: { md: '09-24', source: src(wiki('Jim_Henson'), 'September 24, 1936') },
    gender: 'man',
    field: 'Puppetry and film',
    essence: 'Gave the world Kermit the Frog.',
    whoTheyWere: 'An American puppeteer and filmmaker who changed how puppetry is filmed and shown.',
    famousFor: 'Creating the Muppets, Fraggle Rock and the Muppets of Sesame Street.',
    facts: [
      fact('f1', 'He achieved worldwide fame as the creator of the Muppets.', src(wiki('Jim_Henson'), 'creator of the Muppets')),
      fact('f2', 'He created the Muppets for Sesame Street and created Fraggle Rock.', src(wiki('Jim_Henson'), 'Muppets for Sesame Street', 'Fraggle Rock')),
      fact('f3', 'He directed The Dark Crystal and Labyrinth.', src(wiki('Jim_Henson'), 'The Dark Crystal', 'Labyrinth')),
    ],
    moments: [
      moment('m1', 'He changed the way puppetry is captured and presented on screen.', src(wiki('Jim_Henson'), 'the way puppetry is captured and presented in video media')),
      moment('m2', 'Later in life he founded the Jim Henson Foundation.', src(wiki('Jim_Henson'), 'founded the Jim Henson Foundation')),
    ],
    angles: [
      angle('a1', 'the frog', 'What does the man behind Kermit have in common with you?', 'A soft, silly idea can end up meaning a lot to millions of people.'),
      angle('a2', 'puppets for TV', 'How do you make a sock feel alive on a screen?', 'Rethinking how something is shown can change what it is.'),
      angle('a3', 'kids and grown-ups', 'Why do Muppets work for every age?', 'Kindness and silliness together reach almost everyone.'),
      angle('a4', 'big, strange worlds', 'What happens when a puppeteer builds a whole fantasy film?', 'Following your strangest ideas can lead somewhere wonderful.'),
    ],
    tags: [
      tag('playfulness', 'high', 'made the Muppets', 'He built a world of silly, lovable characters.'),
      tag('openness', 'high', 'reinvented puppetry', 'He changed how puppets are filmed.'),
      tag('agreeableness', 'high', 'gentle and kind', 'His characters are known for warmth.'),
      tag('relatedness', 'high', 'built with a team', 'His work grew from a company of puppeteers.'),
    ],
    vetting: 'Puppeteer and filmmaker, died 1990; no office; broadly beloved.',
  },
  {
    id: 'lf_bruce_lee',
    name: 'Bruce Lee',
    kind: 'real',
    hall: 'screen',
    region: 'east_asia',
    place: 'Hong Kong and the United States',
    era: '1940–1973',
    died: 1973,
    birthday: { md: '11-27', source: src(wiki('Bruce_Lee'), 'November 27, 1940') },
    gender: 'man',
    field: 'Martial arts and film',
    essence: 'Told the world to be like water.',
    whoTheyWere: 'A Hong Kong and American martial artist, actor and filmmaker who bridged East and West.',
    famousFor: 'Enter the Dragon, and founding the martial arts philosophy Jeet Kune Do.',
    facts: [
      fact('f1', 'He founded Jeet Kune Do, a hybrid martial arts philosophy.', src(wiki('Bruce_Lee'), 'founder of Jeet Kune Do, a hybrid martial arts philosophy')),
      fact('f2', 'Time named him one of the 100 most important people of the 20th century.', src(wiki('Bruce_Lee'), '100 most important people of the 20th century')),
      fact('f3', 'He is seen as a pop culture icon who bridged the gap between East and West.', src(wiki('Bruce_Lee'), 'bridged the gap between East and West')),
    ],
    moments: [
      moment('m1', 'He wrote poetry too, and is known for the line “Be formless ... shapeless, like water.”', src(wiki('Bruce_Lee'), 'shapeless, like water')),
      moment('m2', 'He starred in the American-Hong Kong co-production Enter the Dragon.', src(wiki('Bruce_Lee'), 'Enter the Dragon (1973)')),
    ],
    angles: [
      angle('a1', 'like water', 'What does a martial artist who wanted to be like water have in common with you?', 'Being flexible isn’t weakness. It can be the strongest move.'),
      angle('a2', 'his own style', 'Why build a whole new way of fighting?', 'Taking what works from many places and making it yours is a real skill.'),
      angle('a3', 'the poet', 'Can a fighter also write poems?', 'You can be strong and thoughtful at the same time.'),
      angle('a4', 'two worlds', 'What happens when you belong to East and West?', 'Being between two cultures can let you connect both.'),
    ],
    tags: [
      tag('autonomy', 'high', 'made his own martial art', 'He founded his own fighting philosophy.'),
      tag('self_efficacy', 'high', 'trusted his own skill', 'He became one of the most influential martial artists.'),
      tag('conscientiousness', 'high', 'trained relentlessly', 'His art came from discipline and practice.'),
      tag('openness', 'high', 'mixed many traditions', 'Jeet Kune Do blended ideas from many sources.'),
    ],
    vetting: 'Martial artist and actor, died 1973; no office; broadly admired.',
  },
  {
    id: 'lf_hedy_lamarr',
    name: 'Hedy Lamarr',
    kind: 'real',
    hall: 'screen',
    region: 'europe',
    place: 'Austria and the United States',
    era: '1914–2000',
    died: 2000,
    birthday: { md: '11-09', source: src(wiki('Hedy_Lamarr'), 'November 9, 1914') },
    gender: 'woman',
    field: 'Film and invention',
    essence: 'A movie star whose invention helped lead to Wi-Fi.',
    whoTheyWere: 'An Austrian and American actress and inventor, famous on screen while inventing on the side.',
    famousFor: 'Co-inventing frequency hopping, whose principles are used in Bluetooth and early Wi-Fi.',
    facts: [
      fact('f1', 'With composer George Antheil she co-developed a frequency-hopping system.', src(wiki('Hedy_Lamarr'), 'frequency-hopping system she co-developed with George Antheil')),
      fact('f2', 'Its principles are used in Bluetooth and early versions of Wi-Fi.', src(wiki('Hedy_Lamarr'), 'Bluetooth and early versions of Wi-Fi')),
      fact('f3', 'Her technical achievements were not fully recognised until decades later.', src(wiki('Hedy_Lamarr'), 'not fully recognized until decades later')),
    ],
    moments: [
      moment('m1', 'She was celebrated for her acting, while her invention went largely unnoticed for decades.', src(wiki('Hedy_Lamarr'), 'celebrated for her acting career')),
      moment('m2', 'Her frequency-hopping idea became foundational to spread spectrum communications.', src(wiki('Hedy_Lamarr'), 'foundational to later spread spectrum communications')),
    ],
    angles: [
      angle('a1', 'the hidden inventor', 'What does a film star with a secret inventor side have in common with you?', 'People may only see one side of you. The other side still counts.'),
      angle('a2', 'recognised late', 'What happens when your best idea is ignored for decades?', 'Being overlooked now doesn’t decide what your work is worth.'),
      angle('a3', 'an odd partnership', 'Why would an actress and a composer invent together?', 'Unexpected teammates can bring the best ideas.'),
      angle('a4', 'more than one thing', 'Can you be known for one thing and great at another?', 'You don’t have to stay in the box people put you in.'),
    ],
    tags: [
      tag('openness', 'high', 'acted and invented', 'She worked on inventions alongside her film career.'),
      tag('autonomy', 'high', 'refused to be one thing', 'She pursued invention while famous for acting.'),
      tag('competence', 'high', 'solved a real problem', 'Her idea became foundational to wireless tech.'),
      tag('relatedness', 'low', 'tinkered on her own time', 'Much of her inventing happened privately.'),
    ],
    vetting: 'Actress and inventor, died 2000; no office; broadly admired. Wartime purpose described neutrally.',
  },
  {
    id: 'lf_akira_kurosawa',
    name: 'Akira Kurosawa',
    kind: 'real',
    hall: 'screen',
    region: 'east_asia',
    place: 'Japan',
    era: '1910–1998',
    died: 1998,
    gender: 'man',
    field: 'Film directing',
    essence: 'A painter who became one of cinema’s greatest directors.',
    whoTheyWere: 'A Japanese filmmaker who was involved in every part of making his films.',
    famousFor: 'Rashomon and Seven Samurai.',
    facts: [
      fact('f1', 'Rashomon was the surprise winner of the Golden Lion at the 1951 Venice Film Festival.', src(wiki('Akira_Kurosawa'), 'surprise winner of the Golden Lion')),
      fact('f2', 'His films include Ikiru, Seven Samurai and Yojimbo.', src(wiki('Akira_Kurosawa'), 'Seven Samurai (1954)', 'Yojimbo (1961)')),
      fact('f3', 'After their first film together, he and the actor Toshiro Mifune made 15 more.', src(wiki('Akira_Kurosawa'), 'collaborate on 15 more films')),
    ],
    moments: [
      moment('m1', 'After a brief time as a painter, he joined the Japanese film industry in 1936.', src(wiki('Akira_Kurosawa'), 'brief stint as a painter')),
      moment('m2', 'Rashomon’s success opened Western film markets to Japanese films for the first time.', src(wiki('Akira_Kurosawa'), 'opened Western film markets to Japanese films')),
    ],
    angles: [
      angle('a1', 'from painter to director', 'What does a painter who switched to film have in common with you?', 'Skills from an old path can make your new one stronger.'),
      angle('a2', 'the surprise win', 'What happens when nobody expects your work to win?', 'Low expectations can be the best place to surprise people.'),
      angle('a3', 'the long partnership', 'Why keep working with the same actor, film after film?', 'Finding your people and sticking with them pays off.'),
      angle('a4', 'every job at once', 'Why direct, write, produce and edit?', 'Caring about every part is how a vision stays whole.'),
    ],
    tags: [
      tag('conscientiousness', 'high', 'controlled every step', 'He worked on every part of production himself.'),
      tag('autonomy', 'high', 'directed, wrote and edited', 'He kept control of his films.'),
      tag('relatedness', 'high', 'worked with one actor for years', 'He made film after film with Toshiro Mifune.'),
      tag('growth_mindset', 'high', 'switched from painting', 'He moved from painting to film and mastered it.'),
    ],
    vetting: 'Director, died 1998; no office; broadly admired.',
  },
  {
    id: 'lf_fred_astaire',
    name: 'Fred Astaire',
    kind: 'real',
    hall: 'screen',
    region: 'americas',
    place: 'United States',
    era: '1899–1987',
    died: 1987,
    birthday: { md: '05-10', source: src(wiki('Fred_Astaire'), 'May 10, 1899') },
    gender: 'man',
    field: 'Dance and film',
    essence: 'Spent weeks rehearsing so a dance looked effortless.',
    whoTheyWere: 'An American dancer, actor, singer and choreographer whose career spanned stage, film and television.',
    famousFor: 'Ten Hollywood musicals with Ginger Rogers, including Top Hat.',
    facts: [
      fact('f1', 'He made ten Hollywood musicals with Ginger Rogers, including Top Hat.', src(wiki('Fred_Astaire'), 'co-starred in ten Hollywood musicals', 'Top Hat (1935)')),
      fact('f2', 'He insisted dances be filmed in as few shots as possible, with the dancers in full view.', src(wiki('Fred_Astaire'), 'in as few shots as possible')),
      fact('f3', 'He was a dancer, actor, singer, musician and choreographer.', src(wiki('Fred_Astaire'), 'dancer, actor, singer, musician, choreographer')),
    ],
    moments: [
      moment('m1', 'He and his partners spent weeks creating dance sequences in a secluded rehearsal space before filming.', src(wiki('Fred_Astaire'), 'spend weeks creating all the dance sequences in a secluded rehearsal space')),
      moment('m2', 'He wanted audiences to see the whole dancer, so the camera tracked the dance instead of cutting away.', src(wiki('Fred_Astaire'), 'closely tracking dolly camera')),
    ],
    angles: [
      angle('a1', 'weeks for minutes', 'What does a dancer who rehearsed for weeks have in common with you?', 'Hours of practice nobody sees are what make it look easy.'),
      angle('a2', 'the whole picture', 'Why refuse to cut away from the dancers?', 'Showing the full thing, not just highlights, takes confidence.'),
      angle('a3', 'the partnership', 'What makes ten films with one partner work?', 'Great pairs make each other better.'),
      angle('a4', 'many talents', 'Singer, dancer, actor: how do you do it all?', 'Combining your skills is what makes you hard to replace.'),
    ],
    tags: [
      tag('conscientiousness', 'high', 'weeks of rehearsal', 'He rehearsed each dance for weeks.'),
      tag('competence', 'high', 'made it look effortless', 'His dancing set a standard on film.'),
      tag('conflict_assertiveness', 'high', 'insisted on how to film', 'He insisted dances be shot in long, full takes.'),
      tag('relatedness', 'high', 'shone with a partner', 'His partnership with Ginger Rogers is legendary.'),
    ],
    vetting: 'Dancer and actor, died 1987; no office; broadly admired.',
  },
  {
    id: 'lf_anna_may_wong',
    name: 'Anna May Wong',
    kind: 'real',
    hall: 'screen',
    region: 'americas',
    place: 'United States',
    era: '1905–1961',
    died: 1961,
    birthday: { md: '01-03', source: src(wiki('Anna_May_Wong'), 'January 3, 1905') },
    gender: 'woman',
    field: 'Film',
    essence: 'Hollywood’s first Chinese-American star, who walked away from bad roles.',
    whoTheyWere: 'An American actress whose career spanned silent film, sound film, television and stage.',
    famousFor: 'Being the first Chinese-American film star in Hollywood.',
    facts: [
      fact('f1', 'She is considered the first Chinese-American film star in Hollywood.', src(wiki('Anna_May_Wong'), 'first Chinese-American film star in Hollywood')),
      fact('f2', 'She acted in The Toll of the Sea, one of the first films made in colour.', src(wiki('Anna_May_Wong'), 'The Toll of the Sea (1922), one of the first films made in color')),
      fact('f3', 'In 1960 she received a star on the Hollywood Walk of Fame, the first Asian-American actress to do so.', src(wiki('Anna_May_Wong'), 'first Asian-American actress to receive this honor')),
    ],
    moments: [
      moment('m1', 'Frustrated by stereotypical supporting roles, she left Hollywood for Europe in 1928 and starred in notable plays and films there.', src(wiki('Anna_May_Wong'), 'left for Europe in March 1928')),
      moment('m2', 'In the 1920s and 1930s she was acclaimed as one of the top fashion icons.', src(wiki('Anna_May_Wong'), 'top fashion icons')),
    ],
    angles: [
      angle('a1', 'walking away', 'What does an actress who left Hollywood over bad roles have in common with you?', 'Walking away from what doesn’t fit you can be the bravest step.'),
      angle('a2', 'first through the door', 'What does it take to be the first?', 'Going first is hard, and it makes the path easier for others.'),
      angle('a3', 'colour film', 'What’s it like to be part of something brand new?', 'Saying yes to new things puts you in the story early.'),
      angle('a4', 'the icon', 'How do you make people see you on your own terms?', 'How you carry yourself can say what words can’t.'),
    ],
    tags: [
      tag('conflict_assertiveness', 'high', 'refused the stereotypes', 'She left Hollywood rather than keep playing narrow roles.'),
      tag('autonomy', 'high', 'took her career abroad', 'She moved to Europe to find better work.'),
      tag('self_efficacy', 'high', 'first of her kind', 'She became Hollywood’s first Chinese-American star.'),
      tag('conflict_cooperativeness', 'low', 'wouldn’t accept less', 'She wouldn’t settle for the roles offered.'),
    ],
    vetting: 'Actress, died 1961; no office; broadly admired.',
  },
  {
    id: 'lf_lucille_ball',
    name: 'Lucille Ball',
    kind: 'real',
    hall: 'screen',
    region: 'americas',
    place: 'United States',
    era: '1911–1989',
    died: 1989,
    birthday: { md: '08-06', source: src(wiki('Lucille_Ball'), 'August 6, 1911') },
    gender: 'woman',
    field: 'Comedy and television',
    essence: 'Made everyone laugh, then ran the studio.',
    whoTheyWere: 'An American comedian, actress, producer and studio executive.',
    famousFor: 'I Love Lucy, and becoming the first woman to run a major TV studio.',
    facts: [
      fact('f1', 'She and Desi Arnaz created the sitcom I Love Lucy.', src(wiki('Lucille_Ball'), 'created the sitcom I Love Lucy')),
      fact('f2', 'In 1962 she became the first woman to run a major television studio, Desilu Productions.', src(wiki('Lucille_Ball'), 'first woman to run a major television studio')),
      fact('f3', 'Desilu produced Mission: Impossible and Star Trek.', src(wiki('Lucille_Ball'), 'Mission: Impossible and Star Trek')),
    ],
    moments: [
      moment('m1', 'She produced and starred in the Broadway musical Wildcat.', src(wiki('Lucille_Ball'), 'produced and starred in the Broadway musical Wildcat')),
      moment('m2', 'Time later named her one of the most influential women of the 20th century, as comedian, actress, producer and executive.', src(wiki('Lucille_Ball'), 'most influential women of the 20th century')),
    ],
    angles: [
      angle('a1', 'funny and the boss', 'What does a comedian who ran a TV studio have in common with you?', 'Being the funny one and being in charge can go together.'),
      angle('a2', 'Star Trek’s backer', 'Why would a sitcom star back a space show?', 'Betting on other people’s strange ideas can pay off hugely.'),
      angle('a3', 'the first woman', 'What changes when you’re first at the top?', 'Taking the seat nobody like you had before matters.'),
      angle('a4', 'four jobs', 'How do you get great at four different roles?', 'Each role you take on teaches you the next one.'),
    ],
    tags: [
      tag('playfulness', 'high', 'the queen of physical comedy', 'Her comedy made millions laugh.'),
      tag('locus_of_control', 'high', 'took charge of the studio', 'She became the first woman to run a major TV studio.'),
      tag('extraversion', 'high', 'loved an audience', 'She built her career in front of crowds.'),
      tag('self_efficacy', 'high', 'backed big new shows', 'Her studio produced bold new series.'),
    ],
    vetting: 'Comedian and executive, died 1989; no office; broadly beloved.',
  },
  {
    id: 'lf_satyajit_ray',
    name: 'Satyajit Ray',
    kind: 'real',
    hall: 'screen',
    region: 'south_asia',
    place: 'India',
    era: '1921–1992',
    died: 1992,
    birthday: { md: '05-02', source: src(wiki('Satyajit_Ray'), '2 May 1921') },
    gender: 'man',
    field: 'Film directing',
    essence: 'His first film won eleven international prizes.',
    whoTheyWere: 'An Indian film director, writer, illustrator and composer from Calcutta.',
    famousFor: 'The Apu Trilogy, beginning with Pather Panchali.',
    facts: [
      fact('f1', 'His first film, Pather Panchali, won eleven international prizes.', src(wiki('Satyajit_Ray'), 'won eleven international prizes')),
      fact('f2', 'He directed 36 films, including features, documentaries and shorts.', src(wiki('Satyajit_Ray'), 'Ray directed 36 films')),
      fact('f3', 'He illustrated all his books and designed their covers.', src(wiki('Satyajit_Ray'), 'illustrated all his books')),
    ],
    moments: [
      moment('m1', 'Twenty-four days before his death, Audrey Hepburn presented him with an Honorary Academy Award by video-link.', src(wiki('Satyajit_Ray'), 'Honorary Academy Award by Audrey Hepburn')),
      moment('m2', 'He started work on his first film after returning from a visit to London.', src(wiki('Satyajit_Ray'), 'started work on his first film after he returned from London')),
    ],
    angles: [
      angle('a1', 'the first film', 'What does a director whose first film won eleven prizes have in common with you?', 'Your first real attempt can be stronger than you expect.'),
      angle('a2', 'doing it all', 'Director, writer, illustrator, composer: why all four?', 'Many small skills can add up to one clear voice.'),
      angle('a3', 'home stories', 'Why tell stories about the place you know?', 'The world you know best can speak to everyone.'),
      angle('a4', 'honoured late', 'What does recognition mean at the very end?', 'Your work is valued even before anyone says so.'),
    ],
    tags: [
      tag('openness', 'high', 'worked in many arts', 'He directed, wrote, drew and composed.'),
      tag('conscientiousness', 'high', 'designed every detail', 'He illustrated his books and created their publicity.'),
      tag('extraversion', 'low', 'quiet storyteller', 'His films are known for quiet, careful storytelling.'),
      tag('competence', 'high', 'mastered film fast', 'His first film won eleven international prizes.'),
    ],
    vetting: 'Director, died 1992; no office; broadly admired.',
  },
];
