import type { LegendFigure } from '../types';
import { angle, fact, moment, src, tag, wiki } from './define';

const OWENS = wiki('Jesse_Owens');
const FANNY = wiki('Fanny_Blankers-Koen');
const DUKE = wiki('Duke_Kahanamoku');

export const SPORT_LEGENDS: readonly LegendFigure[] = [
  {
    id: 'lf_jesse_owens',
    name: 'Jesse Owens',
    kind: 'real',
    hall: 'sport',
    region: 'americas',
    place: 'United States',
    era: '1913–1980',
    died: 1980,
    birthday: { md: '09-12', source: src(OWENS, 'September 12, 1913') },
    gender: 'man',
    field: 'Track and field',
    essence: 'Got his name from a teacher who misheard him, then made it famous.',
    whoTheyWere: 'An American track and field athlete who grew up in Cleveland and took small jobs in his spare time.',
    famousFor: 'Four gold medals at the 1936 Olympic Games.',
    facts: [
      fact('f1', 'He won four gold medals at the 1936 Olympic Games.', src(OWENS, '1936 Olympic Games by winning four gold medals')),
      fact('f2', 'He set individual Olympic records in each of his events.', src(OWENS, 'setting individual Olympic records')),
      fact('f3', 'He is widely regarded as one of the greatest athletes in track and field.', src(OWENS, 'one of the greatest athletes in track and field')),
    ],
    moments: [
      moment(
        'm1',
        'When a new teacher asked his name, he said “J. C.”, and because of his accent she heard “Jesse”. The name stuck.',
        src(OWENS, 'she thought he said "Jesse"', 'The name stuck'),
      ),
      moment('m2', 'He won the 100 m dash by one tenth of a second over his college friend Ralph Metcalfe.', src(OWENS, 'college friend Ralph Metcalfe')),
    ],
    angles: [
      angle('a1', 'the misheard name', 'What does an athlete named by a teacher’s mistake have in common with you?', 'A label you didn’t choose can still become something you’re proud of.'),
      angle('a2', 'one tenth of a second', 'What separates first and second when both are friends?', 'You can race someone hard and still be on their side.'),
      angle('a3', 'four for four', 'How do you stay steady through four finals?', 'Doing your thing calmly, one event at a time, adds up.'),
      angle('a4', 'spare-time jobs', 'Why would a future champion deliver groceries after school?', 'The ordinary work around your dream is part of the dream.'),
    ],
    tags: [
      tag('steadiness', 'high', 'calm through four finals', 'He won four events at the same Games.'),
      tag('competence', 'high', 'record after record', 'He set Olympic records in each of his events.'),
      tag('agreeableness', 'high', 'raced a friend, stayed friends', 'He beat his college friend by a tenth of a second.'),
      tag('relatedness', 'high', 'ran with his teammates', 'His friends and teammates were part of his story.'),
    ],
    vetting: 'Athlete, died 1980; no office; broadly admired.',
  },
  {
    id: 'lf_fanny_blankers_koen',
    name: 'Fanny Blankers-Koen',
    kind: 'real',
    hall: 'sport',
    region: 'europe',
    place: 'Netherlands',
    era: '1918–2004',
    died: 2004,
    birthday: { md: '04-26', source: src(FANNY, '26 April 1918') },
    gender: 'woman',
    field: 'Track and field',
    essence: 'Called too old at thirty, then won four golds.',
    whoTheyWere: 'A Dutch track and field athlete who competed at the 1948 London Olympics as a mother of two.',
    famousFor: 'Four gold medals in 1948, earning the nickname “the Flying Housewife”.',
    facts: [
      fact('f1', 'She won four gold medals at the 1948 Summer Olympics in London.', src(FANNY, 'four gold medals at the 1948 Summer Olympics')),
      fact('f2', 'She competed as a 30-year-old mother of two and was nicknamed “the Flying Housewife”.', src(FANNY, '30-year-old mother of two', 'Flying Housewife')),
      fact('f3', 'Before the Games, a British team manager said she was “too old to make the grade”.', src(FANNY, 'too old to make the grade')),
    ],
    moments: [
      moment(
        'm1',
        'Shortly before the 200 m semi-final she broke down from homesickness. After a long talk with her husband, she decided to run anyway.',
        src(FANNY, 'broke down because of homesickness', 'decided to run anyway'),
      ),
      moment('m2', 'Two months before the Games she broke her own world record in the 80 m hurdles.', src(FANNY, 'beating her own 80 m hurdles world record')),
    ],
    angles: [
      angle('a1', 'too old', 'What does a sprinter told she was too old have in common with you?', 'Someone else’s timeline for your life is only a guess.'),
      angle('a2', 'the homesick semi-final', 'What happens when a champion wants to go home the day before the race?', 'Doubting yourself right before the big moment doesn’t mean you’re not ready.'),
      angle('a3', 'the talk', 'Who do you call when you nearly quit?', 'Talking it through with someone close can turn a no into a yes.'),
      angle('a4', 'both lives', 'Can you be a parent and the fastest person there?', 'You don’t have to shrink one part of your life to grow another.'),
    ],
    tags: [
      tag('self_efficacy', 'low', 'nearly didn’t run', 'Homesick and overwhelmed, she almost skipped the semi-final.'),
      tag('steadiness', 'low', 'felt it all before the race', 'She broke down shortly before running.'),
      tag('attachment_avoidance', 'low', 'leaned on her husband', 'A long talk with her husband got her to the start line.'),
      tag('locus_of_control', 'high', 'answered critics on the track', 'Told she was too old, she won four golds.'),
    ],
    vetting: 'Athlete, died 2004; no office; broadly admired.',
  },
  {
    id: 'lf_duke_kahanamoku',
    name: 'Duke Kahanamoku',
    kind: 'real',
    hall: 'sport',
    region: 'oceania',
    place: 'Hawaiʻi',
    era: '1890–1968',
    died: 1968,
    birthday: { md: '08-24', source: src(DUKE, 'August 24, 1890') },
    gender: 'man',
    field: 'Swimming and surfing',
    essence: 'Won Olympic gold, then taught the world to surf.',
    whoTheyWere: 'A Native Hawaiian swimmer and lifeguard who spread surfing far beyond Hawaiʻi.',
    famousFor: 'Olympic swimming golds, and the surfing exhibition that helped start surfing in Australia.',
    facts: [
      fact('f1', 'He won a gold medal in the 100-meter freestyle at the 1912 Olympics in Stockholm.', src(DUKE, '1912 Summer Olympics in Stockholm', 'gold medal in the 100-meter freestyle')),
      fact('f2', 'His 1914 surfing exhibition at Freshwater Beach in Sydney is seen as a turning point for surfing in Australia.', src(DUKE, 'Freshwater Beach', 'seminal event')),
      fact('f3', 'He trained and loaned equipment to new surfers.', src(DUKE, 'loaned equipment to new surfers')),
    ],
    moments: [
      moment(
        'm1',
        'In 1925 at Newport Beach, he used his surfboard to rescue eight men from a capsized fishing boat, making repeated trips through heavy surf.',
        src(DUKE, 'rescued eight men', 'Using his surfboard'),
      ),
      moment('m2', 'He built a surfboard in Australia from a piece of local pine.', src(DUKE, 'piece of pine')),
    ],
    angles: [
      angle('a1', 'sharing the waves', 'What does a champion who lent his boards to beginners have in common with you?', 'Teaching what you love is a way of keeping it alive.'),
      angle('a2', 'the rescue', 'What do you do when the surf is heavy and people need help?', 'Using your everyday skill when it counts is a kind of courage.'),
      angle('a3', 'gold and play', 'Can the same person be an Olympic champion and a beach show-off?', 'Taking something seriously and having fun with it can go together.'),
      angle('a4', 'build your own board', 'Why build a surfboard out of whatever wood is nearby?', 'Making do with what’s around you can start something big.'),
    ],
    tags: [
      tag('playfulness', 'high', 'made the waves fun', 'He spread surfing through exhibitions people loved.'),
      tag('agreeableness', 'high', 'lent out his boards', 'He trained and loaned equipment to new surfers.'),
      tag('relatedness', 'high', 'brought surfing to new shores', 'He shared surfing with people in other countries.'),
      tag('attachment_anxiety', 'low', 'trusted strangers on his board', 'He shared his gear and skills freely with beginners.'),
    ],
    vetting: 'Athlete and lifeguard, died 1968; no office; broadly beloved.',
  },
  {
    id: 'lf_jim_thorpe',
    name: 'Jim Thorpe',
    kind: 'real',
    hall: 'sport',
    region: 'americas',
    place: 'United States (Sac and Fox Nation)',
    era: '1887–1953',
    died: 1953,
    gender: 'man',
    field: 'Track, football, baseball',
    essence: 'Won two Olympic golds and played three pro sports.',
    whoTheyWere: 'An American athlete and citizen of the Sac and Fox Nation, one of the most versatile athletes of modern sports.',
    famousFor: 'Olympic gold in both the pentathlon and decathlon in 1912.',
    facts: [
      fact('f1', 'He won Olympic gold in the classic pentathlon and the decathlon in 1912.', src(wiki('Jim_Thorpe'), 'classic pentathlon', 'decathlon')),
      fact('f2', 'He was the first Native American to win an Olympic gold medal for the United States.', src(wiki('Jim_Thorpe'), 'first Native American to win a gold medal for the United States')),
      fact('f3', 'He played professional football, baseball and basketball.', src(wiki('Jim_Thorpe'), 'professional football, baseball, and basketball')),
    ],
    moments: [
      moment('m1', 'His Olympic titles were taken away over amateur rules, then restored by the IOC in 1983, 30 years after his death.', src(wiki('Jim_Thorpe'), "restored Thorpe's Olympic medals")),
      moment('m2', 'He is considered one of the most versatile athletes of modern sports.', src(wiki('Jim_Thorpe'), 'most versatile athletes of modern sports')),
    ],
    angles: [
      angle('a1', 'good at everything', 'What does an athlete who played three pro sports have in common with you?', 'Being good at many things is a strength, not a lack of focus.'),
      angle('a2', 'taken, then given back', 'What happens when something you earned is taken away?', 'What you did is still real, even when someone takes the medal.'),
      angle('a3', 'first', 'What does it mean to be the first from your nation to win?', 'Going first carries the hopes of the people behind you.'),
      angle('a4', 'two events in one Games', 'How do you win the hardest all-round events twice in one week?', 'Range and grit together go a long way.'),
    ],
    tags: [
      tag('competence', 'high', 'great at every sport', 'He excelled in track, football, baseball and basketball.'),
      tag('openness', 'high', 'tried every sport', 'He moved between many sports professionally.'),
      tag('steadiness', 'high', 'kept going after the loss', 'He kept playing after his titles were taken.'),
      tag('locus_of_control', 'low', 'the officials decided', 'His medals were taken by officials, outside his control.'),
    ],
    vetting: 'Athlete, died 1953; no office; broadly admired. Birth date disputed, so no On this day.',
  },
  {
    id: 'lf_babe_didrikson_zaharias',
    name: 'Babe Didrikson Zaharias',
    kind: 'real',
    hall: 'sport',
    region: 'americas',
    place: 'United States',
    era: '1911–1956',
    died: 1956,
    birthday: { md: '06-26', source: src(wiki('Babe_Didrikson_Zaharias'), 'June 26, 1911') },
    gender: 'woman',
    field: 'Track and golf',
    essence: 'Olympic champion in track, then a golf legend.',
    whoTheyWere: 'An American athlete who excelled in golf, basketball, baseball, and track and field.',
    famousFor: 'Two Olympic golds in 1932, then 10 major golf championships.',
    facts: [
      fact('f1', 'She won two gold medals and a silver in track and field at the 1932 Olympics.', src(wiki('Babe_Didrikson_Zaharias'), 'two gold medals and a silver in track and field at the 1932 Summer Olympics')),
      fact('f2', 'She won 10 LPGA major championships in golf.', src(wiki('Babe_Didrikson_Zaharias'), '10 LPGA major championships')),
      fact('f3', 'She was a founding member of the Ladies Professional Golf Association in 1950.', src(wiki('Babe_Didrikson_Zaharias'), 'founding member of the Ladies Professional Golf Association')),
    ],
    moments: [
      moment('m1', 'After her Olympic success she switched to professional golf, and dominated it.', src(wiki('Babe_Didrikson_Zaharias'), 'before turning to professional golf')),
      moment('m2', 'She was the sixth of seven children, born to Norwegian immigrants in Texas.', src(wiki('Babe_Didrikson_Zaharias'), 'sixth of seven children')),
    ],
    angles: [
      angle('a1', 'switching sports', 'What does an Olympic champion who switched to golf have in common with you?', 'Starting over in something new can lead to a second peak.'),
      angle('a2', 'building the league', 'Why help start a league instead of just playing?', 'Building the place for others to play is a win too.'),
      angle('a3', 'all-rounder', 'What happens when you’re good at every game?', 'Range keeps you curious and hard to beat.'),
      angle('a4', 'one of seven', 'How do you stand out in a big family?', 'Finding your own thing is how you become yourself.'),
    ],
    tags: [
      tag('self_efficacy', 'high', 'won in any sport', 'She won at the Olympics and then in golf.'),
      tag('extraversion', 'high', 'loved the spotlight', 'She thrived in front of crowds across many sports.'),
      tag('growth_mindset', 'high', 'learned a new sport', 'She took up golf after track and mastered it.'),
      tag('locus_of_control', 'high', 'helped found the league', 'She was a founding member of the LPGA.'),
    ],
    vetting: 'Athlete, died 1956; no office; broadly admired.',
  },
  {
    id: 'lf_wilma_rudolph',
    name: 'Wilma Rudolph',
    kind: 'real',
    hall: 'sport',
    region: 'americas',
    place: 'United States',
    era: '1940–1994',
    died: 1994,
    birthday: { md: '06-23', source: src(wiki('Wilma_Rudolph'), 'June 23, 1940') },
    gender: 'woman',
    field: 'Sprinting',
    essence: 'Wore a leg brace until twelve, then became the fastest woman alive.',
    whoTheyWere: 'An American sprinter who overcame childhood polio to become an Olympic champion.',
    famousFor: 'Three gold medals at the 1960 Olympics in Rome.',
    facts: [
      fact('f1', 'She overcame polio as a child and wore a leg brace until she was 12.', src(wiki('Wilma_Rudolph'), 'overcame polio as a child', 'wore a leg brace until she was 12')),
      fact('f2', 'She won three gold medals at the 1960 Olympics in Rome.', src(wiki('Wilma_Rudolph'), 'three gold medals')),
      fact('f3', 'She was acclaimed as the fastest woman in the world in the 1960s.', src(wiki('Wilma_Rudolph'), 'fastest woman in the world in the 1960s')),
    ],
    moments: [
      moment('m1', 'She became the first American woman to win three gold medals in track and field at one Olympic Games.', src(wiki('Wilma_Rudolph'), 'first American woman to win three gold medals in track and field during a single Olympic Games')),
      moment('m2', 'Four years earlier, at the 1956 Olympics, she had won a relay bronze.', src(wiki('Wilma_Rudolph'), 'bronze medal in the 4 × 100-meter relay at the 1956 Summer Olympics')),
    ],
    angles: [
      angle('a1', 'from brace to gold', 'What does a sprinter who wore a leg brace until twelve have in common with you?', 'Where you start doesn’t set the limit on where you finish.'),
      angle('a2', 'bronze first', 'What do you do with a bronze before your golds?', 'An early result is a step, not the final word.'),
      angle('a3', 'the fastest', 'What does it feel like to be the fastest anywhere?', 'Your hard years can become your speed.'),
      angle('a4', 'three in one Games', 'How do you win three times in a row?', 'Confidence builds race by race.'),
    ],
    tags: [
      tag('growth_mindset', 'high', 'went from brace to gold', 'She overcame childhood polio to become a champion.'),
      tag('self_efficacy', 'high', 'believed she could run', 'She became the fastest woman in the world.'),
      tag('steadiness', 'high', 'calm in three finals', 'She won three golds at one Games.'),
      tag('agreeableness', 'high', 'warm and gracious', 'She became a beloved international icon.'),
    ],
    vetting: 'Athlete, died 1994; no office; broadly admired.',
  },
  {
    id: 'lf_babe_ruth',
    name: 'Babe Ruth',
    kind: 'real',
    hall: 'sport',
    region: 'americas',
    place: 'United States',
    era: '1895–1948',
    died: 1948,
    birthday: { md: '02-06', source: src(wiki('Babe_Ruth'), 'February 6, 1895') },
    gender: 'man',
    field: 'Baseball',
    essence: 'Started as a star pitcher and became baseball’s greatest slugger.',
    whoTheyWere: 'An American baseball player whose Major League career spanned 22 seasons.',
    famousFor: '714 home runs with the Boston Red Sox and New York Yankees.',
    facts: [
      fact('f1', 'He began as a star left-handed pitcher for the Boston Red Sox.', src(wiki('Babe_Ruth'), 'star left-handed pitcher for the Boston Red Sox')),
      fact('f2', 'He became famous as a slugging outfielder for the New York Yankees.', src(wiki('Babe_Ruth'), 'slugging outfielder for the New York Yankees')),
      fact('f3', 'He was nicknamed “the Bambino” and “the Sultan of Swat”.', src(wiki('Babe_Ruth'), 'the Bambino', 'the Sultan of Swat')),
    ],
    moments: [
      moment('m1', 'He was one of the “first five” members elected to the Baseball Hall of Fame.', src(wiki('Babe_Ruth'), 'first five')),
      moment('m2', 'His career home run total stood at 714.', src(wiki('Babe_Ruth'), '714')),
    ],
    angles: [
      angle('a1', 'pitcher to slugger', 'What does a pitcher who became the greatest hitter have in common with you?', 'Switching roles can unlock the thing you’re best at.'),
      angle('a2', 'the big swing', 'Why swing for the fences every time?', 'Going big sometimes means missing, and that’s part of it.'),
      angle('a3', 'the nickname', 'What does it mean when the world gives you a nickname?', 'Being yourself loudly is how people remember you.'),
      angle('a4', 'first five', 'What does it take to be in the first group remembered?', 'Doing something nobody had done sets the bar for everyone after.'),
    ],
    tags: [
      tag('extraversion', 'high', 'larger than life', 'He became one of sport’s biggest celebrities.'),
      tag('playfulness', 'high', 'played with joy', 'He was known for his big, fun personality.'),
      tag('self_efficacy', 'high', 'swung for the fences', 'He set home run records.'),
      tag('conscientiousness', 'low', 'played by feel', 'He was known for his instinct more than his routine.'),
    ],
    vetting: 'Athlete, died 1948; no office; broadly admired.',
  },
  {
    id: 'lf_roberto_clemente',
    name: 'Roberto Clemente',
    kind: 'real',
    hall: 'sport',
    region: 'americas',
    place: 'Puerto Rico',
    era: '1934–1972',
    died: 1972,
    birthday: { md: '08-18', source: src(wiki('Roberto_Clemente'), 'August 18, 1934') },
    gender: 'man',
    field: 'Baseball',
    essence: 'A baseball great who spent his off-seasons helping others.',
    whoTheyWere: 'A Puerto Rican baseball player who played 18 seasons for the Pittsburgh Pirates.',
    famousFor: '3,000 hits, and his charity work across Latin America.',
    facts: [
      fact('f1', 'He had 3,000 hits in his major league career.', src(wiki('Roberto_Clemente'), '3,000 hits')),
      fact('f2', 'He was a two-time World Series champion.', src(wiki('Roberto_Clemente'), 'two-time World Series champion')),
      fact('f3', 'In the off-season he did charity work in Latin American and Caribbean countries.', src(wiki('Roberto_Clemente'), 'involved in charity work in Latin American and Caribbean countries')),
    ],
    moments: [
      moment('m1', 'In 1972 he was flying to deliver emergency relief to earthquake survivors in Nicaragua when his plane went down.', src(wiki('Roberto_Clemente'), 'earthquake in Nicaragua')),
      moment('m2', 'He played 18 seasons for the Pittsburgh Pirates.', src(wiki('Roberto_Clemente'), '18 seasons')),
    ],
    angles: [
      angle('a1', 'off the field', 'What does a star who spent his off-seasons helping others have in common with you?', 'What you do when nobody’s watching says the most about you.'),
      angle('a2', 'three thousand hits', 'How do you get to three thousand?', 'Consistency, one at-bat at a time, adds up.'),
      angle('a3', 'going himself', 'Why deliver help in person?', 'Showing up yourself can matter as much as what you bring.'),
      angle('a4', 'pride in home', 'What does it mean to carry your home with you?', 'Where you come from can be a source of strength.'),
    ],
    tags: [
      tag('conflict_cooperativeness', 'high', 'gave his off-seasons away', 'He did charity work across Latin America.'),
      tag('relatedness', 'high', 'stood by his people', 'He was devoted to his community.'),
      tag('conscientiousness', 'high', 'consistent for 18 seasons', 'He reached 3,000 hits over 18 seasons.'),
      tag('locus_of_control', 'high', 'went to help in person', 'He chose to deliver aid himself.'),
    ],
    vetting: 'Athlete and humanitarian, died 1972; no office; broadly admired. His death is described gently.',
  },
  {
    id: 'lf_arthur_ashe',
    name: 'Arthur Ashe',
    kind: 'real',
    hall: 'sport',
    region: 'americas',
    place: 'United States',
    era: '1943–1993',
    died: 1993,
    birthday: { md: '07-10', source: src(wiki('Arthur_Ashe'), 'July 10, 1943') },
    gender: 'man',
    field: 'Tennis',
    essence: 'The only Black man to win Wimbledon, US Open and Australian Open singles.',
    whoTheyWere: 'An American tennis player with a powerful serve-and-volley game.',
    famousFor: 'Three Grand Slam singles titles, including Wimbledon.',
    facts: [
      fact('f1', 'He won three Grand Slam singles titles and two in doubles.', src(wiki('Arthur_Ashe'), 'three Grand Slam singles titles')),
      fact('f2', 'He was the first Black player selected for the United States Davis Cup team.', src(wiki('Arthur_Ashe'), 'first Black player selected to the United States Davis Cup team')),
      fact('f3', 'He is the only Black man to win the singles titles at Wimbledon, the US Open and the Australian Open.', src(wiki('Arthur_Ashe'), 'only Black man ever to win the singles titles at Wimbledon, the US Open, and the Australian Open')),
    ],
    moments: [
      moment('m1', 'In 1975 he won the season-ending WCT Finals.', src(wiki('Arthur_Ashe'), 'In 1975 he won the season-ending WCT Finals')),
      moment('m2', 'He played as an amateur before the Open Era began.', src(wiki('Arthur_Ashe'), 'remained an amateur player before the advent of the Open Era')),
    ],
    angles: [
      angle('a1', 'first on the team', 'What does the first Black player on the Davis Cup team have in common with you?', 'Being first in a room can be lonely, and it changes the room.'),
      angle('a2', 'calm power', 'How do you win with a big serve and a calm face?', 'Quiet confidence can be the strongest kind.'),
      angle('a3', 'the season finale', 'What does it take to win when everyone is at their best?', 'Bringing your best when it counts is a skill you build.'),
      angle('a4', 'three different courts', 'Why win on grass, hard court and more?', 'Adapting to new conditions keeps you winning.'),
    ],
    tags: [
      tag('steadiness', 'high', 'calm on court', 'He was known for his composure.'),
      tag('competence', 'high', 'won on every surface', 'He won singles at three different Grand Slams.'),
      tag('self_efficacy', 'high', 'first through the door', 'He was the first Black player on the Davis Cup team.'),
      tag('agreeableness', 'high', 'gracious in sport', 'He was admired for his dignity.'),
    ],
    vetting: 'Athlete, died 1993; no office; broadly admired.',
  },
  {
    id: 'lf_emil_zatopek',
    name: 'Emil Zátopek',
    kind: 'real',
    hall: 'sport',
    region: 'europe',
    place: 'Czechoslovakia',
    era: '1922–2000',
    died: 2000,
    birthday: { md: '09-19', source: src(wiki('Emil_Zátopek'), '19 September 1922') },
    gender: 'man',
    field: 'Long-distance running',
    essence: 'Ran his first marathon at the Olympics, on a whim, and won.',
    whoTheyWere: 'A Czech long-distance runner nicknamed the “Czech Locomotive”.',
    famousFor: 'Three gold medals at the 1952 Olympics: 5,000 m, 10,000 m and the marathon.',
    facts: [
      fact('f1', 'He won three gold medals at the 1952 Olympics in Helsinki.', src(wiki('Emil_Zátopek'), 'three gold medals at the 1952 Summer Olympics')),
      fact('f2', 'He was nicknamed the “Czech Locomotive”.', src(wiki('Emil_Zátopek'), 'Czech Locomotive')),
      fact('f3', 'In 1954 he was the first runner to break 29 minutes in the 10,000 metres.', src(wiki('Emil_Zátopek'), 'first runner to break the 29-minute barrier')),
    ],
    moments: [
      moment('m1', 'After winning the 5,000 m and 10,000 m, he decided at the last minute to run the first marathon of his life, and won it.', src(wiki('Emil_Zátopek'), 'decided at the last minute to compete in the first marathon of his life')),
      moment('m2', 'He came first in both the 5,000 and 10,000 metres in Helsinki.', src(wiki('Emil_Zátopek'), 'came first in the 5,000 metres and 10,000 metres')),
    ],
    angles: [
      angle('a1', 'the last-minute marathon', 'What does a runner who entered his first marathon on a whim have in common with you?', 'Saying yes to something new at the last minute can be your best call.'),
      angle('a2', 'three in a week', 'How do you win three races in one Games?', 'Momentum is real: one win gives you nerve for the next.'),
      angle('a3', 'the locomotive', 'What does it mean to just keep going?', 'Relentless effort beats looking smooth.'),
      angle('a4', 'breaking the barrier', 'What happens when you go under a number nobody had?', 'Limits are often just the best anyone has done so far.'),
    ],
    tags: [
      tag('openness', 'high', 'a new race, on a whim', 'He ran his first marathon at the Olympics.'),
      tag('conscientiousness', 'low', 'decided at the last minute', 'He entered the marathon at the last minute.'),
      tag('self_efficacy', 'high', 'believed he could do three', 'He won three golds at one Games.'),
      tag('steadiness', 'high', 'kept a relentless pace', 'He was nicknamed the Czech Locomotive.'),
    ],
    vetting: 'Athlete, died 2000; no office; entry avoids Cold War politics; broadly admired.',
  },
];
