import type { LegendFigure } from '../types';
import { angle, fact, moment, src, tag, wiki } from './define';

const RYOKAN = wiki('Ryōkan');

export const WORDS_LEGENDS: readonly LegendFigure[] = [
  {
    id: 'lf_ryokan',
    name: 'Ryōkan',
    kind: 'real',
    hall: 'words',
    region: 'east_asia',
    place: 'Japan',
    era: '1758–1831',
    died: 1831,
    gender: 'man',
    field: 'Poetry and calligraphy',
    essence: 'A hermit poet who wished he could give a thief the moon.',
    whoTheyWere: 'A quiet Japanese monk and poet who lived much of his life alone in a mountain hut.',
    famousFor: 'Simple poems about nature, his calligraphy, and stories of his kindness.',
    facts: [
      fact('f1', 'He lived much of his life as a hermit.', src(RYOKAN, 'lived much of his life as a hermit')),
      fact('f2', 'He refused any position as a priest, or even the title of poet.', src(RYOKAN, 'refused to accept any position as a priest')),
      fact('f3', 'He sometimes forgot to beg for food because he was playing with the village children.', src(RYOKAN, 'playing with the children of the nearby village')),
    ],
    moments: [
      moment(
        'm1',
        'As the story goes, a thief found nothing to steal in his hut, so Ryōkan gave him his clothes, then sat watching the moon, wishing he could have given him that too.',
        src(RYOKAN, 'thief', 'I wish I could have given him this beautiful moon'),
      ),
      moment('m2', 'His poems show a good sense of humour and a man who didn’t take himself too seriously.', src(RYOKAN, 'good sense of humour')),
    ],
    angles: [
      angle('a1', 'the moon', 'What does a poet who gave a thief his clothes have in common with you?', 'Letting go of what you can’t keep can leave room for what you actually love.'),
      angle('a2', 'no title', 'Why would someone refuse to be called a poet?', 'You can do the thing well without needing the label that comes with it.'),
      angle('a3', 'playing instead', 'What happens when you forget your errands because the game is better?', 'Time spent playing isn’t lost. It can be the part of the day that matters.'),
      angle('a4', 'enough', 'How much do you really need in one small hut?', 'Having less can make what’s left feel like plenty.'),
    ],
    tags: [
      tag('locus_of_control', 'low', 'let things go easily', 'He met being robbed with calm acceptance.'),
      tag('relatedness', 'low', 'content alone in his hut', 'He lived much of his life by himself on a mountain.'),
      tag('playfulness', 'high', 'played with the village kids', 'He forgot to beg for food because he was playing with children.'),
      tag('conflict_cooperativeness', 'high', 'gave the thief his clothes', 'He gave away what little he had to the man who robbed him.'),
      tag('self_efficacy', 'low', 'refused the title of poet', 'He refused any position as a priest, or even the title of poet.'),
    ],
    vetting: 'Hermit poet, died 1831; refused every religious post (not a founder or leader); broadly loved.',
  },
  {
    id: 'lf_hans_christian_andersen',
    name: 'Hans Christian Andersen',
    kind: 'real',
    hall: 'words',
    region: 'europe',
    place: 'Denmark',
    era: '1805–1875',
    died: 1875,
    birthday: { md: '04-02', source: src(wiki('Hans_Christian_Andersen'), '2 April 1805') },
    gender: 'man',
    field: 'Fairy tales',
    essence: 'Wanted to be an actor, then wrote The Ugly Duckling.',
    whoTheyWere: 'A Danish writer of plays, travelogues, novels and poems, best remembered for his fairy tales.',
    famousFor: '“The Little Mermaid”, “The Ugly Duckling” and “The Snow Queen”.',
    facts: [
      fact('f1', 'His 156 fairy tales have been translated into more than 125 languages.', src(wiki('Hans_Christian_Andersen'), '156 stories', 'more than 125 languages')),
      fact('f2', 'His tales include “The Little Mermaid”, “The Ugly Duckling” and “The Snow Queen”.', src(wiki('Hans_Christian_Andersen'), 'The Little Mermaid', 'The Ugly Duckling', 'The Snow Queen')),
      fact('f3', 'His stories have inspired ballets, plays and films.', src(wiki('Hans_Christian_Andersen'), 'inspired ballets, plays, and animated and live-action films')),
    ],
    moments: [
      moment('m1', 'At 14 he moved to Copenhagen hoping to become an actor, and was accepted into the Royal Danish Theatre, but his voice soon changed.', src(wiki('Hans_Christian_Andersen'), 'At 14, Andersen moved to Copenhagen', 'his voice soon changed')),
      moment('m2', 'As a boy he worked as an apprentice to a weaver and then a tailor.', src(wiki('Hans_Christian_Andersen'), 'apprentice to a weaver')),
    ],
    angles: [
      angle('a1', 'the changed voice', 'What does a boy whose acting dream ended with a changed voice have in common with you?', 'When one door closes, the thing you love can find another way out.'),
      angle('a2', 'the ugly duckling', 'Why does a story about not fitting in last two centuries?', 'Feeling out of place now says nothing about where you’ll belong later.'),
      angle('a3', 'a hundred languages', 'How does a story from a small country reach the whole world?', 'Simple, true feelings travel further than you think.'),
      angle('a4', 'from weaver to writer', 'What do odd early jobs give a storyteller?', 'Every job you’ve had is material for something.'),
    ],
    tags: [
      tag('steadiness', 'low', 'felt like the odd one out', 'His tales often follow characters who don’t fit in.'),
      tag('openness', 'high', 'imagined whole worlds', 'He wrote 156 fairy tales full of invention.'),
      tag('self_efficacy', 'high', 'moved to the city at fourteen', 'He went to Copenhagen alone to chase the stage.'),
      tag('growth_mindset', 'high', 'changed course and grew', 'When acting didn’t work out, he found writing.'),
      tag('competence', 'low', 'the acting plan didn’t work', 'He hoped to act, but his voice changed.'),
    ],
    vetting: 'Writer, died 1875; no office; broadly beloved.',
  },
  {
    id: 'lf_murasaki_shikibu',
    name: 'Murasaki Shikibu',
    kind: 'real',
    hall: 'words',
    region: 'east_asia',
    place: 'Japan',
    era: 'c. 973–c. 1014',
    died: 1025,
    gender: 'woman',
    field: 'Novels and poetry',
    essence: 'Wrote one of the world’s first novels a thousand years ago.',
    whoTheyWere: 'A Japanese novelist, poet and lady-in-waiting at the Imperial court in the Heian period.',
    famousFor: 'The Tale of Genji, widely considered one of the world’s first novels.',
    facts: [
      fact('f1', 'She wrote The Tale of Genji, widely considered one of the world’s first novels.', src(wiki('Murasaki_Shikibu'), "one of the world's first novels")),
      fact('f2', 'She was a lady-in-waiting at the Imperial court.', src(wiki('Murasaki_Shikibu'), 'lady-in-waiting at the Imperial court')),
      fact('f3', 'Her personal name is unknown; Murasaki Shikibu is a descriptive name.', src(wiki('Murasaki_Shikibu'), 'personal name is unknown')),
    ],
    moments: [
      moment('m1', 'Heian women were usually kept from learning Chinese, the language of government, but she showed a gift for the Chinese classics in her father’s household.', src(wiki('Murasaki_Shikibu'), 'excluded from learning Chinese', 'aptitude for the Chinese')),
      moment('m2', 'The Tale of Genji was written in Japanese between about 1000 and 1012.', src(wiki('Murasaki_Shikibu'), 'between about 1000 and 1012')),
    ],
    angles: [
      angle('a1', 'learning anyway', 'What does a writer who learned what she wasn’t supposed to have in common with you?', 'Quietly learning the thing you’re told isn’t for you can change everything.'),
      angle('a2', 'the first novel', 'What does it take to write something nobody had a word for yet?', 'You don’t need a category to make something real.'),
      angle('a3', 'the name nobody knows', 'How do you become unforgettable without anyone knowing your name?', 'Your work can matter more than your name on it.'),
      angle('a4', 'watching the court', 'What can you write when you notice everything around you?', 'Paying close attention to people is a kind of superpower.'),
    ],
    tags: [
      tag('extraversion', 'low', 'watched the court quietly', 'Her writing came from close observation of court life.'),
      tag('openness', 'high', 'learned forbidden classics', 'She studied Chinese classics women were kept from.'),
      tag('attachment_avoidance', 'high', 'kept her own name private', 'Even her real name is unknown.'),
      tag('competence', 'high', 'wrote a masterpiece', 'Her novel is still read a thousand years later.'),
      tag('autonomy', 'low', 'served at court', 'She was a lady-in-waiting at the Imperial court.'),
    ],
    vetting: 'Writer, died c. 1014–1025; no office; broadly admired.',
  },
  {
    id: 'lf_jane_austen',
    name: 'Jane Austen',
    kind: 'real',
    hall: 'words',
    region: 'europe',
    place: 'England',
    era: '1775–1817',
    died: 1817,
    birthday: { md: '12-16', source: src(wiki('Jane_Austen'), '16 December 1775') },
    gender: 'woman',
    field: 'Novels',
    essence: 'Published as “A Lady” and became one of the most read novelists ever.',
    whoTheyWere: 'An English writer known for six novels that look sharply at the society around her.',
    famousFor: 'Pride and Prejudice, Sense and Sensibility and Emma.',
    facts: [
      fact('f1', 'She wrote major novels before 22 but was not published until she was 35.', src(wiki('Jane_Austen'), 'not published until she was 35')),
      fact('f2', 'Sense and Sensibility appeared in 1811, described as written “By a Lady”.', src(wiki('Jane_Austen'), 'By a Lady')),
      fact('f3', 'Her novels were published anonymously and did not bring her fame in her lifetime.', src(wiki('Jane_Austen'), 'did not bring her public fame in her lifetime')),
    ],
    moments: [
      moment('m1', 'She kept writing for years before anything was published.', src(wiki('Jane_Austen'), 'major novels before the age of 22')),
      moment('m2', 'She left a novel, later titled Sanditon, unfinished.', src(wiki('Jane_Austen'), 'Sanditon')),
    ],
    angles: [
      angle('a1', 'the drawer of drafts', 'What does a novelist who waited thirteen years to be published have in common with you?', 'Work that waits isn’t wasted. It can be ready when the moment comes.'),
      angle('a2', 'by a lady', 'Why write without your name on it?', 'Doing it for the work, not the credit, can be freeing.'),
      angle('a3', 'the sharp eye', 'What happens when you notice exactly how people act at a party?', 'Seeing people clearly, with a little humour, is a gift.'),
      angle('a4', 'fame later', 'Can your work matter long after you’re gone?', 'You can’t see all of your impact from where you stand.'),
    ],
    tags: [
      tag('playfulness', 'high', 'wrote with sly humour', 'Her novels comment on society with wit.'),
      tag('conflict_assertiveness', 'low', 'published without her name', 'Her novels appeared anonymously.'),
      tag('steadiness', 'high', 'kept writing for years', 'She wrote for over a decade before being published.'),
      tag('openness', 'high', 'saw society clearly', 'Her novels critique the world around her.'),
      tag('self_efficacy', 'low', 'published as “A Lady”', 'Her novels were published anonymously.'),
    ],
    vetting: 'Novelist, died 1817; no office; broadly beloved.',
  },
  {
    id: 'lf_rabindranath_tagore',
    name: 'Rabindranath Tagore',
    kind: 'real',
    hall: 'words',
    region: 'south_asia',
    place: 'India',
    era: '1861–1941',
    died: 1941,
    birthday: { md: '05-07', source: src(wiki('Rabindranath_Tagore'), '7 May 1861') },
    gender: 'man',
    field: 'Poetry and song',
    essence: 'Wrote the national anthems of two countries.',
    whoTheyWere: 'A Bengali poet, author, musician, composer and painter, a leading figure of the Bengal Renaissance.',
    famousFor: 'Gitanjali, and in 1913 becoming the first non-European to win the Nobel Prize in Literature.',
    facts: [
      fact('f1', 'In 1913 he became the first non-European to win the Nobel Prize in Literature.', src(wiki('Rabindranath_Tagore'), 'first non-European to receive a Nobel Prize in Literature')),
      fact('f2', 'He wrote and composed the national anthems of India and Bangladesh.', src(wiki('Rabindranath_Tagore'), 'national anthems of India and Bangladesh')),
      fact('f3', 'He was also a musician, composer and painter.', src(wiki('Rabindranath_Tagore'), 'musician, composer')),
    ],
    moments: [
      moment('m1', 'His collection Gitanjali was called “profoundly sensitive, fresh and beautiful”.', src(wiki('Rabindranath_Tagore'), 'profoundly sensitive, fresh and beautiful')),
      moment('m2', 'He reshaped Bengali literature and music.', src(wiki('Rabindranath_Tagore'), 'reshaped Bengali literature and music')),
    ],
    angles: [
      angle('a1', 'two anthems', 'What does a poet who wrote two countries’ anthems have in common with you?', 'Words you write for yourself can end up belonging to many people.'),
      angle('a2', 'many arts', 'Poet, composer, painter: why do it all?', 'Moving between ways of making keeps each one alive.'),
      angle('a3', 'first from his part of the world', 'What does it mean to be the first from where you’re from?', 'Being first can open the door for everyone behind you.'),
      angle('a4', 'sensitive and fresh', 'Can gentle writing change a whole culture?', 'Quiet, honest work can shift more than loud work.'),
    ],
    tags: [
      tag('openness', 'high', 'poet, composer and painter', 'He worked across many arts.'),
      tag('relatedness', 'high', 'wrote songs for whole nations', 'His songs became national anthems.'),
      tag('steadiness', 'low', 'wrote with deep feeling', 'His poetry was called profoundly sensitive.'),
      tag('locus_of_control', 'high', 'reshaped his culture', 'He set out to renew Bengali literature and music.'),
    ],
    vetting: 'Poet, died 1941; no office; broadly admired.',
  },
  {
    id: 'lf_astrid_lindgren',
    name: 'Astrid Lindgren',
    kind: 'real',
    hall: 'words',
    region: 'europe',
    place: 'Sweden',
    era: '1907–2002',
    died: 2002,
    birthday: { md: '11-14', source: src(wiki('Astrid_Lindgren'), '14 November 1907') },
    gender: 'woman',
    field: 'Children’s books',
    essence: 'Created Pippi Longstocking, the strongest girl in the world.',
    whoTheyWere: 'A Swedish writer of fiction and screenplays, best known for her children’s books.',
    famousFor: 'Pippi Longstocking, Emil of Lönneberga and Ronia the Robber’s Daughter.',
    facts: [
      fact('f1', 'Her series include Pippi Longstocking, Emil of Lönneberga and Karlsson-on-the-Roof.', src(wiki('Astrid_Lindgren'), 'Pippi Longstocking', 'Emil of Lönneberga')),
      fact('f2', 'Pippi Longstocking has been translated into at least 100 languages.', src(wiki('Astrid_Lindgren'), 'at least 100 languages')),
      fact('f3', 'She also wrote the fantasy novels Ronia the Robber’s Daughter and The Brothers Lionheart.', src(wiki('Astrid_Lindgren'), "Ronia the Robber's Daughter", 'The Brothers Lionheart')),
    ],
    moments: [
      moment('m1', 'Many of her books were known for an irreverent attitude towards adult authority.', src(wiki('Astrid_Lindgren'), 'irreverent attitude towards adult authority')),
      moment('m2', 'She worked on the children’s literature editorial board at the publisher Rabén & Sjögren.', src(wiki('Astrid_Lindgren'), 'Rabén & Sjögren')),
    ],
    angles: [
      angle('a1', 'the strongest girl', 'What does the writer behind Pippi have in common with you?', 'A little cheekiness toward the rules can be good for everyone.'),
      angle('a2', 'kids first', 'Why write stories that take children’s side?', 'Taking young people seriously is a kind of respect.'),
      angle('a3', 'one hundred languages', 'How does one wild girl travel the whole world?', 'Characters who are fully themselves are the ones people love.'),
      angle('a4', 'the editor', 'What changes when the writer also picks other people’s books?', 'Helping other people’s work along is part of making your own.'),
    ],
    tags: [
      tag('playfulness', 'high', 'made mischief into stories', 'Her characters are cheeky and full of fun.'),
      tag('agreeableness', 'low', 'teased the grown-ups', 'Her books were irreverent toward adult authority.'),
      tag('autonomy', 'high', 'wrote her own way', 'Her stories broke with how children’s books usually sounded.'),
      tag('openness', 'high', 'from farm tales to fantasy', 'She wrote realistic stories and fantasy novels.'),
    ],
    vetting: 'Writer, died 2002; no office; broadly beloved.',
  },
  {
    id: 'lf_matsuo_basho',
    name: 'Matsuo Bashō',
    kind: 'real',
    hall: 'words',
    region: 'east_asia',
    place: 'Japan',
    era: '1644–1694',
    died: 1694,
    gender: 'man',
    field: 'Poetry',
    essence: 'Named himself after a banana tree and mastered the haiku.',
    whoTheyWere: 'A Japanese poet of the Edo period, recognised as the greatest master of haiku.',
    famousFor: 'His haiku and The Narrow Road to the Deep North.',
    facts: [
      fact('f1', 'He is recognised as the greatest master of haiku.', src(wiki('Matsuo_Bashō'), 'greatest master of haiku')),
      fact('f2', 'His masterwork is The Narrow Road to the Deep North.', src(wiki('Matsuo_Bashō'), 'The Narrow Road to the Deep North')),
      fact('f3', 'Many of his poems are inscribed on monuments and traditional sites.', src(wiki('Matsuo_Bashō'), 'inscribed on monuments')),
    ],
    moments: [
      moment('m1', 'His students built him a rustic hut and planted a banana tree, a bashō, in the yard, which gave him his name.', src(wiki('Matsuo_Bashō'), 'planted a Japanese banana tree', 'giving Bashō a new haigō')),
      moment('m2', 'In 1689 he left Edo on foot with his student Kawai Sora for the trip he described in his masterwork.', src(wiki('Matsuo_Bashō'), 'Kawai Sora')),
    ],
    angles: [
      angle('a1', 'the banana tree', 'What does a poet named after a banana tree have in common with you?', 'Small things you love can become part of you.'),
      angle('a2', 'the long walk', 'Why walk across a country to write?', 'Moving slowly through the world gives you more to notice.'),
      angle('a3', 'seventeen syllables', 'How much can you say in a tiny poem?', 'Saying less, carefully, can say more.'),
      angle('a4', 'the quiet hut', 'What happens when a famous poet steps away from the crowd?', 'Stepping back from the noise can sharpen your work.'),
    ],
    tags: [
      tag('extraversion', 'low', 'stepped back into a hut', 'He moved toward a quieter, more reclusive life.'),
      tag('openness', 'high', 'walked to see the country', 'He made long journeys to write about them.'),
      tag('relatedness', 'low', 'content in his hut', 'He chose a rustic, solitary home.'),
      tag('conscientiousness', 'high', 'refined every word', 'He perfected a very short, exact form.'),
    ],
    vetting: 'Poet, died 1694; no office; broadly admired.',
  },
  {
    id: 'lf_miguel_de_cervantes',
    name: 'Miguel de Cervantes',
    kind: 'real',
    hall: 'words',
    region: 'europe',
    place: 'Spain',
    era: '1547–1616',
    died: 1616,
    gender: 'man',
    field: 'Novels',
    essence: 'Survived captivity and wrote what many call the first modern novel.',
    whoTheyWere: 'A Spanish writer, seen as the greatest writer in the Spanish language.',
    famousFor: 'Don Quixote, considered the first modern novel.',
    facts: [
      fact('f1', 'His two-part novel Don Quixote is considered the first modern novel.', src(wiki('Miguel_de_Cervantes'), 'first modern novel')),
      fact('f2', 'Many authors have called Don Quixote the “best book of all time”.', src(wiki('Miguel_de_Cervantes'), 'best book of all time')),
      fact('f3', 'He lost the use of his left arm and hand after being badly wounded in 1571.', src(wiki('Miguel_de_Cervantes'), 'lost the use of his left arm and hand')),
    ],
    moments: [
      moment('m1', 'In 1575 he was captured at sea and held for ransom in Algiers.', src(wiki('Miguel_de_Cervantes'), 'captured by Barbary pirates', 'held for ransom')),
      moment('m2', 'In 1580 he was set free and returned to Madrid.', src(wiki('Miguel_de_Cervantes'), 'In 1580 Cervantes was set free')),
    ],
    angles: [
      angle('a1', 'after captivity', 'What does a writer who survived five years held for ransom have in common with you?', 'What you live through can become the depth in what you make.'),
      angle('a2', 'the dreamer knight', 'Why does a man who tilts at windmills still make us smile?', 'Holding on to a dream, even a silly one, keeps life interesting.'),
      angle('a3', 'the late masterpiece', 'What can someone write after a hard, full life?', 'Your best work can come after everything else.'),
      angle('a4', 'one good arm', 'How do you keep going after an injury changes things?', 'You can adapt and still do the thing you’re meant to do.'),
    ],
    tags: [
      tag('steadiness', 'high', 'survived years of captivity', 'He endured five years held for ransom.'),
      tag('playfulness', 'high', 'wrote a comic knight', 'Don Quixote is full of humour.'),
      tag('locus_of_control', 'low', 'took fate as it came', 'He lived through capture and hardship he could not control.'),
      tag('growth_mindset', 'high', 'turned hardship into art', 'He wrote his masterpiece after years of struggle.'),
    ],
    vetting: 'Writer, died 1616; served as a soldier, never a commander; broadly admired.',
  },
  {
    id: 'lf_jules_verne',
    name: 'Jules Verne',
    kind: 'real',
    hall: 'words',
    region: 'europe',
    place: 'France',
    era: '1828–1905',
    died: 1905,
    birthday: { md: '02-08', source: src(wiki('Jules_Verne'), '8 February 1828') },
    gender: 'man',
    field: 'Adventure novels',
    essence: 'Went around the world in eighty days without leaving his desk.',
    whoTheyWere: 'A French novelist, poet and playwright whose adventure novels used the science of his day.',
    famousFor: 'Twenty Thousand Leagues Under the Seas and Around the World in Eighty Days.',
    facts: [
      fact('f1', 'He wrote Twenty Thousand Leagues Under the Seas and Around the World in Eighty Days.', src(wiki('Jules_Verne'), 'Twenty Thousand Leagues Under the Seas', 'Around the World in Eighty Days')),
      fact('f2', 'He has been the second most-translated author in the world since 1979.', src(wiki('Jules_Verne'), 'second most-translated author in the world')),
      fact('f3', 'He has sometimes been called the “father of science fiction”.', src(wiki('Jules_Verne'), 'father of s')),
    ],
    moments: [
      moment('m1', 'His publisher announced that his books would form a series, the Extraordinary Voyages.', src(wiki('Jules_Verne'), 'Extraordinary Voyages')),
      moment('m2', 'His novels used the scientific knowledge of his time to imagine what might come next.', src(wiki('Jules_Verne'), 'contemporary scientific knowledge')),
    ],
    angles: [
      angle('a1', 'travel by imagination', 'What does a writer who sent readers under the sea have in common with you?', 'You can explore a lot from your own chair, if you’re curious enough.'),
      angle('a2', 'science as a story', 'Why turn facts into adventures?', 'Making something exciting is a great way to make it stick.'),
      angle('a3', 'the series', 'What happens when your books become one big voyage?', 'Seeing your work as one long project can give it shape.'),
      angle('a4', 'read everywhere', 'How do adventure stories end up translated into so many languages?', 'Wonder is something almost everyone shares.'),
    ],
    tags: [
      tag('openness', 'high', 'imagined trips to the moon', 'His novels imagined journeys nobody had made.'),
      tag('extraversion', 'low', 'explored from his desk', 'His adventures happened on the page.'),
      tag('conscientiousness', 'high', 'researched the science', 'He built his stories on the science of his day.'),
      tag('playfulness', 'high', 'made science an adventure', 'His books turned facts into thrilling stories.'),
      tag('self_efficacy', 'low', 'travelled from his desk', 'He went around the world in his books, not in person.'),
    ],
    vetting: 'Novelist, died 1905; no office; broadly admired.',
  },
  {
    id: 'lf_emily_dickinson',
    name: 'Emily Dickinson',
    kind: 'real',
    hall: 'words',
    region: 'americas',
    place: 'United States',
    era: '1830–1886',
    died: 1886,
    birthday: { md: '12-10', source: src(wiki('Emily_Dickinson'), 'December 10, 1830') },
    gender: 'woman',
    field: 'Poetry',
    essence: 'Wrote nearly 1,800 poems and published only ten.',
    whoTheyWere: 'An American poet from Amherst, Massachusetts, largely unpublished and unknown in her lifetime.',
    famousFor: 'Poems with short lines and slant rhyme, now seen as groundbreaking.',
    facts: [
      fact('f1', 'Only 10 of her nearly 1,800 poems were published during her lifetime.', src(wiki('Emily_Dickinson'), 'only 10 of her nearly 1,800 poems were published')),
      fact('f2', 'Her poems are now widely regarded as groundbreaking.', src(wiki('Emily_Dickinson'), 'widely regarded as groundbreaking')),
      fact('f3', 'She was born in Amherst, Massachusetts, and returned there after her studies.', src(wiki('Emily_Dickinson'), 'born in Amherst, Massachusetts')),
    ],
    moments: [
      moment('m1', 'She kept writing hundreds of poems that almost nobody read while she was alive.', src(wiki('Emily_Dickinson'), 'Largely unpublished and unknown during her lifetime')),
      moment('m2', 'She studied at the Amherst Academy for seven years before going home.', src(wiki('Emily_Dickinson'), 'Amherst Academy for seven years')),
    ],
    angles: [
      angle('a1', 'the private drawer', 'What does a poet who kept almost all her poems to herself have in common with you?', 'What you make for yourself still counts.'),
      angle('a2', 'short lines', 'Why write poems that break the rules on purpose?', 'Doing it your own way can be exactly what makes it last.'),
      angle('a3', 'home', 'Can a whole world fit in one house?', 'A small, familiar place can be enough to think big.'),
      angle('a4', 'found later', 'What happens to work that nobody sees yet?', 'Being unseen now doesn’t decide what your work means later.'),
    ],
    tags: [
      tag('attachment_avoidance', 'high', 'kept her poems private', 'Almost none of her poems were published in her life.'),
      tag('extraversion', 'low', 'wrote quietly at home', 'She spent most of her life in her family home.'),
      tag('openness', 'low', 'stayed close to home', 'She lived nearly all her life in Amherst.'),
      tag('autonomy', 'high', 'broke the rules of verse', 'Her style went against the conventions of her day.'),
      tag('self_efficacy', 'low', 'published only ten poems', 'She wrote nearly 1,800 poems and published only ten.'),
    ],
    vetting: 'Poet, died 1886; no office; broadly admired.',
  },
];
