/**
 * GENERATED by `npm run load:daily-line` from docs/daily-line-review.md.
 * Do not edit by hand: tick lines in the review file and run the loader.
 *
 * Empty until emci has picked winners; bank.ts falls back to its first-draft
 * lines while this is empty.
 */
export interface LoadedLine {
  /** 'starter', 'openness:high', or 'openness:high+autonomy:high'. */
  tag: string;
  text: string;
}

export const LOADED_LINES: readonly LoadedLine[] = [];
