/**
 * AUTO-GENERATED by scripts/play-art-pack.ts — do not edit by hand.
 *
 * One entry per packed clip sheet: the sheet's pixel size and the crop rect of
 * every frame inside it, keyed by the same '<direction>/frame_NNN' tail the
 * old per-frame registry used.
 */
import type { ImageSourcePropType } from 'react-native';

export type SheetFrameRect = { x: number; y: number; w: number; h: number };

export type PlaySheet = {
  sheet: string;
  sheetW: number;
  sheetH: number;
  frames: Record<string, SheetFrameRect>;
};

/** Frame rects per clip sheet. */
export const PLAY_SHEETS: Record<string, PlaySheet> = {
  "sheets/cast/heroes/archangel/Angelic_Flinch": {
    "sheet": "sheets/cast/heroes/archangel/Angelic_Flinch.png",
    "sheetW": 1160,
    "sheetH": 257,
    "frames": {
      "east/frame_000": {
        "x": 0,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_001": {
        "x": 129,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_002": {
        "x": 258,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_003": {
        "x": 387,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_004": {
        "x": 516,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_005": {
        "x": 645,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_006": {
        "x": 774,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_007": {
        "x": 903,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_008": {
        "x": 1032,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "west/frame_000": {
        "x": 0,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_001": {
        "x": 129,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_002": {
        "x": 258,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_003": {
        "x": 387,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_004": {
        "x": 516,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_005": {
        "x": 645,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_006": {
        "x": 774,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_007": {
        "x": 903,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_008": {
        "x": 1032,
        "y": 129,
        "w": 128,
        "h": 128
      }
    }
  },
  "sheets/cast/heroes/archangel/Attack_01_Seraph_Strike": {
    "sheet": "sheets/cast/heroes/archangel/Attack_01_Seraph_Strike.png",
    "sheetW": 1418,
    "sheetH": 257,
    "frames": {
      "east/frame_000": {
        "x": 0,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_001": {
        "x": 129,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_002": {
        "x": 258,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_003": {
        "x": 387,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_004": {
        "x": 516,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_005": {
        "x": 645,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_006": {
        "x": 774,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_007": {
        "x": 903,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_008": {
        "x": 1032,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_009": {
        "x": 1161,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_010": {
        "x": 1290,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "west/frame_000": {
        "x": 0,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_001": {
        "x": 129,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_002": {
        "x": 258,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_003": {
        "x": 387,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_004": {
        "x": 516,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_005": {
        "x": 645,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_006": {
        "x": 774,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_007": {
        "x": 903,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_008": {
        "x": 1032,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_009": {
        "x": 1161,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_010": {
        "x": 1290,
        "y": 129,
        "w": 128,
        "h": 128
      }
    }
  },
  "sheets/cast/heroes/archangel/Celestial_Drift": {
    "sheet": "sheets/cast/heroes/archangel/Celestial_Drift.png",
    "sheetW": 1418,
    "sheetH": 257,
    "frames": {
      "east/frame_000": {
        "x": 0,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_001": {
        "x": 129,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_002": {
        "x": 258,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_003": {
        "x": 387,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_004": {
        "x": 516,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_005": {
        "x": 645,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_006": {
        "x": 774,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_007": {
        "x": 903,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_008": {
        "x": 1032,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_009": {
        "x": 1161,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_010": {
        "x": 1290,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "west/frame_000": {
        "x": 0,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_001": {
        "x": 129,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_002": {
        "x": 258,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_003": {
        "x": 387,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_004": {
        "x": 516,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_005": {
        "x": 645,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_006": {
        "x": 774,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_007": {
        "x": 903,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_008": {
        "x": 1032,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_009": {
        "x": 1161,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_010": {
        "x": 1290,
        "y": 129,
        "w": 128,
        "h": 128
      }
    }
  },
  "sheets/cast/heroes/archangel/Celestial_Rush": {
    "sheet": "sheets/cast/heroes/archangel/Celestial_Rush.png",
    "sheetW": 1418,
    "sheetH": 257,
    "frames": {
      "east/frame_000": {
        "x": 0,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_001": {
        "x": 129,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_002": {
        "x": 258,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_003": {
        "x": 387,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_004": {
        "x": 516,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_005": {
        "x": 645,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_006": {
        "x": 774,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_007": {
        "x": 903,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_008": {
        "x": 1032,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_009": {
        "x": 1161,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_010": {
        "x": 1290,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "west/frame_000": {
        "x": 0,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_001": {
        "x": 129,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_002": {
        "x": 258,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_003": {
        "x": 387,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_004": {
        "x": 516,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_005": {
        "x": 645,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_006": {
        "x": 774,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_007": {
        "x": 903,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_008": {
        "x": 1032,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_009": {
        "x": 1161,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_010": {
        "x": 1290,
        "y": 129,
        "w": 128,
        "h": 128
      }
    }
  },
  "sheets/cast/heroes/archangel/Divine_Flight": {
    "sheet": "sheets/cast/heroes/archangel/Divine_Flight.png",
    "sheetW": 1547,
    "sheetH": 257,
    "frames": {
      "east/frame_000": {
        "x": 0,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_001": {
        "x": 129,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_002": {
        "x": 258,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_003": {
        "x": 387,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_004": {
        "x": 516,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_005": {
        "x": 645,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_006": {
        "x": 774,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_007": {
        "x": 903,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_008": {
        "x": 1032,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_009": {
        "x": 1161,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_010": {
        "x": 1290,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_011": {
        "x": 1419,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "west/frame_000": {
        "x": 0,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_001": {
        "x": 129,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_002": {
        "x": 258,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_003": {
        "x": 387,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_004": {
        "x": 516,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_005": {
        "x": 645,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_006": {
        "x": 774,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_007": {
        "x": 903,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_008": {
        "x": 1032,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_009": {
        "x": 1161,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_010": {
        "x": 1290,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_011": {
        "x": 1419,
        "y": 129,
        "w": 128,
        "h": 128
      }
    }
  },
  "sheets/cast/heroes/archangel/Hover_Idle": {
    "sheet": "sheets/cast/heroes/archangel/Hover_Idle.png",
    "sheetW": 1418,
    "sheetH": 257,
    "frames": {
      "east/frame_000": {
        "x": 0,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_001": {
        "x": 129,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_002": {
        "x": 258,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_003": {
        "x": 387,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_004": {
        "x": 516,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_005": {
        "x": 645,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_006": {
        "x": 774,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_007": {
        "x": 903,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_008": {
        "x": 1032,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_009": {
        "x": 1161,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_010": {
        "x": 1290,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "west/frame_000": {
        "x": 0,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_001": {
        "x": 129,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_002": {
        "x": 258,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_003": {
        "x": 387,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_004": {
        "x": 516,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_005": {
        "x": 645,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_006": {
        "x": 774,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_007": {
        "x": 903,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_008": {
        "x": 1032,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_009": {
        "x": 1161,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_010": {
        "x": 1290,
        "y": 129,
        "w": 128,
        "h": 128
      }
    }
  },
  "sheets/cast/heroes/archangel/Ultimate_Final_Judgment": {
    "sheet": "sheets/cast/heroes/archangel/Ultimate_Final_Judgment.png",
    "sheetW": 2192,
    "sheetH": 257,
    "frames": {
      "east/frame_000": {
        "x": 0,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_001": {
        "x": 129,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_002": {
        "x": 258,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_003": {
        "x": 387,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_004": {
        "x": 516,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_005": {
        "x": 645,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_006": {
        "x": 774,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_007": {
        "x": 903,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_008": {
        "x": 1032,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_009": {
        "x": 1161,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_010": {
        "x": 1290,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_011": {
        "x": 1419,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_012": {
        "x": 1548,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_013": {
        "x": 1677,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_014": {
        "x": 1806,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_015": {
        "x": 1935,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east/frame_016": {
        "x": 2064,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "west/frame_000": {
        "x": 0,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_001": {
        "x": 129,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_002": {
        "x": 258,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_003": {
        "x": 387,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_004": {
        "x": 516,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_005": {
        "x": 645,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_006": {
        "x": 774,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_007": {
        "x": 903,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_008": {
        "x": 1032,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_009": {
        "x": 1161,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_010": {
        "x": 1290,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_011": {
        "x": 1419,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_012": {
        "x": 1548,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_013": {
        "x": 1677,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_014": {
        "x": 1806,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_015": {
        "x": 1935,
        "y": 129,
        "w": 128,
        "h": 128
      },
      "west/frame_016": {
        "x": 2064,
        "y": 129,
        "w": 128,
        "h": 128
      }
    }
  },
  "sheets/cast/heroes/archangel/rotations": {
    "sheet": "sheets/cast/heroes/archangel/rotations.png",
    "sheetW": 1031,
    "sheetH": 128,
    "frames": {
      "north": {
        "x": 0,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "north-east": {
        "x": 129,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "east": {
        "x": 258,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "south-east": {
        "x": 387,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "south": {
        "x": 516,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "south-west": {
        "x": 645,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "west": {
        "x": 774,
        "y": 0,
        "w": 128,
        "h": 128
      },
      "north-west": {
        "x": 903,
        "y": 0,
        "w": 128,
        "h": 128
      }
    }
  }
} as const;

/** Bundled sheet images (spike). Replaced by cached remote URIs when the art
 * moves to storage — every other module reads sheets through `playSheetArt`. */
export const PLAY_SHEET_ART: Record<string, ImageSourcePropType> = {
  'sheets/cast/heroes/archangel/Angelic_Flinch': require('@/assets/play/sheets/cast/heroes/archangel/Angelic_Flinch.png'),
  'sheets/cast/heroes/archangel/Attack_01_Seraph_Strike': require('@/assets/play/sheets/cast/heroes/archangel/Attack_01_Seraph_Strike.png'),
  'sheets/cast/heroes/archangel/Celestial_Drift': require('@/assets/play/sheets/cast/heroes/archangel/Celestial_Drift.png'),
  'sheets/cast/heroes/archangel/Celestial_Rush': require('@/assets/play/sheets/cast/heroes/archangel/Celestial_Rush.png'),
  'sheets/cast/heroes/archangel/Divine_Flight': require('@/assets/play/sheets/cast/heroes/archangel/Divine_Flight.png'),
  'sheets/cast/heroes/archangel/Hover_Idle': require('@/assets/play/sheets/cast/heroes/archangel/Hover_Idle.png'),
  'sheets/cast/heroes/archangel/Ultimate_Final_Judgment': require('@/assets/play/sheets/cast/heroes/archangel/Ultimate_Final_Judgment.png'),
  'sheets/cast/heroes/archangel/rotations': require('@/assets/play/sheets/cast/heroes/archangel/rotations.png'),
};
