import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { Icon, Label, NativeTabs, VectorIcon } from 'expo-router/unstable-native-tabs';

import { useCircleContext } from '@/lib/circle-context';
import { useTheme } from '@/hooks/use-theme';

// Purpose-made silhouette of the pixel character: squircle body outline + two
// dot-eye cutouts, alpha-only (no baked color). Generated by
// scripts/gen-sage-icon.ts. Native tabs template-tint any image source, so
// this reads as "the character" in outline, tinted like the other tabs.
const SAGE_MASK_ICON = require('@/assets/kenney/shape/tab/sage-mask.png');

export default function AppTabs() {
  const colors = useTheme();
  const { hasCircle } = useCircleContext();

  // Keying the navigator by hasCircle forces a clean, atomic remount when the
  // Circle tab appears/disappears. Toggling the trigger's `hidden` prop alone
  // is documented-unsupported at runtime: it remounts the navigator but the
  // tap handler can read a stale descriptor mid-remount, leaving the tab
  // visible-but-dead (the re-add bug). A `key` remount re-registers routes in
  // one commit, so a tap always finds a live route.
  return (
    <NativeTabs
      key={hasCircle ? 'circle-on' : 'circle-off'}
      backgroundColor={colors.background}
      indicatorColor={colors.backgroundElement}
      disableTransparentOnScrollEdge
      blurEffect="none"
      minimizeBehavior="never"
      shadowColor="transparent"
      tintColor={colors.text}
      iconColor={{ default: colors.textSecondary, selected: colors.text }}
      labelStyle={{
        default: { color: colors.textSecondary },
        selected: { color: colors.text },
      }}>
      <NativeTabs.Trigger name="index">
        <Label>Home</Label>
        <Icon src={<VectorIcon family={MaterialCommunityIcons} name="home" />} />
      </NativeTabs.Trigger>

      {/* Sage uses the character silhouette mask (template-tinted like the
          other tabs). The live pixel face is the nav companion, not the tab. */}
      <NativeTabs.Trigger name="sage">
        <Label>Sage</Label>
        <Icon src={SAGE_MASK_ICON} />
      </NativeTabs.Trigger>

      <NativeTabs.Trigger name="around">
        <Label>Around</Label>
        <Icon src={<VectorIcon family={MaterialCommunityIcons} name="map-marker-radius-outline" />} />
      </NativeTabs.Trigger>

      {/* Circle does not exist until a scan. The Trigger stays statically in
          the layout (expo-router rejects dynamically added/removed triggers);
          `hidden` excludes the route from the navigator until a connection
          exists — functionally "not present, not hidden-in-the-bar". The
          navigator's key above makes each flip a clean remount. */}
      <NativeTabs.Trigger name="circle" hidden={!hasCircle}>
        <Label>Circle</Label>
        <Icon src={<VectorIcon family={MaterialCommunityIcons} name="account-group" />} />
      </NativeTabs.Trigger>

      <NativeTabs.Trigger name="you">
        <Label>You</Label>
        <Icon src={<VectorIcon family={MaterialCommunityIcons} name="account" />} />
      </NativeTabs.Trigger>
    </NativeTabs>
  );
}
