/**
 * Load emci's picked daily lines into the app.
 * Run: npm run load:daily-line            (ticked lines only)
 *      npm run load:daily-line -- --all   (every line in the review file)
 *      npm run load:daily-line -- --dry-run
 *
 * Same shape as the intake questions: the lines become a fixed list that ships
 * in the app (`src/lib/daily-line/lines.generated.ts`, like QUESTIONS_BANK),
 * and the same rows as shared `authored` rows in the database pool
 * (`supabase/seeds/daily_line_authored.sql`, like wave49's insert).
 *
 * It refuses, and writes nothing, when:
 * - a picked line breaks a rule (too long, "you are", advice, framework word);
 * - a heading is not a trait lean this app knows;
 * - any single trait lean has fewer than MIN_PER_LEAN picked lines, or there
 *   are fewer than MIN_STARTERS starters. A thin bank repeats.
 *
 * Offline. No sign-in, no model call, no database call.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';

import { lineRuleViolation, parseLeanTag, STARTER_TAG } from '../src/lib/daily-line/bank';
import { TRAIT_AXES } from '../src/lib/traits';

const ROOT = path.resolve(__dirname, '..');
export const REVIEW_FILE = 'docs/daily-line-review.md';
const OUT_TS = 'src/lib/daily-line/lines.generated.ts';
const OUT_SQL = 'supabase/seeds/daily_line_authored.sql';

export const MIN_PER_LEAN = 4;
export const MIN_STARTERS = 8;

export interface ReviewLine {
  tag: string;
  text: string;
  ticked: boolean;
}

/** Every candidate in the review file, in order. A line before any heading is ignored. */
export function parseReviewFile(markdown: string): ReviewLine[] {
  return readReviewFile(markdown).lines;
}

/**
 * The candidates, plus every row that LOOKS like a heading or a tick line but
 * could not be read. Those are reported rather than skipped: a tick that is
 * silently ignored is a line emci picked and never got.
 */
export function readReviewFile(markdown: string): { lines: ReviewLine[]; unreadable: string[] } {
  const lines: ReviewLine[] = [];
  const unreadable: string[] = [];
  let tag: string | null = null;
  for (const raw of markdown.split(/\r?\n/)) {
    if (/^###\s/.test(raw)) {
      const heading = /^###\s+`([^`]+)`\s*$/.exec(raw);
      tag = heading ? heading[1]!.trim() : null;
      if (!heading) unreadable.push(raw);
      continue;
    }
    if (/^##\s/.test(raw)) {
      tag = null;
      continue;
    }
    if (!/^\s*[-*]\s*\[/.test(raw)) continue;
    const item = /^- \[( |x|X)\]\s+(.+?)\s*$/.exec(raw);
    if (item && tag) lines.push({ tag, text: item[2]!, ticked: item[1] !== ' ' });
    else unreadable.push(raw);
  }
  return { lines, unreadable };
}

export interface LoadPlan {
  picked: ReviewLine[];
  problems: string[];
}

export function planLoad(lines: readonly ReviewLine[], takeAll: boolean): LoadPlan {
  const picked = lines.filter((line) => takeAll || line.ticked);
  const problems: string[] = [];
  const seen = new Set<string>();
  for (const line of picked) {
    if (!parseLeanTag(line.tag)) problems.push(`unknown heading \`${line.tag}\`: ${line.text}`);
    const violation = lineRuleViolation(line.text);
    if (violation) problems.push(`${violation}: ${line.text}`);
    if (seen.has(line.text)) problems.push(`picked twice: ${line.text}`);
    seen.add(line.text);
  }
  for (const axis of TRAIT_AXES) {
    for (const lean of ['high', 'low'] as const) {
      const tag = `${axis}:${lean}`;
      const count = picked.filter((line) => line.tag === tag).length;
      if (count < MIN_PER_LEAN) problems.push(`\`${tag}\` has ${count} picked, needs ${MIN_PER_LEAN}`);
    }
  }
  const starters = picked.filter((line) => line.tag === STARTER_TAG).length;
  if (starters < MIN_STARTERS) problems.push(`\`${STARTER_TAG}\` has ${starters} picked, needs ${MIN_STARTERS}`);
  return { picked, problems };
}

function tsFile(picked: readonly ReviewLine[]): string {
  const rows = picked.map((line) => `  { tag: ${JSON.stringify(line.tag)}, text: ${JSON.stringify(line.text)} },`).join('\n');
  return `/**
 * GENERATED by \`npm run load:daily-line\` from docs/daily-line-review.md.
 * Do not edit by hand: tick lines in the review file and run the loader.
 *
 * ${picked.length} lines emci picked. While this list is non-empty it IS the
 * written bank; bank.ts's first-draft lines are not used.
 */
export interface LoadedLine {
  /** 'starter', 'openness:high', or 'openness:high+autonomy:high'. */
  tag: string;
  text: string;
}

export const LOADED_LINES: readonly LoadedLine[] = [
${rows}
];
`;
}

function sqlFile(picked: readonly ReviewLine[]): string {
  const quote = (value: string) => `'${value.replace(/'/g, "''")}'`;
  const rows = picked.map((line) => `  (${quote(line.tag)}, ${quote(line.text)}, 'authored')`).join(',\n');
  return `-- GENERATED by \`npm run load:daily-line\`. The same ${picked.length} lines that ship in
-- src/lib/daily-line/lines.generated.ts, as shared 'authored' rows (wave77).
-- Safe to run again: a line already in the pool is skipped.
insert into public.daily_line_pool (lean_key, line, source) values
${rows}
on conflict (line) where source = 'authored' do nothing;
`;
}

function main() {
  const takeAll = process.argv.includes('--all');
  const dryRun = process.argv.includes('--dry-run');
  const { lines, unreadable } = readReviewFile(readFileSync(path.join(ROOT, REVIEW_FILE), 'utf8'));
  const { picked, problems } = planLoad(lines, takeAll);
  for (const row of unreadable) problems.push(`could not read this row (check the heading or the tick box): ${row.trim()}`);
  console.log(`${lines.length} candidates in ${REVIEW_FILE}, ${picked.length} ${takeAll ? 'taken (--all)' : 'ticked'}.`);
  if (problems.length > 0) {
    console.log(`\nNot loaded. ${problems.length} thing(s) to fix:`);
    for (const problem of problems) console.log(`  - ${problem}`);
    process.exit(1);
  }
  if (dryRun) {
    console.log('Dry run: everything checks out, nothing written.');
    return;
  }
  writeFileSync(path.join(ROOT, OUT_TS), tsFile(picked), 'utf8');
  mkdirSync(path.dirname(path.join(ROOT, OUT_SQL)), { recursive: true });
  writeFileSync(path.join(ROOT, OUT_SQL), sqlFile(picked), 'utf8');
  console.log(`Loaded ${picked.length} lines.\n  app:      ${OUT_TS}\n  database: ${OUT_SQL} (run it once so the pool has the same rows)`);
}

if (require.main === module) main();
