/**
 * Builds wave84 (moment-voice question wording, 2026-10-05) from the code, so
 * the server's copy is generated, never hand-transcribed.
 * Run: npx tsx ./scripts/gen-wave84-rows.ts > supabase/migrations/wave84_question_voice.sql
 *
 * 1. intake_questions: one row per CURRENT intake question. A reworded prompt
 *    is a new row; the old row stays, so an old bundle that still sends the
 *    old wording is answered exactly as before (answer_intake_question matches
 *    the prompt text exactly and reads the value by option position, which the
 *    rewrite never moves). A prompt that kept its words gets its new option
 *    labels; values are identical.
 * 2. question_bank_pool: the 70 authored rows seeded from this bank (wave49 /
 *    wave78) get the new wording in place. Same id, same trait, same values in
 *    the same order; question_items (people's own copies of served rounds) are
 *    never touched, and no answer is changed.
 */
import { QUESTIONS_BANK, ROUND_ONLY_BANK } from '../src/lib/questions/bank';
import { QUESTIONS_BANK_V1, ROUND_ONLY_BANK_V1 } from '../src/lib/questions/bank-v1';
import type { QuestionDraft } from '../src/lib/questions/types';

import { intakeRowsOf, wave79IntakeRowSql } from './gen-wave79-intake';

function sqlText(text: string): string {
  return `'${text.replace(/'/g, "''")}'`;
}

function optionsJson(draft: QuestionDraft): string {
  return JSON.stringify(draft.options.map((opt) => ({ text: opt.text, value: opt.value })));
}

export function wave84IntakeRows(): { draft: QuestionDraft; setNo: number }[] {
  return intakeRowsOf(QUESTIONS_BANK);
}

/** [old row, new row] for every authored pool row this bank seeded. */
export function wave84PoolPairs(): [QuestionDraft, QuestionDraft][] {
  const out: [QuestionDraft, QuestionDraft][] = [];
  QUESTIONS_BANK_V1.forEach((row, i) => out.push([row, QUESTIONS_BANK[i]!]));
  ROUND_ONLY_BANK_V1.forEach((row, i) => out.push([row, ROUND_ONLY_BANK[i]!]));
  return out;
}

export function wave84Sql(): string {
  const intake = wave84IntakeRows().map(wave79IntakeRowSql).join(',\n');
  const pool = wave84PoolPairs()
    .map(([before, after]) => `  (${sqlText(before.prompt)}, ${sqlText(after.prompt)}, ${sqlText(optionsJson(after))})`)
    .join(',\n');
  return `-- wave84: moment-voice wording for the question bank (emci 2026-10-05).
-- GENERATED by scripts/gen-wave84-rows.ts from src/lib/questions/bank.ts — do not hand-edit.
-- Pinned by check:question-voice.
--
-- Wording only. Every row keeps its trait, set, option order and option values,
-- so scoring cannot move. The old intake wording stays in intake_questions so a
-- phone still on an older bundle is never told "unknown question". No answer,
-- trait value or served round copy (question_items) is touched.

-- 1. intake_questions: add the new wording; refresh option labels on unchanged prompts.
insert into public.intake_questions (prompt, axis, set_no, options) values
${intake}
on conflict (prompt) do update
  set options = excluded.options
  where intake_questions.axis = excluded.axis
    and intake_questions.set_no = excluded.set_no
    and (select array_agg((o->>'value')::numeric order by i) from jsonb_array_elements(intake_questions.options) with ordinality as t(o, i))
      = (select array_agg((o->>'value')::numeric order by i) from jsonb_array_elements(excluded.options) with ordinality as t(o, i));

-- 2. question_bank_pool: reword the authored rows in place (same id, same values).
create temporary table wave84_pool (old_prompt text, new_prompt text, new_options jsonb);
insert into wave84_pool (old_prompt, new_prompt, new_options) values
${pool};

do $$
declare
  bad int;
begin
  -- Refuse the whole migration if any reworded row would change a value or the option count.
  select count(*) into bad
  from public.question_bank_pool p
  join wave84_pool w on w.old_prompt = p.prompt
  where p.source = 'authored'
    and (select array_agg((o->>'value')::numeric order by i) from jsonb_array_elements(p.options) with ordinality as t(o, i))
      is distinct from (select array_agg((o->>'value')::numeric order by i) from jsonb_array_elements(w.new_options) with ordinality as t(o, i));
  if bad > 0 then
    raise exception 'wave84: % pool rows would change a value', bad;
  end if;
end;
$$;

update public.question_bank_pool p
set prompt = w.new_prompt,
    options = w.new_options
from wave84_pool w
where p.prompt = w.old_prompt
  and p.source = 'authored'
  and (p.prompt <> w.new_prompt or p.options <> w.new_options)
  and (w.new_prompt = w.old_prompt
       or not exists (select 1 from public.question_bank_pool q where q.prompt = w.new_prompt));

drop table wave84_pool;
`;
}

if (require.main === module) {
  process.stdout.write(wave84Sql());
}
