/**
 * Writes docs/team-names-review.md from src/lib/ai-library/teams.ts: every
 * phrase + icon per trait side, the category endings, and every team name.
 * Run: npx tsx scripts/gen-team-names-review.ts
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { allDiveBuckets } from '../src/lib/ai-library/deep-dive';
import { TEAM_ENDINGS, TEAM_SIDES, teamForBucket } from '../src/lib/ai-library/teams';
import { AXIS_POLE_NAME } from '../src/lib/axis-poles';
import { CATEGORY_DEFS } from '../src/lib/categories';
import { CATEGORY_DISPLAY_NAMES } from '../src/lib/category-labels';
import type { TraitAxis } from '../src/lib/traits';

const lines: string[] = [
  '# Deep-dive team names — review (emci)',
  '',
  'Draft. `TEAM_COPY_REVIEWED = false` in `src/lib/ai-library/teams.ts`. Generated by',
  '`scripts/gen-team-names-review.ts`; edit the phrases in teams.ts, then re-run.',
  '',
  'Each trait side gives one phrase + one icon (the same in every category); each',
  'category adds its own ending. "How You Love" has no team on purpose.',
  '',
  '## Phrases and icons',
  '',
  '| Trait | Leans high | Middle | Leans low |',
  '|---|---|---|---|',
];
for (const [axis, sides] of Object.entries(TEAM_SIDES)) {
  const a = axis as TraitAxis;
  lines.push(
    `| ${AXIS_POLE_NAME[a].high} / ${AXIS_POLE_NAME[a].low} | ${sides!.h.phrase} \`${sides!.h.icon}\` | ${sides!.m.phrase} \`${sides!.m.icon}\` | ${sides!.l.phrase} \`${sides!.l.icon}\` |`,
  );
}
lines.push('', '## Endings', '');
for (const def of CATEGORY_DEFS) {
  lines.push(`- ${CATEGORY_DISPLAY_NAMES[def.id] ?? def.name}: ${TEAM_ENDINGS[def.id] ?? '(no team)'}`);
}
lines.push('', '## Every team', '');
for (const def of CATEGORY_DEFS) {
  if (!TEAM_ENDINGS[def.id]) continue;
  lines.push(`### ${CATEGORY_DISPLAY_NAMES[def.id] ?? def.name}`, '');
  for (const bucket of allDiveBuckets(def.id)) {
    const team = teamForBucket(bucket);
    if (team) lines.push(`- ${team.name} — ${team.why.map((w) => w.line.replace('you lean ', '').replace('you’re in the middle', 'middle')).join(', ')}`);
  }
  lines.push('');
}
writeFileSync(resolve(__dirname, '../docs/team-names-review.md'), lines.join('\n'));
console.log('wrote docs/team-names-review.md');
