/**
 * Builds supabase/functions/_shared/ai-library.bundle.js from
 * src/lib/ai-library/server.ts (wave93): the server writes and checks shared
 * library cards with exactly the app's prompt and check code.
 *
 * Run: npm run gen:ai-library   (then deploy the ai-library Edge Function)
 * check:ai-library rebuilds it in memory and fails when the committed file differs.
 *
 * esbuild comes with tsx (a devDependency), so this adds no dependency.
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(__dirname, '..');
export const BUNDLE_PATH = resolve(root, 'supabase/functions/_shared/ai-library.bundle.js');

export async function buildAiLibraryBundle(): Promise<string> {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const esbuild = require('esbuild') as typeof import('esbuild');
  const out = await esbuild.build({
    entryPoints: [resolve(root, 'src/lib/ai-library/server.ts')],
    bundle: true,
    write: false,
    format: 'esm',
    platform: 'neutral',
    target: 'es2022',
    alias: { '@': resolve(root, 'src') },
    resolveExtensions: ['.ts', '.tsx', '.js', '.json'],
    mainFields: ['module', 'main'],
    legalComments: 'none',
    logLevel: 'silent',
  });
  const body = out.outputFiles[0]!.text.replace(/\r\n/g, '\n');
  return `// GENERATED by scripts/gen-ai-library-bundle.ts from src/lib/ai-library/server.ts. Do not edit.\n// deno-lint-ignore-file\n${body}`;
}

if (require.main === module) {
  void buildAiLibraryBundle().then((text) => {
    writeFileSync(BUNDLE_PATH, text);
    console.log(`wrote ${BUNDLE_PATH} (${Math.round(text.length / 1024)} KB)`);
  });
}
