/**
 * Writes docs/legend-figures-review.md from the roster (the same way the
 * insight bank has a review doc): one checkbox per legend with every word the
 * app can show, each fact's source, the trait tags, and the AI prompt.
 *
 *   npx tsx scripts/gen-legend-figures-review.ts
 *
 * Re-run after any roster edit; check:legend-roster fails if a legend is
 * missing from the doc.
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { AXIS_POLE_NAME } from '../src/lib/axis-poles';
import { LEGEND_ROSTER } from '../src/lib/legend-figures/roster';
import { buildLegendPrompt, legendPairs } from '../src/lib/legend-figures/story';
import { HALL_LABEL, LEGEND_HALLS } from '../src/lib/legend-figures/types';

const lines: string[] = [];
const push = (...rows: string[]) => lines.push(...rows);

push(
  '# Legends museum — review (LEGEND_FIGURES_COPY_REVIEWED = false)',
  '',
  'Generated by `scripts/gen-legend-figures-review.ts` from `src/lib/legend-figures/roster/`. Do not edit by hand — edit the roster and re-run.',
  '',
  '**How to review:** tick each legend once you are happy with every line under it (label, facts, moments, angles, trait tags). Tell me anything to change. When every box is ticked, `LEGEND_FIGURES_COPY_REVIEWED` flips to `true`. The app shows no draft badge either way.',
  '',
  '**How facts were checked (2026-10-08):** every fact, moment and birthday cites an English Wikipedia page, and each one names exact phrases that were found in that page’s text by `scripts/legend-roster-verify.ts` (all 183 phrases found). That proves the source says it, not that every nuance is perfect, so a human read is still the bar. Anything that could not be confirmed would be marked **UNVERIFIED** below; it is never shown in the app or sent to the AI. (None in this pilot.)',
  '',
  '**Rules every legend follows:** real people died 2005 or earlier; no heads of state or government, military commanders or religious founders/leaders; nobody with credible abuse or eugenics ties. Myth, folklore and ghost tales are labelled “Story, not history”, never a figure sacred in a religion practised today, never a tale built on harm to children (Zashiki-warashi was dropped for this reason: one origin theory involves harm to children).',
  '',
  '**Your calls (from the review):** (1) Anansi’s tale names Nyame, the sky god of Akan religion, which people still practise; Anansi himself is a folktale trickster, not worshipped. Keep, or drop Anansi? (2) Umm Kulthum’s birth date is disputed, so she has no On this day.',
  '',
  `**Pilot:** ${LEGEND_ROSTER.length} legends across ${LEGEND_HALLS.length} halls; every one of the 32 trait sides has at least one visible legend (the full roster will need 8 each).`,
  '',
);

for (const hall of LEGEND_HALLS) {
  const hallLegends = LEGEND_ROSTER.filter((l) => l.hall === hall);
  push(`## ${HALL_LABEL[hall]} (${hallLegends.length})`, '');
  for (const l of hallLegends) {
    const kind = l.kind === 'story' ? 'Story, not history' : `Real, died ${l.died}`;
    push(`- [ ] \`${l.id}\` — **${l.name}** · ${kind} · ${l.place} · ${l.era}${l.hidden ? ' · **HIDDEN**' : ''}`);
    push(`  - Essence: ${l.essence}`);
    push(`  - Who they were: ${l.whoTheyWere}`);
    push(`  - Famous for: ${l.famousFor}`);
    for (const f of l.facts) {
      push(`  - Fact ${f.id}${f.source.verified ? '' : ' **UNVERIFIED**'}: ${f.text} — [source](${f.source.url}) (checked on: ${f.source.check.map((c) => `“${c}”`).join(', ')})`);
    }
    for (const m of l.moments) {
      push(`  - Moment ${m.id}${m.source.verified ? '' : ' **UNVERIFIED**'}: ${m.text} — [source](${m.source.url})`);
    }
    if (l.birthday) push(`  - Birthday (On this day): ${l.birthday.md} — [source](${l.birthday.source.url})`);
    for (const a of l.angles) push(`  - Angle ${a.id} *${a.name}* — teaser: ${a.teaser} · meaning: ${a.meaning}`);
    for (const t of l.tags) push(`  - Tag: ${AXIS_POLE_NAME[t.axis][t.lean]} (${t.axis} ${t.lean}) — “${t.them}” — ${t.why}`);
    if (l.hidden) {
      push(`  - Hidden until: ${l.hidden.needs.map((n) => AXIS_POLE_NAME[n.axis][n.lean]).join(' + ')}`);
    }
    push(`  - Vetting: ${l.vetting}`);
  }
  push('');
}

const sample = LEGEND_ROSTER.find((l) => l.id === 'lf_hokusai')!;
const samplePairs = legendPairs(sample, [
  { axis: 'growth_mindset', lean: 'high', strength: 0.4 },
  { axis: 'openness', lean: 'high', strength: 0.3 },
]);
push(
  '## The AI prompt (sample: Hokusai, a reader who leans Learning + Adventurous)',
  '',
  'The AI only writes “Where you match”, the one line under each moment, and “What it means for you”. The moment text, the facts and the label are always the hand-written ones above. Answers are rejected (one retry, then the hand-written fallback) if they contain any number, name or quote that is not in the entry, an unknown trait or moment, “you are”, “always”, “!”, emoji, a framework word, or a myth told as history.',
  '',
  '```',
  buildLegendPrompt({ legend: sample, angle: sample.angles[0]!, focusMomentId: 'm1', pairs: samplePairs }),
  '```',
  '',
);

writeFileSync(resolve(__dirname, '../docs/legend-figures-review.md'), `${lines.join('\n')}\n`, 'utf8');
console.log(`wrote docs/legend-figures-review.md (${LEGEND_ROSTER.length} legends)`);
