/**
 * Writes docs/category-deep-dive-review.md: what the Home deep dive shows,
 * the rules every AI line passes, and the exact prompt for two sample readers
 * (one ordinary category, and Love / closeness with its gentle block).
 *
 *   npx tsx scripts/gen-category-deep-dive-review.ts
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { CATEGORY_DEFS } from '../src/lib/categories';
import { buildDivePrompt, type DiveLean } from '../src/lib/category-deep-dive/dive';

const open = CATEGORY_DEFS.find((d) => d.id === 'cat_openness')!;
const love = CATEGORY_DEFS.find((d) => d.id === 'cat_love')!;
const openLeans: DiveLean[] = [
  { axis: 'openness', lean: 'high', pct: 90 },
  { axis: 'extraversion', lean: 'low', pct: 80 },
];
const loveLeans: DiveLean[] = [
  { axis: 'attachment_avoidance', lean: 'low', pct: 74 },
  { axis: 'attachment_anxiety', lean: 'high', pct: 66 },
];

const lines = [
  '# Category deep dive — review (CATEGORY_DEEP_DIVE_COPY_REVIEWED = false)',
  '',
  'Generated by `scripts/gen-category-deep-dive-review.ts`. Do not edit by hand.',
  '',
  '**What it is:** on Home, under the daily insight. Pick a category; your leanings in it show as “Adventurous 78%” (no AI: 50% is the middle, 100% all the way to that side). “Write my deep dive” runs ONE AI call, one new card a day; a saved card reopens free; a category gets a fresh card when your leanings in it move (a side flips or about ten points).',
  '',
  '**The AI writes:** your title here (“the calm planner”), where it shows up (one moment per top leaning, up to three), how they mix (when there are two or more), what others might notice, and what it means for you. Every part carries the small AI badge.',
  '',
  '**Every AI line is rejected (one retry, then no card) if it has:** any digit, a capitalised name or word that is not a category/side word, a quote, “you are”, “always”, “should”, “!”, emoji, brackets, a framework word, or a clinical word (anxious, insecure, avoidant, attachment, needy, clingy, trauma, toxic, therapy …). Titles also ban worry/doubt/struggle words, since they can be shared.',
  '',
  '**Love / closeness is included (your call, 2026-10-08)** with an extra gentle block in the prompt (below). Worth reading your first few of these closely.',
  '',
  '**No AI = no card:** with AI off, before wave90 is applied, or when today’s deep dive is used, the leanings still show and a plain line says why.',
  '',
  '## Prompt — Openness to life (Adventurous 90%, Reserved 80%)',
  '',
  '```',
  buildDivePrompt(open, openLeans),
  '```',
  '',
  '## Prompt — Love / closeness (Close 74%, Watchful 66%)',
  '',
  '```',
  buildDivePrompt(love, loveLeans),
  '```',
  '',
];
writeFileSync(resolve(__dirname, '../docs/category-deep-dive-review.md'), `${lines.join('\n')}\n`, 'utf8');
console.log('wrote docs/category-deep-dive-review.md');
