/**
 * Builds wave85b (the fixed 400-question bank seed) from the code, so the
 * server's copy is generated, never hand-transcribed.
 * Run: npx tsx ./scripts/gen-wave85-bank.ts > supabase/migrations/wave85b_question_bank_seed.sql
 *
 * Upsert on id: re-running after a wording edit updates that row's prompt and
 * options in place. Answers reference the id, so they are never touched.
 * `check:question-bank` regenerates this text and fails if the file drifted.
 */
import { QUESTIONS_BANK, withRewordAliases } from '../src/lib/questions/bank';
import { QUESTION_BANK, type BankQuestion } from '../src/lib/questions/bank/index';

function sqlText(text: string): string {
  return `'${text.replace(/'/g, "''")}'`;
}

/**
 * The intake wordings an old answer may carry for intake slot N of a trait:
 * today's prompt (src/lib/questions/bank.ts, Nth of that trait) plus its
 * pre-wave84 wording.
 */
export function legacyPromptsFor(row: BankQuestion): string[] {
  if (!row.intakeSlot) return [];
  const intake = QUESTIONS_BANK.filter((d) => d.axis === row.axis)[row.intakeSlot - 1];
  return intake ? withRewordAliases([intake.prompt]) : [];
}

function rowSql(row: BankQuestion): string {
  const options = JSON.stringify(row.options.map((o) => ({ text: o.text, value: o.value })));
  const legacy = legacyPromptsFor(row);
  const legacySql = legacy.length ? `array[${legacy.map(sqlText).join(', ')}]::text[]` : `'{}'::text[]`;
  return `  (${sqlText(row.id)}, ${sqlText(row.axis)}, ${sqlText(row.setting)}, ${sqlText(row.unflattering)}, ${
    row.intakeSlot ?? 'null'
  }, ${sqlText(row.prompt)}, ${sqlText(options)}::jsonb, ${legacySql})`;
}

export function wave85SeedSql(): string {
  return `-- wave85b_question_bank_seed.sql
--
-- GENERATED by scripts/gen-wave85-bank.ts from src/lib/questions/bank/*.ts.
-- Do not edit by hand: edit the trait file, regenerate, and check:question-bank
-- confirms they match. APPLIED 2026-10-06, right after wave85 (in four
-- 100-row upserts; live rows verified identical to the code by fingerprint).
--
-- ${QUESTION_BANK.length} rows. Upsert on id; answers reference id, so a wording change
-- here never touches anyone's answers.

insert into public.question_bank (id, axis, setting, unflattering, intake_slot, prompt, options, legacy_prompts)
values
${QUESTION_BANK.map(rowSql).join(',\n')}
on conflict (id) do update
  set axis = excluded.axis,
      setting = excluded.setting,
      unflattering = excluded.unflattering,
      intake_slot = excluded.intake_slot,
      prompt = excluded.prompt,
      options = excluded.options,
      legacy_prompts = excluded.legacy_prompts,
      updated_at = now();
`;
}

if (require.main === module) {
  process.stdout.write(wave85SeedSql());
}
