/**
 * Writes docs/legend-figures-review.md from the roster (the same way the
 * insight bank has a review doc): one checkbox per legend with every word the
 * app can show, each fact's source, the trait tags, and the AI prompt.
 *
 *   npx tsx scripts/gen-legend-figures-review.ts
 *
 * Re-run after any roster edit; check:legend-roster fails if a legend is
 * missing from the doc.
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { AXIS_POLE_NAME } from '../src/lib/axis-poles';
import { LEGEND_ROSTER } from '../src/lib/legend-figures/roster';
import { legendTitle } from '../src/lib/legend-figures/labels';
import { buildLegendPrompt, legendPairs } from '../src/lib/legend-figures/story';
import { HALL_LABEL, LEGEND_HALLS } from '../src/lib/legend-figures/types';

const phrases = LEGEND_ROSTER.reduce(
  (n, l) => n + [...l.facts, ...l.moments].reduce((m, x) => m + x.source.check.length, 0) + (l.birthday?.source.check.length ?? 0),
  0,
);
const unverified = LEGEND_ROSTER.reduce(
  (n, l) => n + [...l.facts, ...l.moments].filter((x) => !x.source.verified).length,
  0,
);

const lines: string[] = [];
const push = (...rows: string[]) => lines.push(...rows);

push(
  '# Legends museum — review (LEGEND_FIGURES_COPY_REVIEWED = false)',
  '',
  'Generated by `scripts/gen-legend-figures-review.ts` from `src/lib/legend-figures/roster/`. Do not edit by hand — edit the roster and re-run.',
  '',
  '**How to review:** tick each legend once you are happy with every line under it (label, facts, moments, angles, trait tags). Tell me anything to change. When every box is ticked, `LEGEND_FIGURES_COPY_REVIEWED` flips to `true`. The app shows no draft badge either way.',
  '',
  `**How facts were checked (2026-10-08):** every fact, moment and birthday cites an English Wikipedia page, and each one names exact phrases that were found in that page’s text by \`scripts/legend-roster-verify.ts\` (all ${phrases} phrases found). That proves the source says it, not that every nuance is perfect, so a human read is still the bar. Anything that could not be confirmed is marked **UNVERIFIED** below; it is never shown in the app or sent to the AI. (${unverified === 0 ? 'None right now.' : `${unverified} right now.`})`,
  '',
  '**Rules every legend follows:** real people and real animals died 2005 or earlier; no heads of state or government, military commanders or religious founders/leaders; nobody with credible abuse, eugenics, colonial violence, racism or antisemitism ties. Myth, folklore and ghost tales are labelled “Story, not history”, never a figure sacred in a religion practised today, never a tale built on harm to children. Animals are labelled “A real animal”.',
  '',
  '**Left out on purpose:** Zashiki-warashi (one origin theory involves harm to children), Thor Heyerdahl (racial migration theory; Roald Amundsen took his place), Charlie Chaplin, Edward Jenner and Helen Keller (eugenics-related statements or ties). Jim Thorpe and Umm Kulthum have disputed birth dates, so no On this day.',
  '',
  '**One person, two halls:** Leonardo da Vinci has two labels, *as an artist* (Art and design) and *as an inventor* (Science and invention). Whoever meets the second one sees “Another side of Leonardo da Vinci”.',
  '',
  '**Your calls (from the review):** (1) Anansi’s tale names Nyame, the sky god of Akan religion, which people still practise; Anansi himself is a folktale trickster, not worshipped. Keep, or drop Anansi? (2) Umm Kulthum’s birth date is disputed, so she has no On this day.',
  '',
  `**Roster:** ${LEGEND_ROSTER.length} legends across ${LEGEND_HALLS.length} halls; every one of the 32 trait sides has at least 8 visible legends, and every hall spreads over many sides, low ones included. Sources: English Wikipedia only (your call, 2026-10-08).`,
  '',
  '**Gaps to know about:** Africa (2 legends) and Oceania (1) are thin; Europe (50) and the Americas (42) are heavy. Worth a wider pass before launch.',
  '',
);

for (const hall of LEGEND_HALLS) {
  const hallLegends = LEGEND_ROSTER.filter((l) => l.hall === hall);
  push(`## ${HALL_LABEL[hall]} (${hallLegends.length})`, '');
  for (const l of hallLegends) {
    const kind = l.kind === 'story' ? 'Story, not history' : l.kind === 'animal' ? `A real animal, died ${l.died}` : `Real, died ${l.died}`;
    push(`- [ ] \`${l.id}\` — **${legendTitle(l)}** · ${kind} · ${l.place} · ${l.era}${l.hidden ? ' · **HIDDEN**' : ''}`);
    push(`  - Essence: ${l.essence}`);
    push(`  - Who they were: ${l.whoTheyWere}`);
    push(`  - Famous for: ${l.famousFor}`);
    for (const f of l.facts) {
      push(`  - Fact ${f.id}${f.source.verified ? '' : ' **UNVERIFIED**'}: ${f.text} — [source](${f.source.url}) (checked on: ${f.source.check.map((c) => `“${c}”`).join(', ')})`);
    }
    for (const m of l.moments) {
      push(`  - Moment ${m.id}${m.source.verified ? '' : ' **UNVERIFIED**'}: ${m.text} — [source](${m.source.url})`);
    }
    if (l.birthday) push(`  - Birthday (On this day): ${l.birthday.md} — [source](${l.birthday.source.url})`);
    for (const a of l.angles) push(`  - Angle ${a.id} *${a.name}* — teaser: ${a.teaser} · meaning: ${a.meaning}`);
    for (const t of l.tags) push(`  - Tag: ${AXIS_POLE_NAME[t.axis][t.lean]} (${t.axis} ${t.lean}) — “${t.them}” — ${t.why}`);
    if (l.hidden) {
      push(`  - Hidden until: ${l.hidden.needs.map((n) => AXIS_POLE_NAME[n.axis][n.lean]).join(' + ')}`);
    }
    push(`  - Vetting: ${l.vetting}`);
  }
  push('');
}

const sample = LEGEND_ROSTER.find((l) => l.id === 'lf_hokusai')!;
const samplePairs = legendPairs(sample, [
  { axis: 'growth_mindset', lean: 'high', strength: 0.4 },
  { axis: 'openness', lean: 'high', strength: 0.3 },
]);
push(
  '## The AI prompt (sample: Hokusai, a reader who leans Learning + Adventurous)',
  '',
  'The AI only writes “Where you match”, the one line under each moment, and “What it means for you”. The moment text, the facts and the label are always the hand-written ones above. Answers are rejected (one retry, then the hand-written fallback) if they contain any number, name or quote that is not in the entry, an unknown trait or moment, “you are”, “always”, “!”, emoji, a framework word, or a myth told as history.',
  '',
  '```',
  buildLegendPrompt({ legend: sample, angle: sample.angles[0]!, focusMomentId: 'm1', pairs: samplePairs }),
  '```',
  '',
);

writeFileSync(resolve(__dirname, '../docs/legend-figures-review.md'), `${lines.join('\n')}\n`, 'utf8');
console.log(`wrote docs/legend-figures-review.md (${LEGEND_ROSTER.length} legends)`);
