/**
 * Kenney asset-prep script.
 *
 * Re-exports a raw Kenney pack folder into `assets/kenney/<family>/` at one
 * fixed target resolution. The app never reads a raw downloaded folder — the
 * prep script is the only thing that touches the pack's originals.
 *
 * Target resolution: 675px per body-box unit, derived from the app's largest
 * render context — the Share poster renders PixelFace at 200pt, ×3 max pixel
 * density = 600px, ×1.125 (the 1080-wide poster capture upscale) = 675px. Each
 * part is exported at its body-box-unit size × 675, nearest-neighbor scaled so
 * the pixel art stays crisp.
 *
 * Usage:
 *   npx tsx scripts/kenney-prep.ts --family shape --source <raw-pack-folder>
 */
import fs from 'node:fs';
import path from 'node:path';

import { PNG } from 'pngjs';

import { KENNEY_REGISTRY } from '../src/lib/kenney/registry';
import type { KenneyPart } from '../src/lib/kenney/types';

/** Body-box target in px (see header comment). */
export const TARGET_BODY_PX = 675;

interface Args {
  family: string;
  source: string;
}

function parseArgs(argv: string[]): Args {
  const args: Args = { family: '', source: '' };
  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i] === '--family' && argv[i + 1]) args.family = argv[i + 1];
    if (argv[i] === '--source' && argv[i + 1]) args.source = argv[i + 1];
  }
  if (!args.family || !args.source) {
    throw new Error('Usage: kenney-prep.ts --family <family> --source <raw-pack-folder>');
  }
  return args;
}

/** Nearest-neighbor scale preserving hard pixel edges. */
function scaleNearest(src: PNG, scale: number): PNG {
  const w = Math.max(1, Math.round(src.width * scale));
  const h = Math.max(1, Math.round(src.height * scale));
  const out = new PNG({ width: w, height: h });
  for (let y = 0; y < h; y += 1) {
    const sy = Math.min(src.height - 1, Math.floor(y / scale));
    for (let x = 0; x < w; x += 1) {
      const sx = Math.min(src.width - 1, Math.floor(x / scale));
      const si = (sy * src.width + sx) << 2;
      const di = (y * w + x) << 2;
      out.data[di] = src.data[si];
      out.data[di + 1] = src.data[si + 1];
      out.data[di + 2] = src.data[si + 2];
      out.data[di + 3] = src.data[si + 3];
    }
  }
  return out;
}

/**
 * Raw filename for a part state. The normal name for a colorable part is
 * `<variant>_<pattern>_<asset>.png` (e.g. `blue_hand_open.png`). The sprite's
 * `raw` override is ONLY a fallback for when that normal file doesn't exist in
 * the pack — e.g. Shape Characters names yellow hands `hand_yellow_*` instead
 * of `yellow_hand_*`. The override must NOT apply to every variant, or every
 * hand would come out yellow (the hand/body color-mismatch bug).
 */
function rawFileName(part: KenneyPart, stateId: string, sprite: { asset: string; raw?: string }, variant: string, source: string): string {
  if (part.colorable) {
    const normal = `${variant}_${part.sourcePattern}_${sprite.asset}.png`;
    if (fs.existsSync(path.join(source, normal))) return normal;
    if (sprite.raw) return `${sprite.raw}.png`;
    return normal; // will throw a clear "missing raw asset" below
  }
  return `${sprite.asset}.png`;
}

/** Rendered filename: colorable = <asset>.<variant>.png, fixed = <asset>.png. */
function outFileName(part: KenneyPart, sprite: { asset: string }, variant: string): string {
  return part.colorable ? `${sprite.asset}.${variant}.png` : `${sprite.asset}.png`;
}

function roundToPx(bodyUnits: number): number {
  return Math.max(1, Math.round(bodyUnits * TARGET_BODY_PX));
}

function generateAssetRegistry(family: string, parts: KenneyPart[], variants: string[]) {
  const lines: string[] = [];
  lines.push('// AUTO-GENERATED by scripts/kenney-prep.ts — do not edit.');
  lines.push("import type { ImageSourcePropType } from 'react-native';");
  lines.push('');
  lines.push('export const KENNEY_ASSETS: Record<string, ImageSourcePropType> = {');
  for (const part of parts) {
    for (const [, sprite] of Object.entries(part.states)) {
      // `hidden` is a magic rest state with no asset — skip it in the registry too.
      if (sprite.asset === 'hidden') continue;
      const variantsForPart = part.colorable ? variants : [''];
      for (const variant of variantsForPart) {
        const name = outFileName(part, sprite, variant);
        const rel = `@/assets/kenney/${family}/${part.id}/${name}`;
        lines.push(`  '${family}/${part.id}/${name}': require('${rel}'),`);
      }
    }
  }
  lines.push('};');
  return `${lines.join('\n')}\n`;
}

function main() {
  const { family, source } = parseArgs(process.argv.slice(2));
  const manifest = KENNEY_REGISTRY[family];
  if (!manifest) {
    throw new Error(`No manifest for family "${family}". Registered: ${Object.keys(KENNEY_REGISTRY).join(', ')}`);
  }

  const variants = manifest.colorVariants.map((v) => v.id);
  const outRoot = path.resolve(__dirname, `../assets/kenney/${family}`);
  fs.mkdirSync(outRoot, { recursive: true });

  let exported = 0;
  for (const part of manifest.parts) {
    const partDir = path.join(outRoot, part.id);
    fs.mkdirSync(partDir, { recursive: true });

    for (const [stateId, sprite] of Object.entries(part.states)) {
      // `hidden` is a magic rest state with no asset — skip it.
      if (sprite.asset === 'hidden') continue;
      const variantsForPart = part.colorable ? variants : [''];
      for (const variant of variantsForPart) {
        const rawName = rawFileName(part, stateId, sprite, variant, source);
        const rawPath = path.join(source, rawName);
        if (!fs.existsSync(rawPath)) {
          throw new Error(`Missing raw asset: ${rawPath} (declared by ${family}/${part.id}.${stateId})`);
        }

        const src = PNG.sync.read(fs.readFileSync(rawPath));
        // Scale so the sprite's body-box-unit size lands on TARGET_BODY_PX.
        const scaleW = roundToPx(sprite.size.w) / src.width;
        const scaleH = roundToPx(sprite.size.h) / src.height;
        const scaled = scaleNearest(src, Math.max(scaleW, scaleH));

        const outName = outFileName(part, sprite, variant);
        fs.writeFileSync(path.join(partDir, outName), PNG.sync.write(scaled));
        exported += 1;
      }
    }
  }

  const registryPath = path.resolve(__dirname, '../src/lib/kenney/generated-assets.ts');
  fs.writeFileSync(registryPath, generateAssetRegistry(family, manifest.parts, variants));

  console.log(`Exported ${exported} assets -> ${outRoot}`);
  console.log(`Target: ${TARGET_BODY_PX}px body-box (Share poster 200pt ×3× 1.125)`);
  console.log(`Registry: ${registryPath}`);
}

main();
