/**
 * Play art-prep script.
 *
 * Scans the unpacked Play art packs under `assets/play/` (Scribble Dungeons
 * tiles, Masterpiece + Cozy Village avatars, Primal Dynasties beasts, Kenney
 * Fantasy UI borders, Kenney Cursor Pack icons) and emits a string-keyed
 * `require()` registry the same way `scripts/kenney-prep.ts` does for the
 * shared shape family.
 *
 * Keys are POSIX paths relative to `assets/play/` without the extension, with
 * the pack's random `-deadbeef` directory hash stripped so ids stay stable:
 *   avatars/masterpiece/animations/Iron_Slash/south/frame_000
 *
 * Usage: npx tsx scripts/play-art-prep.ts
 */
import fs from 'node:fs';
import path from 'node:path';

import { PNG } from 'pngjs';

const FAMILIES = ['avatars', 'primal', 'kenney-ui', 'kenney-icons', 'kenney-td', 'craftpix-fields', 'craftpix-roads', 'tiles'] as const;
const HASH_SUFFIX = /-[0-9a-f]{8}(?=\/|$)/g;

/**
 * Kenney Fantasy UI panel borders are 48×48 designed for 9-slice with a 16px
 * inset. The app can't 9-slice a single PNG, so bake the eight pieces once into
 * `kenney-ui/border/sliced/` and let `<PlayFrame>` compose them.
 */
function slicePanelBorder(root: string) {
  const source = path.join(root, 'kenney-ui/border/panel-border-000.png');
  const outDir = path.join(root, 'kenney-ui/border/sliced');
  const inset = 16;
  const src = PNG.sync.read(fs.readFileSync(source));
  if (src.width !== 48 || src.height !== 48) {
    throw new Error(`Unexpected panel border size ${src.width}x${src.height}`);
  }
  const spots: Record<string, [number, number]> = {
    tl: [0, 0],
    top: [inset, 0],
    tr: [32, 0],
    left: [0, inset],
    right: [32, inset],
    bl: [0, 32],
    bottom: [inset, 32],
    br: [32, 32],
  };
  fs.rmSync(outDir, { recursive: true, force: true });
  fs.mkdirSync(outDir, { recursive: true });
  for (const [name, [sx, sy]] of Object.entries(spots)) {
    const piece = new PNG({ width: inset, height: inset });
    for (let y = 0; y < inset; y += 1) {
      for (let x = 0; x < inset; x += 1) {
        const si = ((sy + y) * src.width + (sx + x)) * 4;
        const di = (y * inset + x) * 4;
        piece.data[di] = src.data[si];
        piece.data[di + 1] = src.data[si + 1];
        piece.data[di + 2] = src.data[si + 2];
        piece.data[di + 3] = src.data[si + 3];
      }
    }
    fs.writeFileSync(path.join(outDir, `${name}.png`), PNG.sync.write(piece));
  }
}

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (entry.isFile() && entry.name.toLowerCase().endsWith('.png')) out.push(full);
  }
  return out;
}

function keyFor(root: string, file: string): string {
  const rel = path.relative(root, file).split(path.sep).join('/');
  const noExt = rel.replace(/\.png$/i, '');
  return noExt.replace(HASH_SUFFIX, '');
}

function main() {
  const root = path.resolve(__dirname, '../assets/play');
  slicePanelBorder(root);
  const keys = new Map<string, string>();

  for (const family of FAMILIES) {
    const dir = path.join(root, family);
    if (!fs.existsSync(dir)) {
      throw new Error(`Missing Play art family folder: ${dir}`);
    }
    for (const file of walk(dir).sort((a, b) => a.localeCompare(b))) {
      const base = keyFor(root, file);
      let key = base;
      // Two pack folders can share a name after the hash is stripped (e.g.
      // Masterpiece ships two `Walking/.../west` variants). Keep both, stable.
      for (let n = 2; keys.has(key) && keys.get(key) !== file; n += 1) {
        key = `${base}__${n}`;
      }
      if (keys.has(key)) continue;
      keys.set(key, file);
    }
  }

  const sorted = [...keys.entries()].sort(([a], [b]) => a.localeCompare(b));
  const lines: string[] = [];
  lines.push('// AUTO-GENERATED by scripts/play-art-prep.ts — do not edit.');
  lines.push("import type { ImageSourcePropType } from 'react-native';");
  lines.push('');
  lines.push('/** Every PNG bundled under `assets/play/`, keyed by stable id. */');
  lines.push('export const PLAY_ART: Record<string, ImageSourcePropType> = {');
  for (const [key, file] of sorted) {
    const rel = path.relative(path.resolve(__dirname, '..'), file).split(path.sep).join('/');
    lines.push(`  '${key}': require('@/${rel}'),`);
  }
  lines.push('};');
  lines.push('');

  const outPath = path.resolve(__dirname, '../src/play/generated-play-assets.ts');
  fs.writeFileSync(outPath, `${lines.join('\n')}\n`);
  console.log(`Wrote ${sorted.length} Play art keys -> ${outPath}`);
}

main();
