-- wave84: moment-voice wording for the question bank (emci 2026-10-05).
-- GENERATED by scripts/gen-wave84-rows.ts from src/lib/questions/bank.ts — do not hand-edit.
-- Pinned by check:question-voice.
--
-- Wording only. Every row keeps its trait, set, option order and option values,
-- so scoring cannot move. The old intake wording stays in intake_questions so a
-- phone still on an older bundle is never told "unknown question". No answer,
-- trait value or served round copy (question_items) is touched.

-- 1. intake_questions: add the new wording; refresh option labels on unchanged prompts.
insert into public.intake_questions (prompt, axis, set_no, options) values
  ('A new place opened next to your usual spot, and your usual order is already in the app.', 'openness', 1, '[{"text":"I try the new place","value":0.8},{"text":"I save it for next week","value":0.5},{"text":"Usual order. It''s right there","value":0.2}]'::jsonb),
  ('Same restaurant, same order, and a dish you have never tried is on the menu.', 'openness', 2, '[{"text":"I order the new one","value":0.8},{"text":"Depends on the day","value":0.5},{"text":"I know what I like","value":0.2}]'::jsonb),
  ('A friend sends an invite to something you would never pick yourself.', 'openness', 3, '[{"text":"I''m in, that''s the fun part","value":0.8},{"text":"I''d probably pass","value":0.2}]'::jsonb),
  ('The plan you put in your calendar last week hits its boring part today.', 'conscientiousness', 1, '[{"text":"I still see it through","value":0.8},{"text":"I keep it if it stays easy","value":0.5},{"text":"I switch to whatever feels better","value":0.2}]'::jsonb),
  ('Monday. Your calendar says it is due Friday.', 'conscientiousness', 2, '[{"text":"I start chipping at it now","value":0.8},{"text":"I start once it feels close","value":0.5},{"text":"Thursday night, like last time","value":0.2}]'::jsonb),
  ('You said you''d send someone a link. Nobody followed up.', 'conscientiousness', 3, '[{"text":"I still send it","value":0.8},{"text":"It quietly disappears","value":0.2}]'::jsonb),
  ('Saturday afternoon and the group chat is quiet.', 'extraversion', 1, '[{"text":"I text a few people and make plans","value":0.8},{"text":"Either way, I''m fine","value":0.5},{"text":"I keep the afternoon quiet","value":0.2}]'::jsonb),
  ('You walk into a party and know two people. Both are on their phones.', 'extraversion', 2, '[{"text":"I start talking to someone new","value":0.8},{"text":"I go stand with the two I know","value":0.5},{"text":"I''m counting the minutes","value":0.2}]'::jsonb),
  ('Friday, 6pm. Three invites in the group chat.', 'extraversion', 3, '[{"text":"I''m going to at least one","value":0.8},{"text":"Couch. Phone on silent","value":0.2}]'::jsonb),
  ('A group chat is picking a place you don''t really like.', 'agreeableness', 1, '[{"text":"I go along, it''s not worth a fuss","value":0.8},{"text":"I mention it once, then let it go","value":0.5},{"text":"I say I''d rather go somewhere else","value":0.2}]'::jsonb),
  ('On the team call, someone shares your idea as their own.', 'agreeableness', 2, '[{"text":"I let it slide","value":0.8},{"text":"I mention it lightly, later","value":0.5},{"text":"I correct it on the spot","value":0.2}]'::jsonb),
  ('The delivery driver gets your order wrong and looks like their day has been rough.', 'agreeableness', 3, '[{"text":"I give them the benefit of the doubt","value":0.8},{"text":"Bad day or not, wrong is wrong","value":0.2}]'::jsonb),
  ('Your phone hits 3% before you have left the house.', 'steadiness', 1, '[{"text":"I''m mostly over it by lunch","value":0.8},{"text":"It sits with me a bit, then fades","value":0.5},{"text":"It colors the rest of the day","value":0.2}]'::jsonb),
  ('An hour before, the group chat moves the plan somewhere else.', 'steadiness', 2, '[{"text":"Fine, I roll with it","value":0.8},{"text":"Mild whiplash, then fine","value":0.5},{"text":"It throws off the whole evening","value":0.2}]'::jsonb),
  ('A one-word reply lands and it could be read two ways.', 'steadiness', 3, '[{"text":"I read it plain and move on","value":0.8},{"text":"I reread it once, then let it go","value":0.5},{"text":"I reread it a few times","value":0.2}]'::jsonb),
  ('Someone you like has had your message for three hours.', 'attachment_anxiety', 1, '[{"text":"I wonder if they''re pulling away","value":0.8},{"text":"I notice, then get on with my day","value":0.5},{"text":"I don''t think much of it","value":0.2}]'::jsonb),
  ('Your closest friend has gone quiet in the chat this week.', 'attachment_anxiety', 2, '[{"text":"I assume I did something","value":0.8},{"text":"I wonder for a second, then drop it","value":0.5},{"text":"People get busy","value":0.2}]'::jsonb),
  ('You sent a long message an hour ago. It says Read.', 'attachment_anxiety', 3, '[{"text":"I check back more than I''d admit","value":0.8},{"text":"I notice, then put the phone down","value":0.5},{"text":"I forget I sent it","value":0.2}]'::jsonb),
  ('Someone close to you wants to talk something out in person instead of over text.', 'attachment_avoidance', 1, '[{"text":"Sure, that''s fine when it matters","value":0.2},{"text":"I''d rather keep it lighter, over text","value":0.8}]'::jsonb),
  ('A rough week, and someone texts ''how are you, really?''', 'attachment_avoidance', 2, '[{"text":"I tell them the real version","value":0.2},{"text":"I give them the short version","value":0.5},{"text":"I say I''m fine and change the subject","value":0.8}]'::jsonb),
  ('Someone starts texting you good morning every day.', 'attachment_avoidance', 3, '[{"text":"I like it","value":0.2},{"text":"Nice, in small doses","value":0.5},{"text":"My replies get slower","value":0.8}]'::jsonb),
  ('On a work call, someone says something you think is wrong.', 'conflict_assertiveness', 1, '[{"text":"I say so, even if it gets a bit sharp","value":0.8},{"text":"I wait to see if it blows over","value":0.5},{"text":"I let it go rather than push","value":0.2}]'::jsonb),
  ('The order is wrong and the place is busy.', 'conflict_assertiveness', 2, '[{"text":"I send it back","value":0.8},{"text":"Depends how wrong","value":0.5},{"text":"I eat it","value":0.2}]'::jsonb),
  ('Your roommate''s music is loud and asking might annoy them.', 'conflict_assertiveness', 3, '[{"text":"I ask anyway","value":0.8},{"text":"I let it go","value":0.2}]'::jsonb),
  ('You and a friend each sent a different dinner spot. Who gives first?', 'conflict_cooperativeness', 1, '[{"text":"Probably me","value":0.8},{"text":"Depends who cares more","value":0.5},{"text":"Rarely me","value":0.2}]'::jsonb),
  ('A text argument is ten messages deep and it is getting late.', 'conflict_cooperativeness', 2, '[{"text":"I find something we can both live with","value":0.8},{"text":"I park it for tomorrow","value":0.5},{"text":"I hold my line","value":0.2}]'::jsonb),
  ('The group chat is arguing and you know the right answer.', 'conflict_cooperativeness', 3, '[{"text":"I let it go to keep the chat calm","value":0.8},{"text":"I say it once, then drop it","value":0.5},{"text":"I send the link that proves it","value":0.2}]'::jsonb),
  ('A friend sends the whole trip plan in the chat, and it would work fine.', 'autonomy', 1, '[{"text":"I''d still rather do it my way","value":0.8},{"text":"I''ll use theirs if it saves time","value":0.5},{"text":"I''m glad I don''t have to figure it out","value":0.2}]'::jsonb),
  ('Someone messages you step-by-step instructions for a thing you already know how to do.', 'autonomy', 2, '[{"text":"It gets under my skin","value":0.8},{"text":"I notice it, then let it go","value":0.5},{"text":"Fine by me, less to think about","value":0.2}]'::jsonb),
  ('Saturday''s calendar is empty and nobody has texted.', 'autonomy', 3, '[{"text":"Perfect, the day is mine","value":0.8},{"text":"Nice for a morning, then I make plans","value":0.5},{"text":"I start texting people for plans","value":0.2}]'::jsonb),
  ('A hard task lands in your inbox with your name on it.', 'competence', 1, '[{"text":"I feel like I can handle it","value":0.8},{"text":"Depends how hard, honestly","value":0.5},{"text":"I doubt I can pull it off","value":0.2}]'::jsonb),
  ('Three weeks into a language app, and it still marks you wrong.', 'competence', 2, '[{"text":"I can feel myself getting better","value":0.8},{"text":"Some days it clicks","value":0.5},{"text":"I mostly feel behind","value":0.2}]'::jsonb),
  ('Someone at work messages: ''this is your area, right?''', 'competence', 3, '[{"text":"Fair, it is","value":0.8},{"text":"Probably, I''d double-check","value":0.5},{"text":"I''m sure they mean someone else","value":0.2}]'::jsonb),
  ('A friend cancels by text an hour before, no real reason given.', 'relatedness', 1, '[{"text":"I''d want to talk it through","value":0.8},{"text":"I''d let it go, check in eventually","value":0.2}]'::jsonb),
  ('Good news pops up on your phone on an ordinary Tuesday.', 'relatedness', 2, '[{"text":"I''m texting someone before I sit down","value":0.8},{"text":"It comes up next time we talk","value":0.5},{"text":"I just enjoy it","value":0.2}]'::jsonb),
  ('A whole day with no messages from anyone.', 'relatedness', 3, '[{"text":"I feel the gap","value":0.8},{"text":"Bliss","value":0.2}]'::jsonb),
  ('Your first try at a recipe from a video goes badly. What actually happens next?', 'growth_mindset', 1, '[{"text":"I look at what I''d do differently","value":0.8},{"text":"I probably don''t try that again","value":0.2}]'::jsonb),
  ('Someone online is much better than you at a thing you care about.', 'growth_mindset', 2, '[{"text":"I want to know how they got there","value":0.8},{"text":"Good for them, different lane","value":0.5},{"text":"Some people just have it","value":0.2}]'::jsonb),
  ('A friend posts day 60 of learning something new.', 'growth_mindset', 3, '[{"text":"Give me 60 days and I could too","value":0.8},{"text":"Depends on the thing","value":0.5},{"text":"Some people are just built for it","value":0.2}]'::jsonb),
  ('The group trip you helped plan falls apart in the chat.', 'locus_of_control', 1, '[{"text":"I look at what I could have done","value":0.8},{"text":"Some of it was me, some wasn''t","value":0.5},{"text":"It was bound to happen","value":0.2}]'::jsonb),
  ('A good week, and someone texts ''how did you pull that off?''', 'locus_of_control', 2, '[{"text":"Honestly, I worked for it","value":0.8},{"text":"A bit of both","value":0.5},{"text":"Good timing, mostly","value":0.2}]'::jsonb),
  ('New year, blank calendar. How it goes is mostly…', 'locus_of_control', 3, '[{"text":"Up to what I do","value":0.8},{"text":"Half me, half luck","value":0.5},{"text":"Up to what happens","value":0.2}]'::jsonb),
  ('Everyone at the table already knows their order. You don''t.', 'self_efficacy', 1, '[{"text":"I panic-order whatever''s closest","value":0.2},{"text":"Takes a sec, but I land on something","value":0.5},{"text":"I pick something and own it","value":0.8}]'::jsonb),
  ('The wifi drops and you have never fixed it yourself before.', 'self_efficacy', 2, '[{"text":"I''ll figure it out","value":0.8},{"text":"I look it up first","value":0.5},{"text":"I find someone who knows","value":0.2}]'::jsonb),
  ('A big task has sat in your to-do app for two weeks.', 'self_efficacy', 3, '[{"text":"I pick any piece and start","value":0.8},{"text":"I break it down, then wait a bit","value":0.5},{"text":"I keep moving it to tomorrow","value":0.2}]'::jsonb),
  ('A 40-minute delay at the gate, and your phone is at 20%.', 'playfulness', 1, '[{"text":"I''d mess around and see what happens","value":0.8},{"text":"Either way, I am fine","value":0.5},{"text":"I''d rather just get through it","value":0.2}]'::jsonb),
  ('A serious work call, and someone''s cat walks across their keyboard.', 'playfulness', 2, '[{"text":"I take the joke","value":0.8},{"text":"Depends who is on the call","value":0.5},{"text":"I keep it serious","value":0.2}]'::jsonb),
  ('The group chat has a running joke.', 'playfulness', 3, '[{"text":"I started it","value":0.8},{"text":"I keep it going","value":0.5},{"text":"I just react with a laugh","value":0.2}]'::jsonb)
on conflict (prompt) do update
  set options = excluded.options
  where intake_questions.axis = excluded.axis
    and intake_questions.set_no = excluded.set_no
    and (select array_agg((o->>'value')::numeric order by i) from jsonb_array_elements(intake_questions.options) with ordinality as t(o, i))
      = (select array_agg((o->>'value')::numeric order by i) from jsonb_array_elements(excluded.options) with ordinality as t(o, i));

-- 2. question_bank_pool: reword the authored rows in place (same id, same values).
create temporary table wave84_pool (old_prompt text, new_prompt text, new_options jsonb);
insert into wave84_pool (old_prompt, new_prompt, new_options) values
  ('Your Do today was writing down one thing you''re walking into. Was today''s version the safe pick or the different one?', 'A new place opened next to your usual spot, and your usual order is already in the app.', '[{"text":"I try the new place","value":0.8},{"text":"I save it for next week","value":0.5},{"text":"Usual order. It''s right there","value":0.2}]'),
  ('Same restaurant, and there is a menu item you have never tried.', 'Same restaurant, same order, and a dish you have never tried is on the menu.', '[{"text":"I order the new one","value":0.8},{"text":"Depends on the day","value":0.5},{"text":"I know what I like","value":0.2}]'),
  ('A friend wants to drag you to something you would never pick yourself.', 'A friend sends an invite to something you would never pick yourself.', '[{"text":"I''m in, that''s the fun part","value":0.8},{"text":"I''d probably pass","value":0.2}]'),
  ('A plan you made last week hits a boring stretch today.', 'The plan you put in your calendar last week hits its boring part today.', '[{"text":"I still see it through","value":0.8},{"text":"I keep it if it stays easy","value":0.5},{"text":"I switch to whatever feels better","value":0.2}]'),
  ('Something is due Friday. It is Monday.', 'Monday. Your calendar says it is due Friday.', '[{"text":"I start chipping at it now","value":0.8},{"text":"I start once it feels close","value":0.5},{"text":"Thursday night, like last time","value":0.2}]'),
  ('You said you would do a small thing for someone and nobody followed up.', 'You said you''d send someone a link. Nobody followed up.', '[{"text":"I still send it","value":0.8},{"text":"It quietly disappears","value":0.2}]'),
  ('Saturday afternoon, nobody has plans yet.', 'Saturday afternoon and the group chat is quiet.', '[{"text":"I text a few people and make plans","value":0.8},{"text":"Either way, I''m fine","value":0.5},{"text":"I keep the afternoon quiet","value":0.2}]'),
  ('You walk into a party and know maybe two people.', 'You walk into a party and know two people. Both are on their phones.', '[{"text":"I start talking to someone new","value":0.8},{"text":"I go stand with the two I know","value":0.5},{"text":"I''m counting the minutes","value":0.2}]'),
  ('A long week just ended.', 'Friday, 6pm. Three invites in the group chat.', '[{"text":"I''m going to at least one","value":0.8},{"text":"Couch. Phone on silent","value":0.2}]'),
  ('A group chat is picking a place you don''t really like.', 'A group chat is picking a place you don''t really like.', '[{"text":"I go along, it''s not worth a fuss","value":0.8},{"text":"I mention it once, then let it go","value":0.5},{"text":"I say I''d rather go somewhere else","value":0.2}]'),
  ('Someone takes credit for something that was mostly yours.', 'On the team call, someone shares your idea as their own.', '[{"text":"I let it slide","value":0.8},{"text":"I mention it lightly, later","value":0.5},{"text":"I correct it on the spot","value":0.2}]'),
  ('A stranger is clearly in the wrong and clearly having a bad day.', 'The delivery driver gets your order wrong and looks like their day has been rough.', '[{"text":"I give them the benefit of the doubt","value":0.8},{"text":"Bad day or not, wrong is wrong","value":0.2}]'),
  ('A small thing goes wrong first thing in the morning.', 'Your phone hits 3% before you have left the house.', '[{"text":"I''m mostly over it by lunch","value":0.8},{"text":"It sits with me a bit, then fades","value":0.5},{"text":"It colors the rest of the day","value":0.2}]'),
  ('Plans change on you an hour before.', 'An hour before, the group chat moves the plan somewhere else.', '[{"text":"Fine, I roll with it","value":0.8},{"text":"Mild whiplash, then fine","value":0.5},{"text":"It throws off the whole evening","value":0.2}]'),
  ('A one-word reply lands and it could be read two ways.', 'A one-word reply lands and it could be read two ways.', '[{"text":"I read it plain and move on","value":0.8},{"text":"I reread it once, then let it go","value":0.5},{"text":"I reread it a few times","value":0.2}]'),
  ('Someone you like takes a while to reply.', 'Someone you like has had your message for three hours.', '[{"text":"I wonder if they''re pulling away","value":0.8},{"text":"I notice, then get on with my day","value":0.5},{"text":"I don''t think much of it","value":0.2}]'),
  ('A close friend has been quieter than usual this week.', 'Your closest friend has gone quiet in the chat this week.', '[{"text":"I assume I did something","value":0.8},{"text":"I wonder for a second, then drop it","value":0.5},{"text":"People get busy","value":0.2}]'),
  ('You sent a long message an hour ago. It says Read.', 'You sent a long message an hour ago. It says Read.', '[{"text":"I check back more than I''d admit","value":0.8},{"text":"I notice, then put the phone down","value":0.5},{"text":"I forget I sent it","value":0.2}]'),
  ('Someone close to you wants to talk something out in person instead of over text.', 'Someone close to you wants to talk something out in person instead of over text.', '[{"text":"Sure, that''s fine when it matters","value":0.2},{"text":"I''d rather keep it lighter, over text","value":0.8}]'),
  ('A rough week. Someone asks how you actually are.', 'A rough week, and someone texts ''how are you, really?''', '[{"text":"I tell them the real version","value":0.2},{"text":"I give them the short version","value":0.5},{"text":"I say I''m fine and change the subject","value":0.8}]'),
  ('Someone starts texting you good morning every day.', 'Someone starts texting you good morning every day.', '[{"text":"I like it","value":0.2},{"text":"Nice, in small doses","value":0.5},{"text":"My replies get slower","value":0.8}]'),
  ('You disagree with someone in the room.', 'On a work call, someone says something you think is wrong.', '[{"text":"I say so, even if it gets a bit sharp","value":0.8},{"text":"I wait to see if it blows over","value":0.5},{"text":"I let it go rather than push","value":0.2}]'),
  ('The order is wrong and the place is busy.', 'The order is wrong and the place is busy.', '[{"text":"I send it back","value":0.8},{"text":"Depends how wrong","value":0.5},{"text":"I eat it","value":0.2}]'),
  ('You want something and asking might annoy someone.', 'Your roommate''s music is loud and asking might annoy them.', '[{"text":"I ask anyway","value":0.8},{"text":"I let it go","value":0.2}]'),
  ('When you and someone else both want different things with no obvious middle ground, who usually gives first?', 'You and a friend each sent a different dinner spot. Who gives first?', '[{"text":"Probably me","value":0.8},{"text":"Depends who cares more","value":0.5},{"text":"Rarely me","value":0.2}]'),
  ('An argument is going nowhere and it is getting late.', 'A text argument is ten messages deep and it is getting late.', '[{"text":"I find something we can both live with","value":0.8},{"text":"I park it for tomorrow","value":0.5},{"text":"I hold my line","value":0.2}]'),
  ('The group chat is arguing and you know you''re right.', 'The group chat is arguing and you know the right answer.', '[{"text":"I let it go to keep the chat calm","value":0.8},{"text":"I say it once, then drop it","value":0.5},{"text":"I send the link that proves it","value":0.2}]'),
  ('Someone hands you a plan that would work fine.', 'A friend sends the whole trip plan in the chat, and it would work fine.', '[{"text":"I''d still rather do it my way","value":0.8},{"text":"I''ll use theirs if it saves time","value":0.5},{"text":"I''m glad I don''t have to figure it out","value":0.2}]'),
  ('You get told exactly how to do something you already know how to do.', 'Someone messages you step-by-step instructions for a thing you already know how to do.', '[{"text":"It gets under my skin","value":0.8},{"text":"I notice it, then let it go","value":0.5},{"text":"Fine by me, less to think about","value":0.2}]'),
  ('Saturday''s calendar is empty and nobody has texted.', 'Saturday''s calendar is empty and nobody has texted.', '[{"text":"Perfect, the day is mine","value":0.8},{"text":"Nice for a morning, then I make plans","value":0.5},{"text":"I start texting people for plans","value":0.2}]'),
  ('A hard task lands on your plate.', 'A hard task lands in your inbox with your name on it.', '[{"text":"I feel like I can handle it","value":0.8},{"text":"Depends how hard, honestly","value":0.5},{"text":"I doubt I can pull it off","value":0.2}]'),
  ('You are learning something new and you are still bad at it.', 'Three weeks into a language app, and it still marks you wrong.', '[{"text":"I can feel myself getting better","value":0.8},{"text":"Some days it clicks","value":0.5},{"text":"I mostly feel behind","value":0.2}]'),
  ('Someone at work says ''this is your area, right?''', 'Someone at work messages: ''this is your area, right?''', '[{"text":"Fair, it is","value":0.8},{"text":"Probably, I''d double-check","value":0.5},{"text":"I''m sure they mean someone else","value":0.2}]'),
  ('A friend cancels same-day, no real reason given.', 'A friend cancels by text an hour before, no real reason given.', '[{"text":"I''d want to talk it through","value":0.8},{"text":"I''d let it go, check in eventually","value":0.2}]'),
  ('Something good happens to you on an ordinary Tuesday.', 'Good news pops up on your phone on an ordinary Tuesday.', '[{"text":"I''m texting someone before I sit down","value":0.8},{"text":"It comes up next time we talk","value":0.5},{"text":"I just enjoy it","value":0.2}]'),
  ('A whole day with no messages from anyone.', 'A whole day with no messages from anyone.', '[{"text":"I feel the gap","value":0.8},{"text":"Bliss","value":0.2}]'),
  ('You try something new and it goes badly the first time. What actually happens next?', 'Your first try at a recipe from a video goes badly. What actually happens next?', '[{"text":"I look at what I''d do differently","value":0.8},{"text":"I probably don''t try that again","value":0.2}]'),
  ('Someone is much better than you at a thing you care about.', 'Someone online is much better than you at a thing you care about.', '[{"text":"I want to know how they got there","value":0.8},{"text":"Good for them, different lane","value":0.5},{"text":"Some people just have it","value":0.2}]'),
  ('A friend posts day 60 of learning something new.', 'A friend posts day 60 of learning something new.', '[{"text":"Give me 60 days and I could too","value":0.8},{"text":"Depends on the thing","value":0.5},{"text":"Some people are just built for it","value":0.2}]'),
  ('A plan you were in on falls apart.', 'The group trip you helped plan falls apart in the chat.', '[{"text":"I look at what I could have done","value":0.8},{"text":"Some of it was me, some wasn''t","value":0.5},{"text":"It was bound to happen","value":0.2}]'),
  ('A good week. Where does the credit actually go?', 'A good week, and someone texts ''how did you pull that off?''', '[{"text":"Honestly, I worked for it","value":0.8},{"text":"A bit of both","value":0.5},{"text":"Good timing, mostly","value":0.2}]'),
  ('Someone asks how next year''s looking.', 'New year, blank calendar. How it goes is mostly…', '[{"text":"Up to what I do","value":0.8},{"text":"Half me, half luck","value":0.5},{"text":"Up to what happens","value":0.2}]'),
  ('Everyone at the table already knows their order. You don''t.', 'Everyone at the table already knows their order. You don''t.', '[{"text":"I panic-order whatever''s closest","value":0.2},{"text":"Takes a sec, but I land on something","value":0.5},{"text":"I pick something and own it","value":0.8}]'),
  ('Something breaks and you have never fixed one before.', 'The wifi drops and you have never fixed it yourself before.', '[{"text":"I''ll figure it out","value":0.8},{"text":"I look it up first","value":0.5},{"text":"I find someone who knows","value":0.2}]'),
  ('A big task has sat in your to-do app for two weeks.', 'A big task has sat in your to-do app for two weeks.', '[{"text":"I pick any piece and start","value":0.8},{"text":"I break it down, then wait a bit","value":0.5},{"text":"I keep moving it to tomorrow","value":0.2}]'),
  ('A dull stretch with nothing required of you.', 'A 40-minute delay at the gate, and your phone is at 20%.', '[{"text":"I''d mess around and see what happens","value":0.8},{"text":"Either way, I am fine","value":0.5},{"text":"I''d rather just get through it","value":0.2}]'),
  ('A serious conversation hits a genuinely funny moment.', 'A serious work call, and someone''s cat walks across their keyboard.', '[{"text":"I take the joke","value":0.8},{"text":"Depends who is on the call","value":0.5},{"text":"I keep it serious","value":0.2}]'),
  ('The group chat has a running joke.', 'The group chat has a running joke.', '[{"text":"I started it","value":0.8},{"text":"I keep it going","value":0.5},{"text":"I just react with a laugh","value":0.2}]'),
  ('You''re picking a show to watch and there''s something new in your queue you haven''t tried.', 'Something new is sitting in your watch queue, right next to an old favorite.', '[{"text":"New one","value":0.8},{"text":"Depends on my mood","value":0.5},{"text":"Something familiar","value":0.2}]'),
  ('A coworker suggests doing the project a totally different way than you planned.', 'A coworker drops a totally different plan into the project chat.', '[{"text":"I''m curious, let''s see","value":0.8},{"text":"I''ll hear them out","value":0.5},{"text":"I''d rather stick to the plan","value":0.2}]'),
  ('You have a free Saturday and someone mentions a class or hobby you''ve never tried.', 'A friend sends a link to a class for a hobby you have never tried.', '[{"text":"I''d sign up","value":0.8},{"text":"Maybe another time","value":0.2}]'),
  ('Your alarm goes off and you already know today''s to-do list is long.', 'Your alarm goes off and you already know today''s to-do list is long.', '[{"text":"I get moving right away","value":0.8},{"text":"I ease into it","value":0.5},{"text":"I hit snooze","value":0.2}]'),
  ('You told yourself you''d clean up before bed, and you''re tired.', 'Midnight, dishes in the sink, and you promised yourself you''d do them tonight.', '[{"text":"I still do them","value":0.8},{"text":"I do the bare minimum","value":0.5},{"text":"They wait until tomorrow","value":0.2}]'),
  ('A form needs three pieces of information and you only have two handy.', 'An online form wants three things and you only have two handy.', '[{"text":"I track down the third one now","value":0.8},{"text":"I fill in what I can, come back later","value":0.2}]'),
  ('You''ve been working alone for hours and hit a wall.', 'Hours alone with your laptop, and you just hit a wall.', '[{"text":"I go find someone to talk to","value":0.8},{"text":"Either way","value":0.5},{"text":"I push through alone","value":0.2}]'),
  ('A coworker asks if you want to grab lunch with the group instead of eating at your desk.', 'The team chat asks who''s in for lunch.', '[{"text":"Count me in","value":0.8},{"text":"Depends on the day","value":0.5},{"text":"I''d rather eat at my desk","value":0.2}]'),
  ('You''re the one who has to make small talk with someone new at an event.', 'At an event, you end up next to someone new and nobody is talking.', '[{"text":"I don''t mind starting it","value":0.8},{"text":"I''ll follow their lead","value":0.2}]'),
  ('Someone asks for a favor that''s a genuine inconvenience for you.', 'A friend texts asking for a favor that would eat your whole evening.', '[{"text":"I usually say yes anyway","value":0.8},{"text":"Depends how big a favor","value":0.5},{"text":"I say no if it''s a real hassle","value":0.2}]'),
  ('A friend keeps borrowing money and hasn''t paid you back.', 'A friend still hasn''t paid you back for the last three dinners.', '[{"text":"I bring it up directly","value":0.8},{"text":"I hint at it","value":0.5},{"text":"I let it slide","value":0.2}]'),
  ('You just finished something you''re proud of.', 'You just finished something and it came out better than you hoped.', '[{"text":"I want to tell someone right away","value":0.8},{"text":"It can wait until it comes up","value":0.5},{"text":"I keep it to myself","value":0.2}]'),
  ('Someone sends a short reply that could be read two ways.', 'Your manager messages ''can we talk tomorrow?'' and nothing else.', '[{"text":"I read it plain and move on","value":0.8},{"text":"I reread it a few times","value":0.2}]'),
  ('You need reassurance more often than you would like to admit.', 'After a good night out, you scroll back through the chat to check it really went well.', '[{"text":"Yeah, that lands","value":0.8},{"text":"Not really me","value":0.2}]'),
  ('Things are getting closer with someone.', 'The person you''ve been seeing starts saying ''we'' in texts.', '[{"text":"I lean in","value":0.2},{"text":"I want a bit of room","value":0.8}]'),
  ('Winning the point matters more than keeping the peace.', 'Mid-argument, you find the screenshot that proves your point.', '[{"text":"I keep it to myself","value":0.8},{"text":"I send it","value":0.2}]'),
  ('A free day with nothing scheduled and nobody asking anything of you.', 'A day off, notifications muted, and nobody needs anything from you.', '[{"text":"That is the best kind of day","value":0.8},{"text":"I''d rather have a plan","value":0.2}]'),
  ('Someone says you are good at something you do a lot.', 'A coworker messages ''how are you so good at this?''', '[{"text":"Yeah, I think so too","value":0.8},{"text":"I brush it off","value":0.2}]'),
  ('You can get noticeably better at almost anything with enough reps.', 'Day 1 of a 30-day challenge in an app, and it shows.', '[{"text":"I''ll be better by day 30","value":0.8},{"text":"Some things just are not for me","value":0.2}]'),
  ('How next year goes is mostly up to you.', 'The email lands: the job you wanted went to someone else.', '[{"text":"Next time I''ll do it differently","value":0.8},{"text":"Timing decides more than I do","value":0.2}]'),
  ('A big thing you have to do, and no obvious first step.', 'You move apartments next month and the to-do list is just a title.', '[{"text":"I start somewhere and adjust","value":0.8},{"text":"I stall until it gets urgent","value":0.2}]'),
  ('People would say you are one of the sillier people they know.', 'Someone asks who sends the most memes in the group chat.', '[{"text":"Guilty, that''s me","value":0.8},{"text":"Not me, I just react","value":0.2}]');

do $$
declare
  bad int;
begin
  -- Refuse the whole migration if any reworded row would change a value or the option count.
  select count(*) into bad
  from public.question_bank_pool p
  join wave84_pool w on w.old_prompt = p.prompt
  where p.source = 'authored'
    and (select array_agg((o->>'value')::numeric order by i) from jsonb_array_elements(p.options) with ordinality as t(o, i))
      is distinct from (select array_agg((o->>'value')::numeric order by i) from jsonb_array_elements(w.new_options) with ordinality as t(o, i));
  if bad > 0 then
    raise exception 'wave84: % pool rows would change a value', bad;
  end if;
end;
$$;

update public.question_bank_pool p
set prompt = w.new_prompt,
    options = w.new_options
from wave84_pool w
where p.prompt = w.old_prompt
  and p.source = 'authored'
  and (p.prompt <> w.new_prompt or p.options <> w.new_options)
  and (w.new_prompt = w.old_prompt
       or not exists (select 1 from public.question_bank_pool q where q.prompt = w.new_prompt));

drop table wave84_pool;
