import { intake, q, traitBank } from './define';

/** Harmony: "I don't love that plan" (low) to "I'm fine with anything" (high). */
export const AGREEABLENESS_BANK = traitBank('agreeableness', [
  intake(1, q('agreeableness_01', 'friends', 'high', "A group chat is picking a place you don't really like.",
    ["I go along, it's not worth a fuss", 0.8], ['I mention it once, then let it go', 0.5], ["I say I'd rather go somewhere else", 0.2])),
  intake(2, q('agreeableness_02', 'work', 'high', 'On the team call, someone shares your idea as their own.',
    ['I let it slide', 0.8], ['I mention it lightly, later', 0.5], ['I correct it on the spot', 0.2])),
  intake(3, q('agreeableness_03', 'solo', 'low', 'The delivery driver gets your order wrong and looks like their day has been rough.',
    ['I give them the benefit of the doubt', 0.8], ['Bad day or not, wrong is wrong', 0.2])),
  q('agreeableness_04', 'work', 'high', 'A coworker asks you to cover their shift. Again.',
    ['Sure, no problem', 0.8], ['This time, but I say something', 0.5], ['Not this time', 0.2]),
  q('agreeableness_05', 'work', 'low', 'Someone in class gives a presentation with a big mistake in it.',
    ['I point it out in the Q&A', 0.2], ['I tell them after, kindly', 0.5], ['I keep it to myself', 0.8]),
  q('agreeableness_06', 'friends', 'neither', "A friend shows you a photo of a haircut they love. You don't.",
    ['I find one thing I like', 0.5], ['It looks great on you', 0.8], ['I tell them what I think', 0.2]),
  q('agreeableness_07', 'friends', 'low', 'A friend is late for the third time this month.',
    ['No worries, I get it', 0.8], ['I make a little joke about it', 0.5], ['I tell them it bugs me', 0.2]),
  q('agreeableness_08', 'dating', 'high', "Your date picks a movie you already know you'll hate.",
    ['I say no to that one', 0.2], ['I suggest a second option', 0.5], ["I watch it, happy they're happy", 0.8]),
  q('agreeableness_09', 'dating', 'neither', 'Your partner wants to spend the holidays with their family again.',
    ['Sure, but we switch next year', 0.5], ['Fine with me', 0.8], ["It's my family's turn", 0.2]),
  q('agreeableness_10', 'family', 'high', 'A relative makes a comment at dinner that you think is unfair.',
    ['I keep the peace', 0.8], ['I change the subject', 0.5], ['I push back on it', 0.2]),
  q('agreeableness_11', 'family', 'neither', 'Your brother borrows your headphones without asking.',
    ['I want it back, now', 0.2], ['I ask them to ask next time', 0.5], ["What's mine is theirs", 0.8]),
  q('agreeableness_12', 'solo', 'low', 'A stranger cuts in front of you in the coffee line.',
    ['I give them a look', 0.5], ["Maybe they didn't see me", 0.8], ['I tell them I was next', 0.2]),
  q('agreeableness_13', 'online', 'neither', 'Someone online posts an opinion you think is just wrong.',
    ['I scroll past', 0.8], ['I like a reply that says it', 0.5], ['I reply and say why', 0.2]),
  q('agreeableness_14', 'online', 'low', 'A friend asks for honest feedback on their new side hustle website.',
    ['I send a list of fixes', 0.2], ['Mostly praise, one note', 0.5], ['I hype it up', 0.8]),
  q('agreeableness_15', 'money', 'high', 'Splitting the bill, someone suggests even shares. You only had a salad.',
    ['I mention it, then pay even', 0.5], ['Even is fine', 0.8], ['I pay for what I had', 0.2]),
  q('agreeableness_16', 'money', 'neither', 'A friend asks to borrow $50 and still owes you from last time.',
    ['Sure, here you go', 0.8], ['I mention the last one', 0.5], ['Not until the first is back', 0.2]),
  q('agreeableness_17', 'stress', 'high', 'Swamped this week, and someone asks for a favor.',
    ["I say I can't this week", 0.2], ['I offer a smaller version', 0.5], ['I say yes anyway', 0.8]),
  q('agreeableness_18', 'stress', 'low', 'A tense moment at work, and a coworker snaps at you.',
    ['I let it go, but notice', 0.5], ['They must be stressed', 0.8], ['I tell them not to', 0.2]),
  q('agreeableness_19', 'work', 'neither', 'Your boss asks if the new plan works for everyone.',
    ['I nod along', 0.8], ['I ask one question', 0.5], ["I say what won't work", 0.2]),
  q('agreeableness_20', 'friends', 'high', 'The group plans a trip on the dates that are bad for you.',
    ['I say those dates are out', 0.2], ['I ask if we can shift it', 0.5], ['I make it work somehow', 0.8]),
  q('agreeableness_21', 'dating', 'low', 'On a date, they say something you strongly disagree with.',
    ['I ask what they mean', 0.5], ['I let it pass', 0.8], ['I say I see it differently', 0.2]),
  q('agreeableness_22', 'family', 'neither', "Your mom texts you advice about your job that you didn't ask for.",
    ['Thanks, love you', 0.8], ['A thumbs up and move on', 0.5], ['I ask her to stop', 0.2]),
  q('agreeableness_23', 'solo', 'neither', 'The barista makes your drink wrong, and the line behind you is long.',
    ['I ask nicely for a fix', 0.2], ["I drink it, it's fine", 0.8]),
  q('agreeableness_24', 'online', 'high', 'A friend posts a photo of you that you hate.',
    ['I ask them to crop me out', 0.5], ['I leave it, they like it', 0.8], ['I ask them to take it down', 0.2]),
  q('agreeableness_25', 'money', 'low', 'A roommate keeps "forgetting" to pay their share of the wifi.',
    ["I cover it, it's small", 0.8], ['I send a gentle reminder', 0.5], ['I bring it up directly', 0.2]),
]);
