import { intake, q, traitBank } from './define';

/** Reassurance: "They're probably just busy" (low) to "Did I say something wrong?" (high). */
export const ATTACHMENT_ANXIETY_BANK = traitBank('attachment_anxiety', [
  intake(1, q('attachment_anxiety_01', 'dating', 'high', 'Someone you like has had your message for three hours.',
    ["I wonder if they're pulling away", 0.8], ['I notice, then get on with my day', 0.5], ["I don't think much of it", 0.2])),
  intake(2, q('attachment_anxiety_02', 'friends', 'high', 'Your closest friend has gone quiet in the chat this week.',
    ['I assume I did something', 0.8], ['I wonder for a second, then drop it', 0.5], ['People get busy', 0.2])),
  intake(3, q('attachment_anxiety_03', 'online', 'high', 'You sent a long message an hour ago. It says Read.',
    ["I check back more than I'd admit", 0.8], ['I notice, then put the phone down', 0.5], ['I forget I sent it', 0.2])),
  q('attachment_anxiety_04', 'work', 'high', 'Your boss replies to your long email with just "ok."',
    ['I reread my email for mistakes', 0.8], ['A tiny flicker, then fine', 0.5], ['Ok means ok', 0.2]),
  q('attachment_anxiety_05', 'work', 'neither', 'Coworkers go to lunch and nobody pings you.',
    ['They probably forgot', 0.2], ['A little odd, I let it go', 0.5], ['I wonder if they left me out', 0.8]),
  q('attachment_anxiety_06', 'friends', 'high', 'You see friends hanging out in a story. You were not invited.',
    ['A small sting, then fine', 0.5], ['I wonder what I did', 0.8], ['Good for them', 0.2]),
  q('attachment_anxiety_07', 'friends', 'low', "A friend hasn't liked your last three posts.",
    ['I notice and it bugs me', 0.8], ['I notice, then shrug', 0.5], ['I never track that', 0.2]),
  q('attachment_anxiety_08', 'dating', 'high', "Your partner is out with friends and hasn't texted all night.",
    ["They're having fun", 0.2], ['I wonder a bit, then sleep', 0.5], ['I text to check in, twice', 0.8]),
  q('attachment_anxiety_09', 'dating', 'neither', `A date says "let's do this again" but doesn't suggest a day.`,
    ['I wait a day and see', 0.5], ['I read it as a polite no', 0.8], ['I take it at face value', 0.2]),
  q('attachment_anxiety_10', 'dating', 'high', "Your situationship posts a story but hasn't replied to you.",
    ['I spiral a little', 0.8], ['I notice it, then let it go', 0.5], ['They will reply when they reply', 0.2]),
  q('attachment_anxiety_11', 'family', 'neither', 'Your sister answers your call with "can I call you back?"',
    ["She's busy, no big deal", 0.2], ['Sure, I wait for it', 0.5], ["I wonder if she's upset", 0.8]),
  q('attachment_anxiety_12', 'family', 'low', 'Your family group chat goes on without you replying for a week.',
    ['I catch up when I can', 0.5], ['I feel bad, then over-reply', 0.8], ['They know I love them', 0.2]),
  q('attachment_anxiety_13', 'solo', 'high', 'In bed, you replay a conversation from earlier today.',
    ['Did that come out wrong?', 0.8], ['A quick replay, then sleep', 0.5], ["I'm asleep already", 0.2]),
  q('attachment_anxiety_14', 'online', 'high', 'Someone you just met follows you, then unfollows a day later.',
    ["I wouldn't even notice", 0.2], ['Weird, but okay', 0.5], ['I go over what I posted', 0.8]),
  q('attachment_anxiety_15', 'online', 'neither', 'Your friend is "typing…" and then stops. Nothing comes.',
    ['I notice, then forget', 0.5], ['I wonder what they deleted', 0.8], ['They got distracted', 0.2]),
  q('attachment_anxiety_16', 'money', 'neither', 'A friend pays you back exactly to the cent, no message.',
    ['Are they mad at me?', 0.8], ['A little formal, but fine', 0.5], ["Great, we're square", 0.2]),
  q('attachment_anxiety_17', 'money', 'low', "You lent a friend money. They haven't brought it up in weeks.",
    ['They will pay when they can', 0.2], ['I mention it lightly', 0.5], ['I worry it hurts the friendship', 0.8]),
  q('attachment_anxiety_18', 'stress', 'high', 'A hard week, and your partner seems a bit distant.',
    ['I give it a few days', 0.5], ["I ask if we're okay", 0.8], ["We're both tired", 0.2]),
  q('attachment_anxiety_19', 'stress', 'neither', 'Your best friend says "we need to talk later."',
    ["I can't focus until we do", 0.8], ['I wonder, but I wait', 0.5], ['Could be anything, I wait', 0.2]),
  q('attachment_anxiety_20', 'friends', 'neither', 'A friend makes new friends at their new job.',
    ['Great, more people to meet', 0.2], ['A small worry, then fine', 0.5], ["I worry I'll get replaced", 0.8]),
  q('attachment_anxiety_21', 'dating', 'low', 'Your partner wants a night out with friends without you.',
    ['Fine, as long as they text', 0.5], ['I feel a little left out', 0.8], ['Have fun, I have plans', 0.2]),
  q('attachment_anxiety_22', 'work', 'high', 'A meeting invite from HR appears for tomorrow, no agenda.',
    ["I assume it's bad news", 0.8], ['I wonder, then sleep', 0.5], ['Probably paperwork', 0.2]),
  q('attachment_anxiety_23', 'family', 'neither', 'Your parents plan a weekend trip and forget to mention it.',
    ['Good for them', 0.2], ['A little odd, but fine', 0.5], ['I feel left out', 0.8]),
  q('attachment_anxiety_24', 'solo', 'low', 'Your phone has been quiet all evening.',
    ['I notice the quiet', 0.5], ["I check if it's on silent", 0.8], ['I enjoy the quiet', 0.2]),
  q('attachment_anxiety_25', 'online', 'neither', 'You send a meme to the group chat and nobody reacts.',
    ['I think about unsending it', 0.8], ['A little awkward, I move on', 0.5], ['Their loss', 0.2]),
]);
