import { intake, q, traitBank } from './define';

/** Personal space: "Come over, let's talk" (low) to "I'm good, I just need some space" (high). */
export const ATTACHMENT_AVOIDANCE_BANK = traitBank('attachment_avoidance', [
  intake(1, q('attachment_avoidance_01', 'dating', 'high', 'Someone close to you wants to talk something out in person instead of over text.',
    ["Sure, that's fine when it matters", 0.2], ["I'd rather keep it lighter, over text", 0.8])),
  intake(2, q('attachment_avoidance_02', 'stress', 'high', "A rough week, and someone texts 'how are you, really?'",
    ['I tell them the real version', 0.2], ['I give them the short version', 0.5], ["I say I'm fine and change the subject", 0.8])),
  intake(3, q('attachment_avoidance_03', 'dating', 'neither', 'Someone starts texting you good morning every day.',
    ['I like it', 0.2], ['Nice, in small doses', 0.5], ['My replies get slower', 0.8])),
  q('attachment_avoidance_04', 'work', 'neither', 'A coworker starts telling you about their breakup at lunch.',
    ['I steer back to work talk', 0.8], ['I listen, but keep it light', 0.5], ['I lean in and listen', 0.2]),
  q('attachment_avoidance_05', 'work', 'neither', 'Your team plans a weekend bonding retreat.',
    ["Fun, I'm in", 0.2], ['I go, but keep to myself', 0.5], ['I find a reason to skip', 0.8]),
  q('attachment_avoidance_06', 'friends', 'high', `A friend says "I feel like I don't really know you."`,
    ['I share a little more', 0.5], ['I laugh it off', 0.8], ['Fair, I open up more', 0.2]),
  q('attachment_avoidance_07', 'friends', 'low', 'A friend wants to FaceTime every night this week.',
    ["That's a lot for me", 0.8], ['A couple of nights is fine', 0.5], ['Yes, I love that', 0.2]),
  q('attachment_avoidance_08', 'dating', 'high', 'Three months in, your date asks "so what are we?"',
    ['Glad they asked', 0.2], ['I need a minute to think', 0.5], ['I want to change the subject', 0.8]),
  q('attachment_avoidance_09', 'dating', 'low', 'Your partner wants to share locations on your phones.',
    ['Maybe for trips', 0.5], ["I'd rather not", 0.8], ['Sure, makes sense', 0.2]),
  q('attachment_avoidance_10', 'dating', 'high', 'Your partner leaves a toothbrush at your place.',
    ['Feels like a big step', 0.8], ['Fine, one toothbrush', 0.5], ['Cute, it can stay', 0.2]),
  q('attachment_avoidance_11', 'family', 'neither', 'Your mom asks how things are really going.',
    ['I tell her everything', 0.2], ['I tell her the highlights', 0.5], ['"Good, busy," and move on', 0.8]),
  q('attachment_avoidance_12', 'family', 'high', 'A relative hugs you for a long time at a family party.',
    ['A pat on the back', 0.5], ['I count the seconds', 0.8], ['I hug back', 0.2]),
  q('attachment_avoidance_13', 'solo', 'neither', 'A rough day, and you get home to an empty room.',
    ['Alone is how I recover', 0.8], ['I text one friend', 0.5], ['I call someone right away', 0.2]),
  q('attachment_avoidance_14', 'online', 'low', 'A new friend sends a long voice note about their feelings.',
    ['I send a long one back', 0.2], ['A short voice note back', 0.5], ['A text, keep it short', 0.8]),
  q('attachment_avoidance_15', 'online', 'neither', 'Your close friends make a private story for just the group.',
    ['I watch, post sometimes', 0.5], ['I mostly lurk', 0.8], ['I post there all the time', 0.2]),
  q('attachment_avoidance_16', 'money', 'neither', 'Your partner suggests a joint account for shared bills.',
    ['I keep my money separate', 0.8], ['Maybe for rent only', 0.5], ['Makes life easier', 0.2]),
  q('attachment_avoidance_17', 'money', 'high', 'A friend offers to pay for your dinner during a tight month.',
    ['Thank you, I accept', 0.2], ['I accept, then pay them back', 0.5], ["I say no, I'm fine", 0.8]),
  q('attachment_avoidance_18', 'stress', 'high', 'Sick in bed, and a friend offers to bring soup.',
    ['Leave it at the door', 0.5], ["No need, I'm fine", 0.8], ['Yes please', 0.2]),
  q('attachment_avoidance_19', 'stress', 'low', 'A friend going through a hard time texts you at midnight.',
    ['I reply in the morning', 0.8], ['I text back to check in', 0.5], ['I call them right away', 0.2]),
  q('attachment_avoidance_20', 'friends', 'neither', 'A friend you met recently invites you to meet their parents.',
    ['Sure, sounds fun', 0.2], ['A bit soon, but okay', 0.5], ['Too much too fast', 0.8]),
  q('attachment_avoidance_21', 'dating', 'neither', `Your date says "I think I'm falling for you" by text.`,
    ['A heart emoji for now', 0.5], ['I need a day to reply', 0.8], ['I tell them me too', 0.2]),
  q('attachment_avoidance_22', 'family', 'low', 'Your dad wants a weekly call to catch up.',
    ['Weekly feels like a lot', 0.8], ['Every other week works', 0.5], ["I'd love that", 0.2]),
  q('attachment_avoidance_23', 'solo', 'high', 'A friend asks to crash at your place for a week.',
    ['Sure, stay as long as you need', 0.2], ['A few nights is fine', 0.5], ['I suggest a hotel', 0.8]),
  q('attachment_avoidance_24', 'work', 'high', 'A coworker asks to grab a drink and get to know you.',
    ['Maybe a coffee', 0.5], ['I keep work and friends apart', 0.8], ["Sure, let's go", 0.2]),
  q('attachment_avoidance_25', 'online', 'neither', 'Someone you just started dating wants to follow all your accounts.',
    ['I keep some private', 0.8], ['The main one is fine', 0.5], ['Go ahead', 0.2]),
]);
