import { intake, q, traitBank } from './define';

/** Independence: "Just tell me the plan" (low) to "I'll do it my way" (high). */
export const AUTONOMY_BANK = traitBank('autonomy', [
  intake(1, q('autonomy_01', 'friends', 'high', 'A friend sends the whole trip plan in the chat, and it would work fine.',
    ["I'd still rather do it my way", 0.8], ["I'll use theirs if it saves time", 0.5], ["I'm glad I don't have to figure it out", 0.2])),
  intake(2, q('autonomy_02', 'online', 'high', 'Someone messages you step-by-step instructions for a thing you already know how to do.',
    ['It gets under my skin', 0.8], ['I notice it, then let it go', 0.5], ['Fine by me, less to think about', 0.2])),
  intake(3, q('autonomy_03', 'solo', 'neither', "Saturday's calendar is empty and nobody has texted.",
    ['Perfect, the day is mine', 0.8], ['Nice for a morning, then I make plans', 0.5], ['I start texting people for plans', 0.2])),
  q('autonomy_04', 'work', 'neither', 'Your boss gives you a project with zero instructions.',
    ['Finally, my call', 0.8], ['I ask a few questions first', 0.5], ['I ask for a clear brief', 0.2]),
  q('autonomy_05', 'work', 'high', 'A group project, and someone else wants to lead.',
    ['Great, less pressure', 0.2], ['I lead my part', 0.5], ['I end up steering anyway', 0.8]),
  q('autonomy_06', 'work', 'low', 'Two offers land in your inbox: a side hustle, or a steady job with a clear ladder.',
    ['Job now, hustle on weekends', 0.5], ['The side hustle, my rules', 0.8], ['The clear ladder', 0.2]),
  q('autonomy_07', 'friends', 'neither', 'Friends plan your birthday dinner as a surprise.',
    ["I'd rather pick myself", 0.8], ['Cute, if I get a say', 0.5], ['Love it, take over', 0.2]),
  q('autonomy_08', 'dating', 'high', 'Your partner offers to plan all your weekends.',
    ['Yes please', 0.2], ['Some weekends, sure', 0.5], ['No thanks, I like my own time', 0.8]),
  q('autonomy_09', 'dating', 'low', 'Your date orders for both of you at a restaurant.',
    ['Fine, if they ask first', 0.5], ['I order my own', 0.8], ['Nice, one less choice', 0.2]),
  q('autonomy_10', 'family', 'high', 'At dinner, your parents share strong opinions about your career.',
    ['I listen, then do my thing', 0.8], ['I take some of it on', 0.5], ['They know me, I follow it', 0.2]),
  q('autonomy_11', 'family', 'neither', 'Your mom sends a list of what to pack for your trip.',
    ['I follow it line by line', 0.2], ['I skim it for ideas', 0.5], ['I pack my own way', 0.8]),
  q('autonomy_12', 'solo', 'low', 'A week off, a flight booked, and nothing else planned.',
    ['A rough plan, then wander', 0.5], ['I love making it up as I go', 0.8], ['I book a tour with a schedule', 0.2]),
  q('autonomy_13', 'online', 'neither', 'Your phone suggests a new routine based on your habits.',
    ['I ignore it, I set my own', 0.8], ['I try a bit of it', 0.5], ['Great, I follow it', 0.2]),
  q('autonomy_14', 'online', 'high', 'A friend sends you a list of shows to watch, in order.',
    ['I follow the list exactly', 0.2], ['I start with the first', 0.5], ['I pick my own order', 0.8]),
  q('autonomy_15', 'money', 'neither', 'A friend shares a strict budget app they swear by.',
    ['I try it for a month', 0.5], ['I do budgets my own way', 0.8], ['I copy their setup', 0.2]),
  q('autonomy_16', 'money', 'low', 'Your bank app offers to auto-save for you each month.',
    ["I'd rather do it myself", 0.8], ['I set the amount myself', 0.5], ['Yes, automate it', 0.2]),
  q('autonomy_17', 'stress', 'high', 'A crisis at work and your boss starts telling everyone exactly what to do.',
    ['Relief, just tell me', 0.2], ['I follow, with tweaks', 0.5], ['I quietly do it my way', 0.8]),
  q('autonomy_18', 'stress', 'neither', 'Overwhelmed, and a friend offers to plan your week for you.',
    ['Help with one day', 0.5], ["Thanks, I'll manage", 0.8], ['Yes, please take over', 0.2]),
  q('autonomy_19', 'work', 'low', 'A class lets you choose your own project or follow a set one.',
    ['My own, every time', 0.8], ['Set one, with my twist', 0.5], ['The set one, less guessing', 0.2]),
  q('autonomy_20', 'friends', 'high', 'Friends take the same route on every road trip.',
    ['Their route is fine', 0.2], ['I suggest a new one', 0.5], ['I drive, so my route', 0.8]),
  q('autonomy_21', 'dating', 'neither', 'Your partner wants to share a calendar app for everything.',
    ['Shared for big plans only', 0.5], ['I keep my own calendar', 0.8], ['Yes, share it all', 0.2]),
  q('autonomy_22', 'family', 'low', 'Your family does the holidays the same way every year, down to the dinner.',
    ['I start my own way', 0.8], ['I add my own bits', 0.5], ['I love the tradition', 0.2]),
  q('autonomy_23', 'solo', 'high', 'A friend asks to join your solo gym session.',
    ['Yes, I could use company', 0.2], ['Sure, once', 0.5], ['Solo is solo', 0.8]),
  q('autonomy_24', 'money', 'neither', 'A coworker offers to set up your retirement plan for you.',
    ['I take their advice', 0.5], ["I'd rather learn it", 0.8], ['Yes, please do it', 0.2]),
  q('autonomy_25', 'online', 'low', 'An app picks your music for the day based on your mood.',
    ['I pick my own music', 0.8], ['I skip half of it', 0.5], ['I let it play', 0.2]),
]);
