import { intake, q, traitBank } from './define';

/** Confidence: "I'm not sure I can do this" (low) to "Send it to me" (high). */
export const COMPETENCE_BANK = traitBank('competence', [
  intake(1, q('competence_01', 'work', 'low', 'A hard task lands in your inbox with your name on it.',
    ['I feel like I can handle it', 0.8], ['Depends how hard, honestly', 0.5], ['I doubt I can pull it off', 0.2])),
  intake(2, q('competence_02', 'solo', 'low', 'Three weeks into a language app, and it still marks you wrong.',
    ['I can feel myself getting better', 0.8], ['Some days it clicks', 0.5], ['I mostly feel behind', 0.2])),
  intake(3, q('competence_03', 'work', 'low', "Someone at work messages: 'this is your area, right?'",
    ['Fair, it is', 0.8], ["Probably, I'd double-check", 0.5], ["I'm sure they mean someone else", 0.2])),
  q('competence_04', 'work', 'high', 'Your boss asks who can present to the client tomorrow.',
    ['Me, no prep needed', 0.8], ['Me, if I get tonight to prep', 0.5], ['Anyone but me', 0.2]),
  q('competence_05', 'work', 'neither', 'Your exam grade pops up in the app, better than you expected.',
    ['They must have graded easy', 0.2], ['Nice, I got a bit lucky', 0.5], ['Makes sense, I studied', 0.8]),
  q('competence_06', 'friends', 'high', 'A flat tire on a road trip, and nobody in the car has fixed one.',
    ['I look up a video with them', 0.5], ['Move, I got this', 0.8], ['I call for help', 0.2]),
  q('competence_07', 'friends', 'low', 'A friend asks you to cook for their dinner party.',
    ['Sure, I can pull it off', 0.8], ['I can do a simple dish', 0.5], ['I bring drinks instead', 0.2]),
  q('competence_08', 'dating', 'neither', 'Your date scrolls your photos and says you have real talent.',
    ["I'm really not that good", 0.2], ['Thanks, still learning', 0.5], ['Thanks, I worked at it', 0.8]),
  q('competence_09', 'dating', 'high', 'Your partner asks you to help them with their resume.',
    ['I can give a few notes', 0.5], ["Send it, I'll fix it", 0.8], ["I'm not the best at that", 0.2]),
  q('competence_10', 'family', 'low', 'Your parents ask you to fix their phone settings.',
    ['Easy, hand it over', 0.8], ['I can try', 0.5], ["Let's call the store", 0.2]),
  q('competence_11', 'family', 'neither', 'Your little cousin texts you a photo of their math homework.',
    ['Ask someone smarter', 0.2], ["I'll try, no promises", 0.5], ['Sure, I can explain it', 0.8]),
  q('competence_12', 'solo', 'high', 'First time cooking a new recipe in your kitchen, no video to follow.',
    ['I follow it closely', 0.5], ["I wing it, it'll be fine", 0.8], ['I order delivery as backup', 0.2]),
  q('competence_13', 'online', 'neither', 'A friend shares a tricky puzzle game in the group chat.',
    ['I solve it first', 0.8], ['I give it a go', 0.5], ['I wait for the answer', 0.2]),
  q('competence_14', 'online', 'low', 'Your post on a hobby forum gets a question from a beginner.',
    ['Someone else will know better', 0.2], ['I answer with a disclaimer', 0.5], ['I answer, I know this', 0.8]),
  q('competence_15', 'money', 'neither', 'Tax season, and this year you file your own in an app.',
    ['I use an app and hope', 0.5], ['I can figure it out', 0.8], ['I pay someone right away', 0.2]),
  q('competence_16', 'money', 'high', 'A friend asks for tips on investing their first paycheck.',
    ['I have a whole plan for them', 0.8], ['I share what I do', 0.5], ["I'm the wrong person", 0.2]),
  q('competence_17', 'stress', 'low', 'Something breaks at work and everyone looks at you.',
    ["I'm in over my head", 0.2], ["I'll try my best", 0.5], ['I can fix this', 0.8]),
  q('competence_18', 'stress', 'neither', 'The day before your exam, the class changes the topic.',
    ["I'll scrape by", 0.5], ['I can still do well', 0.8], ["I'm going to fail", 0.2]),
  q('competence_19', 'work', 'low', 'You get asked to train the new hire on your team.',
    ['Sure, I know this well', 0.8], ['I can show the basics', 0.5], ['I barely know it myself', 0.2]),
  q('competence_20', 'friends', 'high', 'Your friends plan a trivia night with a topic you love.',
    ["I'll just be there for fun", 0.2], ["I'll help a bit", 0.5], ["We're winning this", 0.8]),
  q('competence_21', 'dating', 'low', 'Your partner asks you to plan a trip abroad.',
    ['I can try', 0.5], ['On it, I love planning', 0.8], ["I'd mess it up", 0.2]),
  q('competence_22', 'family', 'high', 'At dinner, your family debates a topic you studied.',
    ['I set them straight', 0.8], ['I add what I know', 0.5], ['I stay quiet', 0.2]),
  q('competence_23', 'solo', 'neither', 'New furniture for your room, and the instructions are only pictures.',
    ['I give up halfway', 0.2], ['A few extra screws left over', 0.5], ['Done in an hour', 0.8]),
  q('competence_24', 'money', 'low', 'Your phone plan bill looks wrong.',
    ['I look it over', 0.5], ['I call and sort it out', 0.8], ['I just pay it', 0.2]),
  q('competence_25', 'online', 'high', 'A post in your feed says a skill you have takes years to learn.',
    ['Took me weeks', 0.8], ['Sounds about right', 0.5], ["I'm still not there", 0.2]),
]);
