import { intake, q, traitBank } from './define';

/** Compromise: "This is what I need" (low) to "What would work for you?" (high). */
export const CONFLICT_COOPERATIVENESS_BANK = traitBank('conflict_cooperativeness', [
  intake(1, q('conflict_cooperativeness_01', 'friends', 'neither', 'You and a friend each sent a different dinner spot. Who gives first?',
    ['Probably me', 0.8], ['Depends who cares more', 0.5], ['Rarely me', 0.2])),
  intake(2, q('conflict_cooperativeness_02', 'dating', 'low', 'A text argument is ten messages deep and it is getting late.',
    ['I find something we can both live with', 0.8], ['I park it for tomorrow', 0.5], ['I hold my line', 0.2])),
  intake(3, q('conflict_cooperativeness_03', 'online', 'neither', 'The group chat is arguing and you know the right answer.',
    ['I let it go to keep the chat calm', 0.8], ['I say it once, then drop it', 0.5], ['I send the link that proves it', 0.2])),
  q('conflict_cooperativeness_04', 'work', 'neither', 'You and a coworker want different approaches to the same project.',
    ['We mix the best of both', 0.8], ['We try theirs, then mine', 0.5], ['Mine is better, I push it', 0.2]),
  q('conflict_cooperativeness_05', 'work', 'high', 'Your boss wants a change you think is a mistake.',
    ['I argue my case to the end', 0.2], ['I raise it once, then do it', 0.5], ['I find a version we both like', 0.8]),
  q('conflict_cooperativeness_06', 'friends', 'low', 'Friends disagree on where to go for the trip.',
    ['I vote and go with the rest', 0.5], ['I look for a spot that fits all', 0.8], ['I lobby hard for my pick', 0.2]),
  q('conflict_cooperativeness_07', 'friends', 'high', 'A friend is upset you missed their party for work.',
    ['I offer to make it up to them', 0.8], ['I explain and apologize', 0.5], ['Work comes first, they know', 0.2]),
  q('conflict_cooperativeness_08', 'dating', 'neither', 'You want a night in. Your partner wants a night out.',
    ['I stay in, they go out', 0.2], ['We take turns each week', 0.5], ['Dinner out, early night', 0.8]),
  q('conflict_cooperativeness_09', 'dating', 'high', 'Your partner wants to move to a new city for their job.',
    ['I need time to think', 0.5], ['We figure out how it works for both', 0.8], ['My life is here', 0.2]),
  q('conflict_cooperativeness_10', 'family', 'low', 'The family group chat argues about where to spend the holidays.',
    ['I suggest splitting the days', 0.8], ['I go where most want', 0.5], ["I say where I'm going", 0.2]),
  q('conflict_cooperativeness_11', 'family', 'neither', 'Your sibling wants the bigger room on the family trip.',
    ['I called it first', 0.2], ['Fine, this time', 0.5], ['We flip a coin', 0.8]),
  q('conflict_cooperativeness_12', 'solo', 'neither', 'Two friends each text you to pick a side in their fight.',
    ['I stay out of it', 0.5], ['I help them meet halfway', 0.8], ["I say who's right", 0.2]),
  q('conflict_cooperativeness_13', 'online', 'low', 'A comment thread about your post turns into a debate.',
    ['I reply to find common ground', 0.8], ['I mute the thread', 0.5], ['I defend my take', 0.2]),
  q('conflict_cooperativeness_14', 'online', 'high', 'Your gaming squad argues about which game to play tonight.',
    ['My pick or I log off', 0.2], ['Majority vote', 0.5], ['Two rounds each, everybody wins', 0.8]),
  q('conflict_cooperativeness_15', 'money', 'neither', 'Your roommate wants to split the bills by room size.',
    ['Fine, if the math is clear', 0.5], ["Fair, let's work it out", 0.8], ['Even split, like we agreed', 0.2]),
  q('conflict_cooperativeness_16', 'money', 'low', 'You and your partner disagree on a big purchase.',
    ['We find a cheaper middle option', 0.8], ['We wait a month and decide', 0.5], ['I buy what I think is right', 0.2]),
  q('conflict_cooperativeness_17', 'stress', 'high', 'A heated text with a friend late at night, both of you tired.',
    ['I wait for their apology', 0.2], ['We call a pause', 0.5], ['I say sorry first to end it', 0.8]),
  q('conflict_cooperativeness_18', 'stress', 'neither', 'A tight deadline, and the team disagrees on the plan.',
    ['I go with the loudest idea', 0.5], ['I pull together a plan for all', 0.8], ['I do my part my way', 0.2]),
  q('conflict_cooperativeness_19', 'work', 'low', 'Two coworkers both want Friday off and ask you to decide.',
    ['Half day each', 0.8], ['Whoever asked first', 0.5], ['I pick and move on', 0.2]),
  q('conflict_cooperativeness_20', 'friends', 'neither', 'A friend thinks your joke at brunch was rude.',
    ['It was just a joke', 0.2], ['I say sorry, it was a joke', 0.5], ['I ask how I can fix it', 0.8]),
  q('conflict_cooperativeness_21', 'dating', 'low', 'Your partner hates the show you love watching together.',
    ['I watch mine alone', 0.5], ['We find a new one together', 0.8], ['They can learn to like it', 0.2]),
  q('conflict_cooperativeness_22', 'family', 'high', 'Your mom and dad disagree with a big choice you made.',
    ['I hear them out and adjust', 0.8], ['I listen, then do my thing', 0.5], ['My life, my choice', 0.2]),
  q('conflict_cooperativeness_23', 'solo', 'neither', 'You and a stranger both reach for the last item on the shelf.',
    ['I got it first', 0.2], ['Whoever grabbed first', 0.5], ['We split it or I let it go', 0.8]),
  q('conflict_cooperativeness_24', 'money', 'high', 'Friends want a pricey restaurant for a birthday dinner.',
    ['I go and order light', 0.5], ['I suggest a place for all budgets', 0.8], ["I say it's too much for me", 0.2]),
  q('conflict_cooperativeness_25', 'online', 'neither', 'The group chat argues about the date for a reunion.',
    ['I make a poll in the chat', 0.8], ['I go with any date', 0.5], ['I say the date I can do', 0.2]),
]);
