import { intake, q, traitBank } from './define';

/** Directness: "It's fine, never mind" (low) to "Actually, I disagree" (high). */
export const CONFLICT_ASSERTIVENESS_BANK = traitBank('conflict_assertiveness', [
  intake(1, q('conflict_assertiveness_01', 'work', 'high', 'On a work call, someone says something you think is wrong.',
    ['I say so, even if it gets a bit sharp', 0.8], ['I wait to see if it blows over', 0.5], ['I let it go rather than push', 0.2])),
  intake(2, q('conflict_assertiveness_02', 'solo', 'neither', 'The order is wrong and the place is busy.',
    ['I send it back', 0.8], ['Depends how wrong', 0.5], ['I eat it', 0.2])),
  intake(3, q('conflict_assertiveness_03', 'friends', 'low', "Your roommate's music is loud and asking might annoy them.",
    ['I ask anyway', 0.8], ['I let it go', 0.2])),
  q('conflict_assertiveness_04', 'work', 'low', "Your boss hands you extra work that isn't your job.",
    ["I say it's not my role", 0.8], ['I do it, but mention it', 0.5], ['I just do it', 0.2]),
  q('conflict_assertiveness_05', 'work', 'high', "A classmate isn't pulling their weight on a group project.",
    ['I do their part', 0.2], ['I message them privately', 0.5], ['I call it out in the group chat', 0.8]),
  q('conflict_assertiveness_06', 'friends', 'low', 'A friend keeps borrowing your clothes and returning them stained.',
    ['I drop a hint', 0.5], ['I tell them it has to stop', 0.8], ['I stop lending, quietly', 0.2]),
  q('conflict_assertiveness_07', 'friends', 'high', 'Someone at the table tells a story you know is half made up.',
    ['I correct the details', 0.8], ['I raise an eyebrow', 0.5], ['I let them have it', 0.2]),
  q('conflict_assertiveness_08', 'dating', 'low', 'Your date keeps checking their phone at dinner.',
    ['I pull out mine too', 0.2], ['I make a joke about it', 0.5], ['I ask them to put it away', 0.8]),
  q('conflict_assertiveness_09', 'dating', 'neither', 'Your partner makes plans for both of you without asking.',
    ['I mention it later', 0.5], ['I tell them to ask first', 0.8], ['I go along with it', 0.2]),
  q('conflict_assertiveness_10', 'family', 'high', 'A relative gives unasked-for opinions about your life at dinner.',
    ["I tell them it's my call", 0.8], ['I change the subject', 0.5], ['I smile and nod', 0.2]),
  q('conflict_assertiveness_11', 'family', 'low', 'Your parents plan your visit without checking your calendar.',
    ['I cancel my plans', 0.2], ['I try to shuffle my plans', 0.5], ["I tell them that doesn't work", 0.8]),
  q('conflict_assertiveness_12', 'solo', 'neither', 'Someone takes the seat you saved on the train.',
    ['I point at my bag', 0.5], ['I ask them to move', 0.8], ['I find another seat', 0.2]),
  q('conflict_assertiveness_13', 'online', 'high', 'A post spreads something false about a topic you know well.',
    ['I comment the facts', 0.8], ['I share a correction to my story', 0.5], ['I scroll on', 0.2]),
  q('conflict_assertiveness_14', 'online', 'neither', 'A friend posts a photo of you without asking.',
    ['I leave it', 0.2], ['I ask for a better one', 0.5], ['I ask them to take it down', 0.8]),
  q('conflict_assertiveness_15', 'money', 'low', "A shop charges you twice and the cashier doesn't notice.",
    ['I check my bank app later', 0.5], ['I point it out right there', 0.8], ['Not worth the hassle', 0.2]),
  q('conflict_assertiveness_16', 'money', 'high', 'Your landlord ignores your texts about a broken heater.',
    ['I send a formal email with dates', 0.8], ['I text again, firmer', 0.5], ['I buy a space heater', 0.2]),
  q('conflict_assertiveness_17', 'money', 'neither', 'A job offer email comes in lower than you hoped.',
    ['I take it as is', 0.2], ["I ask if there's room", 0.5], ['I negotiate', 0.8]),
  q('conflict_assertiveness_18', 'stress', 'low', 'Your neighbor has a party at 1am on a work night.',
    ['I text them a note', 0.5], ['I knock and ask them to stop', 0.8], ['Earplugs and suffer', 0.2]),
  q('conflict_assertiveness_19', 'stress', 'high', 'A tense team meeting, and someone blames you unfairly.',
    ['I push back right then', 0.8], ['I clear it up after', 0.5], ['I let it slide', 0.2]),
  q('conflict_assertiveness_20', 'friends', 'neither', 'The group chat keeps picking the place you like least.',
    ['I go along again', 0.2], ['I suggest an option', 0.5], ['I veto it this time', 0.8]),
  q('conflict_assertiveness_21', 'dating', 'low', 'A date makes a joke at your expense in front of friends.',
    ['I bring it up later', 0.5], ["I tell them it wasn't funny", 0.8], ['I laugh along', 0.2]),
  q('conflict_assertiveness_22', 'family', 'neither', 'Your sister borrows your car and returns it on empty.',
    ['I ask her to fill it up', 0.8], ['I mention it', 0.5], ['I fill it myself', 0.2]),
  q('conflict_assertiveness_23', 'work', 'neither', 'In a meeting, someone keeps talking over you.',
    ['I stop talking', 0.2], ['I wait, then try again', 0.5], ['I say "let me finish"', 0.8]),
  q('conflict_assertiveness_24', 'online', 'low', 'A friend shares your private message in the group chat.',
    ['I send a "hey, not cool"', 0.5], ["I tell them that wasn't okay", 0.8], ['I say nothing', 0.2]),
  q('conflict_assertiveness_25', 'solo', 'high', 'A waiter brings your food cold for the second time.',
    ['I ask for the manager', 0.8], ['I ask for it heated up', 0.5], ['I eat it cold', 0.2]),
]);
