import { intake, q, traitBank } from './define';

/** Follow-through: "I'll figure it out when I get there" (low) to "I said I'd finish it, so I did" (high). */
export const CONSCIENTIOUSNESS_BANK = traitBank('conscientiousness', [
  intake(1, q('conscientiousness_01', 'solo', 'low', 'The plan you put in your calendar last week hits its boring part today.',
    ['I still see it through', 0.8], ['I keep it if it stays easy', 0.5], ['I switch to whatever feels better', 0.2])),
  intake(2, q('conscientiousness_02', 'work', 'low', 'Monday. Your calendar says it is due Friday.',
    ['I start chipping at it now', 0.8], ['I start once it feels close', 0.5], ['Thursday night, like last time', 0.2])),
  intake(3, q('conscientiousness_03', 'friends', 'low', "You said you'd send someone a link. Nobody followed up.",
    ['I still send it', 0.8], ['It quietly disappears', 0.2])),
  q('conscientiousness_04', 'work', 'high', 'A group project, and one teammate keeps changing the doc you formatted.',
    ['I fix it back every time', 0.8], ['I mention it once', 0.5], ['As long as it gets done', 0.2]),
  q('conscientiousness_05', 'work', 'low', 'Your inbox has 200 unread emails.',
    ["That's just my inbox", 0.2], ['I clear it most weeks', 0.5], ['That would never happen', 0.8]),
  q('conscientiousness_06', 'friends', 'high', 'Friends want a spontaneous weekend trip and nobody has made a plan.',
    ["I book the place, that's it", 0.5], ['I make the shared doc anyway', 0.8], ['We figure it out there', 0.2]),
  q('conscientiousness_07', 'friends', 'low', "You owe a friend money from dinner. They haven't mentioned it.",
    ['I send it that night', 0.8], ['Next time I remember', 0.5], ['They will ask if it matters', 0.2]),
  q('conscientiousness_08', 'dating', 'neither', "You said you would plan the next date. It's Thursday.",
    ['We will just text and see', 0.2], ["I'm looking at options now", 0.5], ['It has been booked since Monday', 0.8]),
  q('conscientiousness_09', 'dating', 'high', 'Your partner leaves dishes in the sink overnight.',
    ['I notice, then let it go', 0.5], ["It bugs me until they're done", 0.8], ['Tomorrow is fine', 0.2]),
  q('conscientiousness_10', 'family', 'low', 'Your mom asks you to call the dentist and book her appointment.',
    ['Done before she hangs up', 0.8], ['Sometime this week', 0.5], ["I'll do it in a minute", 0.2]),
  q('conscientiousness_11', 'family', 'neither', 'Packing for a family trip the night before the flight.',
    ['I throw it in tonight', 0.2], ['I have a list, mostly', 0.5], ['I packed two days ago', 0.8]),
  q('conscientiousness_12', 'solo', 'low', 'Your phone says your screen time is up 40% this week.',
    ['I cut back a little', 0.5], ['I set a limit and keep it', 0.8], ['I set a limit and ignore it', 0.2]),
  q('conscientiousness_13', 'solo', 'neither', 'Clean laundry has been in the basket by your bed for four days.',
    ['That would bother me', 0.8], ['I fold it this weekend', 0.5], ['I wear it from the basket', 0.2]),
  q('conscientiousness_14', 'online', 'low', "A friend sends a voice note you haven't listened to yet. It has been a week.",
    ['Same. They know me', 0.2], ['I listen when I get a minute', 0.5], ["That wouldn't happen", 0.8]),
  q('conscientiousness_15', 'online', 'high', 'Your phone home screen right now.',
    ['Kind of grouped', 0.5], ['Folders, sorted, labeled', 0.8], ['Five pages of chaos', 0.2]),
  q('conscientiousness_16', 'money', 'neither', 'A subscription you stopped using renews tomorrow.',
    ['Already canceled it', 0.8], ['I cancel when the email comes', 0.5], ['I keep meaning to cancel', 0.2]),
  q('conscientiousness_17', 'money', 'high', 'Someone asks what you spent on food last month.',
    ["I'd rather not look", 0.2], ['Roughly, I think', 0.5], ['I can tell you to the dollar', 0.8]),
  q('conscientiousness_18', 'stress', 'low', 'A deadline, an exam and a move, all in the same week.',
    ['I list them, then wing it', 0.5], ['I map out every day', 0.8], ['I do whichever is loudest', 0.2]),
  q('conscientiousness_19', 'stress', 'neither', 'A late night, and the work is good enough to send.',
    ['I send it and sleep', 0.2], ['I check it one more time', 0.8]),
  q('conscientiousness_20', 'work', 'neither', 'Your boss says the deadline moved a week later.',
    ['I use the extra week', 0.2], ['I slow down a little', 0.5], ['I still finish on the old date', 0.8]),
  q('conscientiousness_21', 'friends', 'high', 'Friends are late again and the reservation is in ten minutes.',
    ['I nudge the group chat', 0.5], ['I already texted the restaurant', 0.8], ['I wait and hope', 0.2]),
  q('conscientiousness_22', 'solo', 'low', "You downloaded a habit app on New Year's. It's March.",
    ['Still logging every day', 0.8], ['I open it now and then', 0.5], ['What app?', 0.2]),
  q('conscientiousness_23', 'money', 'low', 'A friend sends a payment request for concert tickets.',
    ['I pay when they remind me', 0.2], ['Paid by the weekend', 0.5], ['Paid within the hour', 0.8]),
  q('conscientiousness_24', 'dating', 'neither', "It's your turn to remember the anniversary dinner booking.",
    ['I remember the week of', 0.5], ['Calendar reminder, set months ago', 0.8], ['Hoping they booked it', 0.2]),
  q('conscientiousness_25', 'family', 'high', 'Your sister borrows your charger and puts it back in the wrong spot.',
    ["It's a charger, it's fine", 0.2], ['I move it back right away', 0.8]),
]);
