import { intake, q, traitBank } from './define';

/** Sociability: "I need a night in" (low) to "Who's around tonight?" (high). */
export const EXTRAVERSION_BANK = traitBank('extraversion', [
  intake(1, q('extraversion_01', 'friends', 'neither', 'Saturday afternoon and the group chat is quiet.',
    ['I text a few people and make plans', 0.8], ["Either way, I'm fine", 0.5], ['I keep the afternoon quiet', 0.2])),
  intake(2, q('extraversion_02', 'friends', 'low', 'You walk into a party and know two people. Both are on their phones.',
    ['I start talking to someone new', 0.8], ['I go stand with the two I know', 0.5], ["I'm counting the minutes", 0.2])),
  intake(3, q('extraversion_03', 'friends', 'neither', 'Friday, 6pm. Three invites in the group chat.',
    ["I'm going to at least one", 0.8], ['Couch. Phone on silent', 0.2])),
  q('extraversion_04', 'work', 'neither', 'Lunch break at work, and coworkers are heading out together.',
    ['I go, I need the chatter', 0.8], ['I join some days', 0.5], ['Desk lunch, headphones in', 0.2]),
  q('extraversion_05', 'work', 'high', 'A meeting goes quiet after the boss asks a question.',
    ['I wait it out', 0.2], ['I talk if I have something', 0.5], ['I fill the silence, every time', 0.8]),
  q('extraversion_06', 'work', 'neither', "First day at a new job, and there's an after-work drinks thing.",
    ['I go for one drink', 0.5], ["I'm there and staying late", 0.8], ['I skip the first one', 0.2]),
  q('extraversion_07', 'dating', 'neither', 'The perfect date night, honestly.',
    ['A busy bar with friends of friends', 0.8], ['Dinner, just the two of us', 0.5], ['Takeout on the couch', 0.2]),
  q('extraversion_08', 'dating', 'high', 'Your partner wants a quiet weekend in, and you got invited to a party.',
    ['Quiet weekend sounds great', 0.2], ['I try to talk them into it', 0.5], ['I go, they can stay in', 0.8]),
  q('extraversion_09', 'family', 'neither', 'A big family birthday with cousins you barely know.',
    ['I stick near my people', 0.5], ['I end up chatting with everyone', 0.8], ['I find the dog and hide', 0.2]),
  q('extraversion_10', 'family', 'low', 'Your mom puts you on speaker with the whole family at dinner.',
    ['I love it, hi everyone', 0.8], ['I say hi, then fade out', 0.5], ['I suddenly have to go', 0.2]),
  q('extraversion_11', 'solo', 'neither', 'You have the apartment to yourself all weekend.',
    ["Heaven. Don't disturb", 0.2], ['A day alone, then I text someone', 0.5], ['By Saturday night I make plans', 0.8]),
  q('extraversion_12', 'solo', 'low', 'A friend calls instead of texting.',
    ['I pick up if I have a minute', 0.5], ['I pick up right away', 0.8], ['I let it ring and text back', 0.2]),
  q('extraversion_13', 'online', 'high', 'Your story from last night got a lot of replies.',
    ['I answer every single one', 0.8], ['I reply to a few', 0.5], ['I post rarely, so no', 0.2]),
  q('extraversion_14', 'online', 'neither', 'A group voice chat starts in the app while you scroll.',
    ['I stay offline', 0.2], ['I listen for a bit first', 0.5], ['I jump in right away', 0.8]),
  q('extraversion_15', 'online', 'neither', 'The group chat has 87 new messages since this morning.',
    ['I scroll up and catch up', 0.5], ['Probably half of them are mine', 0.8], ['I mark it read', 0.2]),
  q('extraversion_16', 'money', 'neither', 'An extra $100 lands in your bank app this month.',
    ['Concert tickets for the group', 0.8], ['A dinner out with one friend', 0.5], ['Something nice for home', 0.2]),
  q('extraversion_17', 'money', 'high', 'Your bank app shows how much went on going out this month.',
    ['Barely anything there', 0.2], ['A bit much, but fine', 0.5], ['Worth it, every night', 0.8]),
  q('extraversion_18', 'stress', 'neither', 'A rough day at work, and you get home at 7.',
    ['I text one person', 0.5], ['I call someone to vent', 0.8], ['Phone down, nobody', 0.2]),
  q('extraversion_19', 'stress', 'low', 'A friend asks you to come out tonight after a long week.',
    ["Yes, that's my reset", 0.8], ['Maybe for an hour', 0.5], ['I cancel on myself', 0.2]),
  q('extraversion_20', 'friends', 'high', "Someone you just met at a party says they're going to a second spot.",
    ['I head home', 0.2], ["Depends who's going", 0.5], ["I'm coming, who else", 0.8]),
  q('extraversion_21', 'friends', 'low', 'Plans got canceled an hour before.',
    ['Bit sad, bit relieved', 0.5], ['I find another plan fast', 0.8], ['Secretly thrilled', 0.2]),
  q('extraversion_22', 'dating', 'neither', 'On a first date, the bartender starts chatting with you both.',
    ['I bring them into the chat', 0.8], ['Friendly, then back to us', 0.5], ['I hope they move on', 0.2]),
  q('extraversion_23', 'family', 'high', 'At a family dinner, the stories start.',
    ['I listen and laugh', 0.2], ['I add one or two', 0.5], ['I tell most of them', 0.8]),
  q('extraversion_24', 'solo', 'low', 'A neighbor in the hallway stops you for a chat.',
    ['A quick catch-up', 0.5], ['I could talk for an hour', 0.8], ['I wave and keep walking', 0.2]),
  q('extraversion_25', 'stress', 'neither', 'Your phone is buzzing with plans after a draining week.',
    ['More people, more energy', 0.8], ['One small plan, max', 0.5], ['Phone on silent until Monday', 0.2]),
]);
