import { intake, q, traitBank } from './define';

/** Growth: "Maybe this just isn't my thing" (low) to "Okay, what do I change?" (high). */
export const GROWTH_MINDSET_BANK = traitBank('growth_mindset', [
  intake(1, q('growth_mindset_01', 'solo', 'low', 'Your first try at a recipe from a video goes badly. What actually happens next?',
    ["I look at what I'd do differently", 0.8], ["I probably don't try that again", 0.2])),
  intake(2, q('growth_mindset_02', 'online', 'low', 'Someone online is much better than you at a thing you care about.',
    ['I want to know how they got there', 0.8], ['Good for them, different lane', 0.5], ['Some people just have it', 0.2])),
  intake(3, q('growth_mindset_03', 'online', 'neither', 'A friend posts day 60 of learning something new.',
    ['Give me 60 days and I could too', 0.8], ['Depends on the thing', 0.5], ['Some people are just built for it', 0.2])),
  q('growth_mindset_04', 'work', 'low', 'Your boss gives you tough feedback on a project.',
    ['I ask how to get better', 0.8], ['I take some of it', 0.5], ["I'm just not good at this", 0.2]),
  q('growth_mindset_05', 'work', 'neither', 'A bad grade on your first exam in a new class.',
    ["This class isn't for me", 0.2], ['I hope the next one is easier', 0.5], ['I change how I study', 0.8]),
  q('growth_mindset_06', 'work', 'high', 'A coworker says your work is "good enough."',
    ['Fair, I take the win', 0.5], ["Good enough isn't my goal", 0.8], ["Great, I'm done", 0.2]),
  q('growth_mindset_07', 'friends', 'neither', 'Friends invite you to a dance class. You have two left feet.',
    ["I go, I'll get better", 0.8], ['I go and watch', 0.5], ["I'm not a dancer", 0.2]),
  q('growth_mindset_08', 'friends', 'high', 'You lose every game on board game night.',
    ["I'm just bad at games", 0.2], ['Next time, maybe', 0.5], ['I look up strategy guides after', 0.8]),
  q('growth_mindset_09', 'dating', 'low', 'A relationship ends and your friend asks what you learned.',
    ['A few things', 0.5], ["A lot, I'm working on it", 0.8], ["That I'm bad at dating", 0.2]),
  q('growth_mindset_10', 'dating', 'neither', 'Your partner says you could be a better listener.',
    ['I ask how I can do better', 0.8], ['I try, when I remember', 0.5], ["That's just how I'm", 0.2]),
  q('growth_mindset_11', 'family', 'low', 'At dinner, your family jokes you have never been good at cooking.',
    ["They're right, I never will be", 0.2], ["I laugh, they aren't wrong", 0.5], ['I take a cooking class', 0.8]),
  q('growth_mindset_12', 'family', 'high', 'Your dad says "you were never a math person."',
    ['Maybe, but I could learn', 0.5], ['Watch me become one', 0.8], ["Fair, I'm not", 0.2]),
  q('growth_mindset_13', 'solo', 'neither', 'A guitar sits in the corner of your room, half-learned.',
    ['I pick it up again this week', 0.8], ['Someday, when I have time', 0.5], ["Music isn't my thing", 0.2]),
  q('growth_mindset_14', 'online', 'high', 'Your fitness app says you fell behind your goal this month.',
    ['I turn off the alerts', 0.2], ['I try to catch up', 0.5], ['I adjust and push harder', 0.8]),
  q('growth_mindset_15', 'money', 'neither', 'Your first try at budgeting in an app falls apart by week two.',
    ['I try a different app', 0.5], ['I tweak it and try again', 0.8], ["I'm just bad with money", 0.2]),
  q('growth_mindset_16', 'money', 'low', 'A side hustle you started online makes zero sales in a month.',
    ["I change what I'm doing", 0.8], ['I give it one more month', 0.5], ["I knew it wouldn't work", 0.2]),
  q('growth_mindset_17', 'stress', 'high', 'A rough week, and you make the same mistake twice at work.',
    ["I'm just like this", 0.2], ['I note it for later', 0.5], ['I figure out why, right away', 0.8]),
  q('growth_mindset_18', 'stress', 'neither', 'A presentation goes badly in front of the whole class.',
    ['I try to forget it', 0.5], ['I practice more next time', 0.8], ['I avoid presenting again', 0.2]),
  q('growth_mindset_19', 'work', 'low', 'A new tool at work is confusing and everyone else gets it.',
    ['I watch tutorials until I do', 0.8], ['I ask someone to show me', 0.5], ["I'm just not a tech person", 0.2]),
  q('growth_mindset_20', 'friends', 'low', 'A friend beats you at a game you have played for years.',
    ["They're just a natural", 0.2], ['Good game, rematch', 0.5], ['I ask them for tips', 0.8]),
  q('growth_mindset_21', 'dating', 'high', 'A date says your texts come across as cold.',
    ['I add more emojis', 0.5], ['I work on my texting', 0.8], ["That's just how I text", 0.2]),
  q('growth_mindset_22', 'family', 'neither', 'Your sister learned to code in six months.',
    ['I could learn it too', 0.8], ['Maybe, with time', 0.5], ['She got the brains', 0.2]),
  q('growth_mindset_23', 'solo', 'high', 'You finally run a 5k. Your phone shows your time.',
    ['Done, never again', 0.2], ['Proud, maybe again', 0.5], ['Already planning to beat it', 0.8]),
  q('growth_mindset_24', 'money', 'neither', 'Your first try at selling old clothes in an app gets no buyers.',
    ['I wait a few more weeks', 0.5], ['I change the photos and price', 0.8], ['I donate them instead', 0.2]),
  q('growth_mindset_25', 'online', 'low', 'Your first post on a new account gets 12 views.',
    ['I study what works and try again', 0.8], ['I post a few more', 0.5], ['I delete the account', 0.2]),
]);
