import { intake, q, traitBank } from './define';

/** Ownership: "It was bound to happen" (low) to "What could I have done differently?" (high). */
export const LOCUS_OF_CONTROL_BANK = traitBank('locus_of_control', [
  intake(1, q('locus_of_control_01', 'friends', 'neither', 'The group trip you helped plan falls apart in the chat.',
    ['I look at what I could have done', 0.8], ["Some of it was me, some wasn't", 0.5], ['It was bound to happen', 0.2])),
  intake(2, q('locus_of_control_02', 'work', 'neither', "A good week, and someone texts 'how did you pull that off?'",
    ['Honestly, I worked for it', 0.8], ['A bit of both', 0.5], ['Good timing, mostly', 0.2])),
  intake(3, q('locus_of_control_03', 'solo', 'low', 'New year, blank calendar. How it goes is mostly…',
    ['Up to what I do', 0.8], ['Half me, half luck', 0.5], ['Up to what happens', 0.2])),
  q('locus_of_control_04', 'work', 'low', 'You miss a deadline at work.',
    ['I should have started sooner', 0.8], ['Bit of me, bit of the week', 0.5], ['Too much landed at once', 0.2]),
  q('locus_of_control_05', 'work', 'high', 'Your team project gets a bad grade.',
    ['The grading was unfair', 0.2], ['We all could have done more', 0.5], ['I go over what I did wrong', 0.8]),
  q('locus_of_control_06', 'work', 'neither', 'The job offer email arrives after your interview.',
    ['Prep and a good day', 0.5], ['I prepped hard for it', 0.8], ['They must have liked my vibe', 0.2]),
  q('locus_of_control_07', 'friends', 'high', 'A friendship fades after you move away for work.',
    ['I should have called more', 0.8], ['We both let it slide', 0.5], ['Distance does that', 0.2]),
  q('locus_of_control_08', 'friends', 'low', 'You show up late and miss the start of the movie with friends.',
    ['The bus was slow', 0.2], ['Traffic and me, both', 0.5], ['My fault, I left late', 0.8]),
  q('locus_of_control_09', 'dating', 'neither', 'A date never texts back after a good night.',
    ['Maybe a bit of both', 0.5], ['I wonder what I could change', 0.8], ['Not meant to be', 0.2]),
  q('locus_of_control_10', 'dating', 'high', 'Your partner is in a bad mood all evening.',
    ['I wonder what I did', 0.8], ['I ask what is up', 0.5], ['Their mood, not mine', 0.2]),
  q('locus_of_control_11', 'family', 'neither', 'You and your mom have the same argument again.',
    ["That's just how she is", 0.2], ['We both play a part', 0.5], ['I try something different this time', 0.8]),
  q('locus_of_control_12', 'family', 'low', 'Family dinner plans fall through again.',
    ['Someone should plan better', 0.5], ['I take the lead on the next one', 0.8], ['Our family is just like that', 0.2]),
  q('locus_of_control_13', 'solo', 'high', 'You forget your keys and get locked out of the car.',
    ['On me, I need a system', 0.8], ['A bad morning', 0.5], ['These things happen', 0.2]),
  q('locus_of_control_14', 'online', 'neither', 'Your post flops while a similar one from a friend blows up.',
    ['The algorithm hates me', 0.2], ['Timing, maybe', 0.5], ['I look at what they did differently', 0.8]),
  q('locus_of_control_15', 'online', 'low', 'Your phone gets hacked through a fake link.',
    ['Could happen to anyone', 0.5], ['I should have checked the link', 0.8], ['Those scams are too good', 0.2]),
  q('locus_of_control_16', 'money', 'high', 'Your bank app shows $12 left, and payday is a week away.',
    ['I look at where it went', 0.8], ['Some bad luck, some me', 0.5], ['Rent is just too high', 0.2]),
  q('locus_of_control_17', 'money', 'neither', 'A friend gets rich from a lucky investment.',
    ['Some people get lucky', 0.2], ['Good for them', 0.5], ['I could make my own luck', 0.8]),
  q('locus_of_control_18', 'stress', 'low', 'A stressful week, and every deadline piles up at once.',
    ['Some of it was me', 0.5], ['I said yes to too much', 0.8], ['Life just hit at once', 0.2]),
  q('locus_of_control_19', 'stress', 'high', 'You get sick right before a big trip.',
    ['I should have slept more', 0.8], ['Bad timing', 0.5], ['Nothing I could do', 0.2]),
  q('locus_of_control_20', 'friends', 'neither', 'A friend says you never make plans.',
    ['They never ask me either', 0.2], ['I make some', 0.5], ['Fair, I start this week', 0.8]),
  q('locus_of_control_21', 'dating', 'low', 'A relationship ends after two years, and a friend asks what happened.',
    ['We both had a part', 0.5], ['I look at my part in it', 0.8], ['It just ran its course', 0.2]),
  q('locus_of_control_22', 'family', 'high', 'Your sister forgets your birthday.',
    ['I should have reminded her', 0.8], ['She has a lot going on', 0.5], ["That's on her", 0.2]),
  q('locus_of_control_23', 'solo', 'neither', 'The plant on your desk dies after a month.',
    ['Bad plant, honestly', 0.2], ['Maybe too much water', 0.5], ['I look up what I did wrong', 0.8]),
  q('locus_of_control_24', 'money', 'low', 'You get a parking ticket.',
    ['The sign was hard to see', 0.5], ['I should have read the sign', 0.8], ['The city is out to get me', 0.2]),
  q('locus_of_control_25', 'work', 'neither', 'You get passed over for a promotion at work.',
    ['I ask what I can improve', 0.8], ['Bit of me, bit of politics', 0.5], ['It was decided already', 0.2]),
]);
