import { intake, q, traitBank } from './define';

/** Curiosity: "I'll have my usual" (low) to "What's that? I'll try it" (high). */
export const OPENNESS_BANK = traitBank('openness', [
  intake(1, q('openness_01', 'solo', 'neither', 'A new place opened next to your usual spot, and your usual order is already in the app.',
    ['I try the new place', 0.8], ['I save it for next week', 0.5], ["Usual order. It's right there", 0.2])),
  intake(2, q('openness_02', 'solo', 'neither', 'Same restaurant, same order, and a dish you have never tried is on the menu.',
    ['I order the new one', 0.8], ['Depends on the day', 0.5], ['I know what I like', 0.2])),
  intake(3, q('openness_03', 'friends', 'neither', 'A friend sends an invite to something you would never pick yourself.',
    ["I'm in, that's the fun part", 0.8], ["I'd probably pass", 0.2])),
  q('openness_04', 'work', 'low', 'Your team switches to a new app for tasks. The old one worked fine.',
    ["I'm already poking around in it", 0.8], ["I'll learn it when I have to", 0.5], ['Honestly, I miss the old one', 0.2]),
  q('openness_05', 'work', 'low', 'A class project lets you pick any topic you want.',
    ["Whatever's quickest to finish", 0.2], ['Something close to what I know', 0.5], ['Something I know nothing about', 0.8]),
  q('openness_06', 'dating', 'neither', 'A date suggests a pottery class instead of drinks.',
    ["Sure, if they're into it", 0.5], ['Wait, that sounds fun', 0.8], ['Drinks felt safer', 0.2]),
  q('openness_07', 'dating', 'neither', 'Your situationship wants to do the exact same thing every weekend.',
    ['Easy is nice, honestly', 0.2], ['I start pitching new plans', 0.8]),
  q('openness_08', 'family', 'low', "Someone brings a dish to family dinner from a cuisine you've never had.",
    ["I'll stick to the usual plates", 0.2], ['One small bite', 0.5], ["I'm trying a bit of everything", 0.8]),
  q('openness_09', 'family', 'low', 'Your parent wants to show you a hobby they just picked up.',
    ["I'll watch for a minute", 0.5], ["Show me, I'm curious", 0.8], ['I nod and go back to my phone', 0.2]),
  q('openness_10', 'solo', 'neither', 'A free night and the streaming app is open.',
    ["Something I've never heard of", 0.8], ['New, but my usual genre', 0.5], ['A rewatch. Comfort first', 0.2]),
  q('openness_11', 'solo', 'neither', 'Your playlist has been the same 30 songs for months.',
    ["They're good songs though", 0.2], ['I add a few when I hear them', 0.5], ['I go hunting for new stuff', 0.8]),
  q('openness_12', 'online', 'low', 'A friend sends a long video about a topic you know nothing about.',
    ['I skim the first few minutes', 0.5], ['I watch the whole thing', 0.8], ['Saved. Never opened', 0.2]),
  q('openness_13', 'online', 'neither', "Your feed starts showing you a hobby you've never tried.",
    ['I fall down the rabbit hole', 0.8], ['I watch one or two', 0.5], ['I scroll right past', 0.2]),
  q('openness_14', 'money', 'high', "Payday. Your usual buy and something you've never tried are both in your cart.",
    ['The new thing. Why not', 0.8], ["The one I know I'll use", 0.2]),
  q('openness_15', 'money', 'neither', 'A friend has a new side hustle idea every month.',
    ['I listen to the good ones', 0.5], ['I want to hear every pitch', 0.8], ['Pick one and stick with it', 0.2]),
  q('openness_16', 'stress', 'neither', "A packed week, and a friend invites you to a class you've never tried.",
    ['Honestly, a good reset', 0.8], ['Next week, maybe', 0.5], ['Not this week', 0.2]),
  q('openness_17', 'stress', 'low', 'Your usual way to unwind after work stops doing it for you.',
    ['I wait for it to work again', 0.2], ['I tweak what I already do', 0.5], ['I try something completely new', 0.8]),
  q('openness_18', 'friends', 'neither', 'The group chat wants the same bar again this Friday.',
    ["I'm fine either way", 0.5], ['I suggest somewhere new to all of us', 0.8], ['Same bar is the whole point', 0.2]),
  q('openness_19', 'friends', 'neither', "A friend abroad mails you a snack and you can't read the label.",
    ['I eat it on the spot', 0.8], ['I look it up first', 0.5], ['It sits in the cupboard', 0.2]),
  q('openness_20', 'work', 'neither', 'Your boss asks for ideas: pitch something new, or polish what exists.',
    ['I pitch the new idea', 0.8], ["I polish what's already working", 0.2]),
  q('openness_21', 'online', 'high', 'Forty tabs open, all things you want to learn about someday.',
    ['A few, I close them weekly', 0.5], ["Guilty. I'll open more", 0.8], ['Two tabs, max', 0.2]),
  q('openness_22', 'dating', 'neither', 'You get to pick the spot for a first date.',
    ['Somewhere neither of us has been', 0.8], ['A place I know is good', 0.2]),
  q('openness_23', 'solo', 'neither', 'A free Sunday, no plans, and the weather is good.',
    ['I go to my favorite spot', 0.2], ["I wander somewhere I've never been", 0.8]),
  q('openness_24', 'family', 'high', 'On a family trip, someone wants to ditch the plan and just explore.',
    ["I'll go if the others do", 0.5], ["I'm the one suggesting it", 0.8], ['Can we stick to the plan', 0.2]),
  q('openness_25', 'money', 'high', 'Friends want to book a trip somewhere none of you know, tonight, on a whim.',
    ['Book it before we change our minds', 0.8], ['Send me the price first', 0.5], ["I'd rather go somewhere I know", 0.2]),
]);
