import { intake, q, traitBank } from './define';

/** Playfulness: "Let's just get it done" (low) to "Okay, but make it fun" (high). */
export const PLAYFULNESS_BANK = traitBank('playfulness', [
  intake(1, q('playfulness_01', 'stress', 'neither', 'A 40-minute delay at the gate, and your phone is at 20%.',
    ["I'd mess around and see what happens", 0.8], ['Either way, I am fine', 0.5], ["I'd rather just get through it", 0.2])),
  intake(2, q('playfulness_02', 'work', 'neither', "A serious work call, and someone's cat walks across their keyboard.",
    ['I take the joke', 0.8], ['Depends who is on the call', 0.5], ['I keep it serious', 0.2])),
  intake(3, q('playfulness_03', 'friends', 'neither', 'The group chat has a running joke.',
    ['I started it', 0.8], ['I keep it going', 0.5], ['I just react with a laugh', 0.2])),
  q('playfulness_04', 'work', 'high', 'A boring team meeting, and you have a funny thought.',
    ['I say it out loud', 0.8], ['I message a coworker', 0.5], ['I keep a straight face', 0.2]),
  q('playfulness_05', 'work', 'low', 'Your boss asks for ideas for the office party.',
    ['Can we skip it this year', 0.2], ['A nice dinner out', 0.5], ['Costumes and a game show', 0.8]),
  q('playfulness_06', 'friends', 'neither', 'Friends start a prank war in the group chat.',
    ['I join in a little', 0.5], ['I plan the best one', 0.8], ['I stay out of it', 0.2]),
  q('playfulness_07', 'friends', 'high', 'A friend is having a bad day and texts you.',
    ['I send memes until they laugh', 0.8], ['A joke, then I listen', 0.5], ['I listen and keep it real', 0.2]),
  q('playfulness_08', 'dating', 'neither', 'Your first date is at a quiet coffee shop.',
    ['We just talk', 0.2], ['A few jokes, mostly chat', 0.5], ['I make up stories about strangers', 0.8]),
  q('playfulness_09', 'dating', 'low', 'Your partner starts a silly voice while you cook dinner.',
    ['I laugh along', 0.5], ['I answer in my own silly voice', 0.8], ['Focus, the pan is hot', 0.2]),
  q('playfulness_10', 'family', 'neither', 'A long family car ride, and everyone is bored.',
    ['I start a road trip game', 0.8], ['I play along if asked', 0.5], ['Headphones in', 0.2]),
  q('playfulness_11', 'family', 'high', 'Your mom sends a serious text about chores.',
    ['"Got it, will do"', 0.2], ['A joke, then yes', 0.5], ['I reply with a funny GIF', 0.8]),
  q('playfulness_12', 'solo', 'neither', 'Cleaning your room on a Sunday afternoon.',
    ['A podcast on', 0.5], ['Music loud, dancing with the mop', 0.8], ['Just get it done', 0.2]),
  q('playfulness_13', 'solo', 'low', 'Waiting in a long line at the store.',
    ['I make a game out of it', 0.8], ['I scroll my phone', 0.5], ['I wait it out', 0.2]),
  q('playfulness_14', 'online', 'neither', 'You get to name the new group chat.',
    ['Just the group name', 0.2], ['A little pun', 0.5], ['Something absurd, with emojis', 0.8]),
  q('playfulness_15', 'online', 'high', 'A serious work email thread, and you could reply with a meme.',
    ['I save it for the group chat', 0.5], ['I send the meme', 0.8], ['I reply properly', 0.2]),
  q('playfulness_16', 'money', 'neither', 'You and a friend split a dinner bill.',
    ['Rock paper scissors for it', 0.8], ['We split it with a joke', 0.5], ['Even split in the app', 0.2]),
  q('playfulness_17', 'money', 'low', 'Planning a birthday with a small budget.',
    ['A simple dinner out', 0.2], ['Cake and a few friends', 0.5], ['A silly theme, homemade props', 0.8]),
  q('playfulness_18', 'stress', 'high', 'A tense deadline at work, and the team is on edge.',
    ['A small smile, keep going', 0.5], ['I crack a joke to break it', 0.8], ['Heads down, no jokes', 0.2]),
  q('playfulness_19', 'stress', 'low', 'Your flight is canceled and the next one leaves tomorrow.',
    ['Airport adventure time', 0.8], ['I make the best of it', 0.5], ['I just want to sleep', 0.2]),
  q('playfulness_20', 'friends', 'low', 'Game night, and someone picks a silly party game.',
    ["I'd rather play cards", 0.2], ['I play, half in', 0.5], ['I go all in', 0.8]),
  q('playfulness_21', 'dating', 'high', 'Your partner is upset and wants to talk seriously.',
    ['I listen, then lighten it', 0.5], ['I try to make them laugh first', 0.8], ['I stay serious with them', 0.2]),
  q('playfulness_22', 'family', 'low', 'Your little nephew wants to play pretend in the living room.',
    ['I become a dragon', 0.8], ['I play for a bit', 0.5], ['I suggest a movie', 0.2]),
  q('playfulness_23', 'solo', 'neither', 'You get to the gym and the playlist is terrible.',
    ['I just push through', 0.2], ['I put on my own', 0.5], ['I dance to it anyway', 0.8]),
  q('playfulness_24', 'online', 'low', 'A friend sends a silly filter photo of themselves.',
    ['I laugh and react', 0.5], ['I send back an even sillier one', 0.8], ['A thumbs up', 0.2]),
  q('playfulness_25', 'money', 'neither', 'A friend suggests a bet on who finishes the show first.',
    ['Loser buys pizza, deal', 0.8], ['A small bet, sure', 0.5], ['No bets, just watch', 0.2]),
]);
