import { intake, q, traitBank } from './define';

/** Connection: "I'm good on my own today" (low) to "I need a real conversation" (high). */
export const RELATEDNESS_BANK = traitBank('relatedness', [
  intake(1, q('relatedness_01', 'friends', 'neither', 'A friend cancels by text an hour before, no real reason given.',
    ["I'd want to talk it through", 0.8], ["I'd let it go, check in eventually", 0.2])),
  intake(2, q('relatedness_02', 'solo', 'neither', 'Good news pops up on your phone on an ordinary Tuesday.',
    ["I'm texting someone before I sit down", 0.8], ['It comes up next time we talk', 0.5], ['I just enjoy it', 0.2])),
  intake(3, q('relatedness_03', 'solo', 'neither', 'A whole day with no messages from anyone.',
    ['I feel the gap', 0.8], ['Bliss', 0.2])),
  q('relatedness_04', 'work', 'neither', 'Working from home all week, no meetings on the calendar.',
    ['I miss people by Wednesday', 0.8], ['A call or two would help', 0.5], ['Best week in months', 0.2]),
  q('relatedness_05', 'work', 'low', 'A coworker asks how your weekend was, and means it.',
    ['"Good, yours?"', 0.2], ['A quick highlight', 0.5], ['I tell them the whole story', 0.8]),
  q('relatedness_06', 'work', 'high', 'Your team chat is all business, no small talk.',
    ['I wish there was a bit', 0.5], ['I start the small talk', 0.8], ['Perfect, less noise', 0.2]),
  q('relatedness_07', 'friends', 'high', 'A friend replies "lol" to your long message about your day.',
    ['I call them to really talk', 0.8], ['A little let down', 0.5], ['Fair, it was long', 0.2]),
  q('relatedness_08', 'friends', 'low', "You haven't seen your closest friend in a month.",
    ['We pick up where we left off', 0.2], ['We will catch up soon', 0.5], ['I set a date right now', 0.8]),
  q('relatedness_09', 'dating', 'neither', 'Your partner is away on a work trip for a week.',
    ['A few texts a day', 0.5], ['We call every night', 0.8], ['I enjoy the space', 0.2]),
  q('relatedness_10', 'dating', 'high', 'A date talks only about surface stuff all night.',
    ['I steer it somewhere deeper', 0.8], ['A bit dull, but fine', 0.5], ['Light is nice for a first date', 0.2]),
  q('relatedness_11', 'family', 'neither', 'A family dinner where everyone is on their phone.',
    ['I check mine too', 0.2], ['I try to start a chat', 0.5], ['I ask everyone to put them away', 0.8]),
  q('relatedness_12', 'family', 'low', 'Your grandma calls just to hear your voice.',
    ['A sweet ten minutes', 0.5], ['I stay on for an hour', 0.8], ['I keep it short', 0.2]),
  q('relatedness_13', 'solo', 'high', 'A long train ride, and the person next to you seems chatty.',
    ["I'm up for a chat", 0.8], ['A few words, then headphones', 0.5], ['Headphones in right away', 0.2]),
  q('relatedness_14', 'online', 'neither', 'Your phone shows 30 likes on a post, but no comments.',
    ['Likes are plenty', 0.2], ['Nice enough', 0.5], ['I wish someone said something', 0.8]),
  q('relatedness_15', 'online', 'high', 'A friend you only know from online wants to meet in person.',
    ['Maybe, somewhere public', 0.5], ["Yes, let's make it real", 0.8], ['Online is fine as is', 0.2]),
  q('relatedness_16', 'money', 'neither', 'A free Friday and $40 to spend.',
    ['Dinner with a friend', 0.8], ['Something for us both', 0.5], ['Something just for me', 0.2]),
  q('relatedness_17', 'money', 'low', 'A friend offers to split a trip so you can go together.',
    ["I'd rather go solo", 0.2], ['If the price is right', 0.5], ['Yes, time with them is the point', 0.8]),
  q('relatedness_18', 'stress', 'high', 'A bad day at work, and you get home.',
    ['I text one friend', 0.5], ['I need to talk it out with someone', 0.8], ['I need quiet, alone', 0.2]),
  q('relatedness_19', 'stress', 'neither', 'Exam week, and a friend invites you to a study group.',
    ['Yes, I study better with people', 0.8], ['For an hour, then solo', 0.5], ['Solo, no distractions', 0.2]),
  q('relatedness_20', 'friends', 'low', 'Your friends start a weekly dinner night.',
    ['Once a month, max', 0.2], ['Most weeks', 0.5], ['I never miss one', 0.8]),
  q('relatedness_21', 'dating', 'low', 'Your partner wants to talk about your feelings before bed.',
    ['Sometimes, not every night', 0.5], ['I love those talks', 0.8], ['Can it wait until morning', 0.2]),
  q('relatedness_22', 'family', 'high', 'Your mom texts the family chat a photo from your childhood.',
    ['I start a whole thread of memories', 0.8], ['A heart and a laugh', 0.5], ['I leave it on read', 0.2]),
  q('relatedness_23', 'solo', 'low', 'You move for work to a new city where you know nobody.',
    ['I enjoy being anonymous', 0.2], ['I meet people slowly', 0.5], ['I join a club in week one', 0.8]),
  q('relatedness_24', 'online', 'neither', 'A group chat you love goes quiet for a few weeks.',
    ['I miss it a bit', 0.5], ['I revive it with a meme', 0.8], ['I barely notice', 0.2]),
  q('relatedness_25', 'work', 'neither', 'Your desk at the office gets moved to a quiet corner alone.',
    ['I miss the chatter', 0.8], ['Fine, I visit people', 0.5], ['Finally, some peace', 0.2]),
]);
