import { intake, q, traitBank } from './define';

/** Self-belief: "That's a lot. I don't know" (low) to "I can do that" (high). */
export const SELF_EFFICACY_BANK = traitBank('self_efficacy', [
  intake(1, q('self_efficacy_01', 'friends', 'low', "Everyone at the table already knows their order. You don't.",
    ["I panic-order whatever's closest", 0.2], ['Takes a sec, but I land on something', 0.5], ['I pick something and own it', 0.8])),
  intake(2, q('self_efficacy_02', 'solo', 'neither', 'The wifi drops and you have never fixed it yourself before.',
    ["I'll figure it out", 0.8], ['I look it up first', 0.5], ['I find someone who knows', 0.2])),
  intake(3, q('self_efficacy_03', 'stress', 'low', 'A big task has sat in your to-do app for two weeks.',
    ['I pick any piece and start', 0.8], ['I break it down, then wait a bit', 0.5], ['I keep moving it to tomorrow', 0.2])),
  q('self_efficacy_04', 'work', 'high', 'Your boss asks if you can take on one more project.',
    ['Yes, I can fit it in', 0.8], ['Maybe, if something moves', 0.5], ["I'm already stretched", 0.2]),
  q('self_efficacy_05', 'work', 'low', 'A class assignment uses software you have never opened.',
    ['I ask to do it another way', 0.2], ['I find a tutorial first', 0.5], ["I'll learn it by Friday", 0.8]),
  q('self_efficacy_06', 'friends', 'neither', 'Friends need someone to organize the group trip.',
    ['I can help with a part', 0.5], ['I can make it happen', 0.8], ['Someone better at it should', 0.2]),
  q('self_efficacy_07', 'friends', 'high', "A friend bets you can't run a 10k next month.",
    ['Watch me', 0.8], ['Maybe with some training', 0.5], ["They're probably right", 0.2]),
  q('self_efficacy_08', 'dating', 'low', 'You want to ask someone out over text.',
    ['I wait for them to ask', 0.2], ['I draft it a few times', 0.5], ['I send it now', 0.8]),
  q('self_efficacy_09', 'dating', 'neither', 'Your partner asks you to meet their whole family this weekend.',
    ["Nervous, but I'll be fine", 0.5], ['I can win them over', 0.8], ['That sounds like a lot', 0.2]),
  q('self_efficacy_10', 'family', 'high', "Your parents need help moving this weekend, and it's a big house.",
    ['I can run the whole move', 0.8], ['I can handle a few rooms', 0.5], ['We should hire movers', 0.2]),
  q('self_efficacy_11', 'family', 'low', 'Your dad asks you to give a toast at his birthday dinner.',
    ['Ask someone else', 0.2], ["I'll write it out first", 0.5], ['I can do it, no notes', 0.8]),
  q('self_efficacy_12', 'solo', 'neither', 'A pipe under your kitchen sink starts dripping.',
    ['I watch a video and try', 0.5], ['I can fix that', 0.8], ['I text the landlord', 0.2]),
  q('self_efficacy_13', 'online', 'high', 'A friend posts a 30-day challenge and tags you.',
    ["I'm in, day one today", 0.8], ["I'll try a few days", 0.5], ["I'll never finish it", 0.2]),
  q('self_efficacy_14', 'online', 'low', 'You want to start a side project online but have no followers.',
    ['No one would watch', 0.2], ['I plan for a while first', 0.5], ['I start anyway', 0.8]),
  q('self_efficacy_15', 'money', 'neither', 'You set a goal in your bank app: save $1,000 in three months.',
    ['Maybe, if nothing comes up', 0.5], ['I can do that', 0.8], ["That isn't realistic", 0.2]),
  q('self_efficacy_16', 'money', 'high', 'Your phone breaks and the repair shop quotes a lot.',
    ['I order the part and fix it', 0.8], ['I look for a cheaper shop', 0.5], ['I pay what they ask', 0.2]),
  q('self_efficacy_17', 'stress', 'neither', 'Three deadline emails land on one Monday morning.',
    ['I feel frozen', 0.2], ["One at a time, I'll try", 0.5], ['I can get through all of it', 0.8]),
  q('self_efficacy_18', 'stress', 'high', 'A friend in a crisis calls and asks you to drop everything.',
    ["I'll do what I can", 0.5], ['I can handle this', 0.8], ["I don't know how to help", 0.2]),
  q('self_efficacy_19', 'work', 'neither', 'A job posting in your inbox asks for skills you only half have.',
    ['I apply and learn the rest', 0.8], ['I apply and hope', 0.5], ['I skip it', 0.2]),
  q('self_efficacy_20', 'friends', 'low', 'Karaoke night at a bar, and your friends hand you the mic.',
    ['I pass it on', 0.2], ['A duet, maybe', 0.5], ['I take the mic', 0.8]),
  q('self_efficacy_21', 'dating', 'high', 'Your date suggests rock climbing, and you have never tried it.',
    ['I give it a go', 0.5], ["I'll be up the wall in no time", 0.8], ["I'll watch from below", 0.2]),
  q('self_efficacy_22', 'family', 'neither', 'Your family asks you to cook the big holiday dinner.',
    ['I can pull it off', 0.8], ['I can do part of it', 0.5], ["I'm not ready for that", 0.2]),
  q('self_efficacy_23', 'solo', 'low', 'You want to learn to swim as an adult at the gym.',
    ['Too late for me', 0.2], ['I look into lessons', 0.5], ['I sign up today', 0.8]),
  q('self_efficacy_24', 'money', 'low', 'You want to ask for a raise at work.',
    ['I prep for weeks first', 0.5], ['I set up the meeting', 0.8], ['I wait for them to offer', 0.2]),
  q('self_efficacy_25', 'online', 'neither', 'Your laptop gets a weird error you have never seen.',
    ['I can sort it out', 0.8], ['I search the error first', 0.5], ['I ask a techy friend', 0.2]),
]);
