import { intake, q, traitBank } from './define';

/** Composure: "I'm still thinking about this morning" (low) to "Oh, that? I forgot about it" (high). */
export const STEADINESS_BANK = traitBank('steadiness', [
  intake(1, q('steadiness_01', 'stress', 'low', 'Your phone hits 3% before you have left the house.',
    ["I'm mostly over it by lunch", 0.8], ['It sits with me a bit, then fades', 0.5], ['It colors the rest of the day', 0.2])),
  intake(2, q('steadiness_02', 'friends', 'low', 'An hour before, the group chat moves the plan somewhere else.',
    ['Fine, I roll with it', 0.8], ['Mild whiplash, then fine', 0.5], ['It throws off the whole evening', 0.2])),
  intake(3, q('steadiness_03', 'online', 'low', 'A one-word reply lands and it could be read two ways.',
    ['I read it plain and move on', 0.8], ['I reread it once, then let it go', 0.5], ['I reread it a few times', 0.2])),
  q('steadiness_04', 'work', 'low', 'Your boss sends "can we talk tomorrow?" with no context.',
    ['Probably nothing, I sleep fine', 0.8], ['I wonder about it tonight', 0.5], ['I replay every email I sent', 0.2]),
  q('steadiness_05', 'work', 'neither', 'You trip over a word in the middle of a presentation.',
    ['I think about it all week', 0.2], ['I recover, but feel it', 0.5], ['I laugh and keep going', 0.8]),
  q('steadiness_06', 'work', 'high', 'A coworker is panicking about a deadline you share.',
    ['I catch a little of it', 0.5], ['Not my panic, I stay chill', 0.8], ["Now we're both panicking", 0.2]),
  q('steadiness_07', 'friends', 'low', 'A friend makes a joke about you in the group chat. Others laugh.',
    ['I laugh too and forget it', 0.8], ['It stings for a minute', 0.5], ['I think about it for days', 0.2]),
  q('steadiness_08', 'dating', 'low', 'A first date goes well, then they take a day to text back.',
    ['My whole day is off', 0.2], ['I check my phone a bit more', 0.5], ['I barely notice', 0.8]),
  q('steadiness_09', 'dating', 'high', "Your partner is upset about something, and you think it's small.",
    ['I take it seriously for them', 0.5], ["I stay calm, it'll pass", 0.8], ['I get upset too', 0.2]),
  q('steadiness_10', 'family', 'low', 'A family group chat turns into a fight about politics.',
    ['I mute it and carry on', 0.8], ['It bugs me for the evening', 0.5], ['It ruins my night', 0.2]),
  q('steadiness_11', 'family', 'neither', 'Your mom calls twice in a row and you missed both.',
    ['I assume the worst', 0.2], ['I call back a bit fast', 0.5], ['She probably wants a recipe', 0.8]),
  q('steadiness_12', 'solo', 'low', 'You lie in bed and remember an awkward thing you said in 2019.',
    ['A quick cringe, then sleep', 0.5], ['That never happens to me', 0.8], ['There goes another hour', 0.2]),
  q('steadiness_13', 'solo', 'neither', 'You spill coffee on your shirt right before work.',
    ['Swap the shirt, move on', 0.8], ['A sigh, then fine', 0.5], ['The day is off to a bad start', 0.2]),
  q('steadiness_14', 'online', 'high', 'A post of yours gets a rude comment from a stranger.',
    ['I keep rereading it', 0.2], ['It bugs me for an hour', 0.5], ['Delete, block, forgotten', 0.8]),
  q('steadiness_15', 'online', 'neither', 'Your laptop freezes and the file might not have saved.',
    ['A little sweaty, but okay', 0.5], ['It probably saved, I wait', 0.8], ['Full panic mode', 0.2]),
  q('steadiness_16', 'money', 'low', 'An unexpected bill shows up in your email.',
    ['I pay it and move on', 0.8], ['Annoyed for the day', 0.5], ['I feel sick about it all week', 0.2]),
  q('steadiness_17', 'money', 'high', 'Your card gets declined at the store with a line behind you.',
    ['I want the floor to swallow me', 0.2], ['My face goes red, then fine', 0.5], ['Weird, I use the other card', 0.8]),
  q('steadiness_18', 'stress', 'neither', "Your train is delayed and you'll be late for work.",
    ['I check the app every minute', 0.5], ['I text ahead and relax', 0.8], ['My heart is racing', 0.2]),
  q('steadiness_19', 'stress', 'high', 'Everything goes wrong at once on a Monday morning.',
    ['Funny, honestly', 0.8], ['Rough start, it gets better', 0.5], ['I want to go back to bed', 0.2]),
  q('steadiness_20', 'friends', 'neither', 'A friend cancels your birthday plans last minute.',
    ['It ruins the birthday', 0.2], ['Disappointed, then okay', 0.5], ['Plans change, no big deal', 0.8]),
  q('steadiness_21', 'dating', 'neither', 'You see your ex tagged in a photo with someone new.',
    ['A weird feeling, then fine', 0.5], ['Good for them', 0.8], ['I scroll their whole profile', 0.2]),
  q('steadiness_22', 'family', 'high', 'Your dad gets lost driving and is getting stressed in the car.',
    ['I stay calm and pull up the map', 0.8], ['I get a bit tense too', 0.5], ["Now we're both stressed", 0.2]),
  q('steadiness_23', 'solo', 'low', 'A small mistake at the store: you forgot the one thing you came for.',
    ["I'm mad at myself all day", 0.2], ['A little annoyed', 0.5], ['I laugh and go back', 0.8]),
  q('steadiness_24', 'money', 'neither', 'Your rent goes up next month.',
    ['I worry for a few days', 0.5], ['I adjust and move on', 0.8], ['I lose sleep over it', 0.2]),
  q('steadiness_25', 'work', 'neither', 'You get feedback at work that was harsher than you expected.',
    ['I take the note, move on', 0.8], ['It stings for a day', 0.5], ['I replay it for a week', 0.2]),
]);
